### ISSUE TITLE
Previous installed PopcornTimeTV stop working

### ISSUE THREAD

**Issue by garranhado** [PopcornTimeTV/PopcornTimeTV#1]
Don't know if about server issues but after constant changes in repositories previous installed PopcornTimeTV app stopped working.

Not tested current commits yet.

**Comment by Evhelden** [comment]
https://www.reddit.com/r/PopCornTime/comments/4wif32/popcorntime_apple_tv_4/

**Comment by tvOSPopcorn** [comment]
@Evhelden @garranhado The previous build off the application should be working now! Reopen this issue if there's still a problem :smile
