### ISSUE TITLE
fast forward

### ISSUE THREAD

**Issue by d1cee** [PopcornTimeTV/PopcornTimeTV#100]
if stream crashes or i need to restart for whatever reason, you cant fast forward.

You can go to the minute but the stream doesn't pick back up? it just hangs.

**Comment by Gsuz** [comment]
scrubbing forwards or backwards for that matter is broken. I've tried all three resolutions. Tested around 10 different movies / episodes. In all cases the playback freezes. Is there any way we can give more helpful feedback?

**Comment by pnewell** [comment]
same issue

**Comment by RefusedFlow** [comment]
This is a known problem, so this issue will be closes as it's already listed on the progress list to be implemented

**You're more than welcome to visit the progress list below** 
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress
