### ISSUE TITLE
Pods issue succeeded! but now There is TopShelf error!

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#101]
Now after all the pods use swift 3 and the there is no popups say to you covert to swift 3 blablabla..
Now when the build is about to end it gave me this error on `TopShelf`
I use the latest commit and the latest pods update an repo update

`Swift Compiler Error`
<img width="589" alt="screen shot 2016-09-30 at 11 46 17 pm" src="https://cloud.githubusercontent.com/assets/19555995/19006457/3d03ca68-8768-11e6-8f77-9fc3117e3bd1.png">

Thanks!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Please be patient. You know we are updating the app as you have seen issue #97.
