### ISSUE TITLE
Fork for iOS

### ISSUE THREAD

**Issue by air720boarder** [PopcornTimeTV/PopcornTimeTV#102]
Will you guys consider forking this off for iOS, as an app with Miracast/Airplay support to stream to other devices like older AppleTV's, Smart TV's, etc?

**Comment by tomto147** [comment]
There is a PopcornTime app for iOS. Just google "PopcornTime iOS" and you will get it. Both for jailbreaked deviced and non jailbreak.

**Comment by air720boarder** [comment]
I've looked into that and am considering forking this as into an iOS app, if it wasn't already planned or started, as the only ones I've found online seem to have slowed significantly.

**Comment by buzzel** [comment]
@air720boarder We do have someone who is working on the iOS counter part.

**Comment by air720boarder** [comment]
Fantastic! When should we expect to see a published fork? You can close this issue with your response, I have nothing more at this time. Thanks.

**Comment by buzzel** [comment]
@air720boarder No ETA yet, but it is being worked on!
