### ISSUE TITLE
Updating PopcornTimeTV on Apple TV 4

### ISSUE THREAD

**Issue by FarFromNormal** [PopcornTimeTV/PopcornTimeTV#103]
Trying to figure out the easiest way to update PopcornTime on my Apple TV 4. Whenever I open it it informs me that there is an update but when I go into xcode and try to do the update I get a bunch of errors. Also, with the current version I have installed I cannot use "Watchlist". It crashes the app every time that I try to add something to it. I also don't have topshelf options. Just a graphic. I am clearly missing something so any assistance would be appreciated. Thanks in advance.

-FFN

**Comment by buzzel** [comment]
The latest version is 0.6.2. You can always check what the latest version is by visiting https://github.com/PopcornTimeTV/PopcornTimeTV/releases. 

The way to update is to open terminal and typ `cd ` and drag the PopcornTime folder into the window. Then it will look something like `cd /Users/YOUR_NAME/Desktop/PopcornTImeTV` once you do that run this command `git stash && git fetch && git rebase && git stash pop && git checkout 0.6.2 && pop update` Its a big one but it should do everything all at once for you. There will be an update script coming later on as well.

**Comment by FarFromNormal** [comment]
I think I may have messed up then. Cause I deleted the original PopcornTimeTV folder off my desktop and tried getting a fresh copy and that's when xcode started giving me a bunch of error messages.

**Comment by FarFromNormal** [comment]
Okay, so I have the fresh copy and opened the project in xcode but I am still getting 2 errors which are preventing me from building successfully. The first error is for Searchrecipe.swift and it states "Value of type 'NetworkManager' has no member 'searchEZTV'. The second error has something to do with the provisioning profile and states "No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier "com.***.PopcornTime.TopShelf" were found. When I try and fix the provisioning profile issue I get another message that states "Unable to add App ID because the '10' App ID limit in'7' days has been exceeded. I haven't done any work recently in xcode so not sure how it's been exceeded or how to fix that issue. Again, any help would be appreciated.

-FFN

**Comment by FarFromNormal** [comment]
Now I had thought I fixed the provisioning issue and it built successfully but when it goes to install to my apple tv I get a new error stating " App Installation Failed This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique."  Help...lol, not sure what I am doing wrong.

**Comment by GillesMontyne** [comment]
did you change the bundle id in both targets(topshelf and popcorntime)? If so, leave the structure intact: only change the "popcorntime" in the bundle ID to something like: your name, so for example the Topshelf target should be something like: com.YOUR_NAME.PopcornTime.Topshelf. Hope this helps..

**Comment by buzzel** [comment]
@FarFromNormal Double check what @GillesMontyne mentioned and try removing the current version from your Apple TV and installing it again.

**Comment by FarFromNormal** [comment]
Thanks for the responses. I had removed the Topshelf at the end of the identifier and have now added it back. However it has started the provisioning error I was getting earlier where its telling me "Unable to add App ID because the '10' App ID limit in '7' days has been exceeded. Again, not sure how this limit has been exceeded since I haven't done anything in xcode in the last month if not longer. Any suggestion would be appreciated.

**Comment by GillesMontyne** [comment]
@FarFromNormal Don't you have another apple ID laying around (sister/brother/...)? Try it with 1 of those and check if the issue persists.

**Comment by FarFromNormal** [comment]
I created another ID, I'll let you know how it works out.

**Comment by FarFromNormal** [comment]
Okay, it seems to be working now with the new ID cause I switched to my Apple TV and it has the PopcornTime graphic on the screen. However in xcode it still says running and has for a while. When will it say finished? I don't want to force something to stop and then have things not work correctly, i.e. watchlist.

**Comment by ozkrtech** [comment]
You can safely hit "stop" on xcode and the app will stop running and close on appletv. Thats completely normal. Then go and open the app lile you would do everyday from the appletv without depending on xcode to launch it for you.

Oscar Rodriguez
IT Technician

On May 17, 2016, at 9:48 AM, FarFromNormal <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, it seems to be working now with the new ID cause I switched to my Apple TV and it has the PopcornTime graphic on the screen. However in xcode it still says running and has for a while. When will it say finished? I don't want to force something to stop and then have things not work correctly, i.e. watchlist.

-

**Comment by FarFromNormal** [comment]
@ozkrtech Thanks for the quick response. I did go back into xcode and clicked stop. Switched back to my Apple TV and it crashes as soon as I click on it to open.

**Comment by FarFromNormal** [comment]
Just reran the process and noticed a message popup stating "fatal error: unexpectedly found nil while unwrapping and optional value (lldb)" and there is a line of code that is highlighted in light green. Not sure what this means or needs to be done now.

**Comment by FarFromNormal** [comment]
So since the previous copy still wasn't working I deleted that folder and downloaded another fresh copy and now I am getting a red stop sign error in xcode under PopcornKit saying "Torrent.swift - No such module 'PopcornTorrent'. All I wanted to do is update...LOL I also have multiple yellow warnings, 1 for PopcornTime regarding the new app id provisioning profile is expiring soon and 6 in TopShelf, 1 same message about provisioning profile expiring soon and the other 5 are saying "Linking against a dylib which is not safe for use in application extentions :/Users/MY_NAME/Library/Developer/Xcode/DerivedData***** long string but they are for Alamofire, ObjectMapper, PopcornKit, PopcornTorrent and SWXMLHash. Really not good with all of this code so any help is appreciated.

**Comment by ozkrtech** [comment]
Same happened to me, go to sourceconteol o  xcode and select the branch named fix99, do not select master this time. I just did it and its working. (I had the exact same problem as you)

Oscar Rodriguez
IT Technician

On May 17, 2016, at 12:15 PM, FarFromNormal <notifications@github.com<mailto:notifications@github.com>> wrote:


So since the previous copy still wasn't working I deleted that folder and downloaded another fresh copy and now I am getting a red stop sign error in xcode under PopcornKit saying "Torrent.swift - No such module 'PopcornTorrent'. All I wanted to do is update...LOL I also have multiple yellow warnings, 1 for PopcornTime regarding the new app id provisioning profile is expiring soon and 6 in TopShelf, 1 same message about provisioning profile expiring soon and the other 5 are saying "Linking against a dylib which is not safe for use in application extentions :/Users/MY_NAME/Library/Developer/Xcode/DerivedData***** long string but they are for Alamofire, ObjectMapper, PopcornKit, PopcornTorrent and SWXMLHash. Really not good with all of this code so any help is appreciated.

-

**Comment by FarFromNormal** [comment]
I assume go to source control then under working copies select PopcornTimeTV then configure PopcornTimeTV and when the next box pops up click branches and then fix/99? Cause I click that and then click done but nothing seems to change and its still failing to build.

**Comment by ozkrtech** [comment]
Yes!, exactly that. Everytime i fownload a new version i check inside the popcorntime folder another folder named "script" and inside that folder theres an executavle named bootstrap. I always run it and it seems to download all pods and updates needed every single time, without doing that it wont work unless you tey to build something previously installed.

Oscar Rodriguez
IT Technician

On May 17, 2016, at 1:08 PM, FarFromNormal <notifications@github.com<mailto:notifications@github.com>> wrote:


I assume go to source control then under working copies select PopcornTimeTV then configure PopcornTimeTV and when the next box pops up click branches and then fix/99? Cause I click that and then click done but nothing seems to change and its still failing to build.

-

**Comment by FarFromNormal** [comment]
Thank you @ozkrtech. So now I am back to the point where it says its installing to apple tv and then running on apple tv and when I switch over to it the PopcornTime backdrop is on my tv screen. So I go back to my mac in xcode and click stop, return to my apple tv, click the popcorn time icon but all I get is a white screen and nothing loads. I am clearly still doing something wrong.

**Comment by ozkrtech** [comment]
When i get a whitescreen on appletv and the words "Loading..." Doesnt show up it means im offline, check you internet conection on modem and appletv and try again.

Oscar Rodriguez
IT Technician

On May 17, 2016, at 1:45 PM, FarFromNormal <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you @ozkrtech<https://github.com/ozkrtech>. So now I am back to the point where it says its installing to apple tv and then running on apple tv and when I switch over to it the PopcornTime backdrop is on my tv screen. So I go back to my mac in xcode and click stop, return to my apple tv, click the popcorn time icon but all I get is a white screen and nothing loads. I am clearly still doing something wrong.

-

**Comment by FarFromNormal** [comment]
Well, I have restarted the Apple TV and I disconnected and reconnected to my wifi. I still can't get PopcornTime to open, now it just crashes instead of the white screen. But it is showing Latest Movies in the TopShelf, but if I click on one of the posters it still just crashes.

**Comment by FarFromNormal** [comment]
So I think I am getting closer to it working but there is still something, not sure what, that is preventing it from working correctly.

**Comment by ozkrtech** [comment]
My apple tv updated itself to latest version before i installed the new (fix/99) (v0.6.3) Popcorntime. If you are not on latest version of tvOS try that.

Oscar Rodriguez
IT Technician

On May 17, 2016, at 2:04 PM, FarFromNormal <notifications@github.com<mailto:notifications@github.com>> wrote:


So I think I am getting closer to it working but there is still something, not sure what, that is preventing it from working correctly.

-

**Comment by FarFromNormal** [comment]
Okay, gonna try updating the apple. Its been asking me to do that the last couple days and I have been  putting it off cause I feared it would also mess up kodi. I'll let you know what happens next. Oh and that fix/99 branch isn't showing up now in xcode. Not sure where it went.

**Comment by FarFromNormal** [comment]
Alright, this has turned into a major headache and all I wanted to do was update it. So I just finished updating my Apple TV (It didn't wipe out Kodi this time, TY Apple) and again tried to install PopcornTime. The app icon installs and I can see latest movies and popular shows in the TopShelf but the app itself keeps crashing whether I click the icon or a poster above. And like I said in my previous post, that fix/99 branch no longer is showing up. LOL Why is this app hating me so?!! LOL

**Comment by ozkrtech** [comment]
I heard sonething about buzzer to merge the new changes into the master branch, maybe thats why.

Oscar Rodriguez
IT Technician

On May 17, 2016, at 2:27 PM, FarFromNormal <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, gonna try updating the apple. Its been asking me to do that the last couple days and I have been putting it off cause I feared it would also mess up kodi. I'll let you know what happens next. Oh and that fix/99 branch isn't showing up now in xcode. Not sure where it went.

-

**Comment by FarFromNormal** [comment]
Is popcorntime now up to 0.6.3? Cause I did git checkout 0.6.3 in Terminal just now and I got the error "pathspec '0.6.3' did not match any file(s) known to git"

**Comment by Evhelden** [comment]
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

I got this

Similar?

**Comment by FarFromNormal** [comment]
Thats different from the issue I am having but I did update cocoapods yesterday to the latest version. Still having the same problem here. Have reinstalled multiple times now and every time it installs the icon and shows the posters in TopShelf but the app won't actually open. I either get white screen (Doesn't show 'Loading...') or it just crashes. Really don't know what else to try. I feel like its really close but I am just missing a step somewhere or missing an error somewhere.

**Comment by FarFromNormal** [comment]
Yeah, I just tried reinstalling again and still notta. The only thing I can see in xcode are those yellow warnings I mentioned earlier about "Linking against a dylib which is not safe for use in application extensions....." There was 5 earlier today, now there is 4. Willing to try any and all suggestions.

**Comment by ozkrtech** [comment]
The build i got from branch fix/99 was i deed 0.6.3 but those fixes might have been merged to master branch with same old cersion 0.6.2

Oscar Rodriguez
IT Technician

On May 17, 2016, at 2:50 PM, FarFromNormal <notifications@github.com<mailto:notifications@github.com>> wrote:


Is popcorntime now up to 0.6.3? Cause I did git checkout 0.6.3 in Terminal just now and I got the error "pathspec '0.6.3' did not match any file(s) known to git"

-

**Comment by FarFromNormal** [comment]
I really don't know what more to try. I have no clue how to clear out those yellow warnings I am getting. That's the only thing i can come up with that is causing it not to work. I have downloaded so many fresh copies today and installed with still no luck actually getting it to work.

**Comment by buzzel** [comment]
@FarFromNormal Here is a list of things to run in terminal and to try

- Run ` rm -rf ~/.cocoapods/repos/popcorntimetv`
- Delete your DerivedData from Xcode run `rm -rf ~/Library/Developer/Xcode/DerivedData`
- Delete all copies of PopcornTime and download a fresh one by running `cd  ~/Desktop/ && git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git && cd PopcornTimeTV && python install.py` copy that whole line or run each one by one. When you run the python install script it will walk you through setting up your local copy and installing all the dependencies.

Don't forget to update the App's bundle ID and the TopShelf's bundle ID. 

Hopefully this will allow you to get it up and running again.

**Comment by pnewell** [comment]
I tried updating to 0.6.3 and I stick can't open American Dad. I am wondering if I did it right, how can I confirm the version I am running, this is my first time installing a new version.

**Comment by pnewell** [comment]
I am getting the following when I run the python script btw:

`python install.py
Traceback (most recent call last):
  File "install.py", line 5, in <module>
    import requests
ImportError: No module named requests`

**Comment by FarFromNormal** [comment]
@buzzel Should I see any response in terminal when I do the first two things in the list? I am also getting the same error as @pnewell when running the python script.

**Comment by FarFromNormal** [comment]
It's working...FINALLY. TY @buzzel and @ozkrtech for helping out today.

**Comment by FarFromNormal** [comment]
Last thing I would like to do and I had done it on my previous install of it is to change the app icon.

**Comment by ozkrtech** [comment]
You welcome!!

Oscar Rodriguez
IT Technician

On May 17, 2016, at 9:03 PM, FarFromNormal <notifications@github.com<mailto:notifications@github.com>> wrote:


It's working...FINALLY. TY @buzzel<https://github.com/buzzel> and @ozkrtech<https://github.com/ozkrtech> for helping out today.

-
