### ISSUE TITLE
The platform of the target `PopcornTime` (tvOS 9.0) is not compatible

### ISSUE THREAD

**Issue by guiwunsch** [PopcornTimeTV/PopcornTimeTV#103]
Hi,
I'm getting this error on installation:

[!] The platform of the target `PopcornTime` (tvOS 9.0) is not compatible with `AlamofireXMLRPC (1.0.0)`, which does not support `tvos`.

Could you help me?

Thanks.

**Comment by moh0sw** [comment]
download the project with the latest commit
then run `pod repo update; pod update;` and it should be fixed
