### ISSUE TITLE
VPN support?

### ISSUE THREAD

**Issue by sarkistlt** [PopcornTimeTV/PopcornTimeTV#104]
Any chance of implementing a VPN into the application?

**Comment by FlaviaBondJamesBondsHusband** [comment]
We are looking into it and hopefully will be added to the next release version.

**Comment by JonnyBoy333** [comment]
This would be immensely useful. Creating a vpn router for the ATV that works with all other services is an incredible pain in the ass.

**Comment by t4t5** [comment]
Why is this closed? There's no VPN support yet is there?
