### ISSUE TITLE
Movies not loading

### ISSUE THREAD

**Issue by GillesMontyne** [PopcornTimeTV/PopcornTimeTV#104]
Not a single movie loads, after selecting quality(720p/1080p) PopcornTimeTV closes and returns to homescreen. TV shows works perfectly so I don't know what is going on in the movies section. Already tried to run an pod update but the issue persists. Any insight is appreciated, love the work you guys have already done, its an amazing project :)

**Comment by Gsuz** [comment]
I just binge watched 2 movies this morning. worked fine. If it helps maybe try clean reinstall?

**Comment by GillesMontyne** [comment]
Tried to clean install, did not solve the issue...  Any other suggestions?

**Comment by buzzel** [comment]
@GillesMontyne If its possible, can you connect this project to Xcode and send me a screenshot of Xcode when the app crashes? It'll show some stuff in the console and highlight a line which usually shows the cause

**Comment by GillesMontyne** [comment]
Alright I'll send a screenshot tommorow, thx in advance!
