### ISSUE TITLE
Certain Shows Won't Open

### ISSUE THREAD

**Issue by pnewell** [PopcornTimeTV/PopcornTimeTV#105]
Certain shows won't open for me. For example:

American Dad (found through Search), when I click on it does nothing
Mike & Molly (found through Search), when I click on it goes to loading circle but never loads

Other shows load fine

**Comment by smith288** [comment]
Look for How It's Made.  I believe the "Overview" is null so the cleaned property is blowing up.

**Comment by buzzel** [comment]
A fix is pushed to master and will be released shortly.
