### ISSUE TITLE
Cant build anything above 5.0 on Xcode 7.3

### ISSUE THREAD

**Issue by kokozaurz** [PopcornTimeTV/PopcornTimeTV#106]
Hi,

I can build 5.0 release no problem, however on any version above that (6.0, 6.1, 6.2) I get the following error message:

`No such module 'PopcornTorrent'` (screenshot: http://i.imgur.com/CLaH14d.png)

I've tried reinstalling cocoa pods, doing update in folder etc - no help.

Any solutions to this? 

Thanks so much!

**Comment by buzzel** [comment]
If you open the Pods folder, is there a PopcornTorrent folder in there?

**Comment by buzzel** [comment]
Also, try running `pod update` again as I just pushed an update to PopcornKit which might also fix this issue.

**Comment by buzzel** [comment]
@kokozaurz 0.6.3 was pushed, see if it fixes your issues.

**Comment by kokozaurz** [comment]
@buzzel Sorry was at work and just got home - 0.6.3 fixes the issue, builds nicely!

Thanks for this and most importantly thanks for making this project happen!

Best,
