### ISSUE TITLE
getting Podfile with Swift 3.0 branch

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#106]
When running pod update or pod update I get this error

[!] Invalid `Podfile` file: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
/Users/Mohammad/Downloads/PopcornTimeTV-Swift3-2.0/Podfile:4: syntax error, unexpected ===, expecting end-of-input
=======
   ^.

 #  from /Users/Mohammad/Downloads/PopcornTimeTV-Swift3-2.0/Podfile:1
 #  -------------------------------------------
 >  <<<<<<< Updated upstream
 #  
 #  -------------------------------------------

And I have macOS Sierra and Xcode 8 and cocoapods 1.1.0.rc.2

**Comment by FlaviaBondJamesBondsHusband** [comment]
Should be fixed now. Please not Swift3.0 branch is not even in alpha. The code will probably not compile.
