### ISSUE TITLE
06.2. issues not closed yet

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#107]
Found the following issues, not yet to close:

1. Genre does not work for sci-fi and film-noir (possibly because of the ' - ' symbol)
2. Subtitles bar shows in movies, actual subtitles do not show
3. Series update is not yet working: E.g. Flash is a mix of two series (click on, the symbol of the older Flash show comes up, only season 1 shows, no season 2). Vinyl still makes the complete app go to the back ground and does not show an update
4. Noticed random memory leaks
5. Do not notice updates in movies ' latest movies ' remain showing the same results in the last two weeks or so.
6. Waiting on the forward, rewind, resume, subtitles on TV show functions

Overall: Super app. Extremely happy to see the hard work. Will keep testing to help optimize.

**Comment by buzzel** [comment]
1. We'll look into this one
2. I just double checked and subtitles are displaying correctly for me. They are only available for Movies as well.
3. When you say series update, do you mean new updates aren't available? If so this is probably cause of an API issue. 
4. What are the leaks you are talking about? I had fixed them all in the 0.6.1 update
5. Again this could be due to an API issue, something we dont have control over but will take a look.
6. Unfortunately the streamer is written in an Obj-C and C++ hybrid language and none of us are familiar enough with C++ to get that working. If you know anyone who does, send them our way! Wecan use the help on that one.

**Comment by Evhelden** [comment]
1. Great
2. I'll check again. I notice different language options per movie (as I suppose it is availability of the subtitles), but no actual display. As stated: I'll check again.
3. With update, I mean: the 0.6.2 version, not the TV shows itself. The update did not yet achieve the hoped result: e.g. Flash is showing in the second screen the other Flash TV series and does only open season 1. Vinyl even less: the app goes directly to the background and no TV show is found.
4. Will share, but the function of the Apple TV is slower and starts to show loading errors with other, from the Apple shop, apps.
5. Please check. Updates of the desktop Popcorn applicatie show new movies. I guess it is the same source. BTW none of them show new movies like ' London has fallen ' or ' Batman vs Superman ' , but that is another point. 
6. I will check out and look for helpers. I do know C++ programmers, but I am not yet sure if they want to help in a torrent stream app on Apple TV. I'll check.

**Comment by buzzel** [comment]
2. Off the top off my head it could be that subtitles for that language aren't been read properly due to formatting. If you can give me a language and movie I can look into it.
3. Just fixed this issue. If you are up for it, feel free to pull that branch and check it out
4. Just double checked here and I dont seem to see anything that would cause issues. There are a few minor leaks, but nothing that would cause things to crash and break. 
5. What popcornTime app are you using, maybe they have a different API. 
6. Sounds good!

**Comment by buzzel** [comment]
@Evhelden 0.6.3 was pushed so give that a try

**Comment by Evhelden** [comment]
Hi Buzzel,

1. Subtitles: Dutch language for ' Deadpool'  (popular), Dutch subtitles for ' Friend for the end of the world ' (latest) and dutch for ' Watch man ' (via search). Noticed that English works for all those films mentioned and some do another language. Never Dutch.
2. TV Shows correct: I have not yet tried 0.6.3. It's been busy and I have issues compiling the sources, which can be solved, but required time to check out. I did last evening check/test against 0.6.2. Vinyl is very clearly not working, please check that one as a good reference of issues in all versions till date. Flash TV series also has issues with the different seasons.
3. Leaks: I notice the operations of the Apple TV impacted. Can not tell (no research/check done) what the cause is. The speed of the device is impacted. Clean reboot solves that: ergo memory leaks remain existing.
4. API: Popcorn time beta 3.9 for Mac from https://popcorntime.sh. Also there no ' London has fallen' , ' Captain America Civil War' or ' Batman vs Superman ' . All releases available on different repositories, but for me not priority over the other issues (Forward/rewind/resume, Correct TV Shows, Subtitles, )
5. C++ and Obj C: Have requested two people, but not yet seeing immediate availability. 

Very happy with the UI and Search functions. Impressed.

**Comment by buzzel** [comment]
@Evhelden 

1. I'll look into that, maybe i'm parsing those wrong. 
2. This should be fixed in 0.6.3 so let me know
3. I'll look into those, but I have not experienced any sort of slow down on my device. 
4. Will look into what API they are using. 
5. Awesome! Thanks!

**Comment by buzzel** [comment]
Going through the Popcorn-Time mac app, there is no difference in the API. Both are returning the same data. I did a search for Captain America and the 2011, and 2014 versions showed up.

**Comment by Evhelden** [comment]
@Buzzel:
Tested against 0.6.3 

1. Subtitles show in movies now. Tried two movies: Deadpool and ' Avengers ' age of Ultron ' , only Dutch. Noticed in ' Avengers, ' Age of Ultron '  sometimes (randomly?) <i> and </i> at start and end of subtitle text. Did not yet try different font sizes and back grounds.
2. Tested series ' Flash '  and ' Vinyl ' . Seems to show perfectly now. Did not go to series with a ' . ' in their name, but I believe this issues can be closed.
3. Update of movies: Yes, they seem to work well. You are correct. It's not yet the newest movies, such as ' Batman vs Superman ' , ' Captain America Civil War ' or ' London has fallen ' , but that is indeed also not the case in the desktop (butter?) version. In other sources, e.g. Movie box or Playbox and ' Movies for tvOS ' this type of movies come, but not always at the highest quality. Current version is indeed same as desktop version. Great.
4. C++ en obj C: Third person asked. Seems considering, but not sure. Pending. 
5. Small cosmetic issue: In top shelf the movies section is called ' latest movies ' , but should be ' popular movies ' . Noticed that ' search ' in movies is capital letters and search in tv shows seems to start with small letters. Genre ' sci-fi '  and ' dark-noir '  do not work. Most probably the ' - ' sign.

I believe with subtitles for TV shows, forward, reverse and resume it could be version 1.0?

**Comment by buzzel** [comment]
Glad most of this stuff is working now. Once the ability to advance when watching shows or movies is implemented, it will be pretty close to 1.0, if not it will be v1.0. As for subtitles for TVShows. I'm using yifysubtitles as OpenSubtitles's API is a pain in the ass to get working. It's so weird too. I'll have to make like 6 network calls just to get a list of subtitles, not to mention downloading them. Something I might experiment in the future with is specific subtitle downloading. Set a language in settings and have it only download that subtitle if its available.
