### ISSUE TITLE
customs subtitles?

### ISSUE THREAD

**Issue by galdo320** [PopcornTimeTV/PopcornTimeTV#107]
there's any way to use customs subtitles? or we'll have another way to download subtitles in future versions like in the Mac version? thanks guys for made PopcornTime & our AppleTV a better device!

**Comment by bubez81** [comment]
i'm interested too

**Comment by Sagi363** [comment]
i'm interested too

**Comment by abusiam84** [comment]
i'm interested too

**Comment by adrienbusin** [comment]
+1

**Comment by guiwunsch** [comment]
+1

**Comment by moh0sw** [comment]
yeah we really need italic of movies the timing is different so wee need to choose another subtitle

**Comment by moh0sw** [comment]
@FlaviaBondJamesBondsHusband when we can see this future ?
estimated ?

**Comment by moh0sw** [comment]
@FlaviaBondJamesBondsHusband ?

**Comment by b1narygh0st** [comment]
tvOS' support of external file handling is very limited at the moment, this would be a nice feature but currently very difficult and "hacky" to implement. 
We will however keep the idea in mind.

**Comment by Lohann** [comment]
+1

**Comment by Lohann** [comment]
A way to increase/decrease the subtitle delay helps too, because most of the subtitles are desynchronized.

**Comment by FlaviaBondJamesBondsHusband** [comment]
This is unfortunately not possible on tvOS
