### ISSUE TITLE
Feature Request: Dark Colour Theme Option

### ISSUE THREAD

**Issue by drew5494** [PopcornTimeTV/PopcornTimeTV#109]
Hey that would be cool to have a dark theme instead of a bright white theme.
Would it be possible?
Thanks!

**Comment by buzzel** [comment]
Since this project is based on TVML the dark theme is completely black like YouTube or Netflix. None of us like that so we have held off on it for now.

**Comment by drew5494** [comment]
@buzzel oh okay np. thanks for the update btw.  How frequent do you expect the updates to be?

**Comment by Sonikkua** [comment]
I prefer bright / colorful anyway, more resembles the homescreen on tvOS and various stock apps. I actually hate that some developers went lazy and just used old ATV3/2/1 apps unchanged and black (looking at you Netflix),

**Comment by drew5494** [comment]
@Sonikkua  I agree but a night mode for those late night movies wouldnt be so bad.  Ya netflix is kind of dull  I guess.
