### ISSUE TITLE
Hang on Installing TVVLCKit-unstable (3.0.0a22)

### ISSUE THREAD

**Issue by bubez81** [PopcornTimeTV/PopcornTimeTV#109]
Hi i'm trying to compile popcorntimetv but when i run pod install i get this:
`Downloading dependencies
Installing AEXML (4.0.1)
Installing Alamofire (4.0.1)
Installing AlamofireXMLRPC (2.1.0)
Installing GCDWebServer (3.3.4)
Installing ObjectMapper (2.0.0)
Installing PopcornKit (2.0.0)
Installing PopcornTorrent (1.1.1.7)
Installing SwiftyJSON (3.1.0)
Installing TVMLKitchen (0.9.6)
Installing TVVLCKit-unstable (3.0.0a22)`

and then nothing....

**Comment by moh0sw** [comment]
@bubez81 no bro it is not hanging, it's installing TVVLCKit-unstable the size is (400M) so thats why it takes so long
Run `pod install --verbose` or `pod update --verbose` and it will show you the exact process and what is the percent of installing

Good luck

**Comment by bubez81** [comment]
i'm a very stupid person...
