### ISSUE TITLE
Charset for subtitle

### ISSUE THREAD

**Issue by abufreeh** [PopcornTimeTV/PopcornTimeTV#11]
recently I compile an AppleTV4 version , I notice if we choose Arabic subtitle it does retrieve the subtitle but when it's showed with wrong charset ... it should be Arabic ISO .. or Arabic Windows
can anyone point me to the code to change the default charset until the team fix all subtitle issues 

Best regards

**Comment by iAYMANi** [comment]
Back to Version 1.0.0
The version 1.0.1 does not work Subtitle until now

**Comment by abufreeh** [comment]
thanks, it's Version 1.0.0 (12)
do u mean this version ?
cause with this version I can't get correct font charset

**Comment by abufreeh** [comment]
I thought seen something like UTF8?? is it's needed for some langs. ? if so how to recompile and enable this option

BR

**Comment by tvOSPopcorn** [comment]
If you're able to fix the Arabic subtitles issue, you're more than welcome to submit a Pull Request.

**Comment by abufreeh** [comment]
well, am newbie with GitHub service how to Pull Request ?

BR

**Comment by BilalBaydoun** [comment]
He meant if you have the fix just put it in Pull request so they can update the source code.

**Comment by BilalBaydoun** [comment]
I found this in old post 

 ```
   if([name isEqualToString:@"Turkish"]){
        NSData* dataFile = [NSData dataWithContentsOfFile:path];
        CFStringRef cfstring = CFStringCreateWithBytes(kCFAllocatorDefault, dataFile.bytes, dataFile.length, kCFStringEncodingISOLatin5, YES);
        string = (__bridge NSString *)cfstring;
        CFRelease(cfstring);
    }
```

if we did the same for arabic it will solve the issue I think but I couldn't find this code in the project to modify it.

http://webcache.googleusercontent.com/search?q=cache:https://github.com/PopcornTimeTV/PopcornTimeTV/issues/116

**Comment by abufreeh** [comment]
sounds great .. Arabic should be "ISO 8859-6" , and Hebrew "ISO 8859-6"

**Comment by abufreeh** [comment]
well, I think it's something related to TVVLCKit ! and it's a Binary file

**Comment by moh0sw** [comment]
the arabic subtitles problem will take for ever :(
when the PopcornTimeTV have released the Arabic Problem is in every version !

**Comment by abufreeh** [comment]
what about Hebrew , it's not complex chars ?

**Comment by popcornMaster** [comment]
We have added the ability to manually select your preferred encoding and will be in the next version. You can already check and see if it works for you guys with by using git pull inside the directory of the project

**Comment by garranhado** [comment]
Last commit changed font size for subtitles.
On TV is too small, can't read.

**Comment by popcornMaster** [comment]
I forgot to change the predefined value, either do another git pull or select from the settings menu your preferred font size :)

**Comment by abufreeh** [comment]
still can't see readable hebrew chars but no problem with arabic..
p.s
how update changes easly to local github

best regards, for the great work

**Comment by FlaviaBondJamesBondsHusband** [comment]
@abufreeh `git pull`

**Comment by abufreeh** [comment]
yes it's suppose to be , but sometimes I get something like this:
MacPro:masterclone mm$ git pull git@github.com:PopcornTimeTV/PopcornTimeTV.git -f
From github.com:PopcornTimeTV/PopcornTimeTV
 * branch            HEAD       -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	PopcornTime/Info.plist
Please, commit your changes or stash them before you can merge.
Aborting
MacPro:masterclone mm$ 


I did not make any changes !

**Comment by popcornMaster** [comment]
If Hebrew do not work, then just select a different encoding for the subtitles from the menu and see when those subtitles work! It is usual that ISO is not used but the windows equivalent of the ISO since many subs are made on windows computers! I am closing this issue as resolved, for any issues with subtitles, please try testing other encodings!
