### ISSUE TITLE
Add a subtitles client

### ISSUE THREAD

**Issue by pepibumur** [PopcornTimeTV/PopcornTimeTV#11]
**Reference** http://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC

**Comment by diogoviannaaraujo** [comment]
Hi, i was interested in trying to implement this if not very hard, i have some code experience but no experience with obj-c or swift directly, was thinking on helping on the project as a way of learning.

Any other ideas or known challenges on implementing it? ive found this opensubtitles api https://github.com/orta/OROpenSubtitleDownloader, do apple tv read srt? dont think so..

**Comment by iAYMANi** [comment]
**I have a question: Will add Subtitles option later on or not?**

Thank you for this great work

**Comment by diogoviannaaraujo** [comment]
Now that i see you guys are using VLC as player framework does it support playing srt subtitles?

**Comment by sasagr** [comment]
I hope so too. I do not see it in the Wiki/Progress. Does it mean that it is not in the future plan?

**Comment by buzzel** [comment]
Added in 7fc550fa8f7bcd8c812224d1e6f989be86396b4f

**Comment by tomto147** [comment]
@buzzel 
How do we access subtitles options? 
Swipe from up does not function, and setiings menu is also dead in my version ;-)

**Comment by pbo1976** [comment]
Hi, so what is the deal with subtitles? Also, the navigation controls while the movie is playing are not clear. 
Thanks

**Comment by pbo1976** [comment]
Everything else looks AMAZING! Love this btw!
