### ISSUE TITLE
version ipa 1.0.3.2

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeTV#110]
version 1.0.3.2 ipa appdb.cc thank you friend

**Comment by galdo320** [comment]
i dont see the 1.0.3.2 in appdb.cc

**Comment by chocolatesuper** [comment]
I also do not see anything version 1.0.3.2 ipa appdb.cc I ask still stand that is not in the page friend appdb.cc

**Comment by moh0sw** [comment]
@chocolatesuper Bro u really can't understand!
The developers said there is a problems with the new versions!
And you keep opining issues abot IPA's!
Bro calm down they said the update is very soon

**Comment by FlaviaBondJamesBondsHusband** [comment]
@chocolatesuper We do not have any affiliation with appdb.cc and will not be releasing ipa's as that is misusing Apples developer ToS.

**Comment by iAYMANi** [comment]
i dont see the new Beta 2.0.0 in appdb.cc
