### ISSUE TITLE
Language selection on settings

### ISSUE THREAD

**Issue by damianxd** [PopcornTimeTV/PopcornTimeTV#111]
First, Thanks for the great work! This is an amazing app and I have been using it from months so far without any big troubles except for the occasional crash. But this time I have a request to make that drives me crazy. Could you make an option on settings where we could pick up the languages we want to display on the player? because it is a pain in the ass to scroll way down to the spanish subs and every time I touch the remote by mistake and choose another language, I have to scroll again and try not to select the wrong one again.

Once again, thanks for everything you're doing with this project.

Kind regards

**Comment by FlaviaBondJamesBondsHusband** [comment]
Will add this to the todo list; Glad you're enjoying the app!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for suggesting this feature. Enjoy!
