### ISSUE TITLE
New App Icons

### ISSUE THREAD

**Issue by FarFromNormal** [PopcornTimeTV/PopcornTimeTV#112]
For anyone who cares, this is the icon I changed mine to on my Apple TV. Thought maybe someone else would like it.
![rectangle 13 popcorn time](https://cloud.githubusercontent.com/assets/19393371/15372905/6f19f236-1d08-11e6-8f71-e9d265bd8b94.png)
![small - back](https://cloud.githubusercontent.com/assets/19393371/15372904/6f1887a2-1d08-11e6-9407-1d6c3118c268.png)

**Comment by FarFromNormal** [comment]
Forgot that the smaller one has to have 2 layers so I just made a transparent png the same size as the back image. So here it is.
![clear](https://cloud.githubusercontent.com/assets/19393371/15373574/f9f94a34-1d0b-11e6-97f9-6d56cec53cdb.png)

**Comment by buzzel** [comment]
Closing this as it's not a relevant bug or issue with the app. 

A new app icon is being worked on, just nothing final.

**Comment by FarFromNormal** [comment]
Cool TY @buzzel

**Comment by drew5494** [comment]
Looks kinda dated I like the current one.  No offence.
