### ISSUE TITLE
Feature Request - Actor/Actress and Director Images + Bio

### ISSUE THREAD

**Issue by ArsalanS1** [PopcornTimeTV/PopcornTimeTV#113]
Was thinking we could implement something like what Squire Media Centre have done where we have clickable links for Actor/Actress/Director with spherical images which takes them to a short bio of them maybe taken from Wikipedia somehow.

**Comment by buzzel** [comment]
This currently isn't a top priority, but it sounds like a good idea to me. Feel free to submit a PR :)

**Comment by lukaskuster** [comment]
Actually working on this one 😉

**Comment by lukaskuster** [comment]
But more like the iTunes Store if you click on the Actor/Actress/Director it will show all of the credited movies and tv shows.

**Comment by buzzel** [comment]
@lukaskuster This sounds awesome! Can't wait to check it out!
