### ISSUE TITLE
API resign

### ISSUE THREAD

**Issue by pbo1976** [PopcornTimeTV/PopcornTimeTV#113]
After downloading the API file..., can someone please explain the next steps to install it? 

Thank you.

**Comment by pbo1976** [comment]
@FlaviaBondJamesBondsHusband did I do something wrong? a little help on what I am asking would have been nice and appreciated.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Apologies, I thought your question was a troll. What exactly is your problem, your description a little unclear (there is no API file and that makes no sense either). The application is broken ATM as we are mid-way through fixing it. Make sure to read the other issues before posting your own! Apologies again.

**Comment by pbo1976** [comment]
Ok. I was referring to the API file linked in your description (see pic).

Cant wait to have successful Build soon! thanks,
p.


![screen shot 2016-10-08 at 17 27 07](https://cloud.githubusercontent.com/assets/19353495/19214106/98b8135e-8d7c-11e6-9c88-d26c262994f8.png)

**Comment by bubez81** [comment]
IPA file not API :)

**Comment by moh0sw** [comment]
Will if you was meaning the ipa file just use iOS App Signer or Impactor to
resign the ipa then you are ready to install!

**Comment by FlaviaBondJamesBondsHusband** [comment]
@pbo1976 theres a big difference between an IPA file and and API file :). Hang tight, a stable(ish) version should be pushed tonight :)
