### ISSUE TITLE
Theme Music Continue's Playing...

### ISSUE THREAD

**Issue by FarFromNormal** [PopcornTimeTV/PopcornTimeTV#114]
Just noticed this as I was adding stuff to my watchlist. When you go to a tv show and the theme music starts up, if you back out to the main app screen it continues playing the music instead of cutting off. Not sure if this is just a bug on my end, its intended to play through the theme song or what. Just an FYI though. It would make more sense for it to cut off if you back out of that series.

**Comment by buzzel** [comment]
Yeah. currently there isn't a callback that says when you stop viewing a TV show to stop the music. @tengis is looking into it on the TVMLKitchen side.

**Comment by drew5494** [comment]
Ya i turned the feature off cause of his issue. 
Hopefully you can fix it ;)
