### ISSUE TITLE
installing TVVLCKit-unstable

### ISSUE THREAD

**Issue by sayed001** [PopcornTimeTV/PopcornTimeTV#114]
Installing TVVLCKit-unstable (3.0.0a22)

[!] Error installing TVVLCKit-unstable
Verification checksum was incorrect, expected 71691951e9c035260d4daa2432db78027e1000cafad8347c153f52d9b7e6b18b, got dc5078d9bc9e43c3ecd33d8f37659bb1fc6fb9da08804afff4c1d81f38849cea

**Comment by sayed001** [comment]
when running pod install , i get this error.

**Comment by sayed001** [comment]
Downloading dependencies
Installing AEXML (4.0.1)
Installing Alamofire (4.0.1)
Installing AlamofireXMLRPC (2.1.0)
Installing GCDWebServer (3.3.4)
Installing ObjectMapper (2.0.0)
Installing PopcornKit (2.0.0)
Installing PopcornTorrent (1.1.1.8)
Installing SwiftyJSON (3.1.0)
Installing TVMLKitchen (0.9.6)
Installing TVVLCKit-unstable (3.0.0a22)

[!] Error installing TVVLCKit-unstable
Verification checksum was incorrect, expected 71691951e9c035260d4daa2432db78027e1000cafad8347c153f52d9b7e6b18b, got dc5078d9bc9e43c3ecd33d8f37659bb1fc6fb9da08804afff4c1d81f38849cea

**Comment by FlaviaBondJamesBondsHusband** [comment]
Make sure you have the latest version of the project cloned. This looks like an issue with your cocoapods installation

**Comment by sayed001** [comment]
My bad i guess the issue is the version of the xcode .. am using xcode 8

**Comment by sayed001** [comment]
Will reinstall xcode 7.3 and will update
