### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by FarFromNormal** [PopcornTimeTV/PopcornTimeTV#115]
It was working great earlier today but tonight I turn on my apple tv and it just sits on a white screen. Any ideas?

**Comment by Kamakiri77** [comment]
Same here. Was hoping there was an update

**Comment by tengis** [comment]
Should be fine now.

**Comment by Kamakiri77** [comment]
It's still not fine

**Comment by tengis** [comment]
@Kamakiri77 Could you kill the app from background applications then try it again?

**Comment by tengis** [comment]
@Kamakiri77 I mean force quite have a look this instructions http://www.howtogeek.com/232960/how-to-force-quit-an-app-on-your-apple-tv/

**Comment by FarFromNormal** [comment]
It's working again for me. So issue can be closed whenever it is resolved for @Kamakiri77.

**Comment by FarFromNormal** [comment]
And I have no solution cause it just started working again for me.

**Comment by Kamakiri77** [comment]
Just started working again for me too

**Comment by buzzel** [comment]
Fixed I guess?

**Comment by pbo1976** [comment]
It's happening to me now as well.

**Comment by Argon2000** [comment]
Happening to me now

**Comment by amilajack** [comment]
I haven't dug into the source but it could be because the API endpoint may be temporarily down. This has happened to me on other platforms.

**Comment by Argon2000** [comment]
Sorry, this was caused by an expired certificate used to sign the app. Sucks that they decreased the length to 7 days from 90...

**Comment by RefusedFlow** [comment]
This should be addressed in the ReadME.md file... Unless your the application is signed by a developer account as an IPA the application will expire after 7 days, unfortunatly a bit of a change from the previous 90 days

**Comment by pbo1976** [comment]
Is there a Developer with a pay account willing to share and sign this project?
