### ISSUE TITLE
[!] Error installing AlamofireXMLRPC  need help please 

### ISSUE THREAD

**Issue by camron114** [PopcornTimeTV/PopcornTimeTV#116]
[!] Error installing AlamofireXMLRPC
[!] /usr/bin/git clone https://github.com/PopcornTimeTV/AlamofireXMLRPC.git /var/folders/jk/5vkj_pzj5snft9tyzdg1bnz00000gn/T/d20161009-6261-f9yo6l --template= --single-branch --depth 1

Cloning into '/var/folders/jk/5vkj_pzj5snft9tyzdg1bnz00000gn/T/d20161009-6261-f9yo6l'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/PopcornTimeTV/AlamofireXMLRPC.git/'

**Comment by FlaviaBondJamesBondsHusband** [comment]
Please use the Swift3.0 branch
