### ISSUE TITLE
error project xcode 8

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeTV#117]
<img width="1440" alt="captura de pantalla 2016-10-10 a las 17 48 25" src="https://cloud.githubusercontent.com/assets/22038180/19253608/eec953b6-8f11-11e6-9cd6-08eab28dbe07.png">

error project xcode 8 

Command /bin/sh failed with exit code 1  Swift3.0  project

**Comment by chocolatesuper** [comment]
<img width="1440" alt="captura de pantalla 2016-10-10 a las 17 59 55" src="https://cloud.githubusercontent.com/assets/22038180/19253804/73e2405c-8f13-11e6-9e2b-954f5ec7e352.png">

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue should be fixed now, thanks for reporting :)
