### ISSUE TITLE
error terminal  project 

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeTV#118]
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine jso

terminal problem

**Comment by FlaviaBondJamesBondsHusband** [comment]
What commands did you run in terminal? Could you please provide a screenshot

**Comment by chocolatesuper** [comment]
<img width="1440" alt="captura de pantalla 2016-10-11 a las 09 18 06" src="https://cloud.githubusercontent.com/assets/22038180/19273893/d3a4ee92-8f93-11e6-80d4-88d1839ea6ad.png">

**Comment by FlaviaBondJamesBondsHusband** [comment]
What commands did you run?

**Comment by chocolatesuper** [comment]
the errors appears when i run swift.install.switf

**Comment by FlaviaBondJamesBondsHusband** [comment]
Install script is working perfectly. Please redownload the master repo

**Comment by rafaelfsramos** [comment]
@FlaviaBondJamesBondsHusband 

The issue in Terminal still continues. i don't get run in xcode

$ swift install.swift
install.swift:5:18: error: 'NSURLSession' has been renamed to 'URLSession'
public extension NSURLSession {
                 ^~~~~~~~~~~~
                 URLSession
install.swift:10:24: error: 'dispatch_semaphore_t' is unavailable in Swift
        let semaphore: dispatch_semaphore_t = dispatch_semaphore_create(0)
                       ^~~~~~~~~~~~~~~~~~~~
install.swift:11:20: error: 'NSURLSession' has been renamed to 'URLSession'
        let task = NSURLSession.sharedSession().dataTaskWithRequest(request, completionHandler: {
                   ^~~~~~~~~~~~
                   URLSession
install.swift:25:41: error: 'NSURL' is not implicitly convertible to 'URL'; did you mean to use 'as' to explicitly convert?
        let request = NSURLRequest(URL: url)
                                        ^
                                            as URL
install.swift:31:26: error: 'NSURLSession' has been renamed to 'URLSession'
        guard let data = NSURLSession.requestSynchronousData(request) else {return nil}
                         ^~~~~~~~~~~~
                         URLSession
install.swift:38:47: error: 'NSURL' is not implicitly convertible to 'URL'; did you mean to use 'as' to explicitly convert?
        let request = NSMutableURLRequest(URL:url)
                                              ^
                                                  as URL
install.swift:46:16: error: 'NSTask' has been renamed to 'Process'
    let task = NSTask()
               ^~~~~~
               Process
install.swift:57:20: error: 'NSFileHandle' has been renamed to 'FileHandle'
    let keyboard = NSFileHandle.fileHandleWithStandardInput()
                   ^~~~~~~~~~~~
                   FileHandle
install.swift:65:4: error: missing argument label 'args:' in call
run("-c", "git stash", "git fetch", "git rebase")
   ^
    args: 
install.swift:72:19: error: 'NSURLSession' has been renamed to 'URLSession'
if let jsonData = NSURLSession.requestSynchronousJSONWithURLString("https://api.github.com/repos/PopcornTimeTV/PopcornTimeTV/releases") as? [[String : AnyObject]] {
                  ^~~~~~~~~~~~
                  URLSession
install.swift:86:21: error: missing argument label 'input:' in call
let version = input("Enter the version number: ")
                    ^
                    input: 
install.swift:102:27: error: missing argument label 'input:' in call
let podsInstalled = input("Do you have cocoapods installed? (Enter Yes or No): ").lowercaseString
                          ^
                          input: 
install.swift:105:8: error: missing argument label 'args:' in call
    run("-c", "sudo gem install cocoapods")
       ^
        args: 
install.swift:110:4: error: missing argument label 'args:' in call
run("-c","rm -rf ~/.cocoapods/repos/PopcornTimeTV")
   ^
    args: 
install.swift:111:4: error: missing argument label 'args:' in call
run("-c","rm -rf Podfile.lock")
   ^
    args: 
install.swift:112:4: error: missing argument label 'args:' in call
run("-c","pod cache clean --all")
   ^
    args: 
install.swift:113:4: error: missing argument label 'args:' in call
run("-c","rm -rf ~/Library/Developer/Xcode/DerivedData/PopcornTime-*")
   ^
    args: 
install.swift:114:4: error: missing argument label 'args:' in call
run("-c","pod repo remove popcornmaster;pod setup;pod repo update")
   ^
    args: 
install.swift:115:4: error: missing argument label 'args:' in call
run("-c","pod install")
   ^
    args: 
install.swift:116:4: error: missing argument label 'args:' in call
run("-c","pod update")
   ^
    args: 
install.swift:121:4: error: missing argument label 'args:' in call
run("-c", "open PopcornTime.xcworkspace")
   ^
    args:
