### ISSUE TITLE
Issues when changing Subtitle encoding and the player has so much issues!

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#119]
when trying to change the subtitle encoding it crash immediately with the latest commit
and now I can't use the options when starting the movie ( changing the subtitle language etc. ) nothing appears! it is just showing me the movie and can't forward or see the time or any thing just the movie or the tv show!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Latest release is barely stable as mentioned in the release notes
