### ISSUE TITLE
Can't open show 'Mr Robot'

### ISSUE THREAD

**Issue by carlosesteves** [PopcornTimeTV/PopcornTimeTV#12]
When I open the app and select Mr Robot the app doesn't open the show details page.
[
<img width="538" alt="screen shot 2016-08-13 at 19 38 19" src="https://cloud.githubusercontent.com/assets/3245520/17644920/a4d95fa0-618d-11e6-9aa0-9add2637212e.png">
](url)

**Comment by tvOSPopcorn** [comment]
Have you tried deleting the application and rebuilding? This use to be an issue months ago but was since fixed and hasn't occurred since in our testing, let me know if that fixes things! 😄 

BTW good choice Mr.Robot is a great series ❤️

**Comment by carlosesteves** [comment]
Oh, it worked! Thanks a lot!
Yeah, pretty awesome series! 👍
