### ISSUE TITLE
Popcorn Time TVOS

### ISSUE THREAD

**Issue by Danieljflopes** [PopcornTimeTV/PopcornTimeTV#120]
Hi!
2 days ago I purchased an account on IPWNSTORE so that I could sideload Popcorn time to my Apple TV 4. Everthing worked just fine... until yesterday. Now it doesn't load. It just displays a blank screen and doesn't work. I've tried erasing it and reinstalling but the problem persists. Also restored apple TV 4 with iTunes but same issue. Any suggestions? Help would be highly appreciated :) Thanks in advance.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Should be working again, would you mind testing?

**Comment by Danieljflopes** [comment]
Yep. Working. Thanks. Might as well ask the following: when I try to play the tv show "How to get away with murder" (latest season) why does it always crash the app?

**Comment by FlaviaBondJamesBondsHusband** [comment]
No idea, the version you are using is outdated so it is using the old API's which were riddled with problems.
