### ISSUE TITLE
Still playing after Atv4 gone to sleep (not an Issue)

### ISSUE THREAD

**Issue by pbo1976** [PopcornTimeTV/PopcornTimeTV#120]
Just wanted to share the following: 

My Atv4 is set to sleep after 30 minutes or so, so after I paused a movie while in PopcornTime and gone into sleep mode, after waking my device the movie was still paused and continued playing flawlessly. Nice!

**Comment by buzzel** [comment]
Glad it works 👍

**Comment by pbo1976** [comment]
@buzzel Hi, where can I find in Xcode how to make bigger fonts for the "loading page" (while processing the movie about to watch - with the progress bar, etc...)? Thanks!
