### ISSUE TITLE
Error Terminal 

### ISSUE THREAD

**Issue by rafaelfsramos** [PopcornTimeTV/PopcornTimeTV#121]
@popcornMaster 

The issue in Terminal still continues. i don't get run in xcode

$ swift install.swift
install.swift:5:18: error: 'NSURLSession' has been renamed to 'URLSession'
public extension NSURLSession {
^~~~~~~~~~~~
URLSession
install.swift:10:24: error: 'dispatch_semaphore_t' is unavailable in Swift
let semaphore: dispatch_semaphore_t = dispatch_semaphore_create(0)
^~~~~~~~~~~~~~~~~~~~
install.swift:11:20: error: 'NSURLSession' has been renamed to 'URLSession'
let task = NSURLSession.sharedSession().dataTaskWithRequest(request, completionHandler: {
^~~~~~~~~~~~
URLSession
install.swift:25:41: error: 'NSURL' is not implicitly convertible to 'URL'; did you mean to use 'as' to explicitly convert?
let request = NSURLRequest(URL: url)
^
as URL
install.swift:31:26: error: 'NSURLSession' has been renamed to 'URLSession'
guard let data = NSURLSession.requestSynchronousData(request) else {return nil}
^~~~~~~~~~~~
URLSession
install.swift:38:47: error: 'NSURL' is not implicitly convertible to 'URL'; did you mean to use 'as' to explicitly convert?
let request = NSMutableURLRequest(URL:url)
^
as URL
install.swift:46:16: error: 'NSTask' has been renamed to 'Process'
let task = NSTask()
^~~~~~
Process
install.swift:57:20: error: 'NSFileHandle' has been renamed to 'FileHandle'
let keyboard = NSFileHandle.fileHandleWithStandardInput()
^~~~~~~~~~~~
FileHandle
install.swift:65:4: error: missing argument label 'args:' in call
run("-c", "git stash", "git fetch", "git rebase")
^
args: 
install.swift:72:19: error: 'NSURLSession' has been renamed to 'URLSession'
if let jsonData = NSURLSession.requestSynchronousJSONWithURLString("https://api.github.com/repos/PopcornTimeTV/PopcornTimeTV/releases") as? [[String : AnyObject]] {
^~~~~~~~~~~~
URLSession
install.swift:86:21: error: missing argument label 'input:' in call
let version = input("Enter the version number: ")
^
input: 
install.swift:102:27: error: missing argument label 'input:' in call
let podsInstalled = input("Do you have cocoapods installed? (Enter Yes or No): ").lowercaseString
^
input: 
install.swift:105:8: error: missing argument label 'args:' in call
run("-c", "sudo gem install cocoapods")
^
args: 
install.swift:110:4: error: missing argument label 'args:' in call
run("-c","rm -rf ~/.cocoapods/repos/PopcornTimeTV")
^
args: 
install.swift:111:4: error: missing argument label 'args:' in call
run("-c","rm -rf Podfile.lock")
^
args: 
install.swift:112:4: error: missing argument label 'args:' in call
run("-c","pod cache clean --all")
^
args: 
install.swift:113:4: error: missing argument label 'args:' in call
run("-c","rm -rf ~/Library/Developer/Xcode/DerivedData/PopcornTime-*")
^
args: 
install.swift:114:4: error: missing argument label 'args:' in call
run("-c","pod repo remove popcornmaster;pod setup;pod repo update")
^
args: 
install.swift:115:4: error: missing argument label 'args:' in call
run("-c","pod install")
^
args: 
install.swift:116:4: error: missing argument label 'args:' in call
run("-c","pod update")
^
args: 
install.swift:121:4: error: missing argument label 'args:' in call
run("-c", "open PopcornTime.xcworkspace")
^
args:

**Comment by tomsbrinkis** [comment]
same for me. what can we do? 

`Tomss-MacBook:PopcornTimeTV Toms$ cd ~/Desktop/PopcornTimeTV
Tomss-MacBook:PopcornTimeTV Toms$ swift install.swift
install.swift:5:18: error: 'NSURLSession' has been renamed to 'URLSession'
public extension NSURLSession {
                 ^~~~~~~~~~~~
                 URLSession
install.swift:10:24: error: 'dispatch_semaphore_t' is unavailable in Swift
        let semaphore: dispatch_semaphore_t = dispatch_semaphore_create(0)
                       ^~~~~~~~~~~~~~~~~~~~
install.swift:11:20: error: 'NSURLSession' has been renamed to 'URLSession'
        let task = NSURLSession.sharedSession().dataTaskWithRequest(request, completionHandler: {
                   ^~~~~~~~~~~~
                   URLSession
install.swift:25:41: error: 'NSURL' is not implicitly convertible to 'URL'; did you mean to use 'as' to explicitly convert?
        let request = NSURLRequest(URL: url)
                                        ^
                                            as URL
install.swift:31:26: error: 'NSURLSession' has been renamed to 'URLSession'
        guard let data = NSURLSession.requestSynchronousData(request) else {return nil}
                         ^~~~~~~~~~~~
                         URLSession
install.swift:38:47: error: 'NSURL' is not implicitly convertible to 'URL'; did you mean to use 'as' to explicitly convert?
        let request = NSMutableURLRequest(URL:url)
                                              ^
                                                  as URL
install.swift:46:16: error: 'NSTask' has been renamed to 'Process'
    let task = NSTask()
               ^~~~~~
               Process
install.swift:57:20: error: 'NSFileHandle' has been renamed to 'FileHandle'
    let keyboard = NSFileHandle.fileHandleWithStandardInput()
                   ^~~~~~~~~~~~
                   FileHandle
install.swift:65:4: error: missing argument label 'args:' in call
run("-c", "git stash", "git fetch", "git rebase")
   ^
    args: 
install.swift:72:19: error: 'NSURLSession' has been renamed to 'URLSession'
if let jsonData = NSURLSession.requestSynchronousJSONWithURLString("https://api.github.com/repos/PopcornTimeTV/PopcornTimeTV/releases") as? [[String : AnyObject]] {
                  ^~~~~~~~~~~~
                  URLSession
install.swift:86:21: error: missing argument label 'input:' in call
let version = input("Enter the version number: ")
                    ^
                    input: 
install.swift:102:27: error: missing argument label 'input:' in call
let podsInstalled = input("Do you have cocoapods installed? (Enter Yes or No): ").lowercaseString
                          ^
                          input: 
install.swift:105:8: error: missing argument label 'args:' in call
    run("-c", "sudo gem install cocoapods")
       ^
        args: 
install.swift:110:4: error: missing argument label 'args:' in call
run("-c","rm -rf ~/.cocoapods/repos/PopcornTimeTV")
   ^
    args: 
install.swift:111:4: error: missing argument label 'args:' in call
run("-c","rm -rf Podfile.lock")
   ^
    args: 
install.swift:112:4: error: missing argument label 'args:' in call
run("-c","pod cache clean --all")
   ^
    args: 
install.swift:113:4: error: missing argument label 'args:' in call
run("-c","rm -rf ~/Library/Developer/Xcode/DerivedData/PopcornTime-*")
   ^
    args: 
install.swift:114:4: error: missing argument label 'args:' in call
run("-c","pod repo remove popcornmaster;pod setup;pod repo update")
   ^
    args: 
install.swift:115:4: error: missing argument label 'args:' in call
run("-c","pod install")
   ^
    args: 
install.swift:116:4: error: missing argument label 'args:' in call
run("-c","pod update")
   ^
    args: 
install.swift:121:4: error: missing argument label 'args:' in call
run("-c", "open PopcornTime.xcworkspace")
   ^
    args: 
Tomss-MacBook:PopcornTimeTV Toms$ 
`

**Comment by rarias84** [comment]
[!] Error installing TVVLCKit-unstable
[!] /usr/bin/curl -f -L -o /var/folders/pw/mjy9db3j45nf1rndd7kt_w1m0000gn/T/d20161012-1448-xqsvyl/file.zip http://download.videolan.org/pub/cocoapods/unstable/TVVLCKit-unstable-3.0.0a10.zip --create-dirs --netrc

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1  408M    1 5698k    0     0  27035      0  4:24:07  0:03:35  4:20:32 27072
curl: (56) Recv failure: Operation timed out

**Comment by FlaviaBondJamesBondsHusband** [comment]
hmmm what do you do? Maybe you download the latest source code off the repo?

**Comment by tomsbrinkis** [comment]
@FlaviaBondJamesBondsHusband i do step by step instalation. Bu then i type to swift install.swift then an error pops.

**Comment by FlaviaBondJamesBondsHusband** [comment]
@tomsbrinkis no you didn't. Re-download the master repo and try again. You are using an outdated version.
