### ISSUE TITLE
Subtitles on Tv shows

### ISSUE THREAD

**Issue by diogoviannaaraujo** [PopcornTimeTV/PopcornTimeTV#122]
Hey, i see you only have subtitles on movies because u have been using imdb code to get from yify subtitles.
Maybe an aproach to tvshows could be using opensubtitles, they have a hash code in swift here:
https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes#SWIFT2
I know you can do that hash with loading torrents, maybe u ll have to wait for some chunks...

It would work for movies too, maybe as main one or as a fallback

Im reading and learning, swift and object c still quite difficult for me

**Comment by ceuaugusto** [comment]
I think that's the same thing that happens on the windows and OS X apps as well. When you watch a TV show, there's no option to choose a subtitle.

**Comment by diogoviannaaraujo** [comment]
Yes, ther is, at least the one i use there is, and there is easier ways to do it too, opensubtitles have a filename based search too

**Comment by buzzel** [comment]
Everyone is quite busy right now so feel free to submit a PR. If you do plan on using OpenSubtitles for TV Shows, swap out the current YIFYSubtitles for movies as well.

**Comment by diogoviannaaraujo** [comment]
I ve been trying to read the code to try to understand and learn some Swift, but as a JS programmer Im still clibing that learning curve..
Maybe someday I will be able,
Wishing for a full featured react native for apple tv

**Comment by buzzel** [comment]
Some subtitle fixes and support for TV shows were pushed to the master branch. Feel free to give it a go and see how it works.

**Comment by buzzel** [comment]
Version 0.6.4 has support for this
