### ISSUE TITLE
Change the way scrubbing works

### ISSUE THREAD

**Issue by reejosamuel** [PopcornTimeTV/PopcornTimeTV#123]
on 0.6.3 the scrubbing does work well at all but the worse problem is touching the trackpad directly scrubbs.

The general behaviour on tv apps is click to enable scrubbing mode and then scrubbing works.

**Comment by buzzel** [comment]
This should be addressed in the mast branch. An actual release will be out shortly.

**Comment by buzzel** [comment]
Version 0.6.4 should fix this
