### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Danieljflopes** [PopcornTimeTV/PopcornTimeTV#123]
Hi. 
I double checked that I'm on the latest version (1.0.3.1(46)) and the app still crashes when I play the TV Show "How to get away with murder". Any thoughts???

Thanks for your help and keep up the good work. You app is top notch!!!

**Comment by FlaviaBondJamesBondsHusband** [comment]
As stated in the Readme, we are not responsible for any bugs in precompiled versions of our app that are hosted on appdb or anywhere else. You do not have the latest version. This issues does not exist in the latest version
