### ISSUE TITLE
Provisioning files expired - 7 days?

### ISSUE THREAD

**Issue by tomto147** [PopcornTimeTV/PopcornTimeTV#124]
Guys, I am new to this world ;-)
Is there a way to get more that 7 days o app signature on provision files?
My installed PopcornApp stopped working today (after 7 days) and I had to install it under new signature from different account.

**Comment by pbo1976** [comment]
I get a similar alert:

The provisioning profile "tvOS Team Provisioning Profile: com.xxxxx.PopcornTime" is expiring soon

what does this mean???

**Comment by tomto147** [comment]
The installed app will not run after 7 days from the initial signature... this is apple thing of limiting test version of the apps.

**Comment by pbo1976** [comment]
So, I'm supposed to reinstall it every 7 days? Isn't there another way to do it? I mean, I did a sideload of kodi more than a week ago and the app still runs...

**Comment by tomto147** [comment]
This was also my question... I'm not an expert, but my PopcornApp stoped working just today in the morning and I hade to sideload it again from different account.

**Comment by pbo1976** [comment]
Is it possible to create an .ipa file, sign it and install it the same way as Kodi?

**Comment by tomto147** [comment]
@pbo1976 
Give mr you email I can send you ipa file with my signature, maybe you will manage to resign it

**Comment by pbo1976** [comment]
Thanks! I'll give it a try!

**Comment by pbo1976** [comment]
@tomto147 I couldn't manage to make it work. Thanks anyway.

**Comment by pbo1976** [comment]
Murphy's law, my Kodi app stopped working today. Had to re-sideload again. It's kind of annoying if I have to do this every week, there's have to be a better way - right?

**Comment by buzzel** [comment]
The only option here is to but the $99 membership from Apple. Then apps last 365 days.

**Comment by tomto147** [comment]
I think there is another option for just 12$ a year ;-) not that I am advertising but it worked for me. http://ipwnstore.me. They have just launched tvOS version and they pull also Popcorn app. As far as I understan they sign with this full certificate and use yor device ID.

**Comment by FarFromNormal** [comment]
I have had kodi sideloaded for months, using a free developer acccount, and have never had it stop working. I have also had the latest version of popcorntime installed for a couple weeks and it to still works fine.

**Comment by FarFromNormal** [comment]
So my popcorntime expired on Tuesday and just today got around to fixing it. It seemed pretty quick and painless and I didn't need to create a whole new account to get it back going. Does it suck doing this once a week, yeah...but compared to paying $99 for a full developer account it seems like a small price to pay to being able to use this app on our Apple TV's. Kodi has not expired on me and I have had it installed for months. Although, I know it needs to be updated and would hate to start running into this issue. But this is a popcorntime discussion board after all so I will leave it at that.

**Comment by buzzel** [comment]
Closing this as it is irrelevant to the project.
