### ISSUE TITLE
Cloning https://github.com/PopcornTimeTV/Specs.git

### ISSUE THREAD

**Issue by rarias84** [PopcornTimeTV/PopcornTimeTV#124]
When I ran install.swift , after install cocoapods, say Cloning spec repo `popcorntimetv` from `https://github.com/PopcornTimeTV/Specs.git` , ask for username GitHub and don't do nothing

When I ran install.swift , after install cocoapods, show Cloning spec repo `popcorntimetv` from `https://github.com/PopcornTimeTV/Specs.git`, is asking for username GitHub and it does nothing.

**Comment by The1PRimeYT** [comment]
u have too fresh install u computer because u used this before
