### ISSUE TITLE
[!] Error installing TVVLCKit-unstable .. cant get over this step

### ISSUE THREAD

**Issue by sayed001** [PopcornTimeTV/PopcornTimeTV#125]
Installing PopcornKit (3.0.0)
Installing PopcornTorrent (1.1.1.8)
Installing SwiftyJSON (3.1.0)
Installing TVMLKitchen (0.9.6)
Installing TVVLCKit-unstable (3.0.0a10)

[!] Error installing TVVLCKit-unstable
[!] /usr/bin/unzip /var/folders/6v/lf3czhf56jz1sjxztk1ll72r0000gn/T/d20161013-1968-qdqwqk/file.zip -d /var/folders/6v/lf3czhf56jz1sjxztk1ll72r0000gn/T/d20161013-1968-qdqwqk

Archive:  /var/folders/6v/lf3czhf56jz1sjxztk1ll72r0000gn/T/d20161013-1968-qdqwqk/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/6v/lf3czhf56jz1sjxztk1ll72r0000gn/T/d20161013-1968-qdqwqk/file.zip or
        /var/folders/6v/lf3czhf56jz1sjxztk1ll72r0000gn/T/d20161013-1968-qdqwqk/file.zip.zip, and cannot find /var/folders/6v/lf3czhf56jz1sjxztk1ll72r0000gn/T/d20161013-1968-qdqwqk/file.zip.ZIP, period.

**Comment by FlaviaBondJamesBondsHusband** [comment]
This is an issue with cocoapods. Remove the project and re-clone and try again. If that doesnt work, clear cocoapods cache and repeat.
