### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by Danieljflopes** [PopcornTimeTV/PopcornTimeTV#127]
Hi. 
Sorry if thus question is complety stupid but I sincerly don't know where to find the answer. I know the latest version of popcorn time tv is 1.0.5 but I only seem to find find 1.0.3.1. Where can I download the latest version IPA file? Sorry in advance for any ignorance.

**Comment by litengulfisk** [comment]
I curious for this as well, would be great to have 1.0.5 on appdb as the current version there is not working to install.

**Comment by tvOSPopcorn** [comment]
#130
