### ISSUE TITLE
PopcornTimeTV crashing router

### ISSUE THREAD

**Issue by riotshield** [PopcornTimeTV/PopcornTimeTV#128]
It seems that when movies start loading PopcornTimeTV is crashing the router. Loading continues when router restarts but during 1 movie the router crashes around 10 times.

I read here https://www.reddit.com/r/PopCornTime/comments/4e7jpm/popcorn_time_crashing_router/ that a possible solution would be to reduce the connections but there is no such option on tvOS version. Could this be somehow changed from the source code?

**Comment by buzzel** [comment]
Im not sure why this would be happening, but I do have a few ideas to possibly work around it. Will look into them and submit a fix in the next week or so
