### ISSUE TITLE
Error can someone help

### ISSUE THREAD

**Issue by camron114** [PopcornTimeTV/PopcornTimeTV#128]
/Users//Desktop/PopcornTimeTV-0.2.0-0/TopShelf/ServiceProvider.swift:65:19: Result of call to 'wait(timeout:)' is unused

ld: warning: directory not found for option '-L/Users//Desktop/PopcornTimeTV-0.2.0-0/PopcornTime/Objective-C/TOSMBClient/libdsm'
ld: warning: directory not found for option '-F/Users//Desktop/PopcornTimeTV-0.2.0-0/tvOS/appletvsimulator'
ld: warning: directory not found for option '-F/Users//Desktop/PopcornTimeTV-0.2.0-0/tvOS/appletvos

**Comment by FlaviaBondJamesBondsHusband** [comment]
These are warnings not errors. The project still compiles and installs. You can ignore all warnings
