### ISSUE TITLE
Rewind - Forward doesn't work

### ISSUE THREAD

**Issue by mtwww** [PopcornTimeTV/PopcornTimeTV#129]
Hi.
While watching a movie Play/Pause function works without any problem.
But when you click touchpad or would like to rewind & forward you are loosing the movie.
You need to start from beginning. I wait almost 30-40 minutes on a place while thinking it might caching that movie but it didn't.

**Comment by mtwww** [comment]
in simulator it seems like working.. at least subtitles keep playing 👍  but on appletv nothing..

**Comment by RefusedFlow** [comment]
**Known issue, as it on the progress list you can view here**
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress
