### ISSUE TITLE
Content not updating

### ISSUE THREAD

**Issue by ciscosurplus** [PopcornTimeTV/PopcornTimeTV#129]
Currently running on 1.0.3.1 which I complied using the instructions, running on TV OS 10

The films and TV series never seem to update, for example in the movies or tv series it has been the same list of items for weeks (static) if I search for something that I know is available it can't find it.  

Does something need to happen to refresh the content DB?

**Comment by tvOSPopcorn** [comment]
Check the latest commit on master, I added a Trending Tab so content is more often updated.
