### ISSUE TITLE
Error installing UniversalDetector

### ISSUE THREAD

**Issue by Mossito** [PopcornTimeTV/PopcornTimeTV#130]
Hi! 
Just pulled the new changes and im having this problem updating the pods, does anyone have this problem?
I have deleted and cloned from zero all the project, reinstalled cocoapods, tried pod update and install but the problem persists.

[!] Error installing UniversalDetector
[!] /usr/bin/git clone https://github.com/PopcornTimeTV/UniversalDetector.git /var/folders/sz/7z5dhbf94838_qbq5sdgc1cc0000gn/T/d20160526-3610-3z57p9 --template= --single-branch --depth 1 --branch 1.4.1 --recursive

Submodule 'external/uchardet' (git@github.com:BYVoid/uchardet.git) registered for path 'external/uchardet'
Cloning into '/var/folders/sz/7z5dhbf94838_qbq5sdgc1cc0000gn/T/d20160526-3610-3z57p9'...
Note: checking out '27070c7bb45f06a49b839c7037de1afc3407bcc0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Cloning into 'external/uchardet'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:BYVoid/uchardet.git' into submodule path 'external/uchardet' failed

**Comment by RefusedFlow** [comment]
Fixed, re-run pod update.

**Comment by Mossito** [comment]
Thanks! it's working now :)
