### ISSUE TITLE
 resign iPA Last version

### ISSUE THREAD

**Issue by adrienbusin** [PopcornTimeTV/PopcornTimeTV#130]
Thanks for your GREAT job !!
But can you build an IPA to resign with the last Beta version ? please :D

**Comment by tvOSPopcorn** [comment]
We don't sign any IPA files and we never will do. *Appdb* signs the IPA file for their users so we have no control over the compiled IPA file since we're not the ones signing it. We'll update the readme.md whenever they decide to compile the latest version

**Comment by wahlmanj** [comment]
Resigned for jailbroken aTV's https://www.sendspace.com/file/gkz84g
