### ISSUE TITLE
Encoding on subtitles

### ISSUE THREAD

**Issue by mtwww** [PopcornTimeTV/PopcornTimeTV#131]
Hi.
Subtitles fetching normal via opensubtitles for movies and tv series. but encoding function still has problems.
ıIşŞğĞ still not working (must be latin5) with current version for Turkish subtitles.
I don't know how is the situation for other languages.

![img_2524](https://cloud.githubusercontent.com/assets/19256012/15593691/634ed1aa-23b7-11e6-9d55-b741f992cc27.jpeg)

The correct subtitle must be like : 
Durun bi saniye. Kimse Yüzbaşı'nın ''Lafına dikkat et'' demesine...

**Comment by mtwww** [comment]
@aggelos81 modification was working well before...

**Comment by buzzel** [comment]
I dont want to use his modification as its a per language solution. If I have to I will, but using a more dynamic solution is what I am after.

**Comment by mtwww** [comment]
yes i understood, of course dynamic one will be more universal. i hope we will find a solution, someone will give an advice..
@aggelos81 any idea ?

**Comment by buzzel** [comment]
@mtwww Open Subs uses the CP1254 encoding, which is WindowsCP1254 Encoding.

**Comment by buzzel** [comment]
@mtwww Do you have like 15 minutes? I have two thing I wanna try really quick. Check out the master branch and run that.

**Comment by aggelos81** [comment]
@buzzel 
I have found a few issues, do not know if they are strictly emulator related. But the subtitle retrieval function is run two times, during the first one the subtitle is found correctly but during the second one the Subtitle.filepath is somehow empty, so the downloadsubtitle is called but when it tries to create the directory to store the subtitle it is unable to, since it already exists and errors out so i made a handler that retrieves the already saved file and passes is to the subtitle.filepath. 

Secondly I have to suggest a new way to find the appropriate encryption to use, without the need for table associations!!!


`CFStringEncoding encodingType = CFStringConvertIANACharSetNameToEncoding((__bridge CFStringRef)encoding);
        CFStringRef cfstring = CFStringCreateWithBytes(kCFAllocatorDefault, data.bytes, data.length, encodingType, YES);
        string = (__bridge NSString *)cfstring;
        CFRelease(cfstring);
        return string;
` 

Which works as it should at least for Greek and French. Do not have the knowledge to test for further languages.

**Comment by mtwww** [comment]
@buzzel i will push the master when i back home today.

the screenshot you sent %100 correct translation. all characters are fine !

**Comment by mtwww** [comment]
@aggelos81 can you put as pull to try ?

**Comment by aggelos81** [comment]
just pushed the pull #132

**Comment by mtwww** [comment]
@aggelos81 @buzzel his fix works perfect !

![1243](https://cloud.githubusercontent.com/assets/19256012/15609928/65c20fb4-242b-11e6-9629-44ac383a050d.jpg)

**Comment by mtwww** [comment]
tv shows also works good.

**Comment by tomto147** [comment]
I can can confirm that Polish subtitles are OK after the update to 0.6.4. The only thing that still needs some work is the markings like {y:i} which normaly mark lines as italics but appletv can not see it.

**Comment by buzzel** [comment]
@mtwww Who's fix works? Mine or what @aggelos81 submitted as a PR? If you haven't tested his, can you and see if it works? 

@tomto147 The {y:i} should of been stripped from string.

**Comment by tomto147** [comment]
@buzzel 
I can still see {y:i}. Try Star Wars episode VII and change to Polish it's just at the begining
Same thing on Avengers Age of Ultron as an example

**Comment by tomto147** [comment]
@buzzel 
I have noticed a new thing. In some movies and TV series evethough Polish subtiles are available from the top menu, after selecting it nothing is beeing displayed. Egzample Game of Thrones season 1 episode 1 or MadMax Fury Road

**Comment by mtwww** [comment]
@buzzel , i didn't push the latest master since last night.
i push @aggelos81 's pulled update and it works great...

**Comment by mtwww** [comment]
@buzzel  you want me to try your latest master without his patch ?

**Comment by puba** [comment]
after succesfull build to ver.064 subtitles on movies or tv shows of any language is not displayed at all???

**Comment by aggelos81** [comment]
That is what I had found and remedied on my build. That sometimes the filepath string inside the subtitle object would become nil.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=ti&cv=7.12.25&pv=9.3.2&source=email_footer_2]
On Fri, May 27, 2016 at 8:34 PM, puba <notifications@github.com> wrote:
after succesfull build to ver.064 subtitles on movies or tv shows of any language is not displayed at all???

**Comment by puba** [comment]
OK, will check it out.

**Comment by buzzel** [comment]
Okay so I merged in @aggelos81 PR (Nice work by the way, didn't think to use CoreFoundation to handle the encoding). I ended up having to put a check in there as there was a crash if the encoding was "unknown" which some languages return. 

I also cleaned up a few things as well. Also, care about force unwrapping in Swift. I had in instant crash when trying to load a movie as the SubTitles had already existed. Just a note, always use an if let statement to get the first item of an array and use a do {} catch {} when you need to use try. Best to be safe and account for things like that. 

@mtwww @puba Let me know how the master branch works now.

**Comment by mtwww** [comment]
@buzzel i pull and check the new master update. its all works fine now.. you can push the update..

**Comment by buzzel** [comment]
@mtwww Awesome! Coming right up!

**Comment by puba** [comment]
works fine by me too, thanks.
