### ISSUE TITLE
Swift Complier Error (Need Help)

### ISSUE THREAD

**Issue by tomsbrinkis** [PopcornTimeTV/PopcornTimeTV#131]
@FlaviaBondJamesBondsHusband can you please help? 

![screen shot 2016-10-16 at 16 41 09](https://cloud.githubusercontent.com/assets/20775280/19417860/ed3050e2-93bf-11e6-8bb2-75003dc5ebb3.png)

**Comment by FlaviaBondJamesBondsHusband** [comment]
run `pod repo update` `pod update`
