### ISSUE TITLE
same bundle-ID no problem with simulator ! but

### ISSUE THREAD

**Issue by abufreeh** [PopcornTimeTV/PopcornTimeTV#132]
when trying to send it to atv , get this error 
This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique.
any idea?

BR

**Comment by adrienbusin** [comment]
Hi, 
Try to
 change Bundler Identifier for popcorPopcornTime Target to com.NAMEHERE.popcorntime
&  change Bundler Identifier for TopShelf Target to com.NAMEHERE.popcorntime.TopShelf 

Must be unique --> com.NAMEHERE.popcorntime  && com.NAMEHERE.popcorntime.TopShelf 

Check on wiki !
