### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by gnyvie** [PopcornTimeTV/PopcornTimeTV#133]
Hello,

the last working version I had installed was 0.5.0. Tried to install 0.6.3 but failed with several issues. Now 0.6.4 is also failing. Heres a screenshot of what Xcode says is wrong. Can anybody help me figure out what to do? Would love to use the app again. 

Thanks in advance and best regards

![screenshot](https://cloud.githubusercontent.com/assets/19609019/15608014/2cf53c74-2417-11e6-9f45-c02e1e728517.png)

**Comment by mtwww** [comment]
better clean all your cache and delete main files. then do all installation procedure from zero.

**Comment by buzzel** [comment]
As @mtwww Make you you run a Build and Clean. Also, make sure you've run `pod update` and you're opening the `.xcworkspace` instead of the `.xcodeproj`

**Comment by gnyvie** [comment]
Thanks to both of you. Didn't know about the cache in Xcode. Deleted everything, reinstalled some things and now it's working!
