### ISSUE TITLE
error bundle ID  xcode 8  problem  

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeTV#134]
<img width="1440" alt="captura de pantalla 2016-10-18 a las 18 16 34" src="https://cloud.githubusercontent.com/assets/22038180/19499995/178456e0-955f-11e6-8b79-e6deb589382b.png">

version 1.0.5 problem project app  xcode 8                                                                                      

timeout unused   serviceprovider.swift error

BUILDTIME

**Comment by FlaviaBondJamesBondsHusband** [comment]
Please change the bundle identifier to something unique.

**Comment by adrienbusin** [comment]
#132 
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki
