### ISSUE TITLE
1.0.5 Problems

### ISSUE THREAD

**Issue by tomto147** [PopcornTimeTV/PopcornTimeTV#135]
After upgrading to 1.0.5 I am unable to change subtitles appearance, coding and size in setting menu. When I try to change anything in this area the app crashes and apple TV returns to home screen. During movie playback I am unable to access top menu for subtitles at all. Swipe from top interferes with movie playback and stops the movie.

**Comment by gtaouil** [comment]
+1

**Comment by iAYMANi** [comment]
+1

**Comment by puba** [comment]
<a href='http://www.easyfreesmileys.com/facebook-smileys.html' title='Facebook smileys'><img src='http://www.easyfreesmileys.com/smileys/free-random-smileys-92.gif' alt='Facebook smileys' border='0'></a><a href='http://www.easyfreesmileys.com/skype-emoticons.html' title='Skype Emoticons'><img src='http://www.easyfreesmileys.com/smileys/free-random-smileys-59.gif' alt='Skype Emoticons' border='0'></a>

**Comment by na9oor506** [comment]
+1

**Comment by FlaviaBondJamesBondsHusband** [comment]
All bugs are known and will be fixed in next release. Please read release notes before updating/posting issues as all of the bugs you mentioned are accounted for
