### ISSUE TITLE
can someone share the ipa v.1.0.5 ? 

### ISSUE THREAD

**Issue by sayed001** [PopcornTimeTV/PopcornTimeTV#136]

**Comment by sayed001** [comment]
Hi thanks for the support,
can we have the ipa for 1.0.5?

thanks again

**Comment by tvOSPopcorn** [comment]
#130

**Comment by sayed001** [comment]
i dont need a signed ipa. i can sign itand install it  using impactor and it will work 100%.

please upload v1.0.5

**Comment by tomto147** [comment]
you can download it from here but 1.0.5 has a broken subtitles option in the settings
[https://www.dropbox.com/s/ua510qjn0sbh5t5/PopcornTime1.0.5.ipa?dl=0](url)

**Comment by sayed001** [comment]
many thanks @tomto147  !

**Comment by wahlmanj** [comment]
Resigned for jailbroken aTV's https://www.sendspace.com/file/gkz84g
