### ISSUE TITLE
Still receiving 7 errors on build (v0.6.5)

### ISSUE THREAD

**Issue by revblaze** [PopcornTimeTV/PopcornTimeTV#136]
First of all, huge fan of what you guys are doing here. I think a native Apple TV application is amazing. That said, I haven't been able to successfully build the project since (0.6.4). I have tried all the methods, as well as their alternatives, and yet, no luck.

![Screenshot of Xcode, Running 7.3.1]
(http://i.imgur.com/aTDmzMW.png)

List of Issues:

- PopcornTimeTV/PopcornTime/Latest.swift:31:21: Value of type 'NetworkManager' has no member 'fetchShows'
- PopcornTimeTV/PopcornTime/Recipes/YIFYSearchRecipe.swift:63:28: Value of type 'NetworkManager' has no member 'fetchShows'
- PopcornTimeTV/PopcornTime/Recipes/GenreRecipe.swift:98:21: Value of type 'NetworkManager' has no member 'fetchShows'
- PopcornTimeTV/PopcornTime/Recipes/MovieProductRecipe.swift:175:90: Value of type 'Movie' has no member 'imdbId'
- PopcornTimeTV/PopcornTime/ActionHandler.swift:117:31: Use of unresolved identifier 'LoadingRecipe'
- PopcornTimeTV/PopcornTime/ActionHandler.swift:119:24: Value of type 'NetworkManager' has no member 'getCreditsForPerson'
- PopcornTimeTV/PopcornTime/Popular.swift:48:21: Value of type 'NetworkManager' has no member 'fetchShows'

**Comment by buzzel** [comment]
Make sure you either run the install script `swift install.swift` or if you're doing it manually, run a `pod update` Those errors are because you have an old version of a pod. Another thing you can try is deleting your DerivedData from Xcode and rebuilding the project.

**Comment by FarFromNormal** [comment]
When I was having an issue updating my build and ended up starting fresh this is what @buzzel told me to do and it worked perfect.

"
- Run rm -rf ~/.cocoapods/repos/popcorntimetv
- Delete your DerivedData from Xcode run rm -rf ~/Library/Developer/Xcode/DerivedData
- Delete all copies of PopcornTime and download a fresh one by running cd ~/Desktop/ && git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git && cd PopcornTimeTV && python install.py copy that whole line or run each one by one. When you run the python install script it will walk you through setting up your local copy and installing all the dependencies.

Don't forget to update the App's bundle ID and the TopShelf's bundle ID."

Hope this helps.

**Comment by buzzel** [comment]
Instead of running the python script (Which has now been removed) run the swift script. That last command would read ` cd ~/Desktop/ && git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git && cd PopcornTimeTV && swift install.swift`
