### ISSUE TITLE
New set of icons

### ISSUE THREAD

**Issue by riotshield** [PopcornTimeTV/PopcornTimeTV#137]
Sorry for posting this as an issue, probably PR would be more appropriate but I tried to do that (see here https://github.com/riotshield/PopcornTimeTV/pull/1) but it changed a lot of files it seems that I didnt intend to change.

Anyway, I have updated the icons as you can see in the above link or here http://i623.photobucket.com/albums/tt318/riotshield/8583B0A2-EEF3-4584-8074-662820C8CD1E.jpg

I think it looks nicer than the basic icon, feel free to use them

**Comment by ozkrtech** [comment]
Thumbs up for his icon. Pretty good!

Oscar Rodriguez
IT Technician

On May 28, 2016, at 10:45 AM, riotshield <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for posting this as an issue, probably PR would be more appropriate but I tried to do that (see here riotshield#1<https://github.com/riotshield/PopcornTimeTV/pull/1>) but it changed a lot of files it seems that I didnt intend to change.

Anyway, I have updated the icons as you can see in the above link or here http://i623.photobucket.com/albums/tt318/riotshield/8583B0A2-EEF3-4584-8074-662820C8CD1E.jpg

I think it looks nicer than the basic icon, feel free to use them

-

**Comment by RefusedFlow** [comment]
Hai, I'm working on a new app icon for PopcornTimeTV... Thanks for your ideas though!
