### ISSUE TITLE
Artwork not downloading for TV shows

### ISSUE THREAD

**Issue by GerTeunis** [PopcornTimeTV/PopcornTimeTV#14]
I get for every tile it wants to present a : "PopcornTime[173:6931] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9814)"

Did a full delete and clean build, can't figure out why this happens. Any clues?

**Comment by GerTeunis** [comment]
Ignore this one. Oddly enough it just started working. Must have been my network acting up

**Comment by tvOSPopcorn** [comment]
Either an issue on your end, or more than likely an issue with the API
