### ISSUE TITLE
Always crash

### ISSUE THREAD

**Issue by marp04** [PopcornTimeTV/PopcornTimeTV#140]
this shit is crap, never play, always crash

**Comment by b1narygh0st** [comment]
Alright let me tell you something, this is an open source project. This means that every single person working on this project receives nothing from it, we also have our daily jobs, but still we volunteer to work on this. It is made by ordinary people like you – well, obviously not you – but by people with no super powerful coding skills, just normal people with good intentions investing their free time on the project.

Secondly, do you think that this issue will be of any use for us? Seriously, not only are you being rude, you are not helping us fix the issue for, which I must underline, **we don't have to**, as this is not our job, you are also wasting our time, my time explaining why this kind of rants are not helpful and keeping me busy not fixing _your_ issue.

Now, shall we try this again?

**Comment by marp04** [comment]
well, still is crashing and still is a crap. btw, I pay for this on tv.ipwnstore.me, so I am on my right.

**Comment by b1narygh0st** [comment]
* Firstly, as written in bold letters in our main documentation file:
> **Please note we are NOT affiliated with appdb and it is not our responsibility if there are bugs in their versions of the app**

* Secondly, even though we are not affiliated with them/it you paid for a service of resigning iOS/tvOS apps. They are doing all that is in contract. 

* Thirdly, this is an Open source project under the license [GPL-3.0](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/LICENSE.md), and according to Article 16 and 17 this program comes with no warranty whatsoever and we are not liable for any danger or malefaction caused to you or your devices. In other words, you are most definitely **NOT** on your rights.

**Comment by marp04** [comment]
relax dude, this is just like my opinion. you need to chill out. btw great work you are doing here people

**Comment by wahlmanj** [comment]
Nobody's forcing you to use it. Likely you are using 1.0.5 where 1.0.3 is A LOT more stable in my opinion. If you jump the gun and install a beta project you will likely get beta results duh. Just saying a project is no good shows that you are nothing more then an impatient individual. Quit crying and get Netflix or plex for the meantime until the project is in a stable state like everyone else. Blame your site and email them for giving you beta software. From what I can tell nobody that maintains this project has released a revision yet for a reason, it's not ready.

**Comment by FlaviaBondJamesBondsHusband** [comment]
@marp04 Thank you for your super insightful question marp. Unfortunately we were unable to narrow down the exact bug you were talking about. Very sorry. Have a nice day!
