### ISSUE TITLE
Top shelf not working on start up again?

### ISSUE THREAD

**Issue by drew5494** [PopcornTimeTV/PopcornTimeTV#140]
Hey this is happening to me again.
Maybe I have done something wrong but can someone else confirm this?
Thanks.

**Comment by FarFromNormal** [comment]
Just loaded up my Apple and it did the same thing. What I do is move it off the top row and then move it back and the top shelf loads.

**Comment by drew5494** [comment]
@FarFromNormal didn't work for me.  it only works if I have the app already started.

**Comment by FarFromNormal** [comment]
@drew5494 Did you move it completely off the top row? I mean get it in wiggle mode, drag it some place and place it, then put it back into wiggle mode and place back on the top row?

**Comment by drew5494** [comment]
Yup still nothing @FarFromNormal

**Comment by RefusedFlow** [comment]
@drew5494 @FarFromNormal Are you guys building the project correctly? I haven't had this issue myself

https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

**Comment by drew5494** [comment]
Ya @RefusedFlow I probably did something wrong.
