### ISSUE TITLE
When selecting TV show "Shark Tank", the entire app crashes. 

### ISSUE THREAD

**Issue by rahalb** [PopcornTimeTV/PopcornTimeTV#142]
Would someone  be able check if they're having the same issue? Other shows that I watch work fine, it just seems to be this one. I tried uninstalling the app and reinstalling it, same issue. I'm on 1.3.2. Thanks in advance.

![giphy](https://cloud.githubusercontent.com/assets/15767229/19688660/9e0429d2-9a98-11e6-80f4-5e62d9c71085.gif)

**Comment by FlaviaBondJamesBondsHusband** [comment]
We cannot fix issues in previous versions of the app unfortunately. This issue does not exist in the latest version of the app. I know the latest version isn't as stable as the version you're running but theres nothing i can do unfortunately. Sry :(
