### ISSUE TITLE
Improve lazy loading

### ISSUE THREAD

**Issue by litengulfisk** [PopcornTimeTV/PopcornTimeTV#142]
The lazy loading of covers seems to start when the new row is starting to get visible.

It would be a much smoother experience if it would lazy load the row below that as well, that would only make the "empty covers" appear when scrolling really fast.

Maybe something for the "settings" if you believe it's too bandwidth consuming to have as default.

I really love how great this has become. Keep up the good work!

**Comment by buzzel** [comment]
This isn't something we have control over. TVML handles all of this. We just pass it the information and it loads everything accordingly.
