### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by Danieljflopes** [PopcornTimeTV/PopcornTimeTV#143]
The certificate for this server is invalid. you might be connecting to a server that is pretending to be "extratorrent.cc" which could put your confidential information at risk. I've checked and this error appears even in version 1.0.6b2. Oddly it only appears in the latest seasons of tv series. I can't seem to see any of them. Could it be just a coincidence or is it the server that you use for more recent seasons?? I looked it up and came upon the following link that explains what to do if this error appears: http://stackoverflow.com/questions/21197834/the-certificate-for-this-server-is-invalid
Could you check to see if it is something related? Thanks in advance.

**Comment by tvOSPopcorn** [comment]
#137
