### ISSUE TITLE
Downloaded file alternative placements

### ISSUE THREAD

**Issue by smith288** [PopcornTimeTV/PopcornTimeTV#143]
I would like to request a new feature to allow the downloaded file to placed somewhere else either FTP or samba share that we could build a library up.

For example, my Asus has attached storage and it would be very useful to be able to place the file there.  Would free up Apple TV storage and quicker reloading if I want to rewatch a previously viewed show/movie.

My quick search for potential libraries brought me to a github project called SMBDriver from Obyect.  It already uses TVVLCKit so it could be implemented with someone more competent than myself.

**Comment by RefusedFlow** [comment]
@smith288 

Hai, pretty neat idea if i'm honest. So whatever content fully downloads on Apple TV you'd like it to transfer over to a local NAS/FTP storage area to build up a local library up?

It's probably something that won't be implemented anytime soon as there's a bunch of other areas of the application that are much more of a higher priority unfortunately. However [Squire](http://squireapp.com/) is something you could checkout as an alternative but requires a mac to be active.

Apart from that you could try track down a developer/friend who could implement such feature? You'll always be free to create PR's to contribute towards the application. 😄 

**You're more than welcome to checkout the progress page below**
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress
