### ISSUE TITLE
Share sheet for .torrent and opening magnet links

### ISSUE THREAD

**Issue by selahssea** [PopcornTimeTV/PopcornTimeTV#144]
It would be great to have an ability to add custom torrent file via web interface for example. Is it possible?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Yes this is possible. Both opening magnet links and torrent files will be added to the next release. However no metadata can be requested from the media meaning no subtitles.

**Comment by mclssk** [comment]
From apple TV opening magnet links? Change url location better no?

Thanks!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for your request and apologies for the long delay. Now implemented in master

**Comment by selahssea** [comment]
@FlaviaBondJamesBondsHusband I'm not actually sure that we were on the same page here. I was talking about apple tv app and about web interface for adding torrent files from browser on other computer. For example opening http://apple-tv.local:9091 in the browser on a laptop should lead me to the web interface, like in [issue #352](https://github.com/PopcornTimeTV/PopcornTimeTV/issues/352) was mentioned or like VLC player for apple tv does.

As far as I remember such functionality was in some previous versions of PopcornTimeTV, and  it had section in Settings pane, but then it disappeared once.
