### ISSUE TITLE
0.6.5 crash after few minutes

### ISSUE THREAD

**Issue by pbo1976** [PopcornTimeTV/PopcornTimeTV#145]
Did several builds, and all with same problem. App quits after some minutes of movie being played or even in pause. Similar to the 9th minute crash on 0.6.3. 

no idea what is going on.

**Comment by pbo1976** [comment]
Did several builds, and all with same problem. App quits after some minutes of movie being played. Similar to the 9th minute crash on 0.6.3.

**Comment by Gsuz** [comment]
Getting similar crashes. It's really random. Not that this bug report is very informative. Is there anything we can do to give a more informative crash report?

**Comment by Gsuz** [comment]
after a little poking I found that when you connect your mac to your apple tv 4 the mac downloads the latest crash reports from the apple tv and places them ~/library/logs/CrashReporter/Mobile Device/Apple TV/Retired/

I'm attaching 4 crash reports in a zip file. Hope this helps.



[Archive.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/292280/Archive.zip)

**Comment by buzzel** [comment]
I've been trying to reproduce this issue for a while now. The only thing I can think of is something might be outdated. Can you run a `pod update` and send me the output in the console?

**Comment by buzzel** [comment]
I pushed some fixes to the master branch, feel free to have a look at that and see if it fixes your issue

**Comment by Gsuz** [comment]
Thx. I'd like to add after restarting the app after crash while playing a movie the app was able to play the whole movie through. I'll install the update and do some more thorough testing tonight.

**Comment by Evhelden** [comment]
Will also rebuild and test again. Keeps happening, but randomly with 13 hours.

**Comment by buzzel** [comment]
@Gsuz Thanks. Some people seem to have this issue and others dont. I'm one of those who don't so trying to debug is a nightmare. Let me know what you find! If you're up to it, plug it into Xcode and have it running from there. If it crashes, Xcode will give you a backtrace so if you get that, could you send me a screenshot?

@Evhelden Have you tried the master branch as well?

**Comment by Gsuz** [comment]
Running current master build .. no immediate crashes. I'll try my hardest to make it crash :)

**Comment by Gsuz** [comment]
@buzzel I Can't get it to crash.. 👍 

I guess we can mark this fixed for the time being atleast.

**Comment by Evhelden** [comment]
@buzzel 
I have recompiled and build the app. Will now run a full movie

**Comment by ynnad696** [comment]
after compile the files and build the app is finally playing on my apple tv , i have a question how can i save the .ipa?

**Comment by buzzel** [comment]
Okay cool. Closing this then. If you guys do encounter it crashing randomly like that, open a new issue :)
