### ISSUE TITLE
PopcornTimeTV: impossible to select Subtitles/Audio

### ISSUE THREAD

**Issue by michelvdwerf** [PopcornTimeTV/PopcornTimeTV#146]
Great app! Thank You very much for Your time to make a great app! Yesterday I made a new build and succesfully installed it on my Apple TV. Unfortunately the subtitles or audio can not be selected. I get a pulldown menu but it's impossible to scroll to subtitles/audio.
I hope it's an easy bug to fix. Succes!
Greetz, Michel

**Comment by tvOSPopcorn** [comment]
#145
