### ISSUE TITLE
Watch List in Top Shelf

### ISSUE THREAD

**Issue by gnyvie** [PopcornTimeTV/PopcornTimeTV#148]
Hi there, 

I don't know if this has been requested or posted as an idea. What I normally do is pick the shows I watch most from the watch list so the watch list would be a nice addition to the top shelf. Even better when top shelf items are listed before the current items.

I really like the app. You've done a great job. Can't thank you guys enough.

#

**Comment by RefusedFlow** [comment]
**Added this idea to the progress list that you can visit below 😄** 
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress
