### ISSUE TITLE
Load default "Subtitle Language" from Apple TV's Settings App

### ISSUE THREAD

**Issue by michelvdwerf** [PopcornTimeTV/PopcornTimeTV#148]
Thanks for the great app! By now we have to manually select the subtitle language in the popcorn app for every film or serie, but the default subtitle language is already known  in the Apple TV's Settings app! Is it possible to load the Apple TV's Subtitle setting as default for PopcornTime?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue #111
