### ISSUE TITLE
Unable to find a specification for `TVVLCKit-unstable (= 3.0.0a10)

### ISSUE THREAD

**Issue by mitcheble** [PopcornTimeTV/PopcornTimeTV#149]
I keep getting this issue when running pod install (error is the very last line)

$ cd ~/Desktop/PopcornTimeTV
$ pod install
Analyzing dependencies
Pre-downloading: `PopcornKit` from `https://github.com/PopcornTimeTV/PopcornKit.git`
Pre-downloading: `PopcornTorrent` from `https://github.com/PopcornTimeTV/PopcornTorrent.git`
Pre-downloading: `TVMLKitchen` from `https://github.com/toshi0383/TVMLKitchen.git`, branch `swift3.0`
[!] Unable to find a specification for `TVVLCKit-unstable (= 3.0.0a10)`

**Comment by FlaviaBondJamesBondsHusband** [comment]
Please use the latest version of master branch
