### ISSUE TITLE
Not all available subtitles are listed.

### ISSUE THREAD

**Issue by lekima** [PopcornTimeTV/PopcornTimeTV#149]
Several languages are missing, despite the fact that the subtitles are available.

**Comment by buzzel** [comment]
Currently everything is being fetched for a given movie. Everything the API returns is loaded.

**Comment by lekima** [comment]
Is the list getting refreshed after the movie is reloaded? I'm looking for Vietnamese subtitles in particular, opensubtitles has them on the website but they're nowhere to be found in the app. Any idea why?

**Comment by buzzel** [comment]
Hmm, no, it should be fetching everything. The way subtitles are fetched after the 0.6.6 update is it search for subtitles based on a file hash and file name search after the movie loads, and in this case, once it starts playing. This is the most accurate search as it provided subtitles tailored to that exact file. I did see Vietnamese subtitles in there. An option that is planned is to allow the user to select a specific subtitle language and have it automatically loaded when a movie starts. As long as you know your language code (Vietnamese is `vie`) you can input that into settings and hopefully it will return the expected results. Hopefully that will fix any issues with languages not being found for users, but considering the API is very finicky it is the best solution we can come up with.

**Comment by RefusedFlow** [comment]
Closing issue as it relates to the subtitles API, reopen if you can solve the issue.
