### ISSUE TITLE
Can't stream at all since this morning

### ISSUE THREAD

**Issue by tdlm** [PopcornTimeTV/PopcornTimeTV#15]
In order, I've tried the following to resolve this issue before bothering you fine people:

- Restarted app
- Restarted Apple TV
- Deleted app and re-installed using iFunBox
- Deleted app, downloaded signed .ipa file again, and installed new version (1.0.1) using iFunBox

Nothing has worked. The Apple TV is connected to a Wireless VPN network that otherwise streams well.

~~I'll try rebooting the router and report back.~~

Confirmed rebooting does nothing. The same behavior occurs. The "play" process happens as usual (press play, choose 720 or 1080, begins buffering), then once it starts to play, the screen goes grey (as if it's going to say "Loading...") but the app immediately exits.

**Comment by Splitix** [comment]
Can confirm I'm having the same issue. This is the error log i'm getting right as the app closes. 

`2016-08-18 01:02:10.858 PopcornTime[196:14292] new startPiece: 10
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) `

Here is a screenshot of the window that opens up in xcode:

<img width="1024" alt="screen shot 2016-08-18 at 1 04 05 am" src="https://cloud.githubusercontent.com/assets/7977304/17763672/b728caa6-64df-11e6-9629-fc83d8fdb446.png">

**Comment by JohnRPoole** [comment]
Can confirm same issue @ 6:27 am EDT.

**Comment by popcornMaster** [comment]
Are all of you connected to VPNs?

**Comment by tdlm** [comment]
Yes, I'm connected through a VPN.

**Comment by Splitusa** [comment]
I'm not connected to a VPN

**Comment by BlackyRoss** [comment]
Same error in the log. Since yesterday, 9:00PM PST. Not connected to VPN

**Comment by FlaviaBondJamesBondsHusband** [comment]
Bug fixed in latest commit
