### ISSUE TITLE
Include of non-modular Header

### ISSUE THREAD

**Issue by Leinadzet** [PopcornTimeTV/PopcornTimeTV#150]
I have been installing different versions now, and I always get this error:

Include of non-modular header inside framework module "PopcornTorrent"  PopcornTorrent.h

Tried different answers I found on SO but none of them worked :( any ideas? 

<img width="881" alt="bildschirmfoto 2016-10-29 um 08 56 33" src="https://cloud.githubusercontent.com/assets/8782897/19827831/d86dff24-9db5-11e6-9843-7584d077472f.png">

**Comment by FlaviaBondJamesBondsHusband** [comment]
have you tried cloning the latest version of master?

**Comment by Leinadzet** [comment]
still having this issue... I just cloned master and latest build...

**Comment by ihatetoregister** [comment]
I get this error too. Building master with Xcode 8.1 (Swift 3.0.1).
