### ISSUE TITLE
 Pulldown menu not working

### ISSUE THREAD

**Issue by gvasilev** [PopcornTimeTV/PopcornTimeTV#151]
Hi and thanks for the great app.

Since version 1.0.5 I am no longer able to turn on the pull down menu when watching a movie. Whenever I touch the touchpad it simply rewinds the video.  The menu from the top with the subtitles and the progress bar are not showing at all. Tried restarting and clearing cache, but with no success. Any ideas?

**Comment by moh0sw** [comment]
#145

**Comment by FlaviaBondJamesBondsHusband** [comment]
@gvasilev the pull down menu and scrubber are both working on latest version

**Comment by GerTeunis** [comment]
Can't select subtitles in the pull down menu. Which is a shame

**Comment by davipt** [comment]
Just cloned a clean version five minutes ago. Pulling down shows "Info" and it's *NOT* possible to go to subtitles or audio. Scroll right does nothing. Scroll left makes the top bar jump. Scroll up dismisses the bar.

Also the progress bar on the bottom of the screen is *always* visible.

**Comment by moh0sw** [comment]
@GerTeunis @davipt guys just read the release change log
**Current known bugs:**

Player UI is unresponsive to everything but pausing and exiting.
Some views are presented weirdly when opening movies from topshelf or search making navigation impossible.
Pagination is janky af.
**Subtitles have yet to be re-implemented.**

**Comment by GerTeunis** [comment]
Only on the simulator using arrow keys I seem to be able to reach subtitles and audio. I can confirm build from master

**Comment by GerTeunis** [comment]
We get that. But shouldn't at least one issue track / represent that bug?

**Comment by FlaviaBondJamesBondsHusband** [comment]
@GerTeunis @davipt They are both working in the latest version on master. Please re-clone and try again

**Comment by FlaviaBondJamesBondsHusband** [comment]
@davipt the progress bar is not "always visible" it is visible at the start and then fades away after 5 seconds, reappears when scrubbing and when paused but can be dismissed by tapping the remote.
