### ISSUE TITLE
Unexpected User input causes video to stop

### ISSUE THREAD

**Issue by Gsuz** [PopcornTimeTV/PopcornTimeTV#152]
This is twofold. 

While watching a video, movie or tv episode dragging you finger up on the trackpad will temporarily pause the video, the video overlay appears and the seeking circle will appear as if the video is loading. After a second the video will start to play again. Expected behaviour would be to just make the video overlay visible.

If you start by pausing the video and then drag your finger up the trackpad something weird happens and you can't unpause the video you will need to exit out with the menu button.

I'm posting this together since im guessing they are related.

**Comment by Gsuz** [comment]
This is probably linked with #141

**Comment by Gsuz** [comment]
While exiting the app during testing the above the application crash. Here is the report.

[PopcornTime-2016-06-01-203341.crash.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/294341/PopcornTime-2016-06-01-203341.crash.zip)

**Comment by buzzel** [comment]
Was this on the master branch or the actual 0.6.5 release? If it was on the master, the player is still being worked on. I'm currently bridging the ProgressView and Player together as a stop gap for the time being. The goal is 

1. If you run out of buffer, the video will pause and let more download (Currently it just breaks)
2. You wont be able to advance past the total amount downloaded to also stopgap the issue above. An overall progress was added to the player bar, you'll probably notice it fills up as more video becomes available.

**Comment by Gsuz** [comment]
@buzzel , this was on master. Should have been more clear on that.

**Comment by buzzel** [comment]
This should be fixed in 0.6.6 now
