### ISSUE TITLE
Where to get PopTimeTV / PopTime iOS .ipa's (help)

### ISSUE THREAD

**Issue by tomsbrinkis** [PopcornTimeTV/PopcornTimeTV#152]
What is the best place where i can download latest .ipa's for aTV and iOS?

**Comment by FlaviaBondJamesBondsHusband** [comment]
We don't distribute any IPA's so download at your own risk.

**Comment by wahlmanj** [comment]
http://www.sinfuliphone.com/showthread.php?t=10086865
