### ISSUE TITLE
The player won't open "The Night Manager" S01E02 480p

### ISSUE THREAD

**Issue by Gsuz** [PopcornTimeTV/PopcornTimeTV#153]
it loads the torrent but when done buffering just reverts back to the Series view.

Same result in the simulator.

**Comment by buzzel** [comment]
I'll have a look at this one later tonight when I have some more time

**Comment by Gsuz** [comment]
downloaded the episode from eztv on my laptop. Plays fine on vlc. Isn't popcorntimeTV using vlc to play mp4 or?

**Comment by buzzel** [comment]
Well the problem is the encoding. If mp4 headers are at the end of the file then it just wont load. Generally the headers are the first few bytes but in this case it could be at the end
