### ISSUE TITLE
Does this work at all? 

### ISSUE THREAD

**Issue by mariosanchez23** [PopcornTimeTV/PopcornTimeTV#153]
I tried to follow the build on latest Xcode and Sierra but it's impossible. Among other errors  I am getting> 
[!] repo popcornmaster does not exist
and
 Pre-downloading: `AlamofireXMLRPC` from `https://github.com/PopcornTimeTV/AlamofireXMLRPC.git`
 
fails as it does not exists...
:-(

**Comment by FlaviaBondJamesBondsHusband** [comment]
You are not selecting the latest version when you run the install script. Latest version (its conveniently at the top for some reason) is 0.2.0-0.
