### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by d00fa** [PopcornTimeTV/PopcornTimeTV#154]
i cant get this to work. Everytime i try and build i get this error: 

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Whenever i run pod install OR pod update i get this:

pod update
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:36:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>

CAN SOMEONE HELP ME PLEASE?

I have no coding experience so please bare with me!

**Comment by tengis** [comment]
@d00fa Please follow this instruction https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

**Comment by d00fa** [comment]
I have :( and im still struggling

**Comment by tengis** [comment]
try this 
`sude gem uninstall xcodeproj && sudo gem install xcodeproj`

**Comment by d00fa** [comment]
Last login: Thu Jun  2 21:26:33 on ttys002
Chelseas-MacBook-Pro:~ baybee_cakes$ cd Desktop/PopcorntimeTV
Chelseas-MacBook-Pro:PopcorntimeTV baybee_cakes$ swift install.swift
# Fetching the latest changes from github...
Saved working directory and index state WIP on (no branch): 431263c Update README
HEAD is now at 431263c Update README

# Fetching the latest verion info...
0.6.5
0.6.4
0.6.3
0.6.2
0.6.1
Enter the version number: 
0.6.5

# Checking out tag 0.6.5...
HEAD is now at 431263c... Update README
Do you have cocoapods installed? (Enter Yes or No): 
no
Installing cocoapod gem...
Successfully installed cocoapods-1.0.1
Parsing documentation for cocoapods-1.0.1
1 gem installed
Updating and installing Cocoapods...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- claide (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj.rb:3:in `<module:Xcodeproj>'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:36:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'
Opening Xcode...
Thanks for installing PopcornTime. WHen a new update is released re-run this script and select the new version.
Chelseas-MacBook-Pro:PopcorntimeTV baybee_cakes$

**Comment by Gsuz** [comment]
you have xcode installed?

**Comment by d00fa** [comment]
Of course I do

**Comment by buzzel** [comment]
@d00fa So there is an issue with the current install script. It is fixed in the master branch. If you dont mind waiting, im planning to release 0.6.6 this afternoon, just have one thing left to fix

**Comment by buzzel** [comment]
@d00fa 0.6.6 is released. What I suggest you do is clone a fresh copy of the repo `https://github.com/PopcornTimeTV/PopcornTimeTV.git` then `cd ~Desktop/PopcorntimeTV` and finally run the install script. `swift install.swift`. If you still get an error when it tries to install cocoapods, manually install that by running `sudo gem install cocoapods`
