### ISSUE TITLE
shuffle option for all available tv shows episodes & user created playlists?

### ISSUE THREAD

**Issue by wahlmanj** [PopcornTimeTV/PopcornTimeTV#154]
shuffle option for all available tv shows episodes & user created playlists? - video example:

https://www.youtube.com/watch?v=n-eWfInFOlU

Code I used based off iBaa's PlexConnect atv2/3 playlist implementation:

https://github.com/wahlmanj3/PlexConnect/commit/e54f201d076443259e7f72ab0964b913aa0f71e9

iBaa implementation using playlists only atv2/3:

https://github.com/iBaa/PlexConnect/commit/deaa7c25a1ca8c6cc1da822c567b50b61ca65887

aTV4 code:

https://github.com/iBaa/PlexConnectApp/commit/2f492c7bbd182a312bbfc201bb1a65694583c306

**Comment by FlaviaBondJamesBondsHusband** [comment]
@wahlmanj Although we appreciate the gesture, it is really not necessary to provide code or reverse-engineered iPA's when suggesting a feature. We are all competent enough regarding our developer skills. Suggest a feature and we'll add it to the pile :).
