### ISSUE TITLE
How to build the latest commit?

### ISSUE THREAD

**Issue by wahlmanj** [PopcornTimeTV/PopcornTimeTV#156]
Is there a specific way to build the project for the latest commit?

I usually type this:

`cd ~/Desktop; git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git; sudo gem install cocoapods; cd ~/Desktop/PopcornTimeTV; pod install; swift install.swift`

followed by this but it only gives me the initial commit, any help would be appreciated :)

`0.2.0-0`

**Comment by FlaviaBondJamesBondsHusband** [comment]
Running install script (`swift install.swift`) will give you the latest stable version. Cloning master and running `pod install` will give you the latest version (may be unstable).
