### ISSUE TITLE
HELP again

### ISSUE THREAD

**Issue by d00fa** [PopcornTimeTV/PopcornTimeTV#159]
So last night i did everything, uninstalled cocoapods, clean copy of PopcorntimeTV, ran the swift install and keep getting the same errors..

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- claide (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj.rb:3:in `<module:Xcodeproj>'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:36:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'

ive done sudo gem install cocoapods and it went fine but when i try to pod update or install it gives me the above errors..

xCode 7.3.1 and latest El Capitan.

I dont know what to do anymore :(

I'm in high hopes that someone could do me a huge favour and upload the .ipa to somewhere for tvOS 9.0 (because i'm on a Jailbroken ATV4)

Please help @buzzel

**Comment by buzzel** [comment]
@d00fa First off, we wont share an precompiled version of the app. Too much of a liability. I would try this out. https://cocoapods.org/app. Its a mac app that has its own version of ruby and cocoapods bundled so it might fix your errors.

**Comment by d00fa** [comment]
Ok cocoapods.app fixed my issues. On to the next issue @buzzel 

URGENT: building for tvOS simulator, but linking in object file (/Users/baybee_cakes/Desktop/PopcornTimeTV/Pods/TVVLCKit/TVVLCKit.framework/TVVLCKit(emms.asm.o)) built for (unknown). Note: This will be an error in the future.

I have 91 of these issues :/
