### ISSUE TITLE
Crash in master build (20161030)

### ISSUE THREAD

**Issue by GerTeunis** [PopcornTimeTV/PopcornTimeTV#160]
[PopcornTime  30-10-2016, 11-05.crash.txt](https://github.com/PopcornTimeTV/PopcornTimeTV/files/560447/PopcornTime.30-10-2016.11-05.crash.txt)

I dont know if you are interested in these but here we go.
Build made from commit: 8dab63fa8c5fc4b482f259aaddc993595ba3a199

Attached the crash log, sadly I was not able to resymbolize them.

**Comment by FlaviaBondJamesBondsHusband** [comment]
@GerTeunis could you tell me what you were doing to cause the crash? Sending a cryptic crash log isn't really helpful.
