### ISSUE TITLE
Player crashes

### ISSUE THREAD

**Issue by litengulfisk** [PopcornTimeTV/PopcornTimeTV#161]
Great work with 0.6.6, pretty much all functions I could with for, still problem with forwarding as it freezes even if the new progress bar shows the video should be preloaded (sometimes works, sometime not).

I had the computer connected during my first run when a movie froze, sharing the screenshot here. Hope it can help you in any way.

![skarmklipp 2016-06-04 08 17 17](https://cloud.githubusercontent.com/assets/18162266/15798084/4c58b354-2a2d-11e6-8222-a9ae69e68ed1.png)

**Comment by mtwww** [comment]
https://github.com/PopcornTimeTV/PopcornTimeTV/issues/134

**Comment by RefusedFlow** [comment]
Fast forward and rewind is a bit of a hit and miss at the moment, it isn't natively implemented yet so don't expect it to be fully working at the moment. We're looking for anyone with C & Obj-c experience to work on the PopcornTorrent section of the application.
