### ISSUE TITLE
Subtitle styles

### ISSUE THREAD

**Issue by lekima** [PopcornTimeTV/PopcornTimeTV#162]
Is it possible to make them look more subtle (like what we're having in PopcornTime Desktop app)?  Having a big background behind isn't very nice, just white text and black border is good enough.

**Comment by RefusedFlow** [comment]
@lekima Open PopcornTime, along the top row of icons scroll to the right and you'll see a settings area. You're able to make some adjustments there, font size and background. 

Feel free to reopen if you're having any issues! 😄
