### ISSUE TITLE
Torrent health

### ISSUE THREAD

**Issue by krantzet** [PopcornTimeTV/PopcornTimeTV#163]
Not really an issue, but more of a wish. 

It would be great if it was possible to see the health (or number of seeders / leachers) of a movie or episode. 

Is this possible?

**Comment by Evhelden** [comment]
Just like the desktop version

**Comment by RefusedFlow** [comment]
Definitely possible but the one used in PopcornTime is written in Javascript, so it would need a rewrite to work in Swift.

@buzzel 

**Reference**  https://github.com/PTCE-Public/torrent-tracker-health

**Comment by Gsuz** [comment]
might not need much rewrite since atv is about to support js natively. https://developer.apple.com/library/tvos/documentation/TVMLJS/Reference/TVJSFrameworkReference/index.html#//apple_ref/doc/uid/TP40016076

**Comment by RefusedFlow** [comment]
Added to the progress page over on the wiki so this issue will be closed.
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress
