### ISSUE TITLE
TVShow details does not load when fetchTraktSeasonEpisodesInfoForIMDB fails

### ISSUE THREAD

**Issue by joaomvfsantos** [PopcornTimeTV/PopcornTimeTV#165]
Ideally this should load the TVShow screen with less detailed information, or as last resort an error message?

This happens on TVShows like "11.22.63", "Reno 911!" and "Deadline!"

**Comment by buzzel** [comment]
I've never encountered this issue before. We'll look into a solution though :)

**Comment by joaomvfsantos** [comment]
@buzzel This is really a corner case, I stumbled upon it by mere chance too ;)

**Comment by T0XicGreif3r** [comment]
This also happens with The Office. :)

**Comment by jberglinds** [comment]
I believe this could be the same problem as in https://github.com/PopcornTimeTV/PopcornTimeTV/issues/86.
It was closed when a separate bug was found and fixed in the issue.

**Comment by joaomvfsantos** [comment]
I am under the suspicion that this problem occurs when the TV Show name contains certain characters like dots and exclamation marks. I realized this also happens on Mr. Robot which incidentally contains also a dot on the name.

**Comment by tiferrei** [comment]
This issue should now be fixed (commit 364), please reply if it continues to happen.
