### ISSUE TITLE
No Subtitles Available

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#165]
when trying to choose the subtitle language it says (No Subtitles Available) on commit (37)
but I tried the same movies and shows on commit (31) and it worked fine
I guess its a new bug

**Comment by FlaviaBondJamesBondsHusband** [comment]
Subtitles are working in latest commit. What movie are you trying to watch?

**Comment by moh0sw** [comment]
@FlaviaBondJamesBondsHusband I tried Nerve and Now You See Me 2 and WestWorld and BlindSpot and all of them I tried on the commit (31) and the subtitles works but now on commit (37) It says No Subtitles Available

**Comment by FlaviaBondJamesBondsHusband** [comment]
Just checked and its working perfectly. Must be an issue with your internet. Would you mind trying again? 

![simulator screen shot 31 oct 2016 18 42 57](https://cloud.githubusercontent.com/assets/20926198/19866893/e6697514-9f99-11e6-8ec9-2ff77f1b4ee0.png)

**Comment by moh0sw** [comment]
@FlaviaBondJamesBondsHusband just give me a sec and I will give it a try

**Comment by moh0sw** [comment]
@FlaviaBondJamesBondsHusband Now On It works after making a new build
Thanks :)

**Comment by FlaviaBondJamesBondsHusband** [comment]
I think it was an issue with the open subtitles api. It may have been down earlier today; IIRC there were some people complaining about it on reddit. No worries :)

**Comment by moh0sw** [comment]
@FlaviaBondJamesBondsHusband there is another issue and I didn't want to open a new issue
the episodes on the shows now don't have a picture just a black photo
and Movie (Suicide Squad) can't even press it :(

**Comment by FlaviaBondJamesBondsHusband** [comment]
@moh0sw there are show images, trakt.tv is having problems with episode images and Suicide Squad isn't even on popcorn time yet. If you were selecting it from suggested movies an alert would have appeared saying no torrents are available for it
