### ISSUE TITLE
getting weird error running swift install.swift

### ISSUE THREAD

**Issue by Gsuz** [PopcornTimeTV/PopcornTimeTV#166]
swift install.swift
install.swift:8:47: warning: extraneous '_' in parameter: 'request' has no keyword argument name
    public static func requestSynchronousData(_ request: URLRequest) -> Data? {
                                              ^~
                                              
install.swift:22:60: warning: extraneous '_' in parameter: 'requestString' has no keyword argument name
    public static func requestSynchronousDataWithURLString(_ requestString: String) -> Data? {
                                                           ^~
                                                           
install.swift:29:47: warning: extraneous '_' in parameter: 'request' has no keyword argument name
    public static func requestSynchronousJSON(_ request: URLRequest) -> Any? {
                                              ^~
                                              
install.swift:35:60: warning: extraneous '_' in parameter: 'requestString' has no keyword argument name
    public static func requestSynchronousJSONWithURLString(_ requestString: String) -> Any? {
                                                           ^~
                                                           
install.swift:44:2: error: unknown attribute 'discardableResult'
@discardableResult func run(_ args: String...) -> Int32 {
 ^
install.swift:44:29: warning: extraneous '_' in parameter: 'args' has no keyword argument name
@discardableResult func run(_ args: String...) -> Int32 {
                            ^~
                            
install.swift:54:12: warning: extraneous '_' in parameter: 'input' has no keyword argument name
func input(_ input: String) -> String {
           ^~
           
install.swift:5:18: error: use of undeclared type 'URLSession'
public extension URLSession {
                 ^~~~~~~~~~
install.swift:45:16: error: 'Process' cannot be constructed because it has no accessible initializers
    let task = Process()
               ^
install.swift:56:20: error: use of unresolved identifier 'FileHandle'
    let keyboard = FileHandle.standardInput
                   ^~~~~~~~~~
install.swift:71:19: error: use of unresolved identifier 'URLSession'
if let jsonData = URLSession.requestSynchronousJSONWithURLString("https://api.github.com/repos/PopcornTimeTV/PopcornTimeTV/releases") as? [[String : AnyObject]] {
                  ^~~~~~~~~~
install.swift:89:4: error: value of type 'String' has no member 'lowercased'
if version.lowercased() != "master" {
   ^~~~~~~ ~~~~~~~~~~
install.swift:101:21: error: value of type 'String' has no member 'lowercased'
let podsInstalled = input("Do you have cocoapods installed? (Enter Yes or No): ").lowercased()
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~

**Comment by FlaviaBondJamesBondsHusband** [comment]
Update to Xcode 8 as the guide for noobs says

**Comment by Gsuz** [comment]
Guess the build guide in the wiki needs updating then..

https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

it says xcode 7.3
