### ISSUE TITLE
the old remote Does not work Unsupported PopcornTime

### ISSUE THREAD

**Issue by iAYMANi** [PopcornTimeTV/PopcornTimeTV#166]
![hand-holding-2-3-gen-remote-right-click](https://cloud.githubusercontent.com/assets/12406459/15809451/4ae5a6b2-2b9a-11e6-88c2-6cd1ed977c0e.jpg)

**Comment by tengis** [comment]
We don’t have any plans currently to support the old remote, but possibly in the future.

You are most welcome submit pull request
