### ISSUE TITLE
crashed and the siri control not working properly ..

### ISSUE THREAD

**Issue by ynnad696** [PopcornTimeTV/PopcornTimeTV#167]
yesterday after couple days working fine with no issues , it started to act like before, when the siri control instead of going forward it just make to appear the subtitles and getting frozen and crashing in the middle of the movie.. I'm using 0.6.6 at the beginning it was fine but yesterday afternoon was bad ....

**Comment by pbo1976** [comment]
I'm experiencing also crashes like before (on 0.6.6 now). Even if the movie is paused. Did a "pod update" but it happened again.

**Comment by GIthHub2die4** [comment]
@pbo1976 How did you manage the 'pod update' .. I am having same problem has you and @ynnad696 can't fast forward, it brings up the subtitle and also sometimes it crashes when watching movie/tv show..

**Comment by pbo1976** [comment]
not sure what i did, i think I reinstalled all over again. it's been almost a week, so I will have to do it again soon.

**Comment by GIthHub2die4** [comment]
with latest 0.7.0 version lots of crash happening.. did it while trying to watch movie and tv show Daredevil

**Comment by ynnad696** [comment]
yes now is worst with the 0.7.0 version, today i had to start the movie 5 times after 5 crash one after one.. sucks ......

**Comment by GIthHub2die4** [comment]
New apple tv remote app should fix this since it has a playing now mode giving you access to the movie progress bar, therefore making it easier to fast forward and rewind.
