### ISSUE TITLE
0.2.0-0 reporting problems

### ISSUE THREAD

**Issue by tomto147** [PopcornTimeTV/PopcornTimeTV#169]
So I have just build from scratch the newest version from 0.2.0-0. Installed it and...
- not possible to change subtitles section in settings (encoding, size, background) - app closes after any change
- not possible to choose from seasons in TV Shows, only one available
- not possible to access subtitle menu from top - app closes after swipe from top.
So as for now only 1.0.3 is more or less functional...

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for reporting all the known bugs
