### ISSUE TITLE
Subtitles unreliable

### ISSUE THREAD

**Issue by Tom2527** [PopcornTimeTV/PopcornTimeTV#17]
At the moment, I cannot get subtitles in Dutch or English. All other available languages work fine, but these languages no longer work. When choosing them, playback stops, and they don't appear. As it's impossible that every episode or movie I tried does have missing/corrupt subtitles in those particular languages, I must assume it's some kind of bug.

**Comment by abufreeh** [comment]
same here with Hebrew language but no problem with arabic it's works great

**Comment by popcornMaster** [comment]
Please try selecting a different encoding, especially for the languages you are referring to. Maybe try utf8 for dutch/english? This issue is not to be resolved by the team, we have a mechanism in place so the user can solve it!
