### ISSUE TITLE
Install tutorial

### ISSUE THREAD

**Issue by woodsbox** [PopcornTimeTV/PopcornTimeTV#170]
Hi Guys,

Saw this GitHub post and it's very cool!
I know some IT thigs only don't understand how to do this installation.
Does anyone have a install video or detaild information?
I just bought the apple tv 4 new from the store so no Jailbraik yet.

Greetz.

**Comment by smith288** [comment]
Pull the code locally on a mac, find the folder you pulled to and run swift Install.swift then when that's done, you run the app in Xcode while hooked up to your appletv.

**Comment by buzzel** [comment]
@woodsbox You can check out our WikiDoc explaining the process https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime
