### ISSUE TITLE
Sideload App issue/question 

### ISSUE THREAD

**Issue by fzhengnyc** [PopcornTimeTV/PopcornTimeTV#172]
Hi,

i did side load popcorn time to my Apple TV 4. It is working perfectly. But I am able to open it after a few days/ a week. I don't what's wrong with my account or Apple TV?

This same thing happened for other side loaded app, like KODI.

Thanks,
Fei

**Comment by RefusedFlow** [comment]
Hai, 

This issue has nothing that relates to the project specifically, without a register developer account you can only sign applications for 7 days (down from 90 days) Your best solution is to find a company that will codesign and activate your UDID for your apple TV.

Closing this issue as it's irrelevant to the application.
