### ISSUE TITLE
0.6.6 error

### ISSUE THREAD

**Issue by kokozaurz** [PopcornTimeTV/PopcornTimeTV#174]
Hi,

I'm running in to issue of copying over 0.6.6 to Apple TV4. 0.6.5 runs completely fine, but 0.6.6 even though it builds successfully it can't copy it over to ATV. It gives me an unknown error at Xcode. Apple TV has the latest update on.

Any solutions?

**Comment by next2non** [comment]
I'm having the same problem "App installation Faildes" An unknown error has occurred. Even though the build was successful.

**Comment by buzzel** [comment]
Try restarting your computer. I've found this helps me.

**Comment by tengis** [comment]
Just released new version 0.7.0 please feel free to download it and give it a try.
