### ISSUE TITLE
IPA file for Popcorntime

### ISSUE THREAD

**Issue by Cheito** [PopcornTimeTV/PopcornTimeTV#175]
Does anyone know how to create an IPA file for PopcornTime? Can anyone build one for the latest 0.6.6 version? I have been having numerous errors when trying to build one myself.

**Comment by RefusedFlow** [comment]
@Cheito We won't be compiling the project into an .ipa you're more than welcome to purchase a developer account yourself and sign the application but we won't unfortunately.
