### ISSUE TITLE
Stuck at loading 'Processing....0%'

### ISSUE THREAD

**Issue by russkn87** [PopcornTimeTV/PopcornTimeTV#176]
When I try to load any content the processing bar is stuck on 'Processing....0%' and just stays that way, with any video and any size format.

Do you know what a solution might be?

**Comment by tengis** [comment]
@russkn87 it might be your torrent ports blocked on you ISP

**Comment by tengis** [comment]
i'm gonna close this issue. If torrent download working on your ISP feel free reopen this issue

**Comment by russkn87** [comment]
Hello, thanks for your response. Torrents aren't blocked by my ISP and I have the same issue with different ISPs which are certainly not blocked, and the Mac App works just fine.

**Comment by tengis** [comment]
@russkn87 Which version are you using? Please try version 0.7.0 and can you send us console logs?

**Comment by russkn87** [comment]
I'm using 0.6.6 from https://tv.ipwnstore.me/, presigned I guess they will update the release soon and then I can test the latest version.

**Comment by tengis** [comment]
oh right
