### ISSUE TITLE
Project Error

### ISSUE THREAD

**Issue by The1PRimeYT** [PopcornTimeTV/PopcornTimeTV#178]
![screen shot 2016-11-08 at 5 32 13 pm](https://cloud.githubusercontent.com/assets/21149526/20120135/742be2e8-a5d9-11e6-8ae4-407f7466ef7e.png)
i need help with this error i did everything but nothing

**Comment by FlaviaBondJamesBondsHusband** [comment]
I take it you are running the install script? If so rerun and select release `0.2.0-5`. Otherwise re-clone the latest version of master
