### ISSUE TITLE
Same movies

### ISSUE THREAD

**Issue by pbo1976** [PopcornTimeTV/PopcornTimeTV#179]
Not sure how to approach this, but I always see the same movie posters at the TopShelf and Popular. And Latest are not really 2016 movies. How is that possible? I know TopShelf and Popular are pretty much the same source, but there are new movies online that simple won't show up in Popular either.

**Comment by RefusedFlow** [comment]
Hai @pbo1976 

I plan on doing some rework on the way content is displayed making it easier to sort and filter content within the next few weeks! I believe content on topshelf if being sorted by seeds at the moment so Popularity. I plan on changing it to display latest movies with a rating better than 3/5 stars and only show movies from 2016 what would you think of that?

**Comment by RefusedFlow** [comment]
Also current latest pulls any new movies added to the API rather than latest movies for 2016, something I'll fix in the coming weeks 😄

**Comment by pbo1976** [comment]
Sounds great! Thanks

**Comment by tengis** [comment]
Hey guys 
Infinite pagination implemented on last commit. Please check
