### ISSUE TITLE
Difficult to select subtitle language

### ISSUE THREAD

**Issue by Tom2527** [PopcornTimeTV/PopcornTimeTV#18]
PopcornTimeTV is simply great!! It's remarkably stable, but It's quite hard to select a subtitle language in the current interface. When swiping left/right to select the appropriate language, the playback slider also moves along. So when finally arriving at the language of your choice, you might have accidentally forwarded playback by 15 minutes. I don't know if this is a bug, or a drawback of the ATV4 interface, but it's very annoying. In any case, it would also be nice to select a default subtitle language. But again, great piece of software!!

**Comment by GIthHub2die4** [comment]
Same here. Also tried selecting French subtitle and never worked.

**Comment by popcornMaster** [comment]
Could you please clarify how you are choosing the subtitles? Are you tapping on the remote to select the subtitle or swiping? Cause swiping should work without an issue, tapping has some slight problem that we have detected!

**Comment by Tom2527** [comment]
1. Video is playing
2. Swipe down
3. Tap to select "Subtitles"
4. Swipe left/right to select language. The playback slider moves too.
5. Tap to select the right subtitles
6. Playback stops (why?)
7. Press play to resume playback with subtitles

**Comment by popcornMaster** [comment]
Thanks for that, fix coming soon ;)

**Comment by Tom2527** [comment]
great!

**Comment by popcornMaster** [comment]
Fix is up, please use git pull to test the new change, it will be integrated on the updated version!
