### ISSUE TITLE
Bundle install

### ISSUE THREAD

**Issue by darkneo29** [PopcornTimeTV/PopcornTimeTV#18]
On Mac how do you do step 2 and 3 with the bundle installs?

**Comment by Fardilha** [comment]
Hi there.

Just to add my "me too" to this problem.

I'm getting this errors:

`Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /Applications/Server.app/Contents/ServerRoot/usr/bin/ruby extconf.rb 
mkmf.rb can't find header files for ruby at /Applications/Server.app/Contents/ServerRoot/usr/lib/ruby/include/ruby.h


Gem files will remain installed in /Users/pedro/.bundler/tmp/14441/gems/json-1.8.3 for inspection.
Results logged to /Users/pedro/.bundler/tmp/14441/gems/json-1.8.3/ext/json/ext/generator/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install son 
-v '1.8.3'` succeeds before bundling.
`

`Parsing documentation for json-1.8.3
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/json/ext/generator.bundle, skipping
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/json/ext/parser.bundle, skipping`

`bundler: command not found: pod
Install missing gem executables with `bundle install``

**Comment by JakeRound** [comment]
Okay so you want to open a Terminal window and run the following commands, this will give you the dependancies to run the commands afterwards.

- `sudo gem install cocoa pods`
- `sudo gem install bundler`

After those to have installed pursue with running the following commands to clone the repository to your desktop. _**Obviously you can change the location if you wish**_

- `cd ~/Desktop`
- `git clone https://github.com/pepibumur/PopcornTimeTV.git`
- `cd ~/Desktop/PopcornTimeTV`
- `bundle install`
- `bundle exec pod install`

After you've successfully run all of the previous commands in terminal you'll be able to open the project that should be on your desktop under a folder called PopcornTimeTV.

**Hope it helps any questions feel free to ask**

**Comment by Fardilha** [comment]
Jake, thank you so much for you help!!
I tried as you pointed out but on the last step i got this:

$bundle exec pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `Localize-Swift` from `https://github.com/pepibumur/localize-swift`, commit `85181e4dee18df3c1345ff378d70a659b91a82ef`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/pedro/.rvm/gems/ruby-2.3.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.2.4
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 1.9.2
Ruby lib dir : /Users/pedro/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6f20b55aa03902295c0d2a0e3737c5e359285dff
               popcorntimetv - https://github.com/PopcornTimeTV/Specs.git @ 36eae381d6bed9fed2963bcbcebf2cb1fec0d050
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
use_frameworks!

source "https://github.com/PopcornTimeTV/Specs.git"
source 'https://github.com/CocoaPods/Specs'

target 'PopcornTime' do
  link_with 'PopcornTime', 'PopcornKit', 'PopcornKitTests', 'PopcornExtension'
  pod 'Genome'
  pod "SnapKit"
  pod "RXHTTPCommander"
  pod 'ReduxKit', '~> 0.1'
  pod 'Localize-Swift', :git => "https://github.com/pepibumur/localize-swift"
  pod "PopcornTorrent"
end

target 'Tests' do
  link_with 'PopcornKitTests'
  pod 'Quick'
  pod 'Nimble'
end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="Alamofire">
Did you mean?  to_query
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/pedro/.rvm/gems/ruby-2.3.0@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/pedro/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/pedro/.rvm/gems/ruby-2.3.0/bin/pod:22:in `load'
/Users/pedro/.rvm/gems/ruby-2.3.0/bin/pod:22:in `<main>'
/Users/pedro/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/pedro/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60to_ary%27+for+%23%3CPod%3A%3ASpecification+name%3D%22Alamofire%22%3E%0ADid+you+mean%3F++to_query&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by JakeRound** [comment]
I honestly don't have a clue what's going on there, i cloned the repository on a clean install of El Capitan. Join the Slack group and i'm sure somebody more experienced than me will be able to figure out what's going on.

Else @pepibumur may have some idea what's going on

**Comment by Fardilha** [comment]
Hi Jake.
I have to assume that between MacPorts and Homebrew installations something broke on a nasty way.
I'll create a clean test instance and try to compile from there.

Thank you for all the help.
Pedro
