### ISSUE TITLE
TV shows and movie update

### ISSUE THREAD

**Issue by GIthHub2die4** [PopcornTimeTV/PopcornTimeTV#181]
Hello, how often does it update movies and tv shows ? Per exemple new season of Orange is new black is up but missing lots of episode ? Anyone else ?

**Comment by RefusedFlow** [comment]
Moves and TV Shows automatically update when they've been added to YTS or EZTV, if you can't find something you're looking for you can always try the new KickAss Search in the latest commit

**Comment by GIthHub2die4** [comment]
Oh ok, I have the latest 0.6.6 but can't find the kickass search..

**Comment by RefusedFlow** [comment]
Download the latest commit from the master branch below. It will then add a tab on the welcome screen. No plans for Putlocker.is unfortunately, we're sticking to PopcornTime torrent streaming only :)

https://github.com/PopcornTimeTV/PopcornTimeTV/archive/master.zip

**Comment by GIthHub2die4** [comment]
Ok, i'm trying just seem to be getting into hard time building the thing lol

**Comment by GIthHub2die4** [comment]
@RefusedFlow i'm getting the following error when trying to archive

bitcode bundle could not be generated because '/Users/brunomedeiros/Desktop/PopcornTimeTV-master-2/Pods/TVVLCKit/TVVLCKit.framework/TVVLCKit(VLCEventManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Evhelden** [comment]
Do you make this a new version any time soon?

**Comment by tengis** [comment]
@GIthHub2die4 Please try install script. Also follow this instructions https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

@Evhelden i hope it's very soon. But you can try latest changes from master branch.

**Comment by tengis** [comment]
Hey guys 
Infinite pagination implemented on last commit. Please check
