### ISSUE TITLE
Service Down?

### ISSUE THREAD

**Issue by JohnRPoole** [PopcornTimeTV/PopcornTimeTV#181]
Popcorn Time has not been loading today.  I have deleted and re-installed .ipa 2x (no issues w/ provisioning profile, etc).  No "loading" splash screen, just the opaque gray background screen.

Is this a local issue or is it more widespread?

**Comment by iAYMANi** [comment]
me 2

**Comment by garranhado** [comment]
Yeps, services down.

**Comment by sqig** [comment]
Same for me on the Apple TV4.
The mac desktop version from popcorn-time.to is still working.

**Comment by JohnRPoole** [comment]
There haven't been any commits to the project in 10 days and no comments by the development team re: outage.  Does anyone know if this has been discontinued?

**Comment by FlaviaBondJamesBondsHusband** [comment]
As stated literally a million times "PSA: We are NOT affiliated with AppDB or any other organization - free or otherwise - that provides resigned IPA files and it is not our responsibility if there are bugs in their versions of the app." 

**You are using an iPA. We do not support iPA's.**
