### ISSUE TITLE
Problem building 0.6.6

### ISSUE THREAD

**Issue by litengulfisk** [PopcornTimeTV/PopcornTimeTV#182]
I get then when trying to build 0.6.6

![skarmklipp 2016-06-23 11 08 23](https://cloud.githubusercontent.com/assets/18162266/16297861/ed286db0-3932-11e6-9c56-269f670c8c4b.png)

**Comment by les69** [comment]
Hi,
Same problem here. I just tried to guess what the developer meant and I just added let kat = servers["kat"] and put it into the function. I'm not sure if this is the right fix, the developers will probably correct that but for the moment it works (on the simulator at least). I am not an experienced swift developer, but I hope this may help anyway! 
![fix](https://cloud.githubusercontent.com/assets/2937623/16301018/49114916-3943-11e6-9f0d-443964fb82ab.png)

**Comment by tengis** [comment]
`rm -rf Pods/`
`pod install`

try these commands. PopcornKit library installed still old version which is one of the dependency. Need to re install

**Comment by tengis** [comment]
Or try this https://github.com/PopcornTimeTV/PopcornTimeTV/archive/master.zip

**Comment by tengis** [comment]
Just released new version 0.7.0 Please feel free to download it and give it a try.

**Comment by GIthHub2die4** [comment]
@tengis version .0.7.0 work on my apple tv4, but when i try to make an ipa out of the project this is the error it gives me:
![screen shot 2016-06-24 at 1 11 02 pm](https://cloud.githubusercontent.com/assets/20074247/16344921/200a551a-3a0d-11e6-8f5a-8fb59ab8d55c.png)

**Comment by tengis** [comment]
Try running this command in terminal `rm -rf ~/.cocoapods/repos/popcorntimetv`
  
then delete the `rm -rf Pods` folder and `rm Podfile.lock` in the PopcornTime folder

& `pod install` then build again

**Comment by GIthHub2die4** [comment]
Ok tried all no success.. running that command from the popcorntime folder does nothing
