### ISSUE TITLE
Sci-Fi Movies Genre not loading

### ISSUE THREAD

**Issue by gnyvie** [PopcornTimeTV/PopcornTimeTV#185]
Hi,

when going to Genres and then scrolling down to Sci-Fi nothing will load. Any other genre shows results but Sci-Fi will just be blank. Anybody else having this issue? Had it since 0.6.6

**Comment by Evhelden** [comment]
Seems caused by the '-' sign. In all versions

**Comment by RefusedFlow** [comment]
Sci-Fi category doesn't actually exist on the current API used
http://62.210.81.37/api/v2/list_movies.json?genre=Sci-Fi

**Comment by RefusedFlow** [comment]
**Closing this issue as it relates to the API we're using rather than the application.**
