### ISSUE TITLE
Player stops after 10%

### ISSUE THREAD

**Issue by krantzet** [PopcornTimeTV/PopcornTimeTV#185]
Using 0.2.0-5 on TVOS10

I am trying to watch a TV Show (this time The Simpsons S28E06). The show starts and for the first 2 minutes (I guess 10% of the show) it works perfect. After this the problem starts. It freezes, startes, plays a few seconds, freezes and so it goes on. Does not matter if its 480p or 720p.

The Player Timeline UI  shows progress on downloading the show and after a short time it shows that the full episode have been downloaded, yet it freezes during playback. First 10% - no problem!

**Comment by FlaviaBondJamesBondsHusband** [comment]
#188
