### ISSUE TITLE
Scrubbing - not working at all

### ISSUE THREAD

**Issue by shaybc** [PopcornTimeTV/PopcornTimeTV#186]
inside a movie or tv show play, once there is enough buffer i will pause, then scrub (slide my finger on the remote in order to reach play point to a certain time at the movie/TV Show),

the scrub works fine until the first 6 minutes, if you try to scrub further then that it will not allow (even if the full episode / movie is buffered), 

when i try to press play in order to continue the movie / tv show the player is frozen in loading state (loading wheel circles forever).

tried to fix it in my local copy and failed, it looks like the problem is within the torrent kit

**Comment by RefusedFlow** [comment]
Scrubbing isn't currently implemented, closing this issue as it related to PopcornTorrent in which already has an open issue

https://github.com/PopcornTimeTV/PopcornTorrent/issues/1
