### ISSUE TITLE
Progress Bar won't go away

### ISSUE THREAD

**Issue by jaburgeson** [PopcornTimeTV/PopcornTimeTV#187]
The progress bar stays on the screen while a video is playing.

**Comment by FlaviaBondJamesBondsHusband** [comment]
tap the remote

**Comment by barbro66** [comment]
Shouldn't the progress bar fade after 10 seconds or so.  I've been watching films with the progress bar, since I didn't realise you needed to tap to make it go away.  That seems pretty unstandard and not obvious to new users?

**Comment by tvOSPopcorn** [comment]
@barbro66 There are plans to replicate how Apple handles the playback options in a future update #194

**Comment by barbro66** [comment]
Thanks!  Much appreciated.  Great work on a GREAT app
