### ISSUE TITLE
Missing tv and movie poster

### ISSUE THREAD

**Issue by GIthHub2die4** [PopcornTimeTV/PopcornTimeTV#187]
Hi all! Since updating to latest version ice noticed some movies and tv shows are missing there poster. The title is written underneath but image is plain white

**Comment by tengis** [comment]
Could you send screenshot?

**Comment by GIthHub2die4** [comment]
![20160627_091156_hdr](https://cloud.githubusercontent.com/assets/20074247/16389051/2c4e45f2-3c6a-11e6-8c24-2ef5fd1ca6dc.jpg)
![20160627_091230_hdr](https://cloud.githubusercontent.com/assets/20074247/16389050/2c49def4-3c6a-11e6-8097-bc78b5f7cd56.jpg)

**Comment by tengis** [comment]
@GIthHub2die4 I saw this issue once on my device. But next time i reloaded the page all working fine. 

I think this is something related with API server we are using
