### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by GIthHub2die4** [PopcornTimeTV/PopcornTimeTV#188]
Hello, when is vpn going to be implemented.. unfortunately with my router i cannot install vpn.. just asking because i got email from my isp for watching daredevil lol..

Thanks

**Comment by RefusedFlow** [comment]
VPN support is [planned](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress) however don't expect it anytime soon, other parts of the application are more of a priority. You're more than welcome to implement VPN support yourself and create a PR.

**Will be closing this issue as it's already on the Progress wiki**

**Comment by drew5494** [comment]
I hope it comes soon I just got a notice from my internet provider, the day after using popcorntime on the Apple TV?

**Comment by RefusedFlow** [comment]
You're probably better off setting up a VPN at router level for the time being, as the Apple TV doesn't natively support VPN's so a work around will take time.

**Comment by drew5494** [comment]
I would but my router doesn't support VPN :(

**Comment by drew5494** [comment]
Ok guys I found a temporary solution for using a VPN on the Apple TV 4 without using a router level VPN.  The solution is internet sharing!  https://www.expressvpn.com/support/vpn-setup/share-vpn-connection-mac/#sharing
