### ISSUE TITLE
fast forward and pause

### ISSUE THREAD

**Issue by puba** [PopcornTimeTV/PopcornTimeTV#188]
I am unable to pause the playing media, clicking once on the touch screen on remote displays only timeline on player. Fast forwarding the media for let say 5 min just freezes the content, the same behavior with rewinding media also. Play/pause button on remote does not work. Everything else working nicely.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Clicking once one the touch screen remote is only supposed to show the timeline. Pressing the play pause button will.. play and pause the media ;). Unfortunately VLCKit is to blame for the other player issues and we cannot do anything about it right now. Hopefully VLCKit 3.0.0 will be out soon. We were using the alpha version before but it was too buggy to continue using
