### ISSUE TITLE
IOS Version keeps crashing

### ISSUE THREAD

**Issue by Faisal-nz** [PopcornTimeTV/PopcornTimeTV#189]
![screen shot 2016-11-18 at 2 29 49 pm](https://cloud.githubusercontent.com/assets/17815290/20429320/fd6afb6c-ad9e-11e6-8f69-5624f2a6b27c.png)

i keep getting this error, tried on 3 devices the same thing happens, either the application get frozen or it starts then when i click on any movie it crash

**Comment by Faisal-nz** [comment]
*** Assertion failure in -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UICollectionView.m:1599
Fri Nov 18 15:07:11 2016: PopcornTime (com.faisal1811.popcorntime.tvos): *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView dataSource is not set'
*** First throw call stack:
(0x1824b6db0 0x181b1bf80 0x1824b6c80 0x182e3c154 0x1877a72c4 0x187679a80 0x187674808 0x1876101e4 0x184fa298c 0x184f9d5c8 0x184f9d488 0x184f9cab8 0x184f9c818 0x184f95ddc 0x18246c728 0x18246a4cc 0x18246a8fc 0x182394c50 0x183c7c088 0x18767e088 0x1001548c4 0x181f328b8)
Fri Nov 18 15:07:11 2016: ReportCrash (Crash Reporter): Formulating report for corpse[3750] PopcornTime

**Comment by FlaviaBondJamesBondsHusband** [comment]
The iOS app is not meant to be used yet. Please use the one at https://github.com/PopcornTimeTV/PopcornTimeiOS

**Comment by Faisal-nz** [comment]
ok. thanks a lot
