### ISSUE TITLE
Three errors when trying to compile

### ISSUE THREAD

**Issue by jonathanfloydian** [PopcornTimeTV/PopcornTimeTV#19]
Both the manual method and the install.swift script give me the following three errors:

- diff: /../Podfile.lock: No such file or directory

- diff: /Manifest.lock: No such file or directory

- error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

 When I try to run pod install to fix the third error, it gives me this error (in the terminal) : 
 - NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AEXML">

Any help would be sincerely appreciated

**Comment by BilalBaydoun** [comment]
open this file "PopcornTime.xcworkspace" then build don't open this file "PopcornTime.xcodeproj"

**Comment by FlaviaBondJamesBondsHusband** [comment]
Looks like theres something wrong with your cocoapods installation. Run these commands to remove them and then re run the install script.
````
gem uninstall cocoapods
gem uninstall cocoapods-core
gem uninstall cocoapods-downloader
rm -rf ~/.cocoapods/
````
