### ISSUE TITLE
No top shelf?

### ISSUE THREAD

**Issue by hessius** [PopcornTimeTV/PopcornTimeTV#192]
Hi, dunno if this is a missing feature or a bug - I'm not getting any top shelf content for the app, which is working fine in all other regards. I'm on latest 9.X tvOS, using the master branch from 5 days ago.

**Comment by RefusedFlow** [comment]
@hessius Try deleting the application, reinstall using the [following guide](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime) from there your topshelf should be present if you change the BundleID of the topshelf.
