### ISSUE TITLE
Kickass search got me in trouble ...

### ISSUE THREAD

**Issue by ynnad696** [PopcornTimeTV/PopcornTimeTV#193]
this mourning i was trying the new Kickass search just to see how it was working after the 0.7.0 update , i watched "The Conjuring 2" just for like 1 minute and them got out , .... 
Now i just got an email from my internet provider telling the received an email complain about that particular movie been download from my IP address...
i've been using Popcorn Time for many months now and never received nothing before , i didn't download any content i was just watching the movie which i stopped soon after it started , can any one tell me if something like that happened before?

**Comment by RefusedFlow** [comment]
Closing this issue as it it has nothing to do with PopcornTimeTV it's self rather than your ISP having an issue with you downloading illegal content, i'd recommend you setup a VPN at router level to get around this issue.
