### ISSUE TITLE
Apple Mach-O Linker Warning Group "issues"

### ISSUE THREAD

**Issue by iAYMANi** [PopcornTimeTV/PopcornTimeTV#196]
any help for the issues 
![screen shot 2016-11-21 at 5 39 24 pm](https://cloud.githubusercontent.com/assets/12406459/20486665/a940c416-b011-11e6-94c9-fc8b887509a1.png)

**Comment by iAYMANi** [comment]
ok how to fix?

**Comment by lockers90** [comment]
I'm running into the exact same issue.
