### ISSUE TITLE
Apple Mach-O Linker Warning Group "issues"

### ISSUE THREAD

**Issue by lockers90** [PopcornTimeTV/PopcornTimeTV#198]
```
ld: bitcode bundle could not be generated because '/Users/Adam/Desktop/PopcornTimeTV 18.57.26/Pods/PopcornTorrent/Build/tvOS/PopcornTorrent.framework/PopcornTorrent' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is the error ive been getting for the past few days. Can anyone help?

ive tried cleaning the libraries and updating libraries and pods. nothing has worked so far.

**Comment by GoldenChaos** [comment]
All you need to do is turn off bitcode and it'll build:
![screen shot 2016-11-23 at 8 08 58 pm](https://cloud.githubusercontent.com/assets/1396727/20583521/aebc85bc-b1b8-11e6-89dd-d68ed18561c9.png)
