### ISSUE TITLE
How to use a VPN with Popcorn Time (Without touching your router)

### ISSUE THREAD

**Issue by drew5494** [PopcornTimeTV/PopcornTimeTV#198]
Hey so if you're like me who keep getting messages from your internet provider telling you  to stop then you should get a VPN!  

 I found a temporary solution for using a VPN on the Apple TV 4 **without using a router level VPN**. The solution is internet sharing! 
https://www.expressvpn.com/support/vpn-setup/share-vpn-connection-mac/#sharing

**Comment by tiferrei** [comment]
Thank you @drew5494! This has been added to the [FAQ].(https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/FAQ)
