### ISSUE TITLE
Error 404 : Install PopCornTime 1.0

### ISSUE THREAD

**Issue by RafaleD** [PopcornTimeTV/PopcornTimeTV#2]
Hello.

Sadly impossible to install PopcornTime 1.0. Bad Link in the script

`Installing PopcornTorrent (1.1.0.1)

[!] Error installing PopcornTorrent
[!] /usr/bin/curl -f -L -o /var/folders/rf/2x5vtb5929jfn00mmj1_3lnr0000gn/T/d20160801-4006-cxgka2/file.zip https://github.com/PopcornTimeTV/PopcornTorrent/releases/download/1.1.0.1/PopcornTorrent.framework.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found`

**Comment by mourke** [comment]
Clear pod cache using `rm -rf ~/.cocoapods/repos/popcorntimetv`

**Comment by RafaleD** [comment]
Still not working :/

**Comment by aggelos81** [comment]
please do a pod repo update and see if it helps

**Comment by RafaleD** [comment]
`MacBook-Pro-de-Dany:PopcornTimeTV Dany$ pod repo update
Updating spec repo `danylokostyshyn`
  $ /usr/local/bin/git pull --ff-only
  Already up-to-date.
Updating spec repo `master`

CocoaPods 1.1.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.beta.1

Updating spec repo `popcorntimetv`
  $ /usr/local/bin/git pull --ff-only
  fatal: Not possible to fast-forward, aborting.

[!] CocoaPods was not able to update the `popcorntimetv` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose``

**Comment by ChronusDev** [comment]
1. Delete your popcorntimetv directory. 
2. Clone PopcornTimeTV directly from the master branch.
3. cd to the PopcornTimeTV directory and run swift install.swift.

**Comment by RafaleD** [comment]
Same error

**Comment by mourke** [comment]
try rm -rf "${HOME}/Library/Caches/CocoaPods”; rm -rf “`` `pwd` ``/Pods/“; pod update

**Comment by RafaleD** [comment]
YES !! It works ;)

Thank you all ;)

**Comment by tomsbrinkis** [comment]
Not working for me. This error ir from yesterday. 

![screen shot 2016-08-01 at 17 51 47](https://cloud.githubusercontent.com/assets/20775280/17297974/b6167b62-5810-11e6-84bd-d38c62f4044d.png)

**Comment by mourke** [comment]
Remove the project on your machine and reclone it from master. Then run the install script

**Comment by tomsbrinkis** [comment]
still the same 
![screen shot 2016-08-01 at 18 14 08](https://cloud.githubusercontent.com/assets/20775280/17298716/cbfad4ac-5813-11e6-9854-222573fd30d6.png)

**Comment by RafaleD** [comment]
Have you try 
 rm -rf "${HOME}/Library/Caches/CocoaPods”; rm -rf “`pwd`/Pods/“; pod update
Like @mourke said. It works for me.

**Comment by tomsbrinkis** [comment]
Yes, didn't work

`$ rm -rf "${HOME}/Library/Caches/CocoaPods"; rm -rf "`pwd`/Pods/"; pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `AlamofireXMLRPC` from `https://github.com/PopcornTimeTV/AlamofireXMLRPC.git`
Pre-downloading: `PopcornKit` from `https://github.com/PopcornTimeTV/PopcornKit.git`, tag `1.1.0`
Pre-downloading: `TVMLKitchen` from `https://github.com/toshi0383/TVMLKitchen.git`, branch `swift2.2`
Downloading dependencies
Installing AEXML (3.0.0)
Installing Alamofire (3.4.1)
Installing AlamofireXMLRPC (1.0.0)
Installing GCDWebServer (3.3.2)
Installing ObjectMapper (1.1.5)
Installing PopcornKit (1.1.0)
Installing PopcornTorrent (1.1.0.2)

[!] Error installing PopcornTorrent
[!] /usr/bin/curl -f -L -o /var/folders/gs/bqk0prwn50qfwtp4n579h0yw0000gp/T/d20160801-6473-zji8lk/file.zip https://github.com/PopcornTimeTV/PopcornTorrent/releases/download/1.1.0.2/PopcornTorrent-iOS.framework.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found


[!] CocoaPods was not able to update the `popcorntimetv` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose``

**Comment by mourke** [comment]
try `pod repo update; pod update PopcornTorrent --verbose`

**Comment by aggelos81** [comment]
Try pod setup!

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=ti&cv=7.12.43&pv=9.3.2&source=email_footer_2]
On Mon, Aug 1, 2016 at 6:22 PM, mourke <notifications@github.com> wrote:
try pod repo update; pod update PopcornTorrent --verbose

**Comment by SubZero1605** [comment]
I'm having the same issue, tried everything that is stated here. but it still tries to install version 1.1.0.1 anyway.

tried:
*deleting and cloning again from master
*pod setup
*running the install.swift script
*using the rm commands stated above..

nothing works :(

**Comment by tomsbrinkis** [comment]
jup, same for me. Nothing works. tried everything twice. :/

**Comment by aggelos81** [comment]
Give me some time people and I will get back to you with a comprehensive fix :)

**Comment by SubZero1605** [comment]
No pressure! you're doing an amazing work! we just want to supply the most accurate details :)

**Comment by tomsbrinkis** [comment]
The error is caused, because there is no such link as https://github.com/PopcornTimeTV/PopcornTorrent/releases/download/1.1.0.2/PopcornTorrent-iOS.framework.zip  

Keep up the good work!

**Comment by aggelos81** [comment]
I want everyone to run this command as I paste it here!
To run it you should be on the directory of popcorntimetv
`rm -rf ~/.cocoapods/repos;pod setup;pod repo update;pod install`

**Comment by garranhado** [comment]
Yep, can't using "swift install.swift"

**Comment by aggelos81** [comment]
@garranhado please use the command I entered above

**Comment by garranhado** [comment]
Thanks, maybe the solution is clean "~/.cocoapods/repos" folder.

**Comment by aggelos81** [comment]
@garranhado did it work for you?

**Comment by SubZero1605** [comment]
@aggelos81 worked for me :)! thanks!

**Comment by aggelos81** [comment]
how about you @tomsbrinkis ?

**Comment by garranhado** [comment]
@aggelos81 By now is "Setting up CocoaPods master repo"

**Comment by SubZero1605** [comment]
@garranhado yeah, that takes a while

**Comment by garranhado** [comment]
Worked for me :)

**Comment by aggelos81** [comment]
Okay just pushed a new update to the master branch! I will enter it into the release branch and hopefully we wont have any more issues!

**Comment by tomsbrinkis** [comment]
@aggelos81  just testet, it worked!
