### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by FlatlineDixie** [PopcornTimeTV/PopcornTimeTV#200]
Just cloned the master branch and and tried to build for tvOS (Xcode 8.1). 
![screen shot 2016-11-27 at 12 10 28](https://cloud.githubusercontent.com/assets/24205402/20647966/8a0da68a-b49a-11e6-9a7e-d1248681c191.png)

Is master supposed to build at the moment?

**Comment by FlaviaBondJamesBondsHusband** [comment]
If you are not competent enough, please use the install script. For over half a year (since cocoapods RC1), spec repos have not been updated by just running `pod install`. Running `pod repo update` will fix your issue.
