### ISSUE TITLE
Problem with pod install

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#201]
I did every thing!

cd ~/Desktop
git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git

Then when I put 
cd ~/Desktop/PopcornTimeTV
 Swift install.swift

And last thing the script ask , Do you have cocoapods installed? (Enter Yes or No): 
I choose no

Then it says (Installing cocoapod gem...)

Then afer that nothing happens! 

Please Help!

**Comment by adrianmihai83** [comment]
Why not install cocoapod before and chose no in the script?

gem install cocoapods or sudo gem install cocoapods if you do not have permission, or change the permissions

I went this way without issue.

**Comment by RefusedFlow** [comment]
@moh0sw https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

**Comment by moh0sw** [comment]
@adrianmihai83 @RefusedFlow I Have tried before

gem install cocoapods
It says after it finish (ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.)

And sudo gem install cocoapods
Says ( ERROR:  Error installing cocoapods:
activesupport requires Ruby version >= 2.2.2.)

**Comment by adrianmihai83** [comment]
sudo gem install activesupport -v 4.2.6

after that

sudo gem install cocoapods

and you are golden ;)

**Comment by moh0sw** [comment]
@adrianmihai83 @RefusedFlow we are having progress :)

Now when I put sudo gem install activesupport -v 4.2.6
then sudo gem install cocoapods

It says now (ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/fuzzy_match)

:\

**Comment by adrianmihai83** [comment]
So activesupport installed ok? And when you try to install cocoapods you get that error...

I think that it has to go in /usr/local/bin not /usr/bin

sudo gem install cocoapods -n /usr/local/bin

**Comment by moh0sw** [comment]
@adrianmihai83 you are the best 👍 💯 

Now it says Setting up CocoaPods master repo
How much I should wait to finish setting up?

**Comment by adrianmihai83** [comment]
well, wait some time, 5 minutes or something

depends on the computing power

**Comment by moh0sw** [comment]
@adrianmihai83 @RefusedFlow it works perfect and have installed on my Apple TV :)

Thank you guys 👍 

Is there a way to add Arabic subtitle to the movie?

Thanks Again 👍
