### ISSUE TITLE
Multiple subtitles support

### ISSUE THREAD

**Issue by ttuygun** [PopcornTimeTV/PopcornTimeTV#202]
It will be great if we embed multiple subtitles for language learners.
![](http://i.imgur.com/62w402R.png)

**Comment by RefusedFlow** [comment]
No plans to implement such feature, there's other parts of the app that are much more of a priority however you're more than welcome to implement it and submit it as a PR. 😄

**Comment by ttuygun** [comment]
I have already cloned the repo in my desktop and started to read code.😀

**Comment by tiferrei** [comment]
@ttuygun: Good way to start! If you need help just say! :)

**Comment by ttuygun** [comment]
Could you send me an invitation to Slack channel? I have already applied via herokuapp but I didn't get an invite. ttuygun@yahoo.com
