### ISSUE TITLE
No such module "PopcornKit"

### ISSUE THREAD

**Issue by colinwdunn** [PopcornTimeTV/PopcornTimeTV#203]
Unable to build due to this error. 

<img width="1512" alt="screen shot 2016-11-28 at 12 33 11 am" src="https://cloud.githubusercontent.com/assets/1424361/20661180/42cd0870-b502-11e6-8d2f-630549a0560d.png">

**Comment by tvOSPopcorn** [comment]
@colinwdunn Are you cloning the current version on the master branch?

**Comment by colinwdunn** [comment]
Ah, I needed to open the workspace not the project file.
