### ISSUE TITLE
PCT 0.2.0-6 IPA

### ISSUE THREAD

**Issue by wahlmanj** [PopcornTimeTV/PopcornTimeTV#204]
Any chance someone could upload a 0.2.0-6 ipa for testing purposes? Looks great on the simulator great work guys 👍 :)

**Comment by tomsbrinkis** [comment]
Yea, it would be awesome. BTW here is the "How To Xcode to .ipa" - http://www.fitzweekly.com/2016/11/how-to-export-xcode-project-to-ipa-file.html 
Maybe @wahlmanj you can try to build ipa and share a download link? ;)

**Comment by iAYMANi** [comment]
@tomsbrinkis Do not work on the free account Only paid 👆🏽

**Comment by tomsbrinkis** [comment]
@iAYMANi darn! Then lets wait until someone will make it .ipa.  👍

**Comment by davipt** [comment]
Guys, just follow the documentation, build it yourself and directly run on the Apple TV, as documented. 

It just works. 

My point is NEVER EVER install a third party built IPA file from anyone else. Ever.

**Comment by tvOSPopcorn** [comment]
This is an open source project, we won't ever be compiling a IPA for several security reasons. You're more than welcome to compile the application with your paid developers account.
