### ISSUE TITLE
PCT 0.2.0-6 IPA

### ISSUE THREAD

**Issue by wahlmanj** [PopcornTimeTV/PopcornTimeTV#205]
Sorry to open this again, I am looking for a ipa only. I do not have a paid developer account. Also my USB is disabled on my aTV4 (Also I'm sure many many others have this issue) since jailbreaking it so I cannot sideload it even if I had a developer account. I do not want or am looking for a ipa from the developers of this project. I am looking for anyone to upload the latest ipa to a file upload site only so I can install it on my jailbroken aTV4. Please if this issue can be left open and unlocked until someone uploads it I would appreciate it. I can resign it myself no problem with iResign. Thanks again for this project and for all the hard work and support.

**Comment by bigfrog** [comment]
same situation here , my usb-c is not detected .. but nobody want to share the .ipa don't understand why...

**Comment by wahlmanj** [comment]
I have searched youtube for it and found the 1.0.3 & 1.0.5 versions but not anything newer. Im sure it will be on there in due time but I would like to use it now obviously. Here is another place I find them but still no luck:

http://www.sinfuliphone.com/showthread.php?t=10086865&page=6

**Comment by moh0sw** [comment]
When i try to archive the project to make it an ipa i all ways get an error
(paid developer) when this problem will be solved?
the latest ipa we can make is 1.0.5 and its not even useable!
Any help?

**Comment by wahlmanj** [comment]
Someone with a paid dev account is needed to export it into a ipa, no way around that.

**Comment by FlaviaBondJamesBondsHusband** [comment]
This isn't a support forum, this is an issues/suggestions page. If you post this question again you will be blocked. We are not going to distribute iPA's. Please download them at your own risk. Its not our responsibility that you do not have a developer account. You want free movies and tv shows? Pay the minor inconvenience of reloading it every few weeks.
