### ISSUE TITLE
Slack invites

### ISSUE THREAD

**Issue by TheAbstractDev** [PopcornTimeTV/PopcornTimeTV#208]
Hello, I try to get an invite for joining the Slack Channel but I never received an email

**Comment by Breaking1** [comment]
I can confirm this issue, never received any invite to the Slack channel via the link on GitHub.

**Comment by RefusedFlow** [comment]
Will look into this and get back to you both @TheAbstractDev @Breaking1

**Comment by tiferrei** [comment]
@TheAbstractDev & @Breaking1: I just wanted to let you know that we have identified the issue and are now in contact with Slack to solve it.

**Comment by RefusedFlow** [comment]
@TheAbstractDev @Breaking1 Issue has been fixed! You're more than welcome to join the Slack group now via https://popcorntimetv.herokuapp.com
