### ISSUE TITLE
Build instructions / help

### ISSUE THREAD

**Issue by ej8** [PopcornTimeTV/PopcornTimeTV#208]
Thanks for providing this.  I'm only semi-technical.  I've gone through the guide you provided here - 
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

When I tried to download the project I get the following error in Terminal: 

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Does this have something to do with Xcode?  Which I don't have I guess.  I figured I'd start through the instructions so I didn't ask any dumb questions (like how to get Xcode) but I couldn't get through the first step.

Thanks so much!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Yes, xcrun is a command line tool and is downloaded once you open Xcode. To build this project, you need at least Xcode 8, which can be downloaded from the app store here: https://itunes.apple.com/app/xcode/id497799835. Make sure you open it once it downloads so it can configure everything!

**Comment by ej8** [comment]
Thanks so much. That helps greatly.
