### ISSUE TITLE
Subtitles menu not showing up.

### ISSUE THREAD

**Issue by gustavolessadublin** [PopcornTimeTV/PopcornTimeTV#209]
Hi,

I just updated my files using install.swift, and scrubbing started working! So, thank you for that!

Unfortunately, I cannot access the subtitles menu anymore.
When I swipe down, just the timeline appears, nothing else.

What can I do to solve this?

Thank you very much!
Gustavo

**Comment by FlaviaBondJamesBondsHusband** [comment]
#194
