### ISSUE TITLE
Movie detail view

### ISSUE THREAD

**Issue by pepibumur** [PopcornTimeTV/PopcornTimeTV#21]
## What?
Movie detail view where the movie information is presented. This view would allow amongst others:
- Select the subtitles
- Favorite the movie
- Save it for later

It's also possible to show related movies

**Comment by pepibumur** [comment]
@PopcornTimeTV/designers needs design!

**Comment by EskiMag** [comment]
Is already some "persistency" implemented in the app? I would like to avoid Core Data if possible. I don't know if it's even possible to use it on Apple TV. What about [Realm.io](www.realm.io)? Or will we just use `NSUserDefaults`?

**Comment by pepibumur** [comment]
NSUserDefaults I'd say is the best approach @EskiMag since the disk persistence is temporary and consequently Realm is removed randomly.

**Comment by EskiMag** [comment]
I see. Thanks for info. So maybe we'll do some `CloudKit` later. But I'll use `NSUserDefaults` for now.

**Comment by steve228uk** [comment]
@pepibumur @EskiMag You'll have some issue with `NSUserDefaults` as it's limited to 500kb. CloudKit or Realm are the best approaches.

**Comment by josefdlange** [comment]
@pepibumur what do you mean the disk persistence is temporary? As in, we only need the disk-cached data temporarily, or we're somehow limited by tvOS in what we can cache?

Just looked at Apple Documentation and indeed that is interesting. CloudKit seems silly -- why "cache" data in the cloud? Fetching from the internet is fetching from the internet -- we may as well have no cache at all. I think using Realm, saving to the cache directory, would work fine. Yeah, the OS may purge it, but if we're using it as a data cache, that's to be expected. Caches aren't meant to be trusted persistently.

**Comment by pepibumur** [comment]
@josefdlange I mean that if you save data in the disk that data could be removed at any point by the system. We could use `NSUserDefaults` for persisting user settings. Realm relies on that temporary directory and they tell you about that in the documentation

**Comment by RefusedFlow** [comment]
![Movie Detail View TVML](http://i.imgur.com/ZdkqWJJ.jpg)
