### ISSUE TITLE
Get an error when installing pod files

### ISSUE THREAD

**Issue by jrodny2012** [PopcornTimeTV/PopcornTimeTV#21]
The error i receive is 
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `AlamofireXMLRPC` from `https://github.com/PopcornTimeTV/AlamofireXMLRPC.git`
Pre-downloading: `PopcornKit` from `https://github.com/PopcornTimeTV/PopcornKit.git`, tag `1.1.0`
Pre-downloading: `TVMLKitchen` from `https://github.com/toshi0383/TVMLKitchen.git`, branch `swift2.2`
[!] Unable to find a specification for `TVVLCKit-unstable (= 3.0.0a10)`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

**Comment by popcornMaster** [comment]
Please try running pod install once again it should work now!

**Comment by jrodny2012** [comment]
nope still giving me the same error @popcornMaster

**Comment by guiwunsch** [comment]
same issue.
