### ISSUE TITLE
Install script stops downloading AlmofireXMLRPC

### ISSUE THREAD

**Issue by isaquebressy** [PopcornTimeTV/PopcornTimeTV#210]
I run `swift install.swift` and choose the stable version... but the script stops pre-downloading `AlmofireXMLRPC`.

```
Analyzing dependencies
Pre-downloading: `AlamofireXMLRPC` from `https://github.com/PopcornTimeTV/AlamofireXMLRPC.git`
Username for 'https://github.com':
```

How can I fix it and continue the install process?
The same is not happening on beta version.

**Comment by mattjis** [comment]
Same problem here :(

**Comment by FlaviaBondJamesBondsHusband** [comment]
The stable version does not work. Please use the latest version
