### ISSUE TITLE
No Shows/Movies

### ISSUE THREAD

**Issue by Baubascat** [PopcornTimeTV/PopcornTimeTV#216]
Nothing is getting loaded into app. All categories are blank. Just a black screen below all headers. The iPA I download was listed as 0.2.0-6 but the app settings are showing 0.2.0-5. The app was working for the past week.

**Comment by FlaviaBondJamesBondsHusband** [comment]
> PSA: We are NOT affiliated with AppDB or any other organization - free or otherwise - that provides resigned IPA files and it is not our responsibility if there are bugs in their versions of the app.

Please read the description before posting issues. If you download an iPA, we cannot, and will not help you with your issue

**Comment by Baubascat** [comment]
I understand why you wont help people who are not making there own build but I feel this isn't an issue with the build that I have but something else. The build was working fine for a week and just today it stopped pulling torrents. I have tried builds other than 0.2.0-6 and non of them pull torrents. Could you please check if you have a working build (one that's pulling torrents) so at least I know its not just me. Thank you.

**Comment by FlaviaBondJamesBondsHusband** [comment]
@Baubascat torrents are working on the latest version

**Comment by FlaviaBondJamesBondsHusband** [comment]
@Baubascat are you sure the problem is not your internet? If you are using an iPA that is marked as  0.2.0-6 and its  0.2.0-5 in settings, that is the latest version and theres no reason why it should not be working as all of our API's are responding. 

> I do appreciate your hard work and wondered if you take donations for it? If so, where would I send it?

We appreciate the kind gesture but this is a non-profit organisation. Just knowing you are enjoying it is payment enough!

**Comment by Baubascat** [comment]
Thanks for the reply it got me thinking. For some reason my VPN was blocking it? Everything on my AppleTV was working except for PopcornTime so I figured it must be the app but as soon as I turned off my VPN all the movies and shows loaded. I turned the VPN back on and everything is still working. Not sure why this happened but I'm glad PopcornTime is working again. Thanks again and I can't wait for the next release.

**Comment by Baubascat** [comment]
Sorry for posting here but I wasn't sure where to ask this. I'm currently on build 0.2.0-7 and was notified by the app about build 3.0.0. I currently sideload PopcornTime so the app tells me that I can not update from "in-app" but if I was jailbroken, would I be able to do an in-app update or is this something planed for the future? As always thanks for your time.
