### ISSUE TITLE
Check for Updates

### ISSUE THREAD

**Issue by Willbbz** [PopcornTimeTV/PopcornTimeTV#217]
Hi, does the UpdateManager for 'Check for Updates' work?

I was checking through the code but can't seem to see where exactly it looks for an update.  I only seem to see the alert in SettingsTableViewController.swift that is displayed after the user selects the Check For Updates button

**Comment by FlaviaBondJamesBondsHusband** [comment]
UpdateManager is handled by PopcornKit. https://github.com/PopcornTimeTV/PopcornKit/blob/master/PopcornKit/Managers/UpdateManager.swift

And yes it does work
