### ISSUE TITLE
time line

### ISSUE THREAD

**Issue by puba** [PopcornTimeTV/PopcornTimeTV#218]
Nice commit @aggelos81,  problems arise when try to forward or rewind media, got only sound and frozen picture when try to start playing it, probably that is connected with torrent flow. 10s delays icons are visible on time line, but has no functionality, or am I missing something?

**Comment by aggelos81** [comment]
You are probably missing something. I have tested the functionality and it is working without a problem. The issues with sound and frozen picture are due to poor Internet speeds! Nothing I can do!

**Comment by puba** [comment]
Can confirm that certain media works fine, rewind and forwarding are nice addons, a real bless, while certain media not, but thats not your fault. Faster internet speed wouldn't harm, agree. Thanks, have a nice day.

**Comment by aggelos81** [comment]
Closing issue as resolved
