### ISSUE TITLE
Organized Watchlist

### ISSUE THREAD

**Issue by Baubascat** [PopcornTimeTV/PopcornTimeTV#218]
It would be nice to be able to organize the watchlist. The interface AppleTV uses would be perfect. Select the show or movie to be moved. Hold the touchpad to activate and then move the show or movie to new location. Even a choice to  alphabetize would be nice.

**Comment by b1narygh0st** [comment]
Hello there @Baubascat, 

thank you for your feedback, we agree and so added it to our features wishlist, you can find it [here](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress).

B1naryGh0st

**Comment by CavalcanteLeo** [comment]
Dunoo if it happens to everyone, or only to me, but when I add an item to watchlist, the item won't be there until I close the app, it salves, but will only display at the next time I open the app

**Comment by tvOSPopcorn** [comment]
@CavalcanteLeo This was something we we're planning on implementing a while back, I'm unsure if it was implemented of not? @FlaviaBondJamesBondsHusband

**Comment by FlaviaBondJamesBondsHusband** [comment]
@tvOSPopcorn @CavalcanteLeo have created a new issue #337

**Comment by FlaviaBondJamesBondsHusband** [comment]
Watchlist now sorted alphabetically
