### ISSUE TITLE
Movies don't load on iOS (Stuck at Processing torrent)

### ISSUE THREAD

**Issue by rmjseeds** [PopcornTimeTV/PopcornTimeTV#219]
I installed PopcornTime in Apple TV 4 and it works fine. I installed PopcornTime in my iPad mini and it works fine. 

(then)

I installed PopcornTime in my iPhone 5s, my brothers iPad mini and brothers iPhone 5s and app installs properly but movies don't open. Its stuck at _**'Processing Torrent**_.

Some of these devices have more than 1 GB free space on them. I running all these devices on the same internet. Is there a minimum space needed to play movies on an iOS device?

See the screenshot on my iPhone running  iOS 10.1.1

P.s - I am in the US

![popcorn](https://cloud.githubusercontent.com/assets/24363797/20952360/df39882a-bbf9-11e6-83d8-1e0593e0507b.png)

**Comment by rmjseeds** [comment]
Note: I am running version 0.2.0-6 on my devices.

**Comment by b1narygh0st** [comment]
Hello @rmjseeds, thanks for reporting this issue, are you using a VPN?

**Comment by rmjseeds** [comment]
No, I am not on VPN.

**Comment by FlaviaBondJamesBondsHusband** [comment]
@rmjseeds are you just having this issue with Suicide Squad? Could you try with Deadpool?

**Comment by FlaviaBondJamesBondsHusband** [comment]
@rmjseeds yes, popcorn time requires at least a GB of free space if you want to stream movies. You can turn on "Clear Cache Upon Exit" and it will delete the movie when you exit the player so as to not take up too much space

**Comment by rmjseeds** [comment]
sorry, that is not a problem.. I have more than 1 GB of free space. I was asking if PopcornTime needs like 4-5 GB of free space.

**Comment by b1narygh0st** [comment]
I can confirm this issue @FlaviaBondJamesBondsHusband, thanks for reporting it @rmjseeds, we'll look into it.

**Comment by b1narygh0st** [comment]
@rmjseeds can you please try to stream the movie "Sully" on 720p quality?

**Comment by mclssk** [comment]
Hi! me too in a version 0.2.0-6.
But in new version 0.2.0-7 the torrent loads correct! 
Now, I can't load subtitle... 

Thanks!

**Comment by rmjseeds** [comment]
Thanks guys for the message.

Now the app does not even open in all my iPhones and iPad mini's. Even the iPad mini that was working and streaming properly is now not even opening the app? When I click the app, it just closes down.

I used a free apple developer account to create this app. I read somewhere that you have reinstall this app every 7 days? Is there a alternative to doing this?

Thanks!

**Comment by b1narygh0st** [comment]
Hello @rmjseeds, as a free developer Apple only gives you certificates that are valid for 7 days, to prevent this particular kind of things. The workarounds to this are:

* To reinstall every 7 days
* To buy a developer membership to extend the expiry period
* To get a code signing service to do it for you (cheaper than dev membership)

**Comment by rmjseeds** [comment]
Thanks, I didn't know that. Could you please suggest a code signing service ? I could not locate one through google search.

**Comment by b1narygh0st** [comment]
I must say that I do not personally advise any of them, nor advertise any of them, however popular options (under no particular order) are:
* iPAStore
* AppAddict.org

I do not particularly recommend any of them, as they tend to be quite dodgy services.

**Comment by marp04** [comment]
same issue here

**Comment by s-dm** [comment]
Same issue here on tvOS, however it starts sometimes if I leave it for 5-10 min.. checked my internet connection, changed router disabled vpn/dns services and so on. So there is a bug in this release!

**Comment by FlaviaBondJamesBondsHusband** [comment]
@s-dm 

> Note: I am running version 0.2.0-6 on my devices.

If you bothered reading the question you would know that the person who posted the issue is running 0.2.0-6. There is nothing wrong with 0.2.0-7, the problem is to do with your internet

**Comment by FlaviaBondJamesBondsHusband** [comment]
This issue isn't reproducible enough to be considered a bug. Working fine for every single device I've tested it on. Odds are it's internet connection/impatience. If you leave it for long enough it will load; nothing we can do about this unfortunately.
