### ISSUE TITLE
1.0.1 error SettingsViewController.swift when compiling

### ISSUE THREAD

**Issue by maitremiju** [PopcornTimeTV/PopcornTimeTV#22]
Hello,

I fetched 1.0.1 version through install.swift and when I try to compile it in Xcode I received this error :

SettingsViewController.swift
Cannot invoke initializer for type 'UIAlertAction' with an argument list of type '(title: String?, style: _, encoding: String?, handler: (_) -> _)'

I tried with 1.0 through install.swift and everything went fine.

Somebody else have the same issue?

**Comment by popcornMaster** [comment]
Sorry about that all should be good now!
