### ISSUE TITLE
I want to explain, to download popcorn time on Apple TV

### ISSUE THREAD

**Issue by ADMNTK** [PopcornTimeTV/PopcornTimeTV#221]
Hi

My brothers, please explain a way to export popcorn time from your MacBook to the Apple TV, I followed the instructions but I face a lot of mistakes.

Please help I want to download the last version of popcorn time, 0.2.0-7.

Thank you!

**Comment by FlaviaBondJamesBondsHusband** [comment]
What mistakes exactly did you face? Without any further information we cannot help you.

**Comment by ADMNTK** [comment]
thank you .

After writing the command : gem install cocoapods

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory

**Comment by FlaviaBondJamesBondsHusband** [comment]
@ADMNTK  instead of running `gem install cocoapods` run `sudo gem install cocoapods` and type in your password

**Comment by ADMNTK** [comment]
I wrote this now, is I'm writing it : gem install cocoapods ?

**Comment by ADMNTK** [comment]
Please explain a detailed

**Comment by FlaviaBondJamesBondsHusband** [comment]
open terminal.app and run `sudo gem install cocoapods`

**Comment by ADMNTK** [comment]
NEXT ?
![Uploading git.png…]()

**Comment by FlaviaBondJamesBondsHusband** [comment]
@ADMNTK Clone the project and run `swift install.swift`. All info is in the build guide. https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

**Comment by ADMNTK** [comment]
problem xcode :(((((((

http://www.3rbz.com/uploads/3578fbd746991.png

**Comment by FlaviaBondJamesBondsHusband** [comment]
@ADMNTK You did not follow the build instructions. They explicitly say that the tvOS BID must be the same as the TopShelf BID + the .TopShelf extension.

**Comment by ADMNTK** [comment]
I've done everything, please explain to me the subject of the photo :(((((

**Comment by ADMNTK** [comment]
Please help me.

**Comment by ADMNTK** [comment]
help me please

**Comment by FlaviaBondJamesBondsHusband** [comment]
@ADMNTK Please **Read the build instructions**. I can clearly see from the screenshot you posted that you have not.

If your Bundle Identifier for PopcornTimetvOS is: `com.abdulrahman.popcorntime.tvos` your topShelf id must be `com.abdulrahman.popcorntime.tvos.TopShelf`

**Comment by ADMNTK** [comment]
gooooooooooooooooooooooooooood

I love you, man.

Do you have the next update works like steps? 

Thank youuuuuuuuu
