### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by mattjis** [PopcornTimeTV/PopcornTimeTV#222]
Is there an easier way to update than re-downloading the whole project & dependencies every time?
e.g check what version I currently have and download only the new things for the update?

**Comment by pbo1976** [comment]
Similar question here. But, after downloading latest 0.2.0-6, it keeps building 0.2.0-5.
What am I doing wrong?

**Comment by mattjis** [comment]
@pbo1976 0.2.0-6 shows as 0.2.0-5 I'm pretty sure. 
0.2.0-7 is available though so maybe give that a shot instead?

**Comment by FlaviaBondJamesBondsHusband** [comment]
@mattjis Unfortunately no. The app has to be recompiled every single time you update it; This is the same for every single executable program. In scripting languages like JS you could do this but for iOS and tvOS applications, a full re-compile is needed.

**Comment by mattjis** [comment]
@FlaviaBondJamesBondsHusband Sorry to bring this up again, but just to be clear. 

I'm fine with compiling/building the project to the Apple TV in Xcode - that was not what I was asking. I was wondering whether the 'swift install.swift' could check what we already have downloaded and only download new stuff for the new update. 

All the dependencies I already have downloaded and it has to go and redownload / overwrite them with exact replicas wasting my time and downloads :(
