### ISSUE TITLE
Terminal Error When Installing PopcornKit Pod

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#223]
When Trying To Install The Project With Latest Commit (78) by `pod install` or `swift install.swift` I get this error:

[!] Error installing PopcornKit
[!] /usr/bin/git clone https://github.com/PopcornTimeTV/PopcornKit.git /var/folders/dw/w6m8dq4d3cnf0_7vw864j_4c0000gn/T/d20161210-29968-1d88f25 --template= --single-branch --depth 1 --branch 3.1.5

Cloning into '/var/folders/dw/w6m8dq4d3cnf0_7vw864j_4c0000gn/T/d20161210-29968-1d88f25'...
warning: Could not find remote branch 3.1.5 to clone.
fatal: Remote branch 3.1.5 not found in upstream origin

Tried on 2 Macs and still getting the same error

Thanks!

**Comment by sqig** [comment]
I get the same message.
Thank you.

**Comment by derickito** [comment]
I also get this error. It seems that for some reason the Podfile is asking for version 3.1.5 of PopcornKit, but it's only up to version 3.1.4. If you change your Podfile it should get you past this error.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Should be fixed now
