### ISSUE TITLE
white screen since yesterday...

### ISSUE THREAD

**Issue by ynnad696** [PopcornTimeTV/PopcornTimeTV#227]
last night all of sudden my popcorn time app went white and it doesn't show any content in any of the 0.7.0 versions that i have.. not only happened in one of my apple tv4 but in two of then same situation , i still have a 0.6.6 version that still working fine.. any ideas why this is happening ?

**Comment by RefusedFlow** [comment]
Issue has been resolved, close app from multitasking and reopen.
