### ISSUE TITLE
Subtitle shift refinements

### ISSUE THREAD

**Issue by GerTeunis** [PopcornTimeTV/PopcornTimeTV#229]
Thanks for the excellent and quick implementation! Love it. 

Could you add a 0.5 second steps to the delays of subtitles. 

And it might be a fluke on my end but no movie shows any subtitles anymore although I tested multiple movies and langauages.

**Comment by FlaviaBondJamesBondsHusband** [comment]
@GerTeunis yeah Opensubtitles API is down atm. Is the -5 to 5 range ok? I think it'll be a bit long if we increment in .5's so how about we decrease the range to -3-3 incrementing in .5s?

**Comment by GerTeunis** [comment]
We can sure try! Think it will be okay for most cases. Too bad there isn't a UIPickerView available on tvOS. 

Don't want to hijack this ticket for all kinds of subtitle issues: would it be possible to give some feedback if subtitle download failed? Might lower support questions as you have a lot of non code related issues. Excellent work you keep your head cool and handle and close those

**Comment by FlaviaBondJamesBondsHusband** [comment]
@GerTeunis unfortunately VLCKit doesn't support non-integer delays. Because this is a rare server side issue with OpenSubtitles, adding an error dialogue would be too much work. If the issue persists, I shall look into it further
