### ISSUE TITLE
Cannot Invoke Initializer for type "UIAlertAction" when compiling code

### ISSUE THREAD

**Issue by JohnRPoole** [PopcornTimeTV/PopcornTimeTV#23]
Good Morning,

I receive the following error when compiling code for newest commit:

![screen shot 2016-08-21 at 9 14 27 am](https://cloud.githubusercontent.com/assets/20939256/17837384/f3bb1012-677f-11e6-98ec-3202d8d007f1.png)

**Comment by abufreeh** [comment]
yes, same here !

**Comment by popcornMaster** [comment]
Sorry about that all should be good now!

**Comment by abufreeh** [comment]
I still get same error after updating!? any idea?

**Comment by tvOSPopcorn** [comment]
@abufreeh Downloaded the latest version from the master branch [here](https://github.com/PopcornTimeTV/PopcornTimeTV/archive/master.zip)

**Comment by matiasloda** [comment]
not working

**Comment by matiasloda** [comment]
I`m still getting the same error at 1.0.1 when compiling

**Comment by matiasloda** [comment]
now I`m trying 1.0.2

**Comment by matiasloda** [comment]
<img width="275" alt="captura de pantalla 2016-08-22 a las 9 09 29 p m" src="https://cloud.githubusercontent.com/assets/18399607/17875995/109fbd26-68ad-11e6-92e7-369119fd2799.png">
the same error trying with 1.0.2

**Comment by maitremiju** [comment]
1.0.2 works here.
Did you try to start from scratch? Remove folder and fresh download.
