### ISSUE TITLE
Parallax Posters

### ISSUE THREAD

**Issue by RefusedFlow** [PopcornTimeTV/PopcornTimeTV#23]
https://lsrdb.com

**Comment by steve228uk** [comment]
@JakeRound Give me a shout if you need/want any changes making to the API.

**Comment by JakeRound** [comment]
@steve228uk Will do thanks! However we're a little low on developers so progress on PopcornTime for tvOS is very slow. Unfortunately i'm not a developer just a designer contributing towards the project and thought Parallax Posters would be awesome!

**Comment by smithington78** [comment]
This may require a change to the LSRDB API to allow a fallback URL to be passed through as we're using TVML and can't test for this. I'll see if I can get in touch with the author of the proj.

**Comment by smithington78** [comment]
The app on the master branch is now using LSRDB but the parallax support doesn't seem to be working in TVML. @PopcornTimeTV/developers, any ideas?

**Comment by joaomvfsantos** [comment]
Changing mediumCoverImage to parallaxPoster on CatalogRecipe.swift should fix this. Not sure it should be changed on other templates. Also, we would need another extension similar as the Movie+Parallax to support tv shows.

**Comment by RefusedFlow** [comment]
@joaomvfsantos We temporally disabled LSRDB on the project as it wasn't making requests from the API correctly, it's implemented but isn't quite working yet... Changing mediumCoverImage to parallaxPoster is correct but there's something funky going on in Movie+Parallax.swift that isn't making the right requests you're more than welcome to create a PR when if you're able to figure it out!
