### ISSUE TITLE
PopcornTorrent bitcode problems

### ISSUE THREAD

**Issue by garranhado** [PopcornTimeTV/PopcornTimeTV#230]
ld: bitcode bundle could not be generated because '/../PopcornTimeTV-0.2.0-7/Pods/PopcornTorrent/Build/tvOS/PopcornTorrent.framework/PopcornTorrent' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by b1narygh0st** [comment]
Hello @garranhado, 

Can you please check that bitcode is disabled on your PopcornTime build settings? To check this go to the project's build settings tab and search for `bitcode`. the tvOS target may not have this parameter, that is OK, but on the iOS target, make sure it is set to`No`. Tell me how that works out for you.

**Comment by garranhado** [comment]
tvOS version problem, target don't have bitcode parameter.
I'm getting archiving (build it's ok) error about "PopcornTorrent.framework" bitcode.

**Comment by b1narygh0st** [comment]
Ah archiving, that is a known problem, we didn't compile PopcornTorrent with archiving in mind, we will look into adding archiving support.

**Comment by garranhado** [comment]
Tks

**Comment by b1narygh0st** [comment]
@garranhado, [Beta 1.1.2](https://github.com/PopcornTimeTV/PopcornTorrent/releases/tag/1.1.2) of PopcornTorrent should fix Bitcode, it's still a beta but you can test it by downloading, compiling, exporting and manually dragging it to replace the Pod on the main repo's folder, we will however release it later tomorrow or even today.

**Comment by b1narygh0st** [comment]
@garranhado, we are having some issues with bitcode, we already compiled `PopcornTorrent` with bitcode, but it doesn't seem to change anything. What is weird is that tvOS does not even support _not_ using Bitcode, it's a system requirement for tvOS and watchOS, so Xcode does not even allow you to disable it. We will continue to look into it, just wanted to keep you posted.

@FlaviaBondJamesBondsHusband, this is a weird one.

**Comment by mitral** [comment]
This is why I wasn't able to archive thanks @b1narygh0st I was wondering why I couldn't export the project as an spa  but I'm still having issues if you can see the latest opened issue I posted

**Comment by FlaviaBondJamesBondsHusband** [comment]
Fixed in master
