### ISSUE TITLE
0.2.0-7 popcorntime ipa resigned for jailbroken aTV4's

### ISSUE THREAD

**Issue by misswhitetiger** [PopcornTimeTV/PopcornTimeTV#231]
https://www.sendspace.com/file/itd3mj

**Comment by tomsbrinkis** [comment]
@misswhitetiger Awesome, thanks!

**Comment by moh0sw** [comment]
@misswhitetigar how did you build it as ipa
I always try to archive it with my own paid developer account and when building i get error!
How did you did it?

**Comment by tomsbrinkis** [comment]
@moh0sw here's how-to (maybe it will help) http://www.fitzweekly.com/2016/11/how-to-export-xcode-project-to-ipa-file.html

**Comment by garranhado** [comment]
Can you send IPA for tvOS too?
I hope for an IPA for every release (in releases page) to avoid compiling problems.

Tks

**Comment by tomsbrinkis** [comment]
@garranhado this .ipa is for aTV.

**Comment by garranhado** [comment]
Hum... its for jailbroken aTV4's only?
Can resign but can't install on device (no jailbroken).

**Comment by b1narygh0st** [comment]
Advertising code singed binaries is not permitted in this repo, this is for your own anonymity and the team involved developing this repo.

**Comment by b1narygh0st** [comment]
We will however provide archiving and code signing tutorials with Impactor in the near future.
