### ISSUE TITLE
customs Remote does not work for v.0.2.0-7

### ISSUE THREAD

**Issue by iAYMANi** [PopcornTimeTV/PopcornTimeTV#232]
customs Remote does not work for v.0.2.0-7

**Comment by FlaviaBondJamesBondsHusband** [comment]
@iAYMANi What is a customs remote?

**Comment by iAYMANi** [comment]
![hand-holding-2-3-gen-remote-right-click](https://cloud.githubusercontent.com/assets/12406459/21123310/0738806c-c0e9-11e6-82af-630ecd460dda.jpg)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Considering that's an ATV 3 remote and this project requires at least an ATV 4, I'm really not that surprised

**Comment by iAYMANi** [comment]
customs Remote Still does not work for v.3.0.0
