### ISSUE TITLE
Genres tab carousel no longer shows covers

### ISSUE THREAD

**Issue by b1narygh0st** [PopcornTimeTV/PopcornTimeTV#233]
![Simulator Screen Shot 12 Dec 2016, 19.40.34](http://static.gitscout.com/62019afbc962ac4e8b49f6b5bec9c272435bb10150428281b3fcb1b703941339.png)

**Comment by b1narygh0st** [comment]
PS: This issue only seems to affect devices (not sims) in specific countries.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Removed from release `3.0.0`
