### ISSUE TITLE
How to build pct for tvOS with a free apple dev account

### ISSUE THREAD

**Issue by misswhitetiger** [PopcornTimeTV/PopcornTimeTV#234]
With a free apple developer account you can export the app:

After I type in this one liner into terminal and grab the latest release (0.2.0-7):

rm -rf ~/Desktop/PopcornTimeTV; cd ~/Desktop; git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git; cd ~/Desktop/PopcornTimeTV; swift install.swift

I open Xcode then I choose my free dev account (for signing) for both targets PopcornTimetvOS & Top shelf

I also change the bundle identifiers to the following in the general tab on both PopcornTimetvOS & Top shelf:

com.pctt.popcorntime.tvos
com.pctt.popcorntime.tvos.TopShelf

You can change "pctt" on both to whatever you want besides its original name. Once that is done I disable bitcode for the target popcorntimeiOS & the project Popcorntime in the build settings tabs.

After I set the PopcornTimetvOS to generic tvOS Device I then choose (under the product dropdown) clean then build then archive. Once its "xarchived" I right click the xarchive and choose show in finder. I then choose show package contents then navigate to Products then Applications and copy the PopcornTime.app to my desktop. Once there I create a folder called Payload (must be a uppercase P) and drop the Popcorntime app into the Payload folder. Now I right click the payload folder and compress it which leaves you with a Payload.zip. I rename Payload.zip to PopcornTime.ipa and select to use the .ipa instead of .zip. I then use Iresign from here to resign it then upload it to my jailbroken Apple TV using the following instructions for iResign:

https://github.com/lechium/iReSign/releases
http://www.sinfuliphone.com/showthread.php?t=10085710

I also change the TopShelf Deployment target to 9.0 for my jailbroken tvOS firmware which is strange that it is set to 10.0 maybe this needs to be updated PCT dev's?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Although we appreciate the effort, this is not a forum. You can post this on reddit: https://www.reddit.com/r/PopCornTime/ but not here. This page is for issues/suggestions, nothing more, nothing less.

**Comment by b1narygh0st** [comment]
Also, thank you for your contribution @misswhitetiger, we will be sure to publish a wiki article covering everything with code signing, archiving and distributing IPAs in the near future.
