### ISSUE TITLE
Swiftc Failed With Exit Code 1 in tvOS 10.1

### ISSUE THREAD

**Issue by JohnGlazier** [PopcornTimeTV/PopcornTimeTV#235]
I'm getting the following error when attempting to compile the code in xCode 8.2 deploying to tvOS 10.1:

![screen shot 2016-12-13 at 4 32 56 pm](https://cloud.githubusercontent.com/assets/23418602/21160219/05910e78-c152-11e6-9d65-6bd8675215fa.png)

**Comment by b1narygh0st** [comment]
Hello @JohnGlazier, can you please provide us with the build log? To get it simply select the little speech balloon icon on the sidebar and on the latest build, make sure the tabs "All" and "All Messages" are selected, then click on the save button, this will create the log file, make sure it is zipped and attach it here. This will allow us to better help you with the issue.

**Comment by JohnGlazier** [comment]
Done

[Build PopcornTimetvOS_2016-12-13T18-03-49.rtf.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/650438/Build.PopcornTimetvOS_2016-12-13T18-03-49.rtf.zip)

**Comment by b1narygh0st** [comment]
OK so according to your build log the problem seems to be that:
```
error: Swift does not support the SDK 'AppleTVOS9.2.sdk'
```
Which basically means that the toolchain used in your Xcode version (8.2 in this case) does not support tvOS 9.2
Now this is weird because the version does indeed support it, what might be happening is that it is not installed in the toolchain, in english, check that the tvOS 9.2 Simulator is installed in the Xcode settings.

**Comment by JohnGlazier** [comment]
I installed the tvOS 9.2 simulator, restarted xCode, compiled, and still got the same error message.

FWIW, I was able to sign and deploy an .ipa file for 1.0.3.1, which worked fine.

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
    cd /Users/Home/Desktop/PopcornTimeTV/Pods
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS9.2.sdk
    export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name AEXML -Onone -D COCOAPODS -sdk /Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS9.2.sdk -target arm64-apple-tvos9.0 -g -module-cache-path /Users/Home/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -application-extension -embed-bitcode-marker -enable-testing -I /Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Products/Debug-appletvos/AEXML-tvOS10.0 -F /Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Products/Debug-appletvos/AEXML-tvOS10.0 -c -j4 /Users/Home/Desktop/PopcornTimeTV/Pods/AEXML/Sources/Document.swift /Users/Home/Desktop/PopcornTimeTV/Pods/AEXML/Sources/Element.swift /Users/Home/Desktop/PopcornTimeTV/Pods/AEXML/Sources/Error.swift /Users/Home/Desktop/PopcornTimeTV/Pods/AEXML/Sources/Options.swift /Users/Home/Desktop/PopcornTimeTV/Pods/AEXML/Sources/Parser.swift -output-file-map /Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/Objects-normal/arm64/AEXML-tvOS10.0-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/Objects-normal/arm64/AEXML.swiftmodule -Xcc -I/Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/AEXML-generated-files.hmap -Xcc -I/Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/AEXML-own-target-headers.hmap -Xcc -I/Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/AEXML-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/AEXML-project-headers.hmap -Xcc -I/Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Products/Debug-appletvos/AEXML-tvOS10.0/include -Xcc -I/Users/Home/Desktop/PopcornTimeTV/Pods/Headers/Private -Xcc -I/Users/Home/Desktop/PopcornTimeTV/Pods/Headers/Public -Xcc -I/Users/Home/Desktop/PopcornTimeTV/Pods/Headers/Public/PopcornTorrent -Xcc -I/Users/Home/Desktop/PopcornTimeTV/Pods/Headers/Public/TVVLCKit-unstable -Xcc -I/Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/DerivedSources/arm64 -Xcc -I/Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/Objects-normal/arm64/AEXML-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/Home/Library/Developer/Xcode/DerivedData/PopcornTime-aaqcpzusgykirjcabdyslqmbpldn/Build/Intermediates/Pods.build/Debug-appletvos/AEXML-tvOS10.0.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/Home/Desktop/PopcornTimeTV/Pods

<unknown>:0: error: Swift does not support the SDK 'AppleTVOS9.2.sdk'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by b1narygh0st** [comment]
Oh so you're trying to _archive_ it, not just compile it.
If that's the case then could you please try installing it to the simulator first?

**Comment by JohnGlazier** [comment]
Got it.  I was running xCode 7.3 and 8.2 concurrently (don't ask).  Went into /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/ and deleted the folder for the tvOS 9.2 SDK.  The project compiled perfectly.

Thanks a lot for your help and your patience.

Have a good evening.

**Comment by b1narygh0st** [comment]
Hum very interesting indeed. Glad I could help, thanks for your contribution to the project!

b1narygh0st
