### ISSUE TITLE
No torrents for TV Shows ?

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#24]
Hi, 
Today I noticed that when selecting TV Shows, I can not go further than ' Processing Episode xx ' . I do not get the number of Peers/seeds and the progress bar does not fill up. Movies still work as before. The issue with the TV Shows is also with shows I have played recently. I guess there is a general setting changed. 

It has not yet been possible for me to take the new release of today yet. I would not mind upgrading, but I hope to be able to continue using my installed version, without mandatory upgrade when there is a new version released. Of course I will try to get the new release installed, but could you check what is changed for TVshows?

Edit: Installed 1.0.1 build 8. Cleared cache etc. Issue remains. I believe it must be a server setting. http://status.popcorntime.sh  Shows all green on status settings for API for shows... Please help?

Strange, one series ' House of cards ' does work as the only one till now. Will try the desktop version later. All other series do currently stay at 0% in the progress bar ' processing xx ' .

**Comment by popcornMaster** [comment]
We have identified the issue, some of the torrents from our api have changed their url format for torrents, we are working on a fix

**Comment by Evhelden** [comment]
Great! I believe the sources of the torrents for desktop and AppleTV version might not be the same? That could be an idea? Anyway.. Thanks for all the work again! Extremely appreciating.

**Comment by popcornMaster** [comment]
Everything is ready! Fixes are up, closing issue as resolved

**Comment by Evhelden** [comment]
Great job!

**Comment by Evhelden** [comment]
Did some random tests. 1 out of 5 series worked.  
Success: Game of Thrones, last episode
Fail: Death in Paradise episode 7, season 5
Fail: Last week tonight John Oliver episode 80 and 81 (last 2)
Fail: Suits, season 6, episode 6
Fail: Waling Death, season 6 episode 16

Progress bar waiting at 0%, same issue still for most shows.

**Comment by hessius** [comment]
+1
