### ISSUE TITLE
Update podfile  tvos

### ISSUE THREAD

**Issue by caramelo2016** [PopcornTimeTV/PopcornTimeTV#240]
Update podfile thank you tvos

**Comment by b1narygh0st** [comment]
This issue is completely useless, how are we supposed to understand what "update podfile" means?

**Comment by b1narygh0st** [comment]
Hola, yo hablo un poco de espanol, tal vez te puedo ayudar.
Cuál es el problema?

**Comment by caramelo2016** [comment]
podfile se actualizarán esa es mi pregunta amigo

**Comment by caramelo2016** [comment]
con la version 0.2.0-7

**Comment by caramelo2016** [comment]
y no cargan bien las categorias  del projecto  no cargar las series y las peliculas y generes todas las funciones  no cargan se queda congelado y la verison de mac os x funciona bien pero la version tvos apple tv 4 no esta todavia estable con la version 0.2.0-7

**Comment by caramelo2016** [comment]
soy de ecuador es un gusto conocerlo amigo

**Comment by b1narygh0st** [comment]
Gracias, lo vo a verificar

**Comment by caramelo2016** [comment]
ok gracias amigo
