### ISSUE TITLE
problem xcode terminal l sudo

### ISSUE THREAD

**Issue by caramelo2016** [PopcornTimeTV/PopcornTimeTV#241]
<img width="1440" alt="captura de pantalla 2016-12-15 a las 15 41 23" src="https://cloud.githubusercontent.com/assets/23708238/21241367/44336ebe-c2dd-11e6-8e25-3c18c742b94a.png">

xcode 8.2  problem 
sudo  problem
thank you  friend
version 10.1 tvos  terminal installer error
license

**Comment by b1narygh0st** [comment]
Tienes que abrir Xcode primero y clicar aceptar.

**Comment by caramelo2016** [comment]
<img width="1440" alt="captura de pantalla 2016-12-15 a las 18 19 43" src="https://cloud.githubusercontent.com/assets/23708238/21245862/19009b2a-c2f3-11e6-99e5-90ea67f39bb3.png">
 
ya abri lo instale devo hacer algo mas amigo  hay le envio la imagen

**Comment by b1narygh0st** [comment]
Bien, ejecuta esto: `sudo xcode-select --install`

**Comment by caramelo2016** [comment]
<img width="1440" alt="captura de pantalla 2016-12-15 a las 19 17 42" src="https://cloud.githubusercontent.com/assets/23708238/21247131/355ace3c-c2fb-11e6-8158-918b9a104fc9.png">

ahora me sale otro problema a instalar los pods una  avertencia que problema es de la imagen nose abre el xcode



["-c", "open PopcornTime.xcworkspace"]
The file /Users/alessandrodelfini/Popcorn22/PopcornTime.xcworkspace does not exist.
Thanks for installing PopcornTime. When a new update is released re-run this script and select the new version.
alessandros-MacBook-Pro:Popcorn22 alessandrodelfini$

**Comment by caramelo2016** [comment]
<img width="1440" alt="captura de pantalla 2016-12-15 a las 19 21 00" src="https://cloud.githubusercontent.com/assets/23708238/21247206/bd350200-c2fb-11e6-94a3-44673fa16af6.png">


nose termani de instalar todo nose abre en xcode 8.2  da errores y proeblemas

**Comment by b1narygh0st** [comment]
Tienes que reinstalar Ruby, se hay danificado. Necesitas ayuda reinstalandolo?

**Comment by caramelo2016** [comment]
si  porfabor amigo

**Comment by caramelo2016** [comment]
como ago eso
como lo instalo

**Comment by b1narygh0st** [comment]
Muy bien, tienes `rvm` instalado?

**Comment by caramelo2016** [comment]
que pagina

**Comment by caramelo2016** [comment]
si tengo instado me lo instalo mi  ternico

**Comment by caramelo2016** [comment]
pero ahora esta fallando antes funcionaba perfecto

**Comment by caramelo2016** [comment]
el me instalo todo

**Comment by caramelo2016** [comment]
tengo que instalar ruby

**Comment by caramelo2016** [comment]
yo no soy muy bueno ayudeme

**Comment by b1narygh0st** [comment]
Sin problema, te voy a ayudar, ejecuta esto: `gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && \curl -sSL https://get.rvm.io | bash -s stable --ruby`

**Comment by caramelo2016** [comment]
como ejecuto estan unidos lo pege pero nose instala

**Comment by caramelo2016** [comment]
como son los pasos porque copie y lo pege al terminal y nose instala amigo

**Comment by b1narygh0st** [comment]
Como asi no se instala?

**Comment by caramelo2016** [comment]
dime los pasos por 1

**Comment by caramelo2016** [comment]
poco a poco pero no que esten mesclados

**Comment by b1narygh0st** [comment]
Ejectuta esto: `gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3`
Y despues: `\curl -sSL https://get.rvm.io | bash -s stable --ruby`

**Comment by caramelo2016** [comment]
<img width="1440" alt="captura de pantalla 2016-12-15 a las 19 38 31" src="https://cloud.githubusercontent.com/assets/23708238/21247547/1c82ce7a-c2fe-11e6-95a0-1e67763fbc0f.png">

**Comment by caramelo2016** [comment]
y despues que ago

**Comment by caramelo2016** [comment]
salio un error not found

**Comment by caramelo2016** [comment]
mac os x tengo

**Comment by b1narygh0st** [comment]
Ai madre, muy bien, lo pienso que reinstalar Xcode es lo mejor a hacer.

**Comment by caramelo2016** [comment]
como ago amigo ya hice todo lo que me dijo

**Comment by caramelo2016** [comment]
ya instale el ruby pero sale esto

: Requirements installation failed with status: 1.
/Users/alessandrodelfini/.rvm/bin/rvm: line 66: shell_session_update: command not found
bash: line 850: shell_session_update: command not found
alessandros-MacBook-Pro:~ alessandrodelfini$

**Comment by b1narygh0st** [comment]
Tienes que retirar Xcode y hacer el download de nuevo.

**Comment by caramelo2016** [comment]
ok pero borre todo del xcode y lo volvi a instalar

**Comment by caramelo2016** [comment]
aver si se resuelve

**Comment by caramelo2016** [comment]
retirar es como descargar de nuevo

**Comment by b1narygh0st** [comment]
Si muy bien, ahora tienes que lo instalar.

**Comment by caramelo2016** [comment]
porque acuelice mi mac os x la version  sierra  ala version  10.12.2 y me dejo de funcionar

**Comment by b1narygh0st** [comment]
No pienso que la nueva version altere nada en ruby.

**Comment by caramelo2016** [comment]
pero igula sale errores

**Comment by caramelo2016** [comment]
se instala pero esta en cero la carpeta

**Comment by caramelo2016** [comment]
bacia

**Comment by b1narygh0st** [comment]
Cual carpeta?

**Comment by caramelo2016** [comment]
yo nose mucho de computadora e borrado el xcode pero sigue dando el mismo problema que nose puedo instalar el ruby

**Comment by caramelo2016** [comment]
instale de nuevo xcode

**Comment by caramelo2016** [comment]
que mas puedo hacer amigo cual es la solucion para esto

**Comment by caramelo2016** [comment]
nunca me a pasado esto

**Comment by b1narygh0st** [comment]
Ahora intenta instalar cocoapods.
