### ISSUE TITLE
KickAss Torrent Search

### ISSUE THREAD

**Issue by moh0sw1** [PopcornTimeTV/PopcornTimeTV#243]
Hi Will After The KickAss Torrents Is Back Again i Think It's The Time To Bring The Old Feature To The Project (KickAss Torrent Search)
The New Website : katcr.co

**Comment by b1narygh0st** [comment]
Hello @moh0sw1 although the website itself is up, the API still seems down, we have to wait until its functionality is fully restored.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Removing milestone until KAT API is back online

**Comment by mattjis** [comment]
The real kick ass torrents is gone for good. These websites are all fake "clones" taken by users...

**Comment by moh0sw1** [comment]
On Sun, Jan 15, 2017 at 6:40 AM mattjis <notifications@github.com> wrote:

> The real kick ass torrents is gone for good. These websites are all fake
> "clones" taken by users...
>
>
> @mattjis no it's real and the old operators run it again

If you can see the "clones" as you see are all with a old data base and you
> can't upload any torrents

This one is all the online blogs talked about it and the database is old

**Comment by FlaviaBondJamesBondsHusband** [comment]
KAT API doesn't seem to be returning any time soon. Will re-open when it comes back online
