### ISSUE TITLE
Subtitle manual search

### ISSUE THREAD

**Issue by marp04** [PopcornTimeTV/PopcornTimeTV#246]
Could you add a manual search for subtitle, to choose a special one. 
Usually all the subtitle automatically downloaded, are out of sync.

**Comment by FlaviaBondJamesBondsHusband** [comment]
You can use the delay option inside the player to adjust the subtitle if it is out of sync. #107

**Comment by marp04** [comment]
i can't see the option

**Comment by marp04** [comment]
Btw, the manual search is a need because sometimes the subtitle downloaded is bad translated.
Sorry for my english.
