### ISSUE TITLE
problem terminal does not exist PocornTime.xcworkspace xcode 8.2 project tvos

### ISSUE THREAD

**Issue by caramelo2016** [PopcornTimeTV/PopcornTimeTV#247]
<img width="1440" alt="captura de pantalla 2016-12-18 a las 02 11 03" src="https://cloud.githubusercontent.com/assets/23708238/21292131/a8148f08-c4c7-11e6-8455-e1c71a4cb763.png">

problem help solution

does not exist  xcode 8.2   error terminal

**Comment by FlaviaBondJamesBondsHusband** [comment]
Do not open a new issue with the exact same problem when your existing issue has not been closed #241.
