### ISSUE TITLE
update Project for the new version?

### ISSUE THREAD

**Issue by ADMNTK** [PopcornTimeTV/PopcornTimeTV#248]
Hi

Can I update the project in case a new version instead of the installation of the new?

Thank you!

**Comment by FlaviaBondJamesBondsHusband** [comment]
@ADMNTK I'm afraid I don't quite understand, could you please re-phrase?

**Comment by ADMNTK** [comment]
Hi .

In the case of the issuance of new update for the application popcorn time, you must re-download the project, install it again?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Re-run the install.swift script

**Comment by ADMNTK** [comment]
I'll apply the method to experience.

**Comment by mattjis** [comment]
@FlaviaBondJamesBondsHusband I think he's asking the same as I was not too long ago: https://github.com/PopcornTimeTV/PopcornTimeTV/issues/222

Basically he doesn't want to have to re-download files he has previously downloaded.
