### ISSUE TITLE
error xcode 8.2 TopShelf Build PopcornTimetvOS  failed 

### ISSUE THREAD

**Issue by caramelo2016** [PopcornTimeTV/PopcornTimeTV#249]
<img width="1440" alt="captura de pantalla 2016-12-18 a las 20 27 35" src="https://cloud.githubusercontent.com/assets/23708238/21298541/7c527b84-c560-11e6-96fc-0939a46d509f.png">

TopShelf Build PopcornTimetvOS  failed error install project xcode 8.2                                           version 10.1 tvos

**Comment by FlaviaBondJamesBondsHusband** [comment]
Navigate to the TopShelf Target in the drop down menu and change the team to your personal team like you have done with the PopcornTimetvOS target
