### ISSUE TITLE
pod install: Error installing PopcornKit

### ISSUE THREAD

**Issue by ryanmaule** [PopcornTimeTV/PopcornTimeTV#25]
[!] Error installing PopcornKit
[!] /usr/bin/git clone git@github.com:PopcornTimeTV/PopcornKit.git /var/folders/yd/zj6f7d8j42xfb8vhtxtd40540000gp/T/d20160324-48387-1ryo4yn

Cloning into '/var/folders/yd/zj6f7d8j42xfb8vhtxtd40540000gp/T/d20160324-48387-1ryo4yn'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by smithington78** [comment]
Hi @ryanmaule!

Thanks for reporting this. It is a known issue at the moment caused by an issue with a pod spec on another repo. We're looking into a fix.

In the meantime could you try `pod update --verbose`

**Comment by ryanmaule** [comment]
I was able to solve this by generating a new set of SSH keys and adding them to Github.
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

Odd that the keys didn't limit any other activities.

**Comment by smithington78** [comment]
Ah as they're public repos now we should switch to cloning via https to avoid this.

**Comment by buzzel** [comment]
There shouldnt be any SSH issues or compile issues now.
