### ISSUE TITLE
Audio delay when using Airplay speakers

### ISSUE THREAD

**Issue by colinwdunn** [PopcornTimeTV/PopcornTimeTV#250]
I can't use PopcornTimeTV because there is a 2 second audio delay when airplaying to my speakers :(

**Comment by FlaviaBondJamesBondsHusband** [comment]
Could you provide a bit more information; Version, Platform, Movie etc?

**Comment by colinwdunn** [comment]
Running PopcornTimeTV 0.2 on my Apple TV 4. Applies to all movies and shows.

**Comment by FlaviaBondJamesBondsHusband** [comment]
You can now manually change the audio delay in the latest version
