### ISSUE TITLE
Clicking the touchpad does not pause

### ISSUE THREAD

**Issue by mattjis** [PopcornTimeTV/PopcornTimeTV#252]
It pauses for a second and then resumes by itself

My theory is: It thinks I moved the playhead and is loading the "new" position instead of pausing like I actually wanted.

Version: 0.2.0-7

**Comment by FlaviaBondJamesBondsHusband** [comment]
Already fixed in master

**Comment by mattjis** [comment]
@FlaviaBondJamesBondsHusband nice! Is there any way for us to test the "master" or do we have to wait for a new beta release?

**Comment by FlaviaBondJamesBondsHusband** [comment]
@mattjis Yeah, just clone the repo and manually build (run `pod install`) instead of selecting a release
