### ISSUE TITLE
Daily Show, Conan, Jimmy Fallon crash PopCorn on Apple TV

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#256]
Hi, the above shows push PopcornTime 0.2.0-7 to the background, or make the app crash on Apple TV. Just my favorite daily doses of nonsense before bedtime. Something wrong with the API?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue has already been fixed in master

**Comment by Evhelden** [comment]
Pulled the new master and installed.
Crashing is fixed, but shows do not show. The page opens, sounds is playing, but no series and no episodes. Do you have time to fix theses shows, so I can play them?
