### ISSUE TITLE
Movies not working

### ISSUE THREAD

**Issue by s-dm** [PopcornTimeTV/PopcornTimeTV#258]
With the latest release movies do not start downloading and streaming, tv shows are ok.. any suggestions on how to fix it?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Could you please provide some more information: Platform? Movie?

**Comment by s-dm** [comment]
Apple TV 4, every movie I tried.. tv shows start, but takes some time before it starts. But on movies they don't start even after 10 min. Tried clearing cache, restarting Apple TV etc.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Must be your internet connection as every movie I have tried is working. Try disabling VPN if activated or restarting router.

**Comment by s-dm** [comment]
Now i have turned off vpn, restarted modem, updated and restarted my AirPort Extreme, but still no go on movies. Speedtest says 40mbits down and 20mbits up. So no speed issues. Worked fine before the latest updat that I downloaded and installed on Tuesday.
