### ISSUE TITLE
Improvements to the playback drop down menu

### ISSUE THREAD

**Issue by mattjis** [PopcornTimeTV/PopcornTimeTV#259]
This is the sort of "playback drop down menu" I am referring to: http://tidbits.com/resources/2015-10/Apple-TV-video-menu.png

**Bugs / user experience issues:**

- When entering the "subtitles" section (and changing a setting) you can no longer get back to the "info" section.

- This whole dropdown menu is also difficult to hide, requires a few "upward flicks" to get it to go away. In all other video apps just starting this "upward flick" makes it completely go away - quite hard to explain I hope this makes sense :)

**Improvements:**

- Audio section with speaker & sound options would be amazing! :) e.g http://tidbits.com/resources/2015-10/Apple-TV-video-menu.png

Platform: Apple TV
Version: master (0.2.0-7)

**Comment by FlaviaBondJamesBondsHusband** [comment]
@mattjis First off I want to thank you for the layout of this feature request! Much easier to read compared to other ones. Also the inclusion of screenshots is very helpful!

Looking into adding these features now as soon as we get AirPlay support re-worked as it has changed a lot in tvOS and iOS 10

**Comment by FlaviaBondJamesBondsHusband** [comment]
@mattjis Can you try out the latest commit to master?

**Comment by mattjis** [comment]
@FlaviaBondJamesBondsHusband I'm trying but every time I "flick down" to check it out the app quits. I've tried 4 times now and it won't seem to open for me :(

**Comment by FlaviaBondJamesBondsHusband** [comment]
Fixed in latest release

**Comment by mattjis** [comment]
@FlaviaBondJamesBondsHusband hmm it's still causing it to crash for me. I'm on the latest master :(

**Comment by tvOSPopcorn** [comment]
@mattjis Are you using release 3.0? This issue was fixed, and I can see it working for myself try rebuilding the application using the 3.0 release.

**Comment by mattjis** [comment]
@tvOSPopcorn Yes I am, it worked after @FlaviaBondJamesBondsHusband claimed it was fixed but then I updated again and it's now broken again. Other people seem to be having problems as well: https://github.com/PopcornTimeTV/PopcornTimeTV/issues/279
