### ISSUE TITLE
Umbrella header for module 'PopcornKit' does not include header 'PopcornKit.h'

### ISSUE THREAD

**Issue by ryanmaule** [PopcornTimeTV/PopcornTimeTV#26]
Have these errors while building:

/PopcornTimeTV/<module-includes>:1:1: Umbrella header for module 'PopcornKit' does not include header 'PopcornKit.h'

Under Report Navigator for Pods:
Warning: no rule to process file '/PopcornTimeTV/Pods/TVMLKitchen/Sources/Templates/AlertRecipe.xml' of type text.xml for architecture x86_64

Warning: no rule to process file '/PopcornTimeTV/Pods/TVMLKitchen/Sources/Templates/Base.xml' of type text.xml for architecture x86_64

Warning: no rule to process file '/PopcornTimeTV/Pods/TVMLKitchen/Sources/Templates/DescriptiveAlertRecipe.xml' of type text.xml for architecture x86_64

Warning: no rule to process file '/PopcornTimeTV/Pods/TVMLKitchen/Sources/kitchen.js' of type sourcecode.javascript for architecture x86_64

Warning: no rule to process file '/PopcornTimeTV/Pods/TVMLKitchen/Sources/Templates/KitchenTabBar.xml' of type text.xml for architecture x86_64

Warning: no rule to process file '/PopcornTimeTV/Pods/TVMLKitchen/Sources/Templates/SearchRecipe.xml' of type text.xml for architecture x86_64

Warning: no rule to process file '/PopcornTimeTV/Pods/TVMLKitchen/Sources/Templates/SearchResult.xml' of type text.xml for architecture x86_64

**Comment by ryanmaule** [comment]
Forgot a part:
CompileSwift normal x86_64 /PopcornTimeTV/PopcornTime/Extensions/String+Cleaned.swift

<module-includes>:1:1: warning: umbrella header for module 'PopcornKit' does not include header 'PopcornKit.h'
#import "Headers/PopcornKit-umbrella.h"
^

**Comment by buzzel** [comment]
This seems to be unreproducible. Can you double check and see if it still happens? If so, reopen this issue.

**Comment by diogoviannaaraujo** [comment]
im having this from a clean install from master branch using python to build 0.6.3
