### ISSUE TITLE
Fail when archiving

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#26]
ld: warning: directory not found for option '-L/Users/Erwin/Desktop/PopcornTimeTV/PopcornTime/Objective-C/TOSMBClient/libdsm'
ld: bitcode bundle could not be generated because '/Users/Erwin/Desktop/PopcornTimeTV/Pods/TVVLCKit-unstable/TVVLCKit-binary/TVVLCKit.framework/TVVLCKit(VLCEmbeddedDialogProvider.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by FlaviaBondJamesBondsHusband** [comment]
We do not compile TVVLCKit. Please [make a bug report with VLC](https://code.videolan.org/videolan/VLCKit/issues).
