### ISSUE TITLE
Remove looping theme song?

### ISSUE THREAD

**Issue by mattjis** [PopcornTimeTV/PopcornTimeTV#260]
The first thing I do when I update is quickly disable the theme song :(
I can hear the theme song when I begin watching the TV Show, why would I want to hear it constantly looping in the background (driving me crazy)?

It also concerns me that this is causing the tv show panel to load slower than usual as it also has to download the theme song. (Hopefully setting volume to 0% also disables it from downloading)

I'm sorry if this is a bit negative - constructive criticism. I just really want your app to be the best it possibly can and this is a major oversight in my opinion.

**Comment by FlaviaBondJamesBondsHusband** [comment]
> The first thing I do when I update is quickly disable the theme song :(  I can hear the theme song when I begin watching the TV Show, why would I want to hear it constantly looping in the background (driving me crazy)?


 If you don't like it, just turn it off, that's why there is an option. Your settings do not reset every time you update the app.

> It also concerns me that this is causing the tv show panel to load slower than usual as it also has to download the theme song. (Hopefully setting volume to 0% also disables it from downloading)

Downloading the **tiny** file is negligible compared to other things being downloaded. Also it is done after the view controller has loaded so it has no impact.
