### ISSUE TITLE
Fails to compile for TVOs10

### ISSUE THREAD

**Issue by mitral** [PopcornTimeTV/PopcornTimeTV#261]
Seems I'm having issues. I've followed the guide with even renaming the bundle  It says I haven't created a provisioning profile but I have.  http://imgur.com/a/BZFO3

Can someone help me out ?

**Comment by nnarayann** [comment]
Open the targets list http://imgur.com/a/ZaNG0 (red circle) and select a _Team_ for each target. Should build without issues after that.

**Comment by FlaviaBondJamesBondsHusband** [comment]
@mitral Please see the updated build instructions https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

**Comment by mitral** [comment]
@FlaviaBondJamesBondsHusband  and @nnarayann I just got this error "This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique."
I changed the bundle ids to be the same for Topsehlf and PopcornTimeTVOS.  

Any idea what I'm doing wrong?  I signed it as the personal team as myself too

**Comment by mitral** [comment]
http://imgur.com/a/NXVGK
@nnarayann and @FlaviaBondJamesBondsHusband  here is what i get ... sit;; errors

**Comment by FlaviaBondJamesBondsHusband** [comment]
@mitral Please screenshot all your Bundle ID's

**Comment by mitral** [comment]
@FlaviaBondJamesBondsHusband I actually managed to built it now. I followed the tutorial once more and made my bundle ids the same way. I think I mistyped one and thats why it wouldn't compile.  I have  one more question about PT. In the Step of the tutorial where it says "swift install.swift" and then it asks you to select a version) I assume this is the PT version list from the repository? I should I assume that the one on the very top is the latest built of PopcornTime?

**Comment by FlaviaBondJamesBondsHusband** [comment]
@mitral Yes it is and the version at the top is the latest.

**Comment by mitral** [comment]
@FlaviaBondJamesBondsHusband Sorry to reopen this issue for a minute but actually it built fine on the mac as a generic TV App but when I pointed it to my TV connected via USB  C to A it fails to built? why?

**Comment by mitral** [comment]
http://imgur.com/a/cgZS1

See these 2 photos? See how its running fine on the 1080p setting but it fails to built when I select the real device? what do I do?
