### ISSUE TITLE
Continuation (PopcornTime builds on GenericTVDevice but doesn't on the Apple TV 4 connected)

### ISSUE THREAD

**Issue by mitral** [PopcornTimeTV/PopcornTimeTV#262]
http://imgur.com/a/cgZS1

It builds via the steps I followed on the guide and  runs fine via the Xcode emulator but not on the Apple Tv while it's connected via USB. Any ideas why?

**Comment by mitral** [comment]
TopShelf has conflicting provisioning settings. TopShelf is automatically signed, but code signing identity Jay Mitra has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.
Code signing is required for product type 'TV App Extension' in SDK 'tvOS 10.0'

**Comment by mitral** [comment]
@FlaviaBondJamesBondsHusband    Sorry to bother you again  but as i posted above it seems to fail still with a code singing error http://imgur.com/a/Sow7I

Im really not sure what I'm doing wrong. I really do appreciate the help you've given thus far and just want to see PT run on the device rather than the simulator

**Comment by FlaviaBondJamesBondsHusband** [comment]
@mitral http://stackoverflow.com/questions/37806538/code-signing-is-required-for-product-type-application-in-sdk-ios-10-0-stic. Try this

**Comment by mitral** [comment]
@FlaviaBondJamesBondsHusband can confirm that fix you posted along with the normal guide works and it successfully built to the TV. Thanks!. I do have a question though. so everyone a new version comes out I have to re run that swift script? and also Do I have to deal with this code singing issue again while rebuilding a new version of PT when one is released? 

Thank you so much

**Comment by mitral** [comment]
Also one last  thing.  When I build a new version on the TV.  Do I need to go to settings and DELETe the old build or will  the new version replace the old build? Wish there was a uatoudpate feature for this

**Comment by FlaviaBondJamesBondsHusband** [comment]
@mitral
 

> I do have a question though. so everyone a new version comes out I have to re run that swift script?

 Yes that is correct, however, you will be notified on device about a new version.

> and also Do I have to deal with this code singing issue again while rebuilding a new version of PT when one is released?

It should not, but I shall leave this linked in the FAQ just in case

> Also one last thing. When I build a new version on the TV. Do I need to go to settings and DELETe the old build or will the new version replace the old build? 

As long as you use the exact same BID, it will be automatically replaced. 

> Wish there was a uatoudpate feature for this

We do too. Unfortunately without a store medium (App Store/Cydia) we not have sufficient access to install apps to the system automatically.

Glad I could be of help :)
