### ISSUE TITLE
Movie search seems to be broken for tvOS & iOS

### ISSUE THREAD

**Issue by derickito** [PopcornTimeTV/PopcornTimeTV#265]
When you search for anything longer than 2 characters you get 0 results.

**Comment by tvOSPopcorn** [comment]
About to reproduce, looks anything longer than 1 characters returns 0 results, however typing the entire movie title seems to display the movie

**Comment by b1narygh0st** [comment]
Unfortunately, there is nothing we can do about this, this is a bug in the PopcornTime API that prevents it from returning the correct search results. [An issue about this](https://github.com/popcorn-official/popcorn-api/issues/70) has ben opened and we will keep track of this issue.
