### ISSUE TITLE
Current subtitle (from options) selected but not working solution

### ISSUE THREAD

**Issue by garranhado** [PopcornTimeTV/PopcornTimeTV#266]
[PCTPlayerViewController.swift]
Move _self.currentSubtitle = media.currentSubtitle_ line from _play func_ to _viewDidLoad func_.

**Problem:**

(play)
_self.currentSubtitle = media.currentSubtitle_

**Solution:**

(viewDidLoad)
_self.currentSubtitle = media.currentSubtitle_

**Comment by FlaviaBondJamesBondsHusband** [comment]
Why would that have any effect on anything?
