### ISSUE TITLE
Updated TV OS and getting error on Xcode when recompiling

### ISSUE THREAD

**Issue by mitral** [PopcornTimeTV/PopcornTimeTV#267]
This Apple TV is running tvOS 10.1 (14U593), which may not be supported by this version of Xcode.
What do I do to recompile Popcorntime?

**Comment by mitral** [comment]
any ideas @FlaviaBondJamesBondsHusband  Also happy Holidays!

**Comment by tvOSPopcorn** [comment]
@mitral Which Xcode version are you using? Update to the latest version and try compile again.

**Comment by mitral** [comment]
@tvOSPopcorn I'm on Version 8.0 (8A218a)  Thats the latest I assume since there doesn't seem to be any updates . I'll check. Is that what you're on?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Xcode 8.2 is the latest version. Please update and try again
