### ISSUE TITLE
Compiler errors on 0.2.0-7

### ISSUE THREAD

**Issue by Sijan117** [PopcornTimeTV/PopcornTimeTV#269]
Not sure if I'm doing something wrong, I went through the guide and got through the install.swift script, setup the account signing and selected my iPad Pro 9.7" (running iOS 10.2) as a device, yet the build fails with the following errors: 

/Users/Sean/Code/PopcornTimeTV/PopcornTime/UI/iOS/Table View Controllers/StreamToDevicesTableViewController.swift:8:92: Use of undeclared type 'ConnectDevicesProtocol'
/Users/Sean/Code/PopcornTimeTV/PopcornTime/UI/iOS/Table View Controllers/StreamToDevicesTableViewController.swift:10:27: Use of unresolved identifier 'MPAVRouteProtocol'
/Users/Sean/Code/PopcornTimeTV/PopcornTime/UI/iOS/Table View Controllers/StreamToDevicesTableViewController.swift:23:39: Cannot assign value of type 'StreamToDevicesTableViewController' to type 'ConnectDevicesDelegate?'
/Users/Sean/Code/PopcornTimeTV/PopcornTime/UI/iOS/Table View Controllers/StreamToDevicesTableViewController.swift:26:38: Cannot assign value of type 'StreamToDevicesTableViewController' to type 'ConnectDevicesDelegate?'
/Users/Sean/Code/PopcornTimeTV/PopcornTime/UI/iOS/Table View Controllers/StreamToDevicesTableViewController.swift:39:49: Use of undeclared type 'MPAVRouteProtocol'
/Users/Sean/Code/PopcornTimeTV/PopcornTime/UI/iOS/Table View Controllers/StreamToDevicesTableViewController.swift:101:40: Value of type 'AirPlayManager' has no member 'airPlayItemImage'

Any ideas? Thanks

**Comment by FlaviaBondJamesBondsHusband** [comment]
@Sijan117  Did you open the `.xcworkspace` file?

**Comment by GIthHub2die4** [comment]
i have same error, and wen i follow guide to build, there is no .xcworspace file? Never had that issue before...

diff: /Users/brunomedeiros/Desktop/PopcornTimeTV/Pods/../Podfile.lock: No such file or directory
diff: /Users/brunomedeiros/Desktop/PopcornTimeTV/Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by vis0r** [comment]
Try installing it all manually.
1) Update pods `sudo gem update`
2) Update spec repo `pod repo update`
3) Install pods `pod install`

**Comment by GIthHub2die4** [comment]
thanks vis0r! manually added the .xcworkspace to my popcorn time folder!
