### ISSUE TITLE
Cannot Install Pods

### ISSUE THREAD

**Issue by samfranz** [PopcornTimeTV/PopcornTimeTV#27]
It works perfectly until it runs up to `Installing TVVLCKit-unstable (3.0.0a10)` and from there it just hangs to no end. Not sure if there is something I have to do on my end to have this work.

**Comment by brockpetrie** [comment]
Honestly, I think it might be because `TVVLCKit-unstable` is freaking massive (it's a 408M download). Try installing in verbose mode, that'll give you a progress indicator for the download (eta ~ 3 hours for me right now).

**Comment by samfranz** [comment]
Wait, so that means anyone who's using this has had to wait for a 2-3 hour terminal download? Did something change recently that made this the slowest thing to ever travel across the internet?

**Comment by brockpetrie** [comment]
I'm guessing this was just a temporary server hiccup. I just tried again and it worked great.

**Comment by samfranz** [comment]
Well this temporary issue seems to rear its head whenever I want to try to download it. Nothing like 6 minutes of downloading with only 11.8M out of 408M. I do have gigabit speed, so I'm not too sure why this happens on my end, but I guess I'll just have to let this run for ~4 hours.
