### ISSUE TITLE
Updated Xcode to 8.2 and still getting errors

### ISSUE THREAD

**Issue by mitral** [PopcornTimeTV/PopcornTimeTV#270]
@tvOSPopcorn followed you advice and updated  but now I cant seem to compule I got this error 
http://imgur.com/a/Hkdfi

Any ideas?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Those are not errors they're warnings. Project will still compile with them

**Comment by mitral** [comment]
It says build failed but perhaps I'll try to recompile it now. Thanks again @FlaviaBondJamesBondsHusband
