### ISSUE TITLE
there is no "PopcornTime.xcworkspace" file inside the popcorntimetv-3.0.0 folder

### ISSUE THREAD

**Issue by itsyaboy** [PopcornTimeTV/PopcornTimeTV#276]
there is no "PopcornTime.xcworkspace" file inside the popcorntimetv-3.0.0 folder and also i get this error       ( ERROR:  While executing gem ... (Errno::ENOTDIR)
                  Not a directory - /usr/local/bin/fuzzy_match)    When running "sudo gem install cocoapods" on mac OS X  sierra or does nothing at all when entering "swift install.swift"  when it gets to the part about having cocaopods installed and selecting "no"

**Comment by tvOSPopcorn** [comment]
@itsyaboy Not an issue related to the PopcornTimeTV rather an issue with installing cocoapods, apparently it's an issue with how your Mac security settings have been setup nevertheless.

Try running
`sudo gem install -n /usr/local/bin cocoapods`

**Comment by itsyaboy** [comment]
tried still no go sorry for posting here is there anywhere i can go for help ? thanks for the reply

**Comment by tvOSPopcorn** [comment]
Try reinstalling cocoapods 

`gem uninstall cocoapods`
`gem install cocoapods`
