### ISSUE TITLE
PCT 3.0 ipa resigned for jailbroken atv4's

### ISSUE THREAD

**Issue by misswhitetiger** [PopcornTimeTV/PopcornTimeTV#277]
https://www.sendspace.com/file/ir8qvt

enjoy ;)

**Comment by tomsbrinkis** [comment]
@misswhitetiger meybe you have no resigned version for use with #Impactor ? :)

**Comment by poipop** [comment]
What I must do working with #Impactor ? :) After using Impactor I tried installing but I get this Error: Error# e8008001. Sorry for the inconvenience. Please send us feedback :(

**Comment by tomsbrinkis** [comment]
@poipop thats because its already signed. I Hope @misswhitetiger can give us not signed version :)

**Comment by poipop** [comment]
@tomsbrinkis Hmmmm... Lets wait then! :) Please @misswhitetiger do your best!!!

**Comment by misswhitetiger** [comment]
https://github.com/PopcornTimeTV/PopcornTimeTV/issues/234
