### ISSUE TITLE
Nothing happens when selecting source

### ISSUE THREAD

**Issue by hessius** [PopcornTimeTV/PopcornTimeTV#28]
For about a week now the app has stopped working for me, whatever video is selected the app just displays "processing xx" and then nothing happens, a few days ago I was intermittently successful in getting a download to start but it would then only play the first seconds before pausing and not being able to resume. This behaviour started without me changing any settings, updating the app or changing my internet connection. I'm not behind a VPN. I've now updated to the latest master but to no avail. The debug log shows no error what I can see.

**Comment by hessius** [comment]
seems to be the same issue as #24 (which has been closed?)

**Comment by Evhelden** [comment]
Agree. Seems similar. It improved for one TV show since it was closed. I have done tests with 5 series/episodes. See issue #24 on the findings.

**Comment by popcornMaster** [comment]
I was able to reproduce this but it was also resolved on its own, at least with show death in paradise. It seems that our solution is working as expected, so it must have been a simple torrent tracker issue. Closing as resolved!

**Comment by Evhelden** [comment]
Thanks for testing again. I am happy to notice. I'll let you know the findings. Thanks a lot already of course!

**Comment by hessius** [comment]
I have not seen any fluctuation in this behaviour, the app has been rendered unusable since this started

**Comment by Evhelden** [comment]
Problem remains. Please re-open? If you want I can do further tests to help. Movies seem fine.

**Comment by popcornMaster** [comment]
Please delete project and re-download as it seams there is an issue with downloaded files, issue is resolved!

**Comment by hessius** [comment]
Deleting and re-downloading I've now been able to stream one show (the first few seconds of whatever was top of the top list)
While others fail;
´´´´
2016-08-24 20:23:54.382 PopcornTime[160:3340] File doesn't exists at path: (null)
2016-08-24 20:23:54.464 PopcornTime[160:3210] creating player instance using shared library
´´´´

Is that simply trackers being offline?

**Comment by popcornMaster** [comment]
please delete application from apple tv and re install. it should fix all your problems!

**Comment by hessius** [comment]
I did that and reinstalled the app with the newly downloaded files and the post above is the result of that

**Comment by popcornMaster** [comment]
I had a similar message on the first show I tried to play after reinstalling, but the next time I tried to play the same torrent, it worked! So did you try another time after that message?

**Comment by hessius** [comment]
Hmm not the same message in the logs, though the same behaviour

**Comment by popcornMaster** [comment]
did you have a message saying something about a list,dict?

**Comment by hessius** [comment]
Don't know what the last commits did but can't reproduce this after updating now. @Evhelden how about you?

**Comment by Evhelden** [comment]
I'll try to check tomorrow. Looking forward to solve this indeed.

**Comment by Evhelden** [comment]
Did get some issues installing. Tried version 1.0.1 but it had the same issue with the TV show. Somehow do not get connection to the torrent providers and remain stuck at 0% progress bar.  I will try the latest version again from scratch. BTW Indeed great new UI! Just saw it for the first time!

**Comment by tvOSPopcorn** [comment]
@Evhelden Ooo glad you liked my work on the updated UI 😉  Try deleting the application and installing a completely fresh build to your device that seems to fix any of those previous problem. Let us know!

**Comment by Evhelden** [comment]
It works with Suits. Seems we are back to the great performance again! Thanks a lot!

**Comment by Evhelden** [comment]
Just one show does not come up: The Voice. When clicking on the tile nothing happens. When there is time to pick this one up, that would be super.

**Comment by hessius** [comment]
This sounds like a different issue, I've also seen this but we should keep issues separate. I'll close this one, can't you open a new issue for this?

**Comment by Evhelden** [comment]
will do
