### ISSUE TITLE
Error when compiling: ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by Sonikkua** [PopcornTimeTV/PopcornTimeTV#28]
I'm able to build and run on the simulator just fine, but when compiling for my actual ATV4 on tvOS 9.2 I get:

ld: warning: ignoring file /Users/robertpetersen/Desktop/PopcornTimeTV/Pods/PopcornTorrent/output/Release-appletvsimulator/PopcornTorrent.framework/PopcornTorrent, file was built for x86_64 which is not the architecture being linked (arm64): /Users/robertpetersen/Desktop/PopcornTimeTV/Pods/PopcornTorrent/output/Release-appletvsimulator/PopcornTorrent.framework/PopcornTorrent
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PTTorrentStreamer", referenced from:
      PopcornKit.Torrent.stream ((__C.PTTorrentStatus) -> (), readyToPlay : (__ObjC.NSURL!) -> (), failure : (__ObjC.NSError!) -> ()) -> () in Torrent.o
      PopcornKit.Torrent.cancelStream () -> () in Torrent.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by buzzel** [comment]
Going to close this as everything seems to be working now with the latest commits. Make sure to run a Clean before running the project again
