### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by vis0r** [PopcornTimeTV/PopcornTimeTV#282]
I noticed the app doesn't do fuzzy search. For example I'd expect "Star tr" to bring back star trek results. The Javascript app is the same.

I've had a quick look and I can see the line in PopcornKit that sends the request https://github.com/PopcornTimeTV/PopcornKit/blob/master/PopcornKit/Managers/MovieManager.swift#L95 and I've had a play around with the API myself but I can't seem to get anything working.

1) Do you know if the API supports wildcards in any way?
2) Is this API documented?
3) Do you know where the source code is for the API so I could try fixing this?

**Comment by mattjis** [comment]
https://github.com/popcorn-official/popcorn-api/issues/70
