### ISSUE TITLE
TVshows 0 episodes for Daily Show, Tonight Show, Conan 

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#288]
In the previous version the app would crash or go to back ground. Fixed but no episodes showing.

**Comment by FlaviaBondJamesBondsHusband** [comment]
This is expected behaviour

**Comment by Evhelden** [comment]
Bummer.. Desktop versions work fine. What’s up?

**Comment by FlaviaBondJamesBondsHusband** [comment]
I guess they're not using the latest API's. Try posting your issue here https://github.com/popcorn-official/popcorn-api/issues/new

**Comment by Evhelden** [comment]
Done.

Kind regards,
Erwin van Helden

**Comment by ChrisAlderson** [comment]
All the shows mentioned here are available through the API as shown by the links below. So this isn't an issue with the API, but rather with this repository. I think this issue needs to be reopened and I'm closing [popcorn-api#73](https://github.com/popcorn-official/popcorn-api/issues/73) @Evhelden.

http://tv-v2.api-fetch.website/show/tt0115147 The Daily Show
http://tv-v2.api-fetch.website/show/tt0437729 The Late Late Show with Craig Ferguson
http://tv-v2.api-fetch.website/show/tt3697842 The Late Show with Stephen Colbert
http://tv-v2.api-fetch.website/show/tt0106053 Late Show with David Letterman
http://tv-v2.api-fetch.website/show/tt3513388 Late Night with Seth Meyers
http://tv-v2.api-fetch.website/show/tt4280606 The Late Late Show with James Corden
http://tv-v2.api-fetch.website/show/tt3444938 The Tonight Show Starring Jimmy Fallon
http://tv-v2.api-fetch.website/show/tt1231460 Late Night with Jimmy Fallon

**Comment by Evhelden** [comment]
Hi,

Got the following answer from Chris Alderson:

All the shows mentioned here are available through the API as shown by the links below. So this isn't an issue with the API, but rather with this repository. I think this issue needs to be reopened and I'm closing popcorn-api#73 <https://github.com/popcorn-official/popcorn-api/issues/73> @Evhelden <https://github.com/Evhelden>.

http://tv-v2.api-fetch.website/show/tt0115147 <http://tv-v2.api-fetch.website/show/tt0115147> The Daily Show
http://tv-v2.api-fetch.website/show/tt0437729 <http://tv-v2.api-fetch.website/show/tt0437729> The Late Late Show with Craig Ferguson
http://tv-v2.api-fetch.website/show/tt3697842 <http://tv-v2.api-fetch.website/show/tt3697842> The Late Show with Stephen Colbert
http://tv-v2.api-fetch.website/show/tt0106053 <http://tv-v2.api-fetch.website/show/tt0106053> Late Show with David Letterman
http://tv-v2.api-fetch.website/show/tt3513388 <http://tv-v2.api-fetch.website/show/tt3513388> Late Night with Seth Meyers
http://tv-v2.api-fetch.website/show/tt4280606 <http://tv-v2.api-fetch.website/show/tt4280606> The Late Late Show with James Corden
http://tv-v2.api-fetch.website/show/tt3444938 <http://tv-v2.api-fetch.website/show/tt3444938> The Tonight Show Starring Jimmy Fallon
http://tv-v2.api-fetch.website/show/tt1231460 <http://tv-v2.api-fetch.website/show/tt1231460> Late Night with Jimmy Fallon

I guess it is not the API?

Erwin

**Comment by FlaviaBondJamesBondsHusband** [comment]
@Evhelden Please see my comment https://github.com/popcorn-official/popcorn-api/issues/73#issuecomment-270221975

**Comment by Evhelden** [comment]
Got it. Thanks for following up!
