### ISSUE TITLE
After downloading a movie, PopcornTime keeps crashing

### ISSUE THREAD

**Issue by mohorani** [PopcornTimeTV/PopcornTimeTV#29]
When testing a movie on the Apple TV it will download and then crash(it won't play) When testing it on Xcode, I get a 'EXC_BAD_ACCESS' error(code=1). Maybe this is because I'm running tvOS 9.2. Can you please fix this issue as soon as possible? Thanks.

**Comment by Sonikkua** [comment]
Seeing the same behavior.

At least it compiles and runs now, next step: add media playback to your media app ;-)

Also on tvOS 9.2

**Comment by RefusedFlow** [comment]
**Console will print this error after buffering to 100% **
```
2016-03-25 22:39:44.009 PopcornTime[431:196193] 0:1 1:1 2:1 3:1 4:1 5:1 6:1 7:1 8:1 9:1 10:1 11:1 12:1 13:1 14:1 523:1 522:1 521:1 520:1 519:1 518:1 517:1 516:1 515:1 514:1 
2016-03-25 22:39:44.010 PopcornTime[431:196193] 100%, 14%, 2.2 MB/s, 170, 196
2016-03-25 22:39:44.115 PopcornTime[431:196193] 15:0 16:1 17:1 18:1 19:0 20:1 21:0 22:0 23:0 24:0 25:0 26:0 27:0 28:0 29:1 
PopcornTorrent was compiled with optimization - stepping may behave oddly; variables may not be available.
(lldb) 
```

**Comment by smithington78** [comment]
@Sonikkua If you want to give fixing it a go, feel free ;-)

**Comment by buzzel** [comment]
I believe this issue is stemming from Swift 2.2. There werent any playback issues on the previous version. Still investigation this as it appears to be an issue with libtorrent.

**Comment by buzzel** [comment]
Fixed as of 78f62e7ec8c566b25301691aa10e609a93481608

**Comment by tengis** [comment]
i'm having this issue some on movies

**Comment by RefusedFlow** [comment]
Assuming it's an issue with **PopcornTorrent** but we haven't got anybody working on it, since it's written in C++ @tengis @buzzel

**Comment by buzzel** [comment]
This should of been fixed. Does it crash soon as it tries to start playing the movie?

**Comment by tengis** [comment]
@buzzel my issue was stuck on ProgressViewController as soon as first pieces downloaded 100% it looks like finished but PlayerViewController won't come up. 

i also created issue on PopcornTorrent 

https://github.com/PopcornTimeTV/PopcornTorrent/issues/3
