### ISSUE TITLE
IP filtering in PopcornTorrent? 

### ISSUE THREAD

**Issue by keloin** [PopcornTimeTV/PopcornTimeTV#290]
Rather question - is it possible to support IP black list (IP filter) functionality in PopcornTorrent? 
I can see that the code is there. And the actual list of IP addresses can be found, say, here: http://john.bitsurge.net/public/biglist.p2p.gz.
Any plans to ram this into the code? 
Would have done it myself if I knew c++ :-) 

Thanks!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Not as far as we're aware. You're welcome to do more research and submit a PR!
