### ISSUE TITLE
Request for Anime to be added

### ISSUE THREAD

**Issue by mitral** [PopcornTimeTV/PopcornTimeTV#293]
Can  I make a suggestion for an Anime section to be added to PT? in future releases as I have on the desktop version?

**Comment by FlaviaBondJamesBondsHusband** [comment]
While this is a good idea, the API for Anime isn't very good and it would require a lot of work to pull all the necessary metadata. Episode quality and quantity isn't that great either. If there is sufficient demand for this feature we shall add it. Until then you can look into implementing it yourself and submitting a PR; Most of the backend legwork is already implemented in [PopcornKit](https://github.com/PopcornTimeTV/PopcornTimeKit). 

If you would like to see anime added, react to the question or comment with a "+1"

**Comment by FlaviaBondJamesBondsHusband** [comment]
Looks like the net demand is 2 people. Anime will be removed from the iOS version in the next release too
