### ISSUE TITLE
App Crashes on launch after period of time/inactivity

### ISSUE THREAD

**Issue by michaellindahl** [PopcornTimeTV/PopcornTimeTV#298]
I'm not sure what is happening but after a while the app no longer launches properly and crashes on launch. Not sure if this occurs after a period of time after installing it or after a period of time of not launching the application. When this does happen I click on the icon and it immediately crashes. To resolve the issues I've always just build and ran the app again from Xcode. Any idea what is happening here or anything I can do to help resolve this issue?

**Comment by tvOSPopcorn** [comment]
This isn't an issue with the application. Provisioning profile's expire after 7 days without a paid developer account, so you'll have to manually rebuild the application every 7 days.

**Way's to get around the issue?**

- Purchase a developer account
- Use a 3rd party application signing service, not advised as they might've tampered with our open source code.

**Comment by mattjis** [comment]
@tvOSPopcorn if I were to create my own .ipa (and install it via impactor) would I still have this 7 day period limitation? Or would I still need a developer account regardless?

**Comment by tvOSPopcorn** [comment]
I didn't work on the latest commit to support application archiving. But yes, once you archive you own .IPA file using the [Archiving Popcorn Time](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Archiving-Popcorn-Time) guide Cydia Impactor bypasses the 7 day period
