### ISSUE TITLE
freezes

### ISSUE THREAD

**Issue by GIthHub2die4** [PopcornTimeTV/PopcornTimeTV#299]
Movies or tv shows freezes after a few seconds of play. I sometime get by it by fast forwarding it a bit. Anyone else with the issue ? Also some movies tend to haver some pixel / freezing at times.

**Comment by mclssk** [comment]
Hi! Me too, in atv. But click to stop and click again to start and show
continue normally.

**Comment by r1qu3br** [comment]
me too

**Comment by GIthHub2die4** [comment]
probably a bug with the buffering of torrents ?

**Comment by FlaviaBondJamesBondsHusband** [comment]
This is an issue with [VLCKit](https://code.videolan.org/videolan/VLCKit) and is therefore out of our control. Your are more than welcome to create an issue over on their gitlab but odds are it won't be responded to as the maintainers don't seem to care about the users (all versions after December 2nd don't even compile)
