### ISSUE TITLE
Ability to hide / remove from "Continue watching"

### ISSUE THREAD

**Issue by mattjis** [PopcornTimeTV/PopcornTimeTV#300]
My "continue watching" section is full of crap I clicked on to test if things were working a while ago. I'd love to be able to hold down on them and "mark as watched" or "mark as unwatched". Something like that would be cool!

At the moment even when I manually find the movie and click the "mark as watched" icon, then "mark as unwatched" it doesn't go away :(

**Comment by CavalcanteLeo** [comment]
nice feature

**Comment by CavalcanteLeo** [comment]
+1

**Comment by gchek** [comment]
+1

**Comment by super20161** [comment]
+1

**Comment by tvOSPopcorn** [comment]
@super20161 @gchek @CavalcanteLeo As a temporary  measure you can remove line 41 from [MediaRecipe.xml](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/PopcornTime/UI/tvOS/Recipes/Media/MediaRecipe.xml#L41) to stop it being displayed within the app.

**Comment by doctor2018** [comment]
1+

**Comment by FlaviaBondJamesBondsHusband** [comment]
Hold selecting on items will display a dialogue with the ability to remove items.

Also:

> At the moment even when I manually find the movie and click the "mark as watched" icon, then "mark as unwatched" it doesn't go away :(

Has been implemented too
