### ISSUE TITLE
problem  xcode installer

### ISSUE THREAD

**Issue by super20161** [PopcornTimeTV/PopcornTimeTV#301]
<img width="1440" alt="captura de pantalla 2017-01-12 a las 10 26 42" src="https://cloud.githubusercontent.com/assets/24682172/21895715/ab484194-d8b1-11e6-8e84-b53fc09a6614.png">

problem xcode 8.2.1 image

**Comment by FlaviaBondJamesBondsHusband** [comment]
Fixed with latest commit to Specs repo. Please run `pod repo update; pod update TVVLCKit` to fix.
