### ISSUE TITLE
popcorntime ios  xcode problem 

### ISSUE THREAD

**Issue by super20161** [PopcornTimeTV/PopcornTimeTV#303]
<img width="1440" alt="captura de pantalla 2017-01-12 a las 18 07 58" src="https://cloud.githubusercontent.com/assets/24682172/21912138/1abdda9e-d8f2-11e6-9e25-15b5744f8209.png">
                                                                                                                                                           buildtime   3 issues   swift  compiler  warning

**Comment by FlaviaBondJamesBondsHusband** [comment]
Those are not errors they are warnings therefore the project will still compile
