### ISSUE TITLE
Project do not archive

### ISSUE THREAD

**Issue by gchek** [PopcornTimeTV/PopcornTimeTV#304]
using latest 3.0.0, the project compiles OK and can be installed on ATV4 but when i try to archive to create an IPA, it failed complaining about bitcode.
at https://github.com/PopcornTimeTV/PopcornTimeTV/issues/230 Flavia says it fixed in master.

where can i get this new master (sorry i am new to coding)

thx.
gc

**Comment by gchek** [comment]
Will try this. Thx guys.

**Comment by FlaviaBondJamesBondsHusband** [comment]
git clean -dnx
    git pull
    pod repo update
    pod install
    open PopcornTime.xcworkspace

Follow archiving guide
