### ISSUE TITLE
OpenSubtitles.org not working

### ISSUE THREAD

**Issue by emarar** [PopcornTimeTV/PopcornTimeTV#305]
Hi, I'm not sure if this is a bug but in the latest version I cannot login with my credentials for OpenSubtitles.org. I always get the error that the credentials are incorrect. I do have a VIP account

**Comment by FlaviaBondJamesBondsHusband** [comment]
Open Subtitles API is down a lot of the time. The errors it returns are not very helpful so we almost always have to default to error 401 (Invalid credentials). Give it a day or two and it should work.
