### ISSUE TITLE
managing multiple appleTVs?

### ISSUE THREAD

**Issue by bgregory1129** [PopcornTimeTV/PopcornTimeTV#306]
How do we deal with updating this deployment when there are multiple apple TVs involved?  Forgive the newness to the whole thing - I just got through the standard install. It said to rerun the script when an update was found, but I wonder how that will be affected if I am deploying to multiple apple tvs?   Does it not matter since I am not releasing/signing an IPA?

**Comment by FlaviaBondJamesBondsHusband** [comment]
No it doesn't affect anything. Run the script once to get the new version and then deploy to all the ATV's you want
