### ISSUE TITLE
Cannot switch between subtitles

### ISSUE THREAD

**Issue by tomeranaray** [PopcornTimeTV/PopcornTimeTV#307]
In version 3.0.0 on ATV it's not possible to switch between subtitles. The option is there in the swipe down menu but settings don't stick. 

Both the language and delay settings don't stick when changing them. The encoding setting does stick (but cannot confirm if it actually works)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue fixed in master

**Comment by tomeranaray** [comment]
Thanks for fixing this. How can I test this update? I'm now on 3.0.0.

**Comment by tvOSPopcorn** [comment]
@tomeranaray [Download Master Here](https://github.com/PopcornTimeTV/PopcornTimeTV/archive/master.zip)

**Comment by tomeranaray** [comment]
Hi, I tried compiling this version but got various errors. I assumed I needed to update Cocoapods, which I did. But that didn't help. Both version 3.1 and version 3.0 now fail while running the install script. Any ideas?


/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : angryduck2 - https://github.com/angryDuck2/CocoaSpecs @ d8ba9783b52fd970b8be590f0ce5de49a4c400e0
               hackormahn - https://github.com/Hackormahn/Specs @ d1a4789e8ac060d7e1d0b003b3cce3bc58185698
               master - https://github.com/CocoaPods/Specs.git @ c0be32056058544ed2a832cb2f5dbf80121ff572
               popcorntimetv - https://github.com/PopcornTimeTV/Specs @ 37d3d337fbc82c15cd5c6a6a8ce18889b08e8fdf
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/angryDuck2/CocoaSpecs'
source 'https://github.com/PopcornTimeTV/Specs'

def pods
    pod 'PopcornTorrent', '~> 1.1.2.1'
    pod 'PopcornKit', '~> 3.1.9'
    pod 'XCDYouTubeKit', '~> 2.5.3'
    pod 'Alamofire', '~> 4.2.0'
    pod 'AlamofireImage', '~> 3.2.0'
    pod 'SwiftyTimer', '~> 2.0.0'
    pod 'SwiftKVC', '~> 3.0.1'
end

target 'PopcornTimeiOS' do
    platform :ios, '9.0'
    pods
    pod 'AlamofireNetworkActivityIndicator', '~> 2.1.0'
    pod 'Reachability', '~> 3.2'
    pod 'JGProgressHUD', '~> 1.4'
    pod 'google-cast-sdk', '~> 3.3.0'
    pod 'OBSlider', '~> 1.1.1'
    pod 'ColorArt', '~> 0.1.1'
    pod '1PasswordExtension', '~> 1.8.4'
    pod 'MobileVLCKit-unstable', '~> 3.0.0a24'
    pod 'FloatRatingView', '~> 2.0'
end

target 'PopcornTimetvOS' do
    platform :tvos, '9.0'
    pods
    pod 'TVVLCKit-unstable', '~> 3.0.0a24'
    pod 'TVMLKitchen', :git => 'https://github.com/toshi0383/TVMLKitchen.git'
    pod 'MBCircularProgressBar', '~> 0.3.5-1'
end

target 'TopShelf' do
    pod 'PopcornKit', '~> 3.1.9'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:851:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:850:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:850:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:845:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command/update.rb:81:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=cannot+load+such+file+--+nanaimo&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - LoadError - cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6281 [closed] [11 comments]
   2 days ago

 - help!   cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6312 [closed] [6 comments]
   4 weeks ago

 - LoadError - cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6214 [closed] [30 comments]
   2 weeks ago

and 10 more at:
https://github.com/cocoapods/cocoapods/search?q=cannot%20load%20such%20file%20--%20nanaimo&type=Issues&utf8=✓
Opening Xcode...
["-c", "open PopcornTime.xcworkspace"]
The file /Users/xxx/Documents/PopcornTimeTV/PopcornTime.xcworkspace does not exist.
Thanks for installing PopcornTime. When a new update is released re-run this script and select the new version.

**Comment by tomeranaray** [comment]
I tried compiling that version but Xcode crashes as soon as I try to open PopcornTime.workspace. Reverting back to 3.0 now also causes this issue. Don't know how to fix it. Usually it goes away after restarting the build process a couple of times, but it would be helpful to know where the problem is
