### ISSUE TITLE
Error on building to the Apple TV: exit 1 signal 0

### ISSUE THREAD

**Issue by ceuaugusto** [PopcornTimeTV/PopcornTimeTV#309]
Hi guys,

First, I apologize for my bad english. Second, these errors are occurring when trying when building and running the PopcornTimeTV into my ATV:

<img width="1280" alt="captura de tela 2017-01-14 as 23 54 08" src="https://cloud.githubusercontent.com/assets/19508685/21959915/33558880-dab5-11e6-8f04-3dcec2fece50.png">
<img width="1280" alt="captura de tela 2017-01-14 as 23 53 56" src="https://cloud.githubusercontent.com/assets/19508685/21959918/33d05696-dab5-11e6-9826-5287b0d29ab8.png">
<img width="1280" alt="captura de tela 2017-01-14 as 23 53 47" src="https://cloud.githubusercontent.com/assets/19508685/21959917/33d038be-dab5-11e6-8d59-bac31a0c8448.png">
<img width="1280" alt="captura de tela 2017-01-14 as 23 53 37" src="https://cloud.githubusercontent.com/assets/19508685/21959919/33d0bc3a-dab5-11e6-99cd-631e24f16a78.png">
<img width="1280" alt="captura de tela 2017-01-14 as 23 53 21" src="https://cloud.githubusercontent.com/assets/19508685/21959916/33cb41ec-dab5-11e6-8797-bc426b93012a.png">

The errors seem to be random. I've tried some "solutions" found here and other sites on the web, but nothing solved so far. Can you help me? Thanks in advance!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Hmm this is a weird one... 

Not really sure why it's not building but here are a few things to try:

1. Delete derived data: `rm -rf ~/Library/Developer/Xcode/DerivedData/`.
2. Clean the project (**⇧+⌘+K**).
3. Quit Xcode.
4. Remove Podfile.lock and .xcworkspace file and re-run `pod install`.

**Comment by ceuaugusto** [comment]
Thanks! I´ll try these tonight! I´m not a programmer, so I have one doubt about step 4: I didn´t run pod install, only the install.swift as metioned on the Building PopcornTime Guide. Where do I run this command? Should I run in Terminal?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Pod install is automatically run by the install script, you don't have to worry about it usually

**Comment by ceuaugusto** [comment]
Hmm, okay. So, especifically, what do I have to do in order to run the pod install command that you mentioned? Sorry for asking so much and thanks!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Apologies, I misunderstood your question. Yes you run these in terminal. Make sure to `cd` into the directory where you have downloaded the project to

**Comment by ceuaugusto** [comment]
Thanks again! I´ll do everything tonight and then post a feedback here!

**Comment by ceuaugusto** [comment]
It worked! The problem was solved by doing the step-by-step, @FlaviaBondJamesBondsHusband! Thanks!
