### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by ciscosurplus** [PopcornTimeTV/PopcornTimeTV#310]
In the past have had no problems building, currently I get

The file /Users/xxx/Desktop/PopcornTimeTV/PopcornTime.xcworkspace does not exist.

the xcworkspace file seems to be missing, if I open the project file and build i get 3 errors

Podfile.lock is missing, manifest.lock is missing also

**Comment by FlaviaBondJamesBondsHusband** [comment]
The project does not come with these files, it is cocoapods' job to generate them. If you are not competent enough, please use the install script. Otherwise run the following commands:

    pod repo update
    pod install
    open PopcornTime.xcworkspace

**Comment by ciscosurplus** [comment]
Have generated fine on the last 4 release it's only since updating Xcode and your update to 3.0.0. It tried the simple install script and the usual way getting cocoa pods to do it, neither are generating the file, verbose mode shows missing blocks in the source files.

**Comment by ciscosurplus** [comment]
Gemma-macbook:PopcornTimeTV gemma$ pod install
Analyzing dependencies
Pre-downloading: `TVMLKitchen` from `https://github.com/toshi0383/TVMLKitchen.git`
Downloading dependencies
Installing 1PasswordExtension (1.8.4)
Installing AEXML (4.0.1)
Installing Alamofire (4.2.0)
Installing AlamofireImage (3.2.0)
Installing AlamofireNetworkActivityIndicator (2.1.0)
Installing AlamofireXMLRPC (2.1.0)
Installing ColorArt (0.1.1)
Installing FloatRatingView (2.0)
Installing GCDWebServer (3.3.3)
Installing JGProgressHUD (1.4)
Installing Locksmith (3.0.0)
Installing MBCircularProgressBar (0.3.5)
Installing MobileVLCKit-unstable (3.0.0a24)
Installing OBSlider (1.1.1)
Installing ObjectMapper (2.2.2)
Installing PopcornKit (3.1.9)
Installing PopcornTorrent (1.1.2.1)
Installing Reachability (3.2)
Installing Reflection (0.14.3)
Installing SRT2VTT (1.0.1)
Installing SwiftKVC (3.0.1)
Installing SwiftyJSON (3.1.4)
Installing SwiftyTimer (2.0.0)
Installing TVMLKitchen (1.0.1)
Installing TVVLCKit-unstable (3.0.0a24)
Installing XCDYouTubeKit (2.5.3)
Installing google-cast-sdk (3.3.0)
Generating Pods project
Abort trap: 6
Gemma-macbook:PopcornTimeTV gemma$ ls
CONTRIBUTING.md		Pods			README.md
LICENSE.md		PopcornTime		TopShelf
Podfile			PopcornTime.xcodeproj	install.swift


As you see no file has been generated, I've tried this on two machines both running the latest Xcode
