### ISSUE TITLE
Start-stop apple tv remote not working 

### ISSUE THREAD

**Issue by gchek** [PopcornTimeTV/PopcornTimeTV#311]
On 3.1 release the start/stop button on Apple TV remote is not responsive.

**Comment by FlaviaBondJamesBondsHusband** [comment]
What's the start/stop button? Do you mean the Play/Pause button? If so where is it not working?

**Comment by gchek** [comment]
Yes. Play/pause. 
During a movie play. Can't stop or pause. 
Sorry for my English. 

I use the version u helped me to archive on my last post which worked fine to extract the IPA. 

Gilles 

On 16 Jan 2017, at 18:34, FlaviaBondJamesBondsHusband <notifications@github.com> wrote:

What's the start/stop button? Do you mean the Play/Pause button? If so where is it not working?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Play/Pause is working and has been working on all versions so the issue must reside with your apple tv. I would suggest reinstalling the iPA
