### ISSUE TITLE
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by loneyliver** [PopcornTimeTV/PopcornTimeTV#312]
Hi everyone

   First off thanks for such a great program. it works great. I am having an issue with archiving popcortime. I followed the build directions here on the GitHub and it builds great. It also installs just fine onto the atv4 by hitting the play button and works great when i use it. But when i try to achrive it to create a file then it gives me the following error.

clang: error: linker command failed with exit code 1 (use -v to see invocation)

What i am trying to do in the end is create an ipa file.

![screen shot 2017-01-16 at 2 19 09 pm](https://cloud.githubusercontent.com/assets/9465528/21996201/0b3974a4-dbf7-11e6-9dcc-a18b8a566e7d.png)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Please use master. 3.0.0 does not support archiving

**Comment by loneyliver** [comment]
ok, but which version is the master,,,, i am going thru terminal and they are all numbered..

**Comment by vbmota** [comment]
1 - at the https://github.com/PopcornTimeTV/PopcornTimeTV click clone/download green button
2- download zip file
3 - unzip it
4 - continue building
