### ISSUE TITLE
Apple TV stops playing ands spins indefinitely after playing a movie

### ISSUE THREAD

**Issue by maven1129** [PopcornTimeTV/PopcornTimeTV#313]
Works great when first booting to a new install.  Play a movie just fine.  Go to play another movie and it gives the spinning working wheel just a few seconds into it.  I tried to close popcorn and re-open, same issue.  Happens on all my Apple TVs on all the different shows and movies I try.   I then open Antenna and it has the same issue - starts to play and then stops.  Is there something being affected by Popcorn that could create a caching issue like this?  Any logs I could retrieve and send, let me know how to do it and I will be happy to.  FYI - when i reboot the machine it works again, but then the same issue persists after going through one film/show.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Nothing to do with Popcorn Time. I would suggest getting better internet
