### ISSUE TITLE
Subtitles not synced

### ISSUE THREAD

**Issue by damiantrimboli** [PopcornTimeTV/PopcornTimeTV#315]
The subtitles are still out of sync. Even after trying to sync them with the offset feature (which shouldn't be used at all since subtitles files are ok) movies like "Snowden" cannot be synced. 
This is a huge bug that affects most of the users: most movies are in english but there are more people who speak other languages than english. (spanish, chinese, portuguese).

The offset option issue was fixed in this one: https://github.com/PopcornTimeTV/PopcornTimeTV/issues/286

**Comment by FlaviaBondJamesBondsHusband** [comment]
#286

**Comment by damiantrimboli** [comment]
@FlaviaBondJamesBondsHusband If you are going to close this one, at least reopen the #286 one. Subtitles sync issue is not fixed.
