### ISSUE TITLE
Some genre results are empty - causing the app to break

### ISSUE THREAD

**Issue by mattjis** [PopcornTimeTV/PopcornTimeTV#316]
If any of the following genres are selected the app will break.

Genres to be removed from filter: 
- Disaster
- Fan Film
- Film Noir
- Holiday
- Indie
- Road
- Short
- Sports
- Sporting Event

These genres have only one result so should probably also be removed:
- Suspense (The meaning is the same as thriller anyway)

**Comment by FlaviaBondJamesBondsHusband** [comment]
We have already contacted the owner of the API and he will not be removing these so nothing more we can do. The fix that i pushed means that you can now choose different genres when an empty genre shows up
