### ISSUE TITLE
Signing for "TopShelf"

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#317]
im getting this error:

Check dependencies

Signing for "TopShelf" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'TV App Extension' in SDK 'tvOS 10.1'

I could install on my iPhone, but not on my apple tv
<img width="1392" alt="captura de tela 2017-01-21 as 13 50 28" src="https://cloud.githubusercontent.com/assets/1735944/22175665/a365e69e-dfe0-11e6-8d1f-ddaabf2cd064.png">

**Comment by FlaviaBondJamesBondsHusband** [comment]
Follow the build instructions https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-Popcorn-Time#signing-in-with-development-team
