### ISSUE TITLE
TV shows on apple tv

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#318]
Is it possible to see all tv shows on apple tv, like game of thrones ?

And is it possible to search for a movie by using the name?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Have you actually opened the app?

**Comment by CavalcanteLeo** [comment]
Yep

**Comment by FlaviaBondJamesBondsHusband** [comment]
There is literally a search section

**Comment by CavalcanteLeo** [comment]
ahhh, just figured out...

have to press menu to see the options 

sorry

**Comment by CavalcanteLeo** [comment]
at the first seen, just saw this:

![file 21-01-17 14 19 28](https://cloud.githubusercontent.com/assets/1735944/22175851/bfa8f536-dfe4-11e6-9f50-87e58fd4419d.jpeg)
