### ISSUE TITLE
The App Cannot Play ONE Movie Reliably 

### ISSUE THREAD

**Issue by computersteve** [PopcornTimeTV/PopcornTimeTV#319]
I have installed this app on 4 apple tv's and on all 4 apple TV's I'm getting freezing when playing a movie... The movie will start, then like 3 minutes into the movie the whole screen freezes, and I can still hear audio playing in the background, but no moving video =(

**Comment by FlaviaBondJamesBondsHusband** [comment]
Awh poor you #299

**Comment by computersteve** [comment]
im not being ungrateful I'm saying that even after stopping the video and playing it again it still does not play back right lol so that bug must be worse than originally thought.
