### ISSUE TITLE
problems downloading pods

### ISSUE THREAD

**Issue by alegye2019** [PopcornTimeTV/PopcornTimeTV#32]
I'm having problems installing the project, i clone the project and run swift install.swift. everything is ok until the line:
installing TVVLCKIT-unstable
It can take hours and nothing more happends, i send you a capture.

please help me.
<img width="570" alt="captura de pantalla 2016-08-25 a las 3 46 07 p m" src="https://cloud.githubusercontent.com/assets/20804744/17985539/ea2944ce-6adb-11e6-8e8e-705cea80f726.png">

**Comment by tvOSPopcorn** [comment]
@alegye2019 **Try using**  `pod install --verbose`

TVVLCKIT-unstable is a good 400mb download so if you've got a poor internet connection it will take longer. Using verbose mode you'll be able to see the current download progress.

**Comment by FlaviaBondJamesBondsHusband** [comment]
It takes long to download, thats all thats to it :).
