### ISSUE TITLE
why do you close these bugs -- I'm on your latest dev build 3.1 and videos don't play right even after restarting... 

### ISSUE THREAD

**Issue by computersteve** [PopcornTimeTV/PopcornTimeTV#320]
I have installed this app on 4 apple tv's and on all 4 apple TV's I'm getting freezing when playing a movie... The movie will start, then like 3 minutes into the movie the whole screen freezes, and I can still hear audio playing in the background, but no moving video, I'm not being ungrateful I'm trying to inform you of a problem that you think you have a fix for by stopping the video then replaying it which doesn't work on any of my players.. I just tried that with "the girl on the train" and everytime it stops at random parts.. with audio still playing.

**Comment by FlaviaBondJamesBondsHusband** [comment]
#319
