### ISSUE TITLE
Possible to download 3.0 IPA

### ISSUE THREAD

**Issue by majedsahi** [PopcornTimeTV/PopcornTimeTV#322]
I keep receiving one or another errors on xcode. Is it possible if someone can please upload the latest IPA file? I will sign it using my own Apple ID.
Thanks.

**Comment by misswhitetiger** [comment]
http://www.sinfuliphone.com/showthread.php?t=10086865

https://github.com/PopcornTimeTV/PopcornTimeTV/issues/234
