### ISSUE TITLE
Audio delay not working

### ISSUE THREAD

**Issue by jeffhodsdon** [PopcornTimeTV/PopcornTimeTV#324]
Hello! This issue is regarding the audio delay feature just introduced. It wasn't working for me and my AirPlay speaker.

I did some debugging and found two issues.

1) Delay assumes seconds but the VLC player delay is in microseconds
2) The delegate on the AudioViewController seems to be nil at times and doesn't actually set the delay

**Comment by FlaviaBondJamesBondsHusband** [comment]
This has been fixed in master for quite a while
