### ISSUE TITLE
Getting errors after trying to switch branch and pull

### ISSUE THREAD

**Issue by tobiasroti** [PopcornTimeTV/PopcornTimeTV#326]
I tried to pull from source controll to fix some error I have had, including no subtitles on popcorntime. However, when I do this I get a message that xcode can't determine current branch. So I created a new branch, then switched back to the original 'master' branch. Now I can pull from GitHub however I get several 'swift compiler errors'. (See image screenshot). 
Is it correct to pull from GitHub to try to fix problems with for example the subtitle issue?
![skjermbilde 2017-01-25 kl 12 01 44](https://cloud.githubusercontent.com/assets/9999896/22288362/e25d29e8-e2f6-11e6-976c-202cfad17a65.png)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Yes but your cocoapods are out of date. Please run `pod repo update; pod install`
