### ISSUE TITLE
Use of unresolved identifier 'currentItem'

### ISSUE THREAD

**Issue by rzgarespo** [PopcornTimeTV/PopcornTimeTV#327]
Hi, 
I'm getting this error:

` Downloads/PopcornTimeTV-master/PopcornTime/UI/tvOS/Recipes/Products/MovieProductRecipe.swift:79:30: Use of unresolved identifier 'currentItem'`

I hadn't any issues first when I build it for my apple tv now after a week tried to rebuild and got this error.
Thank you for any help you could provide.
![error](https://cloud.githubusercontent.com/assets/5732300/22329144/2fc2c4c6-e3c0-11e6-9eed-f13f1e9329ad.jpeg)

**Comment by Dewinster** [comment]
Hi rzgarespo,

The problem you are dealing with are occurring to me aswell.
The solution is simple, replace the object "currentItem" to "movie" so the line number 79 will be:
"if let runtime = Int(movie.runtime) {"

Regards,
Dewin

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue fixed in master, apologies

**Comment by rzgarespo** [comment]
Thank you so much guys!
