### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#328]
We could localize the app, 

I can translate to Portuguese, just need the .string file to translate

**Comment by delut** [comment]
If this moves forward, I can do Spanish.

**Comment by moh0sw1** [comment]
I can do arabic 👍

**Comment by tomsbrinkis** [comment]
I can do Latvian!

**Comment by CavalcanteLeo** [comment]
Does PopcornTimeTV supports RTL?
@moh0sw1

**Comment by moh0sw1** [comment]
@CavalcanteLeo I didn't try to make the whole app RTL
but I tried to translate the words for a RTL language (Arabic) and it worked

**Comment by CavalcanteLeo** [comment]
great..

**Comment by PingedBug92** [comment]
I can do Italian.

**Comment by mtwww** [comment]
hi after long time..
count me in for Turkish

**Comment by GIthHub2die4** [comment]
Can do French

**Comment by Faisal-nz** [comment]
Already translated to Arabic and Localization files are ready

**Comment by FlaviaBondJamesBondsHusband** [comment]
Apologies for the delay, please follow the [Translating Popcorn Time Guide](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Translating-Popcorn-Time),

**Comment by CavalcanteLeo** [comment]
Gonna translate by this weekend

**Comment by CavalcanteLeo** [comment]
@FlaviaBondJamesBondsHusband @RefusedFlow..  reach me at leonardo_cavalcante@msn.com, I don't want to make a PR, I don't want my name in the git history
