### ISSUE TITLE
Connect to TVShow Time for tvOS Version?

### ISSUE THREAD

**Issue by moh0sw1** [PopcornTimeTV/PopcornTimeTV#329]
it is possible to add this future like the Popcorn Time app for Windows and Mac Versions?
it will be so great!

Thanks!

**Comment by moh0sw1** [comment]
@tvOSPopcorn @FlaviaBondJamesBondsHusband @b1narygh0st

**Comment by FlaviaBondJamesBondsHusband** [comment]
There is no plan to add this as we already have Trakt implemented. Your are more than welcome to submit a PR though!
