### ISSUE TITLE
 xcode  ios  problem

### ISSUE THREAD

**Issue by doctor2018** [PopcornTimeTV/PopcornTimeTV#330]
<img width="1440" alt="captura de pantalla 2017-01-31 a las 19 15 01" src="https://cloud.githubusercontent.com/assets/25284483/22490181/a2ca35f8-e7e9-11e6-99c3-fdfdf94b4b70.png">

 problem project

**Comment by FlaviaBondJamesBondsHusband** [comment]
#323
