### ISSUE TITLE
Playback not stable since version 1.0.5

### ISSUE THREAD

**Issue by CompuSteve** [PopcornTimeTV/PopcornTimeTV#331]
I have verified on the latest TV OS 10.1.1 that 1.0.5 plays movies and tv shows very extremely well that even goes for the version before 1.0.5.. once we get to the newer versions such as 3.0 and 2.0 the player though improved with being able to rewind and fast forward does not play the video without stuttering and chopping up & sometimes a complete freeze.. you can see this in Tv shows such as South Park, or the Movie Trolls the bug that someone mentioned about vlc player being the cause doesn't seem to effect these older versions. I watched an entire south park episode without any breakup on 1.0.5 but on 3.0 it couldn't get past the theme song. So I just wanted to alert the team to that. Thanks for all your hard work and keep it up.

**Comment by FlaviaBondJamesBondsHusband** [comment]
#320. Please stop reposting the same issue
