### ISSUE TITLE
Subtitle delays longer than 5s

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#333]
Is there a way to delay a subtitle longer than 5 seconds? In the menu it goes -5...+5

But the movies was something around +50 seconds delayed 

All the tv shows the subtitle are correct, but in movies, most all of them are wrong (PT-BR)

**Comment by hvluu** [comment]
you can change the interval in the SubtitlesViewController.swift file (located in PopcornTimeTV/PopcornTime/UI/tvOS/Option View Controllers/). However, adjusting the delay interval still doesn't work (it sticks with the selected interval but it doesn't do anything). I even tried to adjust it to -30 but the subtitle still goes fastest then the audio just about 5-6 seconds. Can you look into this?

**Comment by FlaviaBondJamesBondsHusband** [comment]
5 second delay is perfectly sufficient. Any more than that means there is something wrong with the subtitle file and you should submit a bug report with OpenSubtitles
