### ISSUE TITLE
Enable play button

### ISSUE THREAD

**Issue by misswhitetiger** [PopcornTimeTV/PopcornTimeTV#334]
Could the play button be enabled so when picking a movie or tv episode it will play the content without having to tap the touchpad to play?

**Comment by tvOSPopcorn** [comment]
Some more detail would be nice, but do you mean when you're on the movie grid you'd like to be able to click the **Play** button on the remote to automatically start streaming the movie or show? This could  work together with #335

**Comment by misswhitetiger** [comment]
Exactly, when on the movie grid when pct is opened initially and similarly when a episode is highlighted just prior to it asking which resolution is disired currently.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for the suggestion. It is now implemented in master. Enjoy!

**Comment by misswhitetiger** [comment]
Hello again! loving the new features so far, thanks! One thing I did notice tho was when playing a highlighted episode (when in the list of episodes in a desired season) the play button does not work. When highlighting a movie and pressing the play button it does work as intended. Could the logic be added to tv shows also?

**Comment by FlaviaBondJamesBondsHusband** [comment]
I agree with
 > (TV episode) Press play - prompts for resolution or plays automatically

but 
> (TV show) Press play - enters season and shows episode list screen (background music etc)

is just plain bad UX. Pressing the play button should explicitly play media and not provide the exact same function as the select button.
