### ISSUE TITLE
Loading new page of results jumps back to top (master branch)

### ISSUE THREAD

**Issue by GerTeunis** [PopcornTimeTV/PopcornTimeTV#336]
Presenting more items to the results grid will cause the current selection to jump back to top which is a serious usability issue.

After adding more resuls can't we focus the previous item?

**Comment by FlaviaBondJamesBondsHusband** [comment]
#274. Nothing we can do about this unfortunately

**Comment by GerTeunis** [comment]
why not? Does tvOS / tvml have a technical problem?
