### ISSUE TITLE
New tvOS UI bugs

### ISSUE THREAD

**Issue by FlaviaBondJamesBondsHusband** [PopcornTimeTV/PopcornTimeTV#337]
- [x] MainViewController's UICollectionView lastFocusedIndexPath not remembered due to calling `reloadData()` in `viewWillAppear:animated:`
- [x] DetailViewController section header spacings
- [x] DetailViewController button labels
- [x] DetailViewController expandable text view
- [x] WatchlistViewController header spacing
- [x] MonogramCollectionViewCell weird shadow and blur placeholder
- [x] Fade to black animation transition for PCTPlayerViewController and AVPlayerViewController
- [x] Redo infoViewControllers subtitle label
- [x] Need for UIFocusGuide on DetailViewController view to help with transition from UICollectionView to buttons
- [x] MainViewController should focus on tab bar buttons first instead of UICollectionView.
- [x] Issues when opening movies/shows from TopShelf.
- [x] DetailViewController initial focus on buttons
- [x] ShowDetailViewController info label and subtitle label font
- [x] UICollectionViewCell growth when focused (subviews not resized accordingly). Use UIImageView's `focusedFrameGuide` property to align properly.
- [x] Need for UIFocusGuide on MainViewControllers to help with transition from UICollectionView to barButtonItems
- [x] DetailViewController needs height constrains for when little to no data is provided
- [x] Theme songs will continue to play if the user leaves the app while in DetailViewController is presented
- [x] Items found from the SearchViewController won't open

**Comment by FlaviaBondJamesBondsHusband** [comment]
If there are any more bugs please comment below

**Comment by tvOSPopcorn** [comment]
- [ ] Product view needs height constrains for when little to no data is provided

**Comment by gustavolessadublin** [comment]
Hi!

After a fresh new install (now update), from fresh files, I can't open any title.
As soon as I choose the resolution, it crashes and closes, going back to Apple TV menu.

Any ideas how to fix it?

Thank you very much!
