### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by PingedBug92** [PopcornTimeTV/PopcornTimeTV#338]
It is possible to know which ports are used by the client?
In terms of Port Forwarding.

**Comment by tvOSPopcorn** [comment]
Almost certain we aren't using any specific ports to run the application, we're just making web requests for the UI. I'm unsure on the whole streaming aspect of the application though @FlaviaBondJamesBondsHusband

**Comment by FlaviaBondJamesBondsHusband** [comment]
we're using port 80 (http) to stream from a local web-server which in turn is streaming through ports 6881-6889 (normal bittorrent ports)
