### ISSUE TITLE
VPN OR DNS? 

### ISSUE THREAD

**Issue by s-dm** [PopcornTimeTV/PopcornTimeTV#339]
Love popcorntimetv, but as someone requested before, we should get a vpn built in to the app. However, there is some great dos services, but are they as safe as vpn when using this app on Apple TV?

**Comment by FlaviaBondJamesBondsHusband** [comment]
We wont be building a vpn into the application as all the free VPN's are very slow and mostly insecure. It is up to apple to provide the ability to do this from the system
