### ISSUE TITLE
I ran all the commands in terminal still issuses installing the build in XCODE

### ISSUE THREAD

**Issue by jsmoove05** [PopcornTimeTV/PopcornTimeTV#34]
Hello all hows it going i have been trying to install Popcorn time TV on my apple tv for a while now. It seems like I did everything my ruby verison is up to date. I installed the cocoapods and ran the script still having errors in the build in xcode I have attached a screen shot.

![image](https://cloud.githubusercontent.com/assets/21265397/18012797/0fd29b46-6b89-11e6-925a-7238a8217483.png)

can someone please help me out I have been at this for days now.

**Comment by moh0sw** [comment]
run "PopcornTime.xcworkspace" not "PopcornTime.xcodeproj"

**Comment by jsmoove05** [comment]
Hi thanks for the fast response Yes this is the workplace im running and im getting those messages.

**Comment by tvOSPopcorn** [comment]
Always read the WIKI before creating an issue, everything is explained over there! https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

**Comment by jsmoove05** [comment]
I read that thing 50x it does not solve this issue........
