### ISSUE TITLE
tv shows freezes in popcorntime ios

### ISSUE THREAD

**Issue by doctor2018** [PopcornTimeTV/PopcornTimeTV#340]
I have problems when playing TV Shows. After click, it takes a long time to start playing, the chapter suddenly freeze and do not play. In the previous version I did not have that problem.

**Comment by FlaviaBondJamesBondsHusband** [comment]
What TV show and episode are you trying to watch? I suspect it is low on seeds and is just buffering, hence the long load time

**Comment by doctor2018** [comment]
With all tvshows is the problems

**Comment by doctor2018** [comment]
With all tvshows is the problems

**Comment by FlaviaBondJamesBondsHusband** [comment]
Specifically what one were you trying. "all tvshows is the problems" is neither correct nor helpful

**Comment by doctor2018** [comment]
yes. all tv shows is the problem

**Comment by FlaviaBondJamesBondsHusband** [comment]
Without any further information I cannot help you

**Comment by doctor2018** [comment]
im trying with south park, any season and any chapter, stuck in the middle, adventure time, best friends whenenever, and many others. Maybe problems withs seeds, but with the old version i dont have this problem, my internet connection is fast.
