### ISSUE TITLE
PopcornTimeTV tvOS crashes back to springboard when launcing on ATV4

### ISSUE THREAD

**Issue by thewusman** [PopcornTimeTV/PopcornTimeTV#342]
Per title.

Compiled, built and archived on Xcode without errors.

Signed and loaded onto ATV4 running 10.1.1

Crashed back to springboard immediately upon attempting to open.

Any ideas ?

Latest git clone and project workspace used to build. [XCode 8.2.1 on Sierra]

**Comment by FlaviaBondJamesBondsHusband** [comment]
Must be some issue with your apple tv as master is working. Could you try removing the app and trying again?

**Comment by thewusman** [comment]
Will try - but other apps that I sign and provision (iOS app signer and Xcode) are fine (Kodi 17, Provenance, Aerial all sideloaded in the same manner).

**Comment by thewusman** [comment]
Update: Builds and sideloads perfectly onto a iPhone 6S using the .ios version.

Any ideas ? Just the tvos that is a crash-no-go.

**Comment by thewusman** [comment]
Updated: FIXED

For some reason the deployment target on the topshelf was set to 10.1

Changing this back to 9 like the iOS version solved the crashing.

Works like a dream !
