### ISSUE TITLE
Subtitle languages.

### ISSUE THREAD

**Issue by Beorn1988** [PopcornTimeTV/PopcornTimeTV#35]
Ok first off thank you for a great update fixad alot of small kinks I've experienced. Earlyer versions like 0.7 I kind of didn't use at all just installed for interest :) but now it's actually sotning great.

Heres my "problem" though.
Swedish language isn't even an option anywhere.
I hardly think there aren't any subtiles for anything in swedish..?
I dimmly recall having these issues with popcorntime on my computer back in the days aswell. Same goes for iPhone. So I'm guessing it's just not added as an option.... Or.?
I tried Messing with different emcodings to see if more options should magically appear but to no avail 😅

**Comment by tvOSPopcorn** [comment]
Unfortunately we aren't controlling the Subtitle languages that are available they're pulled directly from [OpenSubtitles](http://www.opensubtitles.org/en/search) so i'll be closing this issue as it doesn't relate to the project directly 😄
