### ISSUE TITLE
Check subtitles availability

### ISSUE THREAD

**Issue by gustavolessadublin** [PopcornTimeTV/PopcornTimeTV#350]
Hi.

I'm sorry if it's posted in wrong place.
But I'd like to ask if it's possible to add a feature that allows us to verify if there is any subtitles for given release.

Thank you very much,
Gus

**Comment by FlaviaBondJamesBondsHusband** [comment]
I'm not quite sure what you mean. If you mean the ability to see if subtitles are available for a specified movie/episode before viewing, the answer is no as we fetch the subtitles just as the movie is about to play not when the view loads
