### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by misswhitetiger** [PopcornTimeTV/PopcornTimeTV#352]
https://github.com/PopcornTimeTV/PopcornTimeTV/issues/144

How do we add custom magnets or torrents? Is there a web interface or url we visit to add a torrent or magnet url to similar to how there is a web interface here:

https://github.com/jasarien/Provenance/wiki/Importing-ROMs

Instructions would be great on how to use this new feature. I tried visiting the aTV4ip in a browser or the aTV4ip:8080 while PCT app is open. Is there a different port or way to do so? Could this also be added to the wiki & how to use certain other newly added features in the future? Thanks for all the updates :)

Another idea while on the subject, could we save the magnets we add and then browse them later within the PCT app in a page like how we browse current trending movies and/or could we search for other custom magnets from the search tab?

**Comment by FlaviaBondJamesBondsHusband** [comment]
#144 was for iOS only (share sheet and opening magnet links from safari). This functionality is not available on tvOS
