### ISSUE TITLE
The Airplay have only a "Cancel Button" (iphone)

### ISSUE THREAD

**Issue by ntassani** [PopcornTimeTV/PopcornTimeTV#353]
Hi! When you select airplay and see your apple tv you can do the mirror, but the only displayed option is for "cancel". And of course, after press cancel your airplay is terminated.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Already implemented in master

**Comment by ntassani** [comment]
![img_0115](https://cloud.githubusercontent.com/assets/11095490/23094831/bf1972e8-f5de-11e6-8088-ca68a9245eaf.PNG)
No, it's not fixed. You only have the Cancel Button. (Compiled 5 minutes ago).
Please reopen the thread...
Thanks! Nicolai.
