### ISSUE TITLE
No adjust timing for subtitles? (iphone)

### ISSUE THREAD

**Issue by ntassani** [PopcornTimeTV/PopcornTimeTV#354]
Is possible to add an option for accelerate/decrase the speed of the subtitles?
Is a really needed because all the subtitles are always out of timing.
And yes, i see other similar closed issues but without any workaround.
Thanks!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Already implemented in master

**Comment by ntassani** [comment]
Is not implemented (compiled 5 minutes ago).
Please reopen the thread. There are no options for adjust the timing...
![img_0116](https://cloud.githubusercontent.com/assets/11095490/23094862/53d587aa-f5df-11e6-8b7e-700ceecd172e.PNG)
![img_0117](https://cloud.githubusercontent.com/assets/11095490/23094863/542166ca-f5df-11e6-8646-b9b3a3a6b5eb.PNG)
