### ISSUE TITLE
Error compiling 3.1 version

### ISSUE THREAD

**Issue by ntassani** [PopcornTimeTV/PopcornTimeTV#355]
1 - Command failed due to signal: Segmentation fault: 11
2 -/Users/Nicot/Xcode/PopcornTimeTV/PopcornTimeTV/PopcornTime/Extensions/Media+Extension.swift:87:92: 'Int1' is not convertible to 'Bool'

**Comment by FlaviaBondJamesBondsHusband** [comment]
run `pod repo update; pod install`
