### ISSUE TITLE
Error compiling 3.1 version (second round)

### ISSUE THREAD

**Issue by ntassani** [PopcornTimeTV/PopcornTimeTV#356]
No please... Why you close every thread in seconds?
After run "pod repo update; pod install"
i gett:
MacBook-Pro-de-Nicolai:PopcornTimeTV Nicot$ pod repo update; pod install
Updating spec repo `angryduck2`
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C
  /Users/Nicot/.cocoapods/repos/angryduck2 fetch origin
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C
  /Users/Nicot/.cocoapods/repos/angryduck2 rev-parse --abbrev-ref HEAD
  master
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C
  /Users/Nicot/.cocoapods/repos/angryduck2 reset --hard origin/master
  HEAD is now at d8ba978 Update SRT2VTT.podspec
Updating spec repo `master`
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C
  /Users/Nicot/.cocoapods/repos/master fetch origin
  From https://github.com/CocoaPods/Specs
     09f1d62..aec3e9a  master     -> origin/master
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C
  /Users/Nicot/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C
  /Users/Nicot/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at aec3e9a [Add] Bacteria 0.5
Updating spec repo `popcorntimetv`
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C
  /Users/Nicot/.cocoapods/repos/popcorntimetv fetch origin
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C
  /Users/Nicot/.cocoapods/repos/popcorntimetv rev-parse --abbrev-ref HEAD
  master
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git -C
  /Users/Nicot/.cocoapods/repos/popcorntimetv reset --hard origin/master
  HEAD is now at 81f0b80 Update specs
Analyzing dependencies
/Users/Nicot/.cocoapods/repos/popcorntimetv/TVVLCKit/2.1.0/TVVLCKit.podspec:10: warning: duplicated key at line 10 ignored: "Rafaël Carré"
/Users/Nicot/.cocoapods/repos/popcorntimetv/TVVLCKit/2.1.0/TVVLCKit.podspec:10: warning: duplicated key at line 10 ignored: "Rafaël Carré"
Downloading dependencies
Using 1PasswordExtension (1.8.4)
Using AEXML (4.0.2)
Using Alamofire (4.2.0)
Using AlamofireImage (3.2.0)
Using AlamofireNetworkActivityIndicator (2.1.0)
Using AlamofireXMLRPC (2.1.0)
Using FloatRatingView (2.0)
Using GCDWebServer (3.3.3)
Using Locksmith (3.0.0)
Using MBCircularProgressBar (0.3.5)
Using MobileVLCKit-unstable (3.0.0a24)
Using OBSlider (1.1.1)
Using ObjectMapper (2.2.3)
Using PopcornKit (3.2.10)
Using PopcornTorrent (1.1.5)
Using Reachability (3.2)
Using Reflection (0.14.3)
Using SRT2VTT (1.0.1)
Using SwiftKVC (3.0.1)
Using SwiftyJSON (3.1.4)
Using SwiftyTimer (2.0.0)
Using TVMLKitchen (1.0.1)
Using TVVLCKit (2.1.0)
Using XCDYouTubeKit (2.5.4)
Using google-cast-sdk (3.3.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 17 dependencies from the Podfile and 25 total pods installed.

But i have 2 errors:
1 - Command failed due to signal: Segmentation fault: 11
2 -/Users/Nicot/Xcode/PopcornTimeTV/PopcornTimeTV/PopcornTime/Extensions/Media+Extension.swift:87:92: 'Int1' is not convertible to 'Bool'

**Comment by FlaviaBondJamesBondsHusband** [comment]
I closed the issue because in your previous two issues you had not compiled master, even when you were convinced you had, so I just assumed you were doing something incorrect again and it seems I was correct. I have just re-cloned and re-installed all the dependencies on a fresh build and everything is compiling. The issue is with you. If you don't have the competency to compile master, please use the install script. 

Have a nice day

**Comment by ntassani** [comment]
Wow!!! Lady!!! Sorry for consult... And good luck! You will need luck in the real world :)

**Comment by tvOSPopcorn** [comment]
@ntassani I'm sorry but this is a community run project, myself and the team contribute our free time to such project. We do not get paid!! Without us the iOS & Apple TV application would ceased to exist, so could you be a bit greatful just like everybody else who uses this application and appreciate our work.
