### ISSUE TITLE
A way to get better suggestions/Helping out

### ISSUE THREAD

**Issue by mitral** [PopcornTimeTV/PopcornTimeTV#357]
Hi there
I wish there was a better way that PT can give suggestions based n what you've watched . say after you've watched a certain genre of shows, it can create a personal suggested category. can that be implemented at some point on the TV?

Also how can I help out more with PT development ? I'd love to get involved more

**Comment by ntassani** [comment]
With Flavia is impossible. She have the poor version of popcorntime (compared to the all others systems) and she really haven't humility. If any consult anything she assume your aparented "superiority of knowledge" and pum! Coment closed... in the majority of the cases without any help/solution.
Simply see the 140 closed comment and take your conclusions...

**Comment by FlaviaBondJamesBondsHusband** [comment]
> I wish there was a better way that PT can give suggestions based n what you've watched . say after you've watched a certain genre of shows, it can create a personal suggested category. can that be implemented at some point on the TV?

Unfortunately we are not in the situation to create a recommendation/suggestions engine.

> Also how can I help out more with PT development ? I'd love to get involved more

You can start by looking at the open issues with the **enhancement** label on them and submitting PR's.
