### ISSUE TITLE
Slow Speed

### ISSUE THREAD

**Issue by PingedBug92** [PopcornTimeTV/PopcornTimeTV#358]
Why the downloading speed on iOS and TvOS version is so slow? While on PC is much faster.

**Comment by vbmota** [comment]
Man, its all about a new platform. if you read the issues, the compilation, the sources and too many other codes are different from the pc software. Its an indie soft without any pay. And on pc you dont have all Apple Mobile stuff.

**Comment by FlaviaBondJamesBondsHusband** [comment]
@vbmota Exactly, thanks
