### ISSUE TITLE
Theme Song playback 

### ISSUE THREAD

**Issue by sweetw0r** [PopcornTimeTV/PopcornTimeTV#359]
Music could continue playing while the video processing and preloading till the playback starts

**Comment by FlaviaBondJamesBondsHusband** [comment]
What version number are you running?

**Comment by sweetw0r** [comment]
3.0.0

**Comment by FlaviaBondJamesBondsHusband** [comment]
We're completely rewriting the app so we hope to fix your issue in the process. For now ill merge it with #337

**Comment by sweetw0r** [comment]
Complete rewriting is cool. Please just don't throw the old version away at once after new release. People accustomed to it. It will take some time...
