### ISSUE TITLE
Freezing ~2 minutes into video

### ISSUE THREAD

**Issue by 11plustwo** [PopcornTimeTV/PopcornTimeTV#360]
I consistently experience freezes (video stops, the app itself is not frozen) 1 to 2 minutes into movies. I've experienced it with "Suicide Squad," "Doctor Strange," and "Arrival." Played each movie using the default 720p definition on wifi. I at first thought it was a buffering issue so I would pause the video as soon as it started and would wait for several minutes before unpausing, but still experienced freezes. I then noticed that I could scrub past the frozen point and the video played fine, so I don't think it's a buffering issue. After the initial freeze, the rest of the video plays fine.

iPhone 7, iOS 10.2.1
PopcornTime version: 3.0.0

**Comment by tvOSPopcorn** [comment]
#299
