### ISSUE TITLE
Arabic Subtitle

### ISSUE THREAD

**Issue by almoghrabia1** [PopcornTimeTV/PopcornTimeTV#361]
Greetings,

I am facing an issue in arabic subtitle it becomes as symbols such as " %$^$  $%^^& " in the most of the movies. Is there a way to fix this issue.

Regards,
Silver

**Comment by moh0sw1** [comment]
@almoghrabia1 change the subtitle encoding from the settings to (Windows 1256) and it should work fine!

**Comment by FlaviaBondJamesBondsHusband** [comment]
@moh0sw1 Thanks moh0sw!
