### ISSUE TITLE
AirPlay audio delay + Manual audio delay not working

### ISSUE THREAD

**Issue by MatthieuTnsc** [PopcornTimeTV/PopcornTimeTV#367]
I have an audio delay (nearly 3 seconds) when using AirPlay speaker with PopcornTV (I don't have any delay with other video/streaming apps with AirPlay speaker).

Is there any plan to fix it?

FYI. The option to manually delay the audio is not working.

**Comment by FlaviaBondJamesBondsHusband** [comment]
What version number are you using?

**Comment by MatthieuTnsc** [comment]
Using Apple TV platform. Issue encountered with version 3.1 latest commit e6e59917328783bba7df975d1f638e3d3977d4e4

**Comment by FlaviaBondJamesBondsHusband** [comment]
The whole audio panel needs to be rewritten as the majority of it doesn't work. I shall merge this issue with #289
