### ISSUE TITLE
Are the subtitles gone?

### ISSUE THREAD

**Issue by PingedBug92** [PopcornTimeTV/PopcornTimeTV#368]
In every Movie or TV Show the subtitles are unavailable.

**Comment by delut** [comment]
Last night open subtitles was down. Maybe that was the issue?

**Comment by tvOSPopcorn** [comment]
Yeah that would've been the issue, not an issue related to our app.

**Comment by gustavolessadublin** [comment]
For me it's still unavailable.

**Comment by PingedBug92** [comment]
For me too.
