### ISSUE TITLE
CocoaPods was not able to update the `master` repo

### ISSUE THREAD

**Issue by mitcheble** [PopcornTimeTV/PopcornTimeTV#37]
I keep getting this issue when installing. I have tried uninstalling and re-installing cocoapods a few times now and keep getting the same thing. This is the error:

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

**Comment by FlaviaBondJamesBondsHusband** [comment]
Unfortunately we can do nothing about this. This is either an issue with your internet connection or the Cocoapods master repo. Try posting on [stackoverflow](http://stackoverflow.com/) or making an issue [here](https://github.com/CocoaPods/CocoaPods/issues).
