### ISSUE TITLE
Error 403 in all movies/series

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#372]
I can't see anything after the last update.

I've got this error:

## Unknown Error
Uh Oh! An unknown error has occurred (Response status code was unacceptableL 403.). Please try again

![whatsapp image 2017-03-01 at 00 09 40](https://cloud.githubusercontent.com/assets/1735944/23444368/6d3196e4-fe13-11e6-8e96-edf3c3a3c947.jpeg)

**Comment by CavalcanteLeo** [comment]
btw, occurred is misspelled (occured)

**Comment by abadejomr** [comment]
How do you solved it?  I have same problem

**Comment by CavalcanteLeo** [comment]
Fixed in master, dunno in which commit...
