### ISSUE TITLE
Crash to open a movie

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#373]
<img width="1280" alt="captura de tela 2017-03-01 as 00 37 35" src="https://cloud.githubusercontent.com/assets/1735944/23445025/5d02949a-fe17-11e6-9c0a-18945b976e1f.png">

**Comment by damiantrimboli** [comment]
The fix is choosing the right module for PreloadTorrentViewController in main.storyboard, it has none. Should have one.
