### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by stepo11** [PopcornTimeTV/PopcornTimeTV#374]
`Installing PopcornKit (3.2.14)

[!] Error installing PopcornKit
[!] /usr/bin/git clone https://github.com/PopcornTimeTV/PopcornKit.git /var/folders/r8/8pbjl9cx3bg_74wfy6_s1flc0000gn/T/d20170301-6728-8lcaju --template= --single-branch --depth 1 --branch 3.2.14

Cloning into '/var/folders/r8/8pbjl9cx3bg_74wfy6_s1flc0000gn/T/d20170301-6728-8lcaju'...
warning: Could not find remote branch 3.2.14 to clone.
fatal: Remote branch 3.2.14 not found in upstream origin
`

**Comment by FlaviaBondJamesBondsHusband** [comment]
Please use the latest version of master

**Comment by vbmota** [comment]
I am using the latest version of master and getting that error...
