### ISSUE TITLE
Trouble Archiving

### ISSUE THREAD

**Issue by love2bnice** [PopcornTimeTV/PopcornTimeTV#376]
App version: PopcorntimeTv 3.0.0
tvOS version: 10.1.1
User status: Noob

I'm getting this error in xcode when I try to archive the app:

`ld: bitcode bundle could not be generated because '/Users/Bronze/Desktop/PopcornTimeTV/Pods/PopcornTorrent/Build/tvOS/PopcornTorrent.framework/PopcornTorrent' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

help appreciated, thanks in advance.

**Comment by FlaviaBondJamesBondsHusband** [comment]
> User status: Noob

:joy: We appreciate the humour, but I'm sure you're smarter than you give yourself credit for 😄 .

Unfortunately the latest stable release does not support archiving, but master does. Here are the instructions to compile master.

1. Remove your already downloaded PopcornTimeTV folder:
`rm -rf /Users/Bronze/Desktop/PopcornTimeTV`)
2. Re-clone the repo:
`cd ~/Desktop`
`git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git`
`cd PopcornTimeTV/`
`pod repo update; pod install`
3. Open the ***.xcworkspace** project file and continue following the [Archiving Guide](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Archiving-Popcorn-Time):
`open PopcornTime.xcworkspace`

Tell me if you have any issues so we can help you through them 😄

**Comment by love2bnice** [comment]
YES! THANK YOU!!
Success \o/
I really appreciate your work and continues help.

**Comment by FlaviaBondJamesBondsHusband** [comment]
You're very welcome. However, do expect some hiccups with master as it is the latest version available, especially since we're rewriting a large portion of the UI. You can keep track of the progress here: #337
