### ISSUE TITLE
opensubtitles login error

### ISSUE THREAD

**Issue by mtwww** [PopcornTimeTV/PopcornTimeTV#378]
I see there is an existent topic about it, #182 but it was couple of months ago.
I don't know if the same problem still persist ? I just installed popcontimetv and still having same problem. i am vip user at opensubtitles

**Comment by FlaviaBondJamesBondsHusband** [comment]
The API was so bad we actually removed the feature from our app.

Also it seems the API is still down (been about 3 days since it first went down). Nothing we can do unfortunately :(

**Comment by mtwww** [comment]
so how come subtitles ? no way ?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Sorry, what I meant was we removed the ability to log into the API (that was the error title).

You can still download subtitles but they're availability is a bit 'hit or miss' due to the suckyness of their API.
