### ISSUE TITLE
Subtitle API Alt.

### ISSUE THREAD

**Issue by love2bnice** [PopcornTimeTV/PopcornTimeTV#380]
Hi,
Just saw someone suggeting using other subtitle sources, checkout the the following APIs I hope it helps to solve the issue:

https://www.programmableweb.com/category/subtitles/api

http://api.subtitleseeker.com

Best of luck!

**Comment by delut** [comment]
I'm currently working on something that drastically improves subtitle quality for movies and shows. Movies are now 100% accurate, and shows around 90%. 

I need some time for polishing but I'll submit a pull request (that will solve most subtitle related issues) soon.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Subtitle seekers API does not provide the ability to download raw subtitles, it only compiles a list of sources where a user must physically go to the site and click on the download button.

Also, https://www.programmableweb.com sucks. It's never updated and I have no idea who adds information to it but 99% of the time it's wrong. As you can see from the "date" tab, the last updated API - apart from open subtitles - was updated in 2013.
