### ISSUE TITLE
Build error: runtime is String instead of Int

### ISSUE THREAD

**Issue by 11plustwo** [PopcornTimeTV/PopcornTimeTV#381]
Is runtime supposed to be a string?
![screen shot 2017-03-02 at 6 23 50 pm](https://cloud.githubusercontent.com/assets/4984743/23533215/e1aa3234-ff75-11e6-9524-d7f796cf9e19.png)

**Comment by williamoconnorme** [comment]
This was fixed today in the latest commit.

https://github.com/PopcornTimeTV/PopcornTimeTV/commit/d9e0ec6b6c5442349509897fbde5fecc23284f15

**Comment by FlaviaBondJamesBondsHusband** [comment]
Please update your dependencies.

Run `pod repo update; pod install; pod update PopcornKit;`

**Comment by 11plustwo** [comment]
that did it, thanks
