### ISSUE TITLE
App crashes right after launch with latest commit version

### ISSUE THREAD

**Issue by hvluu** [PopcornTimeTV/PopcornTimeTV#382]
App version: 3.1
iOS/tvOS version: 10.1.1

#### Expected Behaviour

...

#### Actual Behaviour

... App launched then crashes right after

#### Steps to reproduce the behaviour

1. ...Download the lastest version ( I downloaded the zip file)
2. ...Install using Cocoapods scripts
3. ...Compile and sideload it onto ATV4
4. ...Launch the app and it'll crashe

**Comment by Dewinster** [comment]
@FlaviaBondJamesBondsHusband This build runs perfectly, no crashes found. Thank you!
