### ISSUE TITLE
"No subtitles available"

### ISSUE THREAD

**Issue by tobiasroti** [PopcornTimeTV/PopcornTimeTV#387]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by FlaviaBondJamesBondsHusband** [comment]
The issue template was created to guide you as to how much information is needed, not to leave completely empty with an equally unhelpful title. Please re-create a new issue with actual information

**Comment by tobiasroti** [comment]
Updated question now
