### ISSUE TITLE
Opensubtitles

### ISSUE THREAD

**Issue by maiiikell1995** [PopcornTimeTV/PopcornTimeTV#388]
Hi, 

Is it just me or do i miss the opensubtitles option in the lastest version both on iOS and tvOS? 

Im on the lastest 3.1 of you build and latest iOS and tvOS.

Thanks!

**Comment by maiiikell1995** [comment]
My bad i just saw you replied it go someone else that you delete the login api sorry! Thanks anyway!

**Comment by apptvgreat** [comment]
Is it possible to rebuild Moviebox iPhone ipa to work on Apple tv4

**Comment by tvOSPopcorn** [comment]
@apptvgreat No plans on writing MovieBox for Apple TV 4, we're just building popcorntime for iOS & Apple TV.

**Comment by apptvgreat** [comment]
Hello.

Thanks for your mail.

Is it possible. To rebuilt the iPhone app.
To work it Nice on a Apple tv4.

I Will try to work it on my tv4.
Is it possible. ?

I love to hear from you.

Thanks.

Verstuurd vanaf mijn IMac

Op 7 mrt. 2017 om 10:04 heeft tvOSPopcorn <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@apptvgreat<https://github.com/apptvgreat> No plans on writing MovieBox for Apple TV 4, we're just building popcorntime for iOS & Apple TV.

**Comment by tvOSPopcorn** [comment]
@apptvgreat Since non of MovieBox is open sources you'll pretty much need to build the application from scratch, good luck bc we're not doing it lol
