### ISSUE TITLE
Crash when swiping to go back and releasing Detail View Controllers

### ISSUE THREAD

**Issue by delut** [PopcornTimeTV/PopcornTimeTV#389]
#### App version:
iOS version, commit a9127c1 (latest at the time of posting).

#### Steps to reproduce the behaviour

1. Open a detail view controller from the Main View Controller (can be show detail or movie detail)
2. Use the swipe from the edge gesture to go to the Main View Controller, but instead of committing the gesture and going to the Main View Controller, let go and stay in the Detail View Controller. (The swipe from the edge its `UINavigationController interactivePopGestureRecognizer`)
3. App crashes.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for reporting, issue fixed in master.
