### ISSUE TITLE
Username for 'https://github.com'

### ISSUE THREAD

**Issue by The1PRimeYT** [PopcornTimeTV/PopcornTimeTV#39]
["-c", "pod install"]
Cloning spec repo `popcorntimetv` from `https://github.com/PopcornTimeTV/Specs.git`
Username for 'https://github.com':
What do I do Pls Help Me

**Comment by FlaviaBondJamesBondsHusband** [comment]
You do not need a username or password, a blank string for both will suffice. Because the repo doesnt exist, cocapods thinks its private and is therefore asking for username and password. If you want to stop this issue from reoccurring, type the following command into terminal:
`sudo rm -fr ~/.cocoapods/repos/popcorntimetv`

**Comment by The1PRimeYT** [comment]
it still come out what do i do

**Comment by tomsbrinkis** [comment]
Same for me, its asking for a username. WHY? it newer happened before. 

I also aded a comand that you prefered. but still nothing! 

`sudo rm -fr ~/.cocoapods/repos/popcorntimetv
Password:
Leas-MacBook:PopcornTimeTV Tom$ cd ~/Desktop/PopcornTimeTV
Leas-MacBook:PopcornTimeTV Tom$ swift install.swift
# Fetching the latest changes from github...
["-c", "git stash", "git fetch", "git rebase"]
Saved working directory and index state WIP on (no branch): 1fd615e fix install script
HEAD is now at 1fd615e fix install script

# Fetching the latest verion info...
1.0.2.1
1.0.2
1.0.1
1.0
Enter the version number: 
1.0.2.1

# Checking out tag 1.0.2.1...
["-c", "git checkout 1.0.2.1", "git pop"]
error: pathspec '1.0.2.1' did not match any file(s) known to git.
Do you have cocoapods installed? (Enter Yes or No): 
yes
Updating and installing Cocoapods...
["-c", "rm -rf ~/.cocoapods/repo/popcorntimetv"]
["-c", "pod cache clean --all"]
["-c", "rm -rf ~/Library/Developer/Xcode/DerivedData/PopcornTime-*"]
["-c", "pod install"]
Cloning spec repo `popcorntimetv` from `https://github.com/PopcornTimeTV/Specs.git`
Username for 'https://github.com': `

**Comment by tvOSPopcorn** [comment]
Issue reopened as multiple users are having this issue

**Comment by FlaviaBondJamesBondsHusband** [comment]
As answered above a blank string will suffice. 

Try removing cocoapod cache: `rm -rf /Library/Caches/CocoaPods` and then deleting Podfile.lock

**Comment by tomsbrinkis** [comment]
Still nothing.. :/ 


`Leas-MacBook:PopcornTimeTV Tom$ rm -rf /Library/Caches/CocoaPods
Leas-MacBook:PopcornTimeTV Tom$ sudo gem install cocoapods
Password:
Successfully installed cocoapods-1.0.1
Parsing documentation for cocoapods-1.0.1
1 gem installed
Leas-MacBook:PopcornTimeTV Tom$ cd ~/Desktop/PopcornTimeTV
Leas-MacBook:PopcornTimeTV Tom$ pod install
Cloning spec repo `popcorntimetv` from `https://github.com/PopcornTimeTV/Specs.git`
Username for 'https://github.com':`

**Comment by ynnad696** [comment]
same here


1.0.3
1.0.2.1
1.0.2
1.0.1
1.0
Enter the version number: 
1.0.3

# Checking out tag 1.0.3...
["-c", "git checkout 1.0.3", "git pop"]
error: pathspec '1.0.3' did not match any file(s) known to git.
Do you have cocoapods installed? (Enter Yes or No): 
yes
Updating and installing Cocoapods...
["-c", "rm -rf ~/.cocoapods/repos/PopcornTimeTV"]
["-c", "rm -rf Podfile.lock"]
["-c", "pod cache clean --all"]
["-c", "rm -rf ~/Library/Developer/Xcode/DerivedData/PopcornTime-*"]
["-c", "pod setup;pod repo update"]
Setting up CocoaPods master repo
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     a95465b..0b4f3a0  master     -> origin/master
  Updating a95465b..0b4f3a0
  Fast-forward
   Specs/BrainCloud/3.0.0/BrainCloud.podspec.json | 40 ++++++++++++++++++++++++++
   1 file changed, 40 insertions(+)
   create mode 100644 Specs/BrainCloud/3.0.0/BrainCloud.podspec.json
Setup completed
Updating spec repo `master`
["-c", "pod install"]
Cloning spec repo `popcorntimetv` from `https://github.com/PopcornTimeTV/Specs.git`
Username for 'https://github.com':

**Comment by maitremiju** [comment]
I still get the issue... I reinstalled Cocoapods, clean cache, try blank entry and it stays stuck at 

> Username for 'https://github.com':

**Comment by maitremiju** [comment]
I managed to fix it with:

> sudo rm -fr ~/.cocoapods/repos/popcornmaster

**Comment by tomsbrinkis** [comment]
@maitremiju please explain step by step how did you manage to resolve this? 

because sudo rm -fr ~/.cocoapods/repos/popcornmaster did not helped me. :/

**Comment by maitremiju** [comment]
Hello,

It kept blocking (asking for username) right after the line:
> Updating spec repo `popcornmaster`

FlaviaBondJamesBondsHusband advised
> sudo rm -fr ~/.cocoapods/repos/popcorntimetv

But it didn't work for me as popcornmaster was the one causing problem.
So I started over, fetch the folder with 
> git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git

Then I typed
> sudo rm -fr ~/.cocoapods/repos/popcornmaster 

Then install.swift and everything worked.

Keep me posted

JuMi

**Comment by tomsbrinkis** [comment]
@maitremiju big thanks! i tried and it worked just fine! ;)

**Comment by pbo1976** [comment]
I am not sure about the steps to follow. Can someone PLEASE explain it step by step... I manage to successfully build 1.0..., but nothing above that. THnx!
