### ISSUE TITLE
App Icon & Top Shelf Banner Design

### ISSUE THREAD

**Issue by DhruveShah** [PopcornTimeTV/PopcornTimeTV#390]
App version:
tvOS 3.0.0

Is it possible to use a fallback image for Top Shelf for when the App has been placed in a folder as it currently only shows 3 dots on the Top Shelf when this is the case as can be seen in the screenshot below

![simulator screen shot 5 mar 2017 22 51 29](https://cloud.githubusercontent.com/assets/6872426/23591792/6041d2a0-01f6-11e7-94e4-0f31728d0e72.png)

**Comment by tvOSPopcorn** [comment]
Something I have planned along with redoing the application icon whenever I get some free time.

**Comment by williamoconnorme** [comment]
Are you looking for a tvOS icon similar to the iOS app icon?

**Comment by tvOSPopcorn** [comment]
@williamoconnorme  Yeah, something alone those lines we want everything to be consistent and the current app icon just doesn't do that.

**Comment by williamoconnorme** [comment]
@tvOSPopcorn Had some time to do one today. If this is alright I'll submit a PR

![screen shot 2017-03-07 at 22 56 38](https://cloud.githubusercontent.com/assets/978081/23681990/6077b160-0389-11e7-8c4d-4c577716d991.png)

![popicongif](https://cloud.githubusercontent.com/assets/978081/23682414/98f9033e-038b-11e7-93a9-bca5d409c85b.gif)

**Comment by MatthieuTnsc** [comment]
Proposal for the background. I'm using it on myApple TV and it fits well beside other apps.

![capture d ecran 2017-03-11 a 07 50 06](https://cloud.githubusercontent.com/assets/7557079/23821332/6467e13e-062f-11e7-96ae-ab684f16641e.png)

**Comment by maiiikell1995** [comment]
@williamoconnorme could you share that app icon somehow with instructions how to do it? Or just a instruction how to do it? Im a noob with this so please help a brother out😁

**Comment by williamoconnorme** [comment]
@maiiikell1995 Here is a fork of the project (3.1.0) with the tvOS app icons https://github.com/williamoconnorme/PopcornTimeTV/tree/tvOSicons.

Just clone the repo, run pod install on the directory, sign the application and build. A PR has already been submitted for this.

**Comment by maiiikell1995** [comment]
Great work! Thank you soo much!
