### ISSUE TITLE
Building error with the latest master

### ISSUE THREAD

**Issue by hvluu** [PopcornTimeTV/PopcornTimeTV#392]
Can't build with the latest master. Screenshot is the error
<img width="1280" alt="screen shot 2017-03-06 at 17 48 03" src="https://cloud.githubusercontent.com/assets/24471628/23638230/270383ae-0295-11e7-895f-43266c31f3d5.png">

**Comment by itsyaboy** [comment]
It's builds for me the issue I'm getting is when I get to the part where I Right click on the .xcarchive file and choose: "Show Package Contents". When I drop PopcornTime into iTunes apps library I get this error ' A provisioning profile named "embededded.mobileprovison" already exists on this computer. Do you want to replace it?' I read somewhere to add "Application Needs IPhone Enviorment" to the info.plist and this works as far as getting iTunes to add the IPA but the IPA won't install I get an error when I try, am I doing something wrong ?

**Comment by tvOSPopcorn** [comment]
@itsyaboy Please create a separate issue, follow the guide on the [WIKI](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Archiving-Popcorn-Time) if you're still having issues create a new issue please

**Comment by tvOSPopcorn** [comment]
Fixed in master.
