### ISSUE TITLE
embededded.mobileprovison Error 

### ISSUE THREAD

**Issue by itsyaboy** [PopcornTimeTV/PopcornTimeTV#394]
App version: 3.1
iOS/tvOS version: 10.0

I'm getting this when I get to the part where I Right click on the .xcarchive file and choose: "Show Package Contents". When I drop PopcornTime into iTunes apps library I get this error ' A provisioning profile named "embededded.mobileprovison" already exists on this computer. Do you want to replace it?' I read somewhere to add "Application Needs IPhone Enviorment" to the info.plist and this works as far as getting iTunes to add the IPA but the IPA won't install, I get an error when I try installing. Am I doing something wrong ? I followed the building tut to the T so I don't know why I'm getting this error

**Comment by itsyaboy** [comment]
Also would like to know if there's a forum for this somewhere I can ask any other questions I may have

**Comment by tvOSPopcorn** [comment]
@itsyaboy [PopcornTime Reddit](https://www.reddit.com/r/PopCornTime/) is your best place

**Comment by itsyaboy** [comment]
Yea that wiki guide is the one I followed, and I'm getting  "A provisioning profile named "embededded.mobileprovison" already exists on this computer. Do you want to replace it?" When I drop popcorntime into iTunes

**Comment by tvOSPopcorn** [comment]
Fixed in the latest commit.

**Comment by itsyaboy** [comment]
What's the latest  commit and how do I get it ?

**Comment by tvOSPopcorn** [comment]
[Download](https://github.com/PopcornTimeTV/PopcornTimeTV/archive/master.zip)

Then just follow the usual install steps

**Comment by itsyaboy** [comment]
Hmmm I think I already have the master I got it from doing this  Re-clone the repo: cd ~/Desktop git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git cd PopcornTimeTV/ pod repo update; pod install
