### ISSUE TITLE
embededded.mobileprovison Error

### ISSUE THREAD

**Issue by itsyaboy** [PopcornTimeTV/PopcornTimeTV#395]
PopcornTime 3.1 Master 

I'm getting this when I get to the part where I Right click on the .xcarchive file and choose: "Show Package Contents". When I drop PopcornTime into iTunes apps library I get this error ' A provisioning profile named "embededded.mobileprovison" already exists on this computer. Do you want to replace it?' I read somewhere to add "Application Needs IPhone Enviorment" to the info.plist and this works as far as getting iTunes to add the IPA but the IPA won't install, I get an error when I try installing. Am I doing something wrong ? I followed the building tut to the T so I don't know why I'm getting this error

**Comment by itsyaboy** [comment]
i reopen because i already had the master copy of popcorn time 3.1 which i got following those steps below so the issue I'm having is with 3.1 master copy 

"1. Remove your already downloaded PopcornTimeTV folder: rm -rf /Users/Bronze/Desktop/PopcornTimeTV) Alternatively you can drag the folder to the trash icon.
2. Re-clone the repo: cd ~/Desktop git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git cd PopcornTimeTV/ pod repo update; pod install
3. Open the *.xcworkspace project file and continue following the Archiving Guide: open PopcornTime.xcworkspace"

**Comment by tvOSPopcorn** [comment]
@itsyaboy Okay I've figured out where you're going wrong, I was able to reproduce your error.

> <img width="751" alt="screen shot 2017-03-07 at 22 00 46" src="https://cloud.githubusercontent.com/assets/20913312/23680039/b90778fe-0381-11e7-8dbe-20181e86347f.png">

This is the vital step you're missing, you're dragging the 
**Popcorn Time 07-03-2017, 21.53.xcarchive** into iTunes which is incorrect and throws the error you're getting.

You need to right click on **Popcorn Time(date & time archived).xcarchive**
2) Show Package Contents
3) Navigate to Products > Applications until you find the following

> <img width="321" alt="screen shot 2017-03-07 at 22 04 45" src="https://cloud.githubusercontent.com/assets/20913312/23680161/1a0fc93a-0382-11e7-88c2-b0cb64cd9770.png">

This is what you should drag into iTunes then you can continue with the article on the Wiki

**Comment by itsyaboy** [comment]
Yea that's exactly what I did I opened  by right clicking and show package contents products / applications then I drag and drop PopcornTime, I even tried setting it on my desktop before dropping let me get on my Mac so I can take a picture

**Comment by itsyaboy** [comment]
Only when I do this it works but then the IPA won't install 

http://stackoverflow.com/questions/3211727/error-when-importing-ad-hoc-distribution-of-iphone-app-into-itunes

**Comment by itsyaboy** [comment]
![pasted image 0](https://cloud.githubusercontent.com/assets/24837094/23681543/58e73d3e-035d-11e7-91e6-cded82db7f08.jpeg)

**Comment by itsyaboy** [comment]
I'm gonna try one more time starting everything from scratch if it doesn't work again  I'll chalk it up to some type of bug with my Mac it's about time I do a fresh install n e way, in order for me to even get cocoapods to work I had to run a homebrew

**Comment by itsyaboy** [comment]
ok so it worked this time last time i changed deployment target to tvos10 not sure if it was that or the copy u gave me that made it work but i doubt it was the copy since i had the master copy also
