### ISSUE TITLE
tvOS 9.0 crash

### ISSUE THREAD

**Issue by misswhitetiger** [PopcornTimeTV/PopcornTimeTV#396]
PCT has worked for me all the way up to this commit on tvos 9.0: https://github.com/PopcornTimeTV/PopcornTimeTV/commit/835b78989eacb29e1ceabaf25c0626ffd850891d

One of the newer commits after the noted one above is causing the app to crash back to the tvOS home screen when selecting any desired movie or tv show. Does anyone else have this issue on tvOS 9.0?

**Comment by FlaviaBondJamesBondsHusband** [comment]
We have identified the issue and are working on a fix. May I ask why are you still running tvOS 9?

**Comment by FlaviaBondJamesBondsHusband** [comment]
tvOS 9 support will be removed in the next version (3.1.0)
