### ISSUE TITLE
download speed overlaps top bar

### ISSUE THREAD

**Issue by 11plustwo** [PopcornTimeTV/PopcornTimeTV#397]
iPhone 7, iOS 10.2.1
PopcornTime version: 3.1.0

![img_0355](https://cloud.githubusercontent.com/assets/4984743/23684881/dce223a2-0366-11e7-800e-e3618a6d25c4.PNG)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue fixed in master, thanks for reporting
