### ISSUE TITLE
Build error on subtitles

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#4]
/Users/Erwin/Desktop/PopcornTimeTV/PopcornTime/VLC/SYVLCPlayerViewController.m:1541:27: No visible @interface for 'VLCMediaPlayer' declares the selector 'addPlaybackSlave:type:enforce:'

**Comment by tropicaxis** [comment]
I'm experiencing the same problem. Any fix or workaround? Is it possible to omit that part of the code for the time being?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Go into your podfile and change the line `pod 'TVVLCKit'` to `pod 'TVVLCKit-unstable',  :git => 'https://github.com/popcornMaster/VLCKit.git'`
