### ISSUE TITLE
Crashes immediately on startup 

### ISSUE THREAD

**Issue by joostiphone** [PopcornTimeTV/PopcornTimeTV#404]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour

Startup 

#### Actual Behaviour

Crashes immediately. 

#### Steps to reproduce the behaviour

1. Start it lol. I'm on iOS 10.2 with the yalu102 jailbreak on a iPhone 6+
2. ...
3. ...

**Comment by PlasmaSoftUK** [comment]
So you mention the Jailbreak, have you tried it on a device that hasn't been messed with? I feel sorry for the developer getting lots of stupid questions like this raised each week. It works fine for me on all my devices, iPhone 6s, iPhone 7, iPad mini 3, iPad Air, Apple TV. Try the stable version, on a clean device, if you still have issues then by all means raise an issue. But complaining something doesn't work on a device you have Jailbroken seems a bit lame to me.

Plasma

**Comment by joostiphone** [comment]
What the heck are you rambling about? The developer himself asked us on reddit to open a issue on github. Don't act like a complete dick and stop writing stupid comments. 

For the dev: I'm using a clean but jailbroken iPhone 6+. Not one who has been messed with.

**Comment by PlasmaSoftUK** [comment]
I'm just trying to help out the developer by answering some of the questions on here as I've seen a lot of questions this week that aren't worth the time of day. You didn't mention reddit, you didn't mention the developer asked you to raise an issue, you also didn't include any other information other than the fact your phone is jailbroken on 10.2. The information I provided shows I've managed to successfully compile and run it on multiple generations of devices, I thought I was adding constructive information to the issue ..... and you think I'm being a dick?  ¯\_(ツ)_/¯

**Comment by joostiphone** [comment]
Yea I do. It's fine that you want to help him, but it wasn't very constructive was it? 

I needed to raise my question here, that's what he said. So I did. Also, I am talking about the Cydia version, so I don't need to compile anything. Perhaps we now stop this discussIon and leave it up to the dev himself.

**Comment by PlasmaSoftUK** [comment]
You also didn't mention you were using the Cydia version either in the opening post. Had your original report included all the information you have since posted in your 2 replies, I probably wouldn't have even commented, and we wouldn't be having this conversation. So maybe a note to self to include all **relevant** information when raising issues, especially as these boards are public and anyone can join in the conversation to try and help, not just the dev who may or may not already be aware of the issue.  But yes I agree we can stop the discussion now.

**Comment by FlaviaBondJamesBondsHusband** [comment]
AppSync is required to run the project as we are not signing the binary. AppSync has not yet been updated for iOS 10. Once it is, the cydia version will work as it does on previous iOS versions. Until then you can install the project using xcode

**Comment by joostiphone** [comment]
Thanks for the reply, but that's not correct. AppSync Unified has been updated for iOS 10. So it really should be solved within the Cydia version instead of AppSyn Unified.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Karen's (the proper) [AppSyncUnified](https://cydia.angelxwind.net/?page/net.angelxwind.appsyncunified) does not yet have a stable release. When a stable version is released, the project will work
