### ISSUE TITLE
ipa only iOS need tvOS

### ISSUE THREAD

**Issue by iAYMANi** [PopcornTimeTV/PopcornTimeTV#405]

**Comment by moh0sw1** [comment]
What are you even saying?! IPA only iOS need tvOS?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Both ipas are available here: https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest

**Comment by iAYMANi** [comment]
@FlaviaBondJamesBondsHusband 
**Thank
Great Great Great job**
