### ISSUE TITLE
Error on installing .IPA with Cydia Impactor

### ISSUE THREAD

**Issue by ceuaugusto** [PopcornTimeTV/PopcornTimeTV#406]
Hi,

When I try to install the latest version (3.0.1) using the .IPA and Cydia Impactor, I get the following error:

Error!
./plist.hpp:92
_assert(plist_get_node_type(plist) == PLIST_STRING)

I'm trying to install the tvOS version, and my ATV4 OS version is 10.1.1.

What can be causing this and how do I solve it? Thanks in advance for the attention!

Cheers!

**Comment by willhseitz** [comment]
Getting the same error. I will try to recompile from scratch to see if I get the same issue.

**Comment by FlaviaBondJamesBondsHusband** [comment]
We are aware of this issue and it only occurs when archiving without codesigning (@willhseitz, you should not have the same issue when archiving from scratch). Interestingly this does not happen with the iOS version. It may take some time to debug as impactor is closed source and its error messages are far from helpful.

**Comment by ceuaugusto** [comment]
I will try installing the .ipa file through Xcode. Is the .ipa file signed or should I resign. 

Should other methods work for installing the .ipa file, like iMazing?

Tks!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Turned out it was a stupid error with the Info.plist file. 

> Is the .ipa file signed or should I resign.

No it is not signed which is why we recommend using Impactor
