### ISSUE TITLE
“PopcornTime” can only be installed on Unknown Device (3).

### ISSUE THREAD

**Issue by chandlervdw** [PopcornTimeTV/PopcornTimeTV#407]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour
Compile and install on my device.

#### Actual Behaviour
I get this error: `“PopcornTime” cannot be installed on iPhone. “PopcornTime” can only be installed on Unknown Device (3).`

#### Steps to reproduce the behaviour

Normal installation, either by `swift install.swfit` or by normal XCode compilation.

**Comment by FuzzyNutz** [comment]
Download the .ipa from releses and install with Cydia impactor

**Comment by chandlervdw** [comment]
My iPhone 7 is not jailbroken. I was able to install 3.0.0 via XCode and my Apple Developer Account. Is that no longer possible?

**Comment by FlaviaBondJamesBondsHusband** [comment]
@chandlervdw why wouldn't that be possible?

**Comment by chandlervdw** [comment]
@FlaviaBondJamesBondsHusband I don’t know, that's why I posted the error I got.

Sideloading 3.0.0 on my ATV worked fine...
