### ISSUE TITLE
Stops for buffering but doesn't resume

### ISSUE THREAD

**Issue by technosid77** [PopcornTimeTV/PopcornTimeTV#408]
I am using the latest 3.1.0 on iphone 6s 64gb iOS 10.2.1. As i start watching an episode, the player starts buffering at 5sec and then doesn't resume, even if use the scrubber to rewind and play. The net speed is fast enough for the video to load in a single go but still it stops. If i play an old episode, it works perfectly fine. This problem is only for new episodes. Please help. I used the ipa that you provided and installed it using cydia impactor.

**Comment by FlaviaBondJamesBondsHusband** [comment]
https://www.lifewire.com/how-torrent-downloading-works-2483513

**Comment by technosid77** [comment]
This problem occurs everyday. Please help!!

**Comment by technosid77** [comment]
https://www.dropbox.com/s/1u1lkqkwm2jbuul/Photo%2012-03-17%2C%2010%2041%2007%20PM.png?dl=0

**Comment by technosid77** [comment]
While it is stuck it this position, my data is still being used.

**Comment by technosid77** [comment]
https://www.dropbox.com/s/6g42bcxqutl0y6g/Photo%2012-03-17%2C%2011%2008%2008%20PM.png?dl=0
This is the usual speed that i get. Which i suppose is enough for 480p bufferless play.

**Comment by FuzzyNutz** [comment]
Guys this may be your internet speed I have the same problem what I do is just pause it right when it loads up and leave it paused for at least 3-5 mins

**Comment by technosid77** [comment]
![img_2636](https://cloud.githubusercontent.com/assets/24605583/23835856/8c62ebe6-0794-11e7-93fe-a291078caf0d.PNG)
I paused the video when it started and waited for 3 mins. As you can see in the image that the video has sufficiently loaded. But still the video stopped at 5 secs. Please solve this issue.
You can try watching this video on your iOS device. It is flash season 3 episode 15.

**Comment by technosid77** [comment]
I even noticed this thing in every movie/show that if the video starts buffering, then it freezes. Even if i wait for a long time, then too the video doesn't play, although its downloading and my data is being used.

**Comment by technosid77** [comment]
#299 i got it, but is there no way to solve the issue?

**Comment by technosid77** [comment]
Because its a lot irritating.

**Comment by technosid77** [comment]
@FlaviaBondJamesBondsHusband
