### ISSUE TITLE
 PopcornTime 3.1 crashes 

### ISSUE THREAD

**Issue by FuzzyNutz** [PopcornTimeTV/PopcornTimeTV#411]
App version: 3.1 copy provided here in releases 
 iOS iPhone 7 10.1.1

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour

...play movie/show 

#### Actual Behaviour

...app crashes 

#### Steps to reproduce the behaviour

1. ...press play 
2. ...wait for it to load and it crashes crashes right before  show or movie starts 

Also is there anyway to upload videos so I can prove this ?

**Comment by FlaviaBondJamesBondsHusband** [comment]
What movie have you tried? Saying "play movie/show" is not helpful as all the movies and shows i've tried are working

**Comment by FuzzyNutz** [comment]
Any movie or show I'm about to upload a video now sorry had to use my Mac to record it

**Comment by FuzzyNutz** [comment]
its actually closing out before the load now but yeah thats what happens 
https://youtu.be/vqispJgbPg4
https://youtu.be/0VvXzQuWtJY

**Comment by FuzzyNutz** [comment]
Ok so strangest thing it seems to be working when on wifi but when on let cellular data it crashes I'm on T-Mobile if that helps

**Comment by FuzzyNutz** [comment]
Has Anybody replicated this ?

**Comment by wahyuhp** [comment]
Installed on iPad Air 2 (jailbroken) 10.2, crash before movie start

**Comment by FuzzyNutz** [comment]
Are u using the .IPA provided here and are you using wifi or data ?

**Comment by wahyuhp** [comment]
using .IPA and use the wifi

**Comment by FlaviaBondJamesBondsHusband** [comment]
@FuzzyNutz can you, or someone else, run the app from xcode and reproduce this bug and screenshot the stacktrace?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue is now fixed in master
