### ISSUE TITLE
The file "/Users/vini/Desktop/PopcornTimeTV-master/PopcornTime/Supporting Files/PopcornTime.entitlements" could not be opened.

### ISSUE THREAD

**Issue by vbmota** [PopcornTimeTV/PopcornTimeTV#412]
App version: 3.1
iOS/tvOS version: 10.1.1

Make sure these boxes are checked before submitting your issue - thanks!

- [x ] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [ x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour
Xcode build
...

#### Actual Behaviour
**The file "/Users/vini/Desktop/PopcornTimeTV-master/PopcornTime/Supporting Files/PopcornTime.entitlements" could not be opened.**

...

#### Steps to reproduce the behaviour

1. ... pod repo update; git etc.
2. ... cd popcorn
3. ... pod install or swift install.swift

**Comment by vbmota** [comment]
MacOS Sierra with case sensitive apfs ssd.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Don't know what to tell you. If master is compiling for us and for [travis](https://travis-ci.org/PopcornTimeTV/PopcornTimeTV/builds/210237657) the problem is on your end. Anyway, compiling is no longer necessary. Use the provided .ipas here: https://github.com/PopcornTimeTV/PopcornTimeTV/releases/tag/3.1.0.

**Comment by vbmota** [comment]
Thank you so much!
