### ISSUE TITLE
Increase subtitle delay

### ISSUE THREAD

**Issue by akaFTS** [PopcornTimeTV/PopcornTimeTV#413]
Currently there's an option to set subtitle delay to a maximum of -10s or +10s. However, some subtitles are really badly synced. Would it be possible to increase that maximum to 20 ou 30 seconds maybe?

**Comment by FlaviaBondJamesBondsHusband** [comment]
We have changed the limit from -10...10 to -60...60 on iOS only. tvOS shall stay from -5...5 as having -60...60 on the current tvOS ui would be horrible UX. Thanks for your suggestion, enjoy!

**Comment by superdoctor1** [comment]
hello
