### ISSUE TITLE
App not installing using cydia impactor

### ISSUE THREAD

**Issue by eldegos** [PopcornTimeTV/PopcornTimeTV#414]
App version: 3.1.0
iOS/tvOS version: Apple TV 4 running tvOS 10.1.1

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour
App installing as normal using cydia impactor v.0.9.40 (IPA file downloaded right from this github page)

#### Actual Behaviour
Show an error saying: 
Plist.hpp:92 
_assert(plist_get_node_type(plist) == PLIST_STRING

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

I want to add that it might be a problem with cydia impactor (though I'm not sure). Sorry if this is not a problem with the application, I have never coded anything and I don't know what this is, but any kind fellow could help me with this would be wonderful. Thanks in advance!

**Comment by eldegos** [comment]
Tried updating to tvOS 10.2 beta 5 and the same thing happens

**Comment by FlaviaBondJamesBondsHusband** [comment]
This issue was already resolved: #406. Are you sure you have the latest binary? Could you try downloading it again from here: https://github.com/PopcornTimeTV/PopcornTimeTV/releases

> Tried updating to tvOS 10.2 beta 5 and the same thing happens

We haven't yet tested/built the app for tvOS 10.2. This is intended to run on tvOS 10 through 10.1.1 (? - whatever the latest stable tvOS release is).

**Comment by eldegos** [comment]
Oh, sorry for asking then, anyways great job on the app!

**Comment by FlaviaBondJamesBondsHusband** [comment]
@eldegos Is your issue solved? If it's not I shall keep the issue open until it is

**Comment by eldegos** [comment]
Yes, my issue is resolved. Thank you for the help and I'm sorry that I didn't see issue #406. Keep up the good work on the app!

**Comment by FlaviaBondJamesBondsHusband** [comment]
No problem, glad to help :)
