### ISSUE TITLE
problem Arabic subtitles in movies - APPLETV

### ISSUE THREAD

**Issue by ADMNTK** [PopcornTimeTV/PopcornTimeTV#416]
Hi

The translation of the Arabic language, in some movies there are some movies disappear after about 20 minutes, please put the option to translate the manual, best user.

Version popcorn time: 3.1.0

Version Apple tv:  10.1

help me .

Thank YOU

**Comment by ADMNTK** [comment]
help me

**Comment by FlaviaBondJamesBondsHusband** [comment]
Subtitles are handled by VLCKit. Please create an issue on their [GitLab](https://code.videolan.org/videolan/VLCKit/issues)

**Comment by ADMNTK** [comment]
Created a topic, unfortunately, there is no response by the staff


Help me
