### ISSUE TITLE
Its a shame......

### ISSUE THREAD

**Issue by loneyliver** [PopcornTimeTV/PopcornTimeTV#418]

**Comment by FuzzyNutz** [comment]
Vlckit ? What's that?

**Comment by technosid77** [comment]
Really the VLCkit thing gets irritating at times. I hope that these brilliant developers would soon find a solution. Hope so!!

**Comment by technosid77** [comment]
@FuzzyNutz refer to #299

**Comment by FuzzyNutz** [comment]
Oh I see... well all I do is just pause for about a min or less and it works fine but that's only when the movies or shows freeze but for the most part everything has been playing pretty smoothly on my Apple TV.

Also I would like to thank the dev for this app, you really knocked it out of the park with this 3.1 update everything is working gr8 😄 I really enjoy it!!

**Comment by FlaviaBondJamesBondsHusband** [comment]
This is not a forum
