### ISSUE TITLE
Swift compiler error: Assigning a property to itself

### ISSUE THREAD

**Issue by se99jmk** [PopcornTimeTV/PopcornTimeTV#419]
App version: 3.1
iOS/tvOS version: iOS 10.3 (beta)

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour

App compiles successfully 

#### Actual Behaviour

Fails to build
MonogramCollectionViewCell.swift:27:27: Assigning a property to itself

#### Steps to reproduce the behaviour

1. Attempt to build to device
![screen shot 2017-03-16 at 12 41 59](https://cloud.githubusercontent.com/assets/26460488/23996705/496273b6-0a46-11e7-8ad9-ecba7f073799.png)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Building for/on Beta versions of iOS/Xcode is not supported

**Comment by dmytrokoren** [comment]
I am having exactly the same issue with tvOS 10.2.
Xcode is all updated, mac os updated. I did git clone yesterday of the new master. Came upon this issue?
