### ISSUE TITLE
Build issue unknown header PopcornKit.h

### ISSUE THREAD

**Issue by litengulfisk** [PopcornTimeTV/PopcornTimeTV#42]
I'm getting this when building. Have tried with both 0.4.0 and 0.4.1

`Umbrella header for module 'PopcornKit' does not include header 'PopcornKit.h'`

Then just the error:
App installation failed
This app contains an app extension with an illegal bundle identifier. App extension bundle identifiers must have a prefix consisting of their containing application's bundle identifier followed by a '.'.

**Comment by buzzel** [comment]
Make sure you run `pod install` If it still fails, uninstall your version of cocoapods and install the bets `gem install cocoapods --pre`
