### ISSUE TITLE
Feature suggestion: Search by Year

### ISSUE THREAD

**Issue by Beorn1988** [PopcornTimeTV/PopcornTimeTV#42]
Well I don't know what others might feel about this so I'm posting to see if others as myself might have thought about it...
Popular movies might not always be new for example. And recent movies is more exactly "recently added"

**Comment by tvOSPopcorn** [comment]
Something I've been wanting to implement for a while now, It's just the whole UI side of things that needs to be worked out but i'll add it to my To-Do list 😄

**Comment by chocolatesuper** [comment]
@Hackormahn  when aver project goes a stable version appdb.cc ipa 2016 without errors

**Comment by chocolatesuper** [comment]
@Hackormahn when aver project goes a stable version appdb.cc ipa 2016 without errors version 1.0.3.1
