### ISSUE TITLE
"No subtitles available"

### ISSUE THREAD

**Issue by tobiasroti** [PopcornTimeTV/PopcornTimeTV#420]
App version:
tvOS

#### Expected Behaviour
 show subtitles in the movies that the pc version have subtitles
...

#### Actual Behaviour

Some times it's says "no subtitles available" when is should be. It's available sometimes and restarting the app seems to fix the problem occasionally. The subtitles are also often out of sync.
...

#### Steps to reproduce the behaviour

1. Open the app and go to a random movie. Sometimes it work, sometimes it doesn't 

I'm pretty certain that I have the latest version. I run the swift.install command several times and pull from the master repoistory

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issues regarding subtitle availability are out of our control as we pull subtitles from the awful OpenSubtitles API

**Comment by tobiasroti** [comment]
Ok. However, that I have to restart the app for the subtitles to work sometimes is surely something that could me fixed in the app and not the subtitles API. Is there a possibility to use another API? For example the same as popcorn time for the PC uses?
