### ISSUE TITLE
Trouble getting pod pod repo update; pod install

### ISSUE THREAD

**Issue by GIthHub2die4** [PopcornTimeTV/PopcornTimeTV#422]
App version:
iOS Master branch:

#### Expected Behaviour

able to clone master and open the project using PopcornTime.xcworkspace

#### Actual Behaviour

Clones the master, but no PopcornTime.xcworkspace present in the folder, then followed the following steps;
cd ~/Desktop
git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git
cd PopcornTimeTV/
pod repo update; pod install

and i keep getting following error;

Cloning into 'PopcornTimeTV'...
remote: Counting objects: 3291, done.
remote: Compressing objects: 100% (234/234), done.
remote: Total 3291 (delta 84), reused 9 (delta 9), pack-reused 3048
Receiving objects: 100% (3291/3291), 7.72 MiB | 360.00 KiB/s, done.
Resolving deltas: 100% (1910/1910), done.
MacBook-Air:Desktop brunomedeiros$ cd PopcornTimeTV/
MacBook-Air:PopcornTimeTV brunomedeiros$ pod repo update; pod install
fatal: Not a git repository (or any of the parent directories): .git
Updating spec repo `popcorntimetv`
  $ /usr/bin/git -C /Users/brunomedeiros/.cocoapods/repos/popcorntimetv fetch
  origin
  $ /usr/bin/git -C /Users/brunomedeiros/.cocoapods/repos/popcorntimetv
  rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/brunomedeiros/.cocoapods/repos/popcorntimetv reset
  --hard origin/master
  HEAD is now at e2bdd00 Remove spec
Setting up CocoaPods master repo
fatal: Not a git repository (or any of the parent directories): .git
**[!] Unable to add a source with url `https://github.com/CocoaPods/Specs` named `master-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
MacBook-Air:PopcornTimeTV brunomedeiros$**

**Comment by FuzzyNutz** [comment]
No need to build anymore just download the .ipa from here https://github.com/PopcornTimeTV/PopcornTimeTV/releases

But most likely you don't have cocoapods installed run this to install "sudo gem install cocoapods"
Minus the quotes, if it does not install you might need to do a fresh install of macOS Sierra theirs some issues when upgrading from el capi or Yosemite

**Comment by FlaviaBondJamesBondsHusband** [comment]
Manual installing is meant for people with knowledge about iOS development. If you don't have the competence to compile master please use the provided install script or download the ipa
