### ISSUE TITLE
No download progress when pausing playback

### ISSUE THREAD

**Issue by clementbarry** [PopcornTimeTV/PopcornTimeTV#423]
App version: 3.1.0
iOS/tvOS version: tvOS 10.1.2

#### Expected Behaviour
See download bar progress even when movie is paused
#### Actual Behaviour
Download progress indicator apparently pauses when movie is paused. Download operation itself isn't paused; when resuming playback, the download progress jumps suddenly to actual position.

#### Steps to reproduce the behaviour
1. Play any movie
2. Pause: see download progress paused as well
3. Resume: see download progress jump to actual position

**Comment by FlaviaBondJamesBondsHusband** [comment]
No idea why I thought implementing it when the player time changes was a good idea. Issue is now fixed in master
