### ISSUE TITLE
High definition trailers (Enhancement)

### ISSUE THREAD

**Issue by misswhitetiger** [PopcornTimeTV/PopcornTimeTV#425]
As the title states, is it possible to prefer 720/1080p movie trailers?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Youtube removed 1080p mp4 videos (https://github.com/0xced/XCDYouTubeKit/blob/master/XCDYouTubeKit/XCDYouTubeVideo.h#L45) so we cannot fetch them.

The order of fetching right now goes: 720p, 360p, 240p
