### ISSUE TITLE
[Feature Request] VPN Support

### ISSUE THREAD

**Issue by willhseitz** [PopcornTimeTV/PopcornTimeTV#426]
I know there has been a few VPN requests in the last few months, but could this feature be revisited? I have been using a router VPN with a paid VPN service and it has worked fantastic with PopcornTime on my ATV. However Netflix is now blocking my VPN service, so I have to disable the VPN or change wireless networks to switch between Popcorntime and Netflix. 

Having a software VPN (pptp, openvpn, l2tp) in the popcorntime app would be great for paid VPN services!

**Comment by FlaviaBondJamesBondsHusband** [comment]
#339. Unfortunately, we cannot provide a paid VPN services without affiliation legality issues. We would do something similar for free services, but a single (free) service that provides fast, secure and reliable VPN connectivity throughout the entire world (we have a very geographically diverse user-base) simply does not exist. 

It is up to the user to implement their own VPN that suits them the best. We are aware that apple do not actually provide the ability to tunnel traffic through a VPN on tvOS (such a feature does exist on iOS, both supported natively and through third party clients), but something like you used have - a router based VPN, is what we would recommend.

Apologies for any inconvenience.

**Comment by willhseitz** [comment]
Sorry, I didn't mean for PopcornTime to offer a paid VPN service, but instead to act as a VPN client for OpenVPN/PPTP/L2TP/etc. Essentially, to be able to use a 3rd party VPN service by entering user/pass/host. The idea is to only use the VPN service within PopcornTime and not for the entire AppleTV.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Although it's an interesting idea, this concept does not exist on iOS or tvOS. The closest thing there is, is per-app VPN which is managed by MDMs (mobile device management - essentially installing management profiles to the user's iOS device which we cannot do for security reasons (leaking our private info etc.) and it's a paid service) and not by individual developers (us).

As stated in #339, it is up to apple to implement VPNs on tvOS, not us. There is a hidden **"Advanced Settings"** tab in the settings menu that allows you to  Load a VPN Profile so maybe apple will publicly release such a feature in tvOS 11.
