### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by Juice805** [PopcornTimeTV/PopcornTimeTV#427]
App version: 3.1.0
iOS/tvOS version: 3.1.0

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour

Run on iOS.

First: Thanks for all the teams hard work on this great project! I've compiled and installed it on all my devices (iPhone, iPad, and TV) previously and it's amazing. I've hit some OAuth errors with Trakt in the app now that I disconnected my Trakt account from Facebook, so I was hoping an update would help, however I'm hitting a snag this time with 3.1.0. 

#### Actual Behaviour

At runtime produces a SIGABRT and the the following output:

```
dyld: Library not loaded: @rpath/AEXML.framework/AEXML
  Referenced from: /private/var/containers/Bundle/Application/AC5B1DD9-5851-45A5-B444-FC284E647190/PopcornTime.app/Frameworks/PopcornKit.framework/PopcornKit
  Reason: image not found
```

#### Steps to reproduce the behaviour

1. `git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git`
2. Either `pod repo update; pod install` or use the included swift installer (Tried both)
3. Basically followed the [Noob guide](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-Popcorn-Time) as I did previously and ran the project with iPhone 7 connected

**Comment by FlaviaBondJamesBondsHusband** [comment]
Compiling the project is no longer necessary. Download the iOS **.ipa** [here](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/download/3.1.0/PopcornTimeiOS.ipa) and install using Impactor. Not sure what to do? Follow our [Installing Guide](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Installing-Popcorn-Time).

**Comment by Juice805** [comment]
I have tried that initially thinking I could save some time. I am not using a Jailbroken devices however and the transfer fails

**Comment by FlaviaBondJamesBondsHusband** [comment]
You don't need a jailbroken device

**Comment by Juice805** [comment]
My apologies. I saw Cydia in the install guide and assumed jailbreaking so I tried through iTunes. I'll try with Impactor. Thank you for the help
