### ISSUE TITLE
Picture In Picture

### ISSUE THREAD

**Issue by Juice805** [PopcornTimeTV/PopcornTimeTV#428]
I'd like to request the implementation of the [Picture In Picture feature](https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/AdoptingMultitaskingOniPad/QuickStartForPictureInPicture.html) on the iPad. It would be awesome to be able to multitask while watching movies on the large screen. Hopefully this can be put in eventually. 

Thanks for the hard work!

**Comment by FlaviaBondJamesBondsHusband** [comment]
This feature is only available when using `AVPlayer`, which we are not.
