### ISSUE TITLE
Watchlist not working on AppleTV

### ISSUE THREAD

**Issue by diogoviannaaraujo** [PopcornTimeTV/PopcornTimeTV#43]
Hi guys, on my apple tv everytime i try to add something to watchlist the app crashes and go back to home, tried to replicate that on emulator without luck. im using 0.4.1, it that bug known?

**Comment by RefusedFlow** [comment]
I believe this bug has been fixed in the latest commit.

**Comment by diogoviannaaraujo** [comment]
Ok, thank you very much. Im reading u guys code right now, hope in the future I can ask less and fix more :)

**Comment by RefusedFlow** [comment]
Not to worry! You're always welcome to submit a pull request :smile:
