### ISSUE TITLE
Unable to play anything with a resolution higher than 480p

### ISSUE THREAD

**Issue by jberglinds** [PopcornTimeTV/PopcornTimeTV#43]
Hello, 
I'm on the very latest version, commit 29, and I'm unable to watch anything with a resolution higher than 480p. I've only tried TV shows so far but I believe the same thing goes for Movies. 

After the buffering is finished and the episode is about to begin, the player freezes. It feels like the app is not powerful to decode it even though I've managed to play in 1080p on previous versions. 
I also get some occasional hiccups when playing 480p but it still manages to play.

The Apple TV output resolution is set to 1080p - 60Hz.

**Comment by popcornMaster** [comment]
I have not been able to reproduce this, please delete project and re-download! It should solve itself after installing from a fresh project!
