### ISSUE TITLE
Download option

### ISSUE THREAD

**Issue by technosid77** [PopcornTimeTV/PopcornTimeTV#431]
App version: 3.1
iOS/tvOS version: iOS 10.2.1 on iphone 6s 

Make sure these boxes are checked before submitting your issue - thanks!

- Used the ipa
- [ tick ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour
It would be great to get download option so that the movie/show can be watched later when offline.
...

#### Actual Behaviour
No download function available
...

#### Steps to reproduce the behaviour

1. ... add download funtionality.
2. ...make sure that the download progresses in background and not only when the screen is on.
3. ...the video should be available to be watched offline.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Popcorn time is not a BitTorrent client, is a media streaming client, you can use another client to download the same content.

**Comment by technosid77** [comment]
Android version of popcorn time has this option.

**Comment by technosid77** [comment]
Okay cool. 😅
