### ISSUE TITLE
Download movies offline (UI)

### ISSUE THREAD

**Issue by hejman** [PopcornTimeTV/PopcornTimeTV#432]
- [x] Implement reactive download button for iOS and tvOS like in iOS app store.
- [x] New `UIViewController` to manage downloads on iOS and tvOS.
- [x] Localise whatever strings are added in the process.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Moved issue here: https://github.com/PopcornTimeTV/PopcornTorrent/issues/3
