### ISSUE TITLE
No option to hide subtitles

### ISSUE THREAD

**Issue by tomeranaray** [PopcornTimeTV/PopcornTimeTV#434]
When playing a video with subtitles, there is no option to hide subtitles. 

If the subtitles in your language are more than 5 seconds out of sync, it would be handy to select "no subtitles" rather than having out of sync subtitles.

**Comment by FuzzyNutz** [comment]
U must have subtitles on in settings turn it off, u can always turn them on per movie / show from the swipe down option on the top of the Apple TV 4 remote

**Comment by FlaviaBondJamesBondsHusband** [comment]
Click the subtitle option again in the subtitle menu. To access subtitle menu swipe down on the siri remote

**Comment by iAYMANi** [comment]
Classic remote for Apple TV3, not working swipe down to Apple TV 4.
