### ISSUE TITLE
errors while building the app

### ISSUE THREAD

**Issue by alshizawi** [PopcornTimeTV/PopcornTimeTV#436]
Hello,

I was trying to build the app to run it on my Apple TV m it is the latest version .. 

When i reach the second step 
`cd ~/Desktop/PopcornTimeTV
swift install.swift`

it shows for me many errors .. 

at the 3rd step .. 
`cd ~/Desktop/PopcornTimeTV
pod repo update; pod install;`

it reaches to ..
`Analyzing dependencies
Pre-downloading: `AlamofireXMLRPC` from `https://github.com/PopcornTimeTV/AlamofireXMLRPC.git`
Username for 'https://github.com': 
`
and asks for the username .. 

how i can fix this problem ?

**Comment by alshizawi** [comment]
@FlaviaBondJamesBondsHusband 
Thank you .. 
It works now 👍 💯

**Comment by FlaviaBondJamesBondsHusband** [comment]
Cool, glad to help :)
