### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by technosid77** [PopcornTimeTV/PopcornTimeTV#437]
App version: 3.1
iOS/tvOS version: iOS 10.3 iPhone 6s

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour
The videos should get saved in cache and play without the need of downloading again.

#### Actual Behaviour
If i play a video again after watching it, the cache automatically gets cleared and the video downloads again.
I also want to mention that the clear cache on exit is off. I have tried both ways of not killing the app and killing the app before playing the same video again, but the result is the same.

#### Steps to reproduce the behaviour

1. Make sure the cache is reloaded when the video is played the second time

**Comment by FlaviaBondJamesBondsHusband** [comment]
Videos are downloaded to `NSTemporaryDirectory()` which is cleared automatically by the system when device space is sparse. The functionality may have changed in iOS 10.3. I would suggest clearing out other unnecessary things from your device to make more room for movies!

**Comment by techno777** [comment]
@FlaviaBondJamesBondsHusband  that didn't help. I have 6gb of storage available. But the cache still gets cleared.
