### ISSUE TITLE
Tv show constant freeze

### ISSUE THREAD

**Issue by Dumeli** [PopcornTimeTV/PopcornTimeTV#439]
App version:
tvOS version 3.1 from .ipa

Make sure these boxes are checked before submitting your issue - thanks!

- [x ] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x ] You have read the [Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md) for this repository.

#### Expected Behaviour

...Play tv shows without freezing

#### Actual Behaviour

...Any tv show ex. Into the badlands, chicago fire, chicago pd, the walking dead, they all start playing fine, but after 20-30 sec it freezes (like it does for the movies..) and it just won't play anymore from that point on

#### Steps to reproduce the behaviour

1. ...download .ipa provided on this website,
2. ...select any tv shows (list mention earlier)
3. ...play and wait a few seconds, tv show will freeze and won't play

**Comment by eldegos** [comment]
I'm pretty sure this is a problem with VLC Kit, not PopcornTime itself, just pause the films/shows for 10 seconds or so and it should work perfectly fine

**Comment by sqig** [comment]
I have been experiencing the same issue. Sometimes I can get them to play again by returning to the start. Mostly this doesnt work.
Are the ipas files updated with the master ?

**Comment by Dumeli** [comment]
The pause bypass works when it happens to movies, but tv shows I was not able to get it pass. I believe it used to work fine in previous version.

**Comment by eldegos** [comment]
The paid bypass works for me when watching shows

**Comment by techno777** [comment]
The pause bypass works only for movies and not for tv shows. Please help!!

**Comment by FlaviaBondJamesBondsHusband** [comment]
#299
