### ISSUE TITLE
Some TV Shows fails to respond

### ISSUE THREAD

**Issue by ozkrtech** [PopcornTimeTV/PopcornTimeTV#44]
Some TV Shows fail to respond to the click, and are always the same ones, i dont know if this is an api issue but there is no problem with those tv shows on the Mac or PC variants, unless they feed from somewhere else their tv shows.

Sorry if this is the wrong place to report this issue, im new to both github and this project.

**Comment by RefusedFlow** [comment]
I belief this issue was resolved in a recent PR, if you download the latest version from the repo instead of a release i belief this has been fixed as there was an error how the title's were displayed? Get back to me if you're still having this issue after cloning from the repo.
