### ISSUE TITLE
Settings page in the application is not aligned with borders (offset)

### ISSUE THREAD

**Issue by dmytrokoren** [PopcornTimeTV/PopcornTimeTV#440]
App version: 3.1.0
iOS/tvOS version: 10.2

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md) for this repository.

#### Expected Behaviour

When you go into settings the display of buttons and icons are not aligned (offset) with TV border.

#### Actual Behaviour

The settings menu should be aligned with TV borders.

#### Steps to reproduce the behaviour

1. Start popcornTimeTV
2. Go to settings
3. Once in settings you will see that the buttons, text, and icons are going behind the borders

![image](https://cloud.githubusercontent.com/assets/20926198/24569248/3702ade4-165d-11e7-8b4e-50a6e39ecee2.png)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue fixed in master

**Comment by dmytrokoren** [comment]
I fetched the new repo and the settings page is still offset. I have 2016 Lg tv 55". I'm wondering is it possible to adjust the screen like in kodi when you can adjust the corners of the screen?
