### ISSUE TITLE
Feature Request: Unified bookmarking between tvOS and iOS

### ISSUE THREAD

**Issue by eldegos** [PopcornTimeTV/PopcornTimeTV#441]
If this is not possible what so ever than that's absolutely fine, I just think this would be a nice thing to add. Example: if your away and not near your Apple TV and you find a film/show that you'd like to watch on your iOS device, you add that to your bookmarks and when you get home that's already bookmarked on your Apple TV (and vice versa).

Regardless of the possibility of this becoming a feature, great job on the app, it's absolutely amazing, keep it up!

**Comment by FlaviaBondJamesBondsHusband** [comment]
This feature already exists, just authenticate with Trakt on both devices on the Settings Tab of the app

**Comment by CavalcanteLeo** [comment]
where in the app I can connect?
