### ISSUE TITLE
popcorntime tvos 3.1.0 arabic subtitle

### ISSUE THREAD

**Issue by AIPS69** [PopcornTimeTV/PopcornTimeTV#443]
Hi,

I'm using popcorntime on Apple TV, it was downloaded online, ipa file type and installed on apple tv using the Impactor program.

when subtitle is chosen as Arabic, strange symbols are coming instead of words. I tried to change the encoding to Universal (UTF-8) but same problem is appearing and when subtitle is enabled through the setting, you can't disable it while watching the movie because there's no (off) choice to choose.

Thanks.

**Comment by Mixer2030** [comment]
Use Encoding Windows-1256

**Comment by FlaviaBondJamesBondsHusband** [comment]
> when subtitle is enabled through the setting, you can't disable it while watching the movie because there's no (off) choice to choose.

Opening the options menu while inside the player and selecting the currently selected subtitle will deselect it

Without more information about your issue, we cannot help

**Comment by AIPS69** [comment]
Thanks both of you, both ways worked perfectly.

Two more things why subtitles are always always wrong, in the previous popcorn time, subtitle offset was sometimes either ahead or late with seconds, where in this version it's always wrong in time and I can't fix it because it's more than + or - 5.
Second question is, many times the picture lags and sound continues, even if I replay or forward it remains the same unless I close the movie and play it again. Sometimes even after playing it again the video picture lags too.

Regards,
Mohammed.

**Comment by AIPS69** [comment]
Just saw the latest version, I downloaded it where it enhanced the subtitle offset. Photo freezed for a while then went back normal.
(Y)
