### ISSUE TITLE
Italian Localisation

### ISSUE THREAD

**Issue by PingedBug92** [PopcornTimeTV/PopcornTimeTV#444]
Hi, I've just completed and checked the Italian Localisation for Popcorn Time. I had to use Mega because github doesn't allow me to attach the .xliff file.

https://mega.nz/#!EQwTBCLL!PYFX7C3ZNReSSdd7dXnVP0T7Ql3GEBlUtr_ltKL5PDM

**Comment by abdullahaljedaie** [comment]
We need an email or website to send ( language.lproj )


To support multiple languages.

And we need to support awesome app for movie and TvShow .

And if you can add choose (subtitles) from (opensubtitle.org).

Thank you for this app .

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks so much for your hard work and apologies for the delay :). If there are any mistakes/things we forgot to localise please open another issue so we can fix it together :)

**Comment by FlaviaBondJamesBondsHusband** [comment]
We're getting ready for the next release and were wondering if you wouldn't mind updating your 
[Localisations](https://github.com/PopcornTimeTV/PopcornTimeTV/files/1128084/Updates.zip). The release is scheduled for next week so please have it completed for then. Thanks!

**Comment by PingedBug92** [comment]
Update ready!.

[https://mega.nz/#!YQAiHAIa!4ptwksP8za_KntkUqVde07L7wCFLdpWQdnuzRy-UDTM](url)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for your hard work. Updates have been pushed to the master branch 😃 .
