### ISSUE TITLE
 Subs after movie freezes

### ISSUE THREAD

**Issue by maiiikell1995** [PopcornTimeTV/PopcornTimeTV#447]
App version: 3.1.1
iOS/tvOS version: tvOS 

Make sure these boxes are checked before submitting your issue - thanks!

- [X ] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... after the movie freezes and reloading the movie it should load subs for movie, where there were subs available before.

#### Actual Behaviour

... subs werent available after the movies freezes and restarting the app. 

Solution: After cleaning cach, close the app, restart the app, clear caches again, restart apple tv the subs load again.. 

#### Steps to reproduce the behaviour

1. ... make sure it freezes during a movie or tv show which you watch with subs on
2. ...close the app
3. ...load the same show or movie and add subs (no subs available)

**Comment by gustavolessadublin** [comment]
This happens to me all the time.
The solution for me is just to close the app and reopen it. I don't need to clean cache.

**Comment by FlaviaBondJamesBondsHusband** [comment]
#299
