### ISSUE TITLE
Cannot install the app with impactor 

### ISSUE THREAD

**Issue by vdhub** [PopcornTimeTV/PopcornTimeTV#448]
App version: 3.1.1

iOS/tvOS version:10.2

I try to install the .ipa with the latest version of impactor from mac and it seems that it does not work, it does the usual things and when it`s almost ready to proceed it crashed and it gives this error 
"./plist.hpp:92
_assert(plist_get_node_type(plist) == PLIST_STRING)"

On GeneratingApplicationMap

so i cannot install. 

Any idea how to fix this ? 

Thanks .

**Comment by vdhub** [comment]
weird, it seems that even that error came , after i restarted the apple tv the app was updated and on the device so i have no idea why that error and if it affects the app usage or not, not even if it`s from the app or from the impactor side. Anyway i`ll keep you updated. 

Thanks again.

**Comment by gustavolessadublin** [comment]
This is happening to me ever since I started using Impactor instead of building with xCode.
However, every single time the app was installed correctly.
So, it seems it's ok to just ignore that error.

**Comment by FlaviaBondJamesBondsHusband** [comment]
This is an issue with impactor
