### ISSUE TITLE
Terms and Conditions popup on first launch of clean application install is not aligned with borders (offset)

### ISSUE THREAD

**Issue by dmytrokoren** [PopcornTimeTV/PopcornTimeTV#449]
App version: 3.1.0
iOS/tvOS version: 10.2

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

When I clean installed PopcornTime TvOS, Terms and Conditions popup (where you have to agree or leave) is not aligned with borders (offset). Same fix needs to be applied to this issue as for Issue #440 

#### Actual Behaviour

First launch of clean install PopcornTime Terms and Conditions should be aligned with TV borders.

#### Steps to reproduce the behaviour
1. Clean install PopcornTime on TvOS
2. When app launches the Terms and Conditions popup
3. The text is offset on TV borders

![image](https://cloud.githubusercontent.com/assets/20926198/25182896/f7c480a2-250d-11e7-88ed-8787d101c641.png)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for reporting, issue fixed in master
