### ISSUE TITLE
Couldn't find some movies

### ISSUE THREAD

**Issue by BilalBaydoun** [PopcornTimeTV/PopcornTimeTV#45]
Hello,

Thank you for hard work guys! I was searching for "now you see me 2" but I couldn't find it while it's available on popcorn time desktop also there is few movies I was looking for and I couldn't find it.

BR

**Comment by tvOSPopcorn** [comment]
That is an API issue, PopcornTimeTV is using the older API's for it's movies and shows... We're in the process of redoing the backend of the application to allow for support of the new API's and other features.

Will be closing this issue as it's already being worked on.
