### ISSUE TITLE
app crash in tv shows - genres

### ISSUE THREAD

**Issue by superdoctor1** [PopcornTimeTV/PopcornTimeTV#450]
App version: 3.1.1
iOS/tvOS version: 10.2

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...it have to shows the tv shows by genres

#### Actual Behaviour

...It crash

#### Steps to reproduce the behaviour

1. ...open app
2. ...go to shows tab
3. ...click en show by genres

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for reporting, issue fixed in master
