### ISSUE TITLE
The app crashes while opening an episode

### ISSUE THREAD

**Issue by sweetw0r** [PopcornTimeTV/PopcornTimeTV#451]
App version: 3.1.1
iOS/tvOS version: 10.2

Make sure these boxes are checked before submitting your issue - thanks!

- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behavior
Playback should start

#### Actual Behavior
The app exits to Apple TV main menu screen

#### Steps to reproduce the behavior
1) Open the app
2) Find tv show "Sherlock"
3) Play 3rd episode of 1st season ("The great game")

Note: the episode works fine in iOS version of the app

**Comment by sweetw0r** [comment]
Reinstalling solved the issue

**Comment by SerhiiAksiutin** [comment]
Actually it is still happening. This time: Gotham s2e11

**Comment by sweetw0r** [comment]
Able to reproduce in the latest build. Gotham s2e11

**Comment by sweetw0r** [comment]
Not reproducible after pulling latest updates
