### ISSUE TITLE
PopcornTime not working

### ISSUE THREAD

**Issue by AIPS69** [PopcornTimeTV/PopcornTimeTV#452]
Hi, I just opened my apple tv and PopcornTime app isn't working. I press on the application to open but it's not opening. Kodi and other applications are working well, I restarted the apple tv nothing changed. Like Popcorntime app crashed and it's not opening. I guess like the rest of the users it worked only for a week.

Note: I'm using the latest version 3.1

Thanks

**Comment by carlosvelez89** [comment]
Did you resign the app with  cydia impactor?

**Comment by AIPS69** [comment]
@carlosvelez89 yes I dragged it to the impactor and installed it through it. That was the only thing I did to install it.

**Comment by carlosvelez89** [comment]
You have to o resign the app after 7 days

**Comment by AIPS69** [comment]
@carlosvelez89 can you please guide me how to do it and should I do it after every 7 days continuously?

**Comment by carlosvelez89** [comment]
It's the same process as signing the app for the for the time. Drag the file into impactor . Use you Apple ID and password and let it sign. If you get an error. Ignore it. It should work fine  popcorn time

**Comment by AIPS69** [comment]
@carlosvelez89 Is it like a weekly process I should do ?

**Comment by carlosvelez89** [comment]
Yes, it's because, if you don't have a developers account . The signing is 7days

**Comment by AIPS69** [comment]
@carlosvelez89 Any other permanent alternative solution ?

**Comment by carlosvelez89** [comment]
Don't know it

**Comment by michrome** [comment]
@AIPS69 you won't have to re-sign every 7 days if you [enrol in the ($99) Apple Developer Program](https://developer.apple.com/programs/enroll/).
