### ISSUE TITLE
cydia impactor

### ISSUE THREAD

**Issue by dinolaza** [PopcornTimeTV/PopcornTimeTV#453]
Hi,

When I try install the .ipa file with cydia impactor I get the following error:

error
./plist.hpp:92
_assert(plist_get_node_type(plist) == PLIST_STRING

Please help?

TvOS 10.2 PopcornTime TvOS (latest version)

**Comment by Dumeli** [comment]
This is an issue with impactor .. #448

**Comment by FlaviaBondJamesBondsHusband** [comment]
App will still install regardless
