### ISSUE TITLE
ar.lproj For Popcorn Time

### ISSUE THREAD

**Issue by abdullahaljedaie** [PopcornTimeTV/PopcornTimeTV#454]
i make translated the language file of popcorn time to Arabic language.

I read all the translation tutorials on you repo and I do it.

so File ( xliff ) for Arabic Translation in Attachments.

Note:
TvOS Does not support RTL 
iOS  support RTL

thank you for This app.
[ar.xliff.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/951573/ar.xliff.zip)

and this URL For File 
https://mega.nz/#!JJF1WBAZ!CpQsFEA3b4eERYaTbmrfTQ3cADwkOjCikBjFQ9Jt1OE

**Comment by Mixer2030** [comment]
bro your translation doesn't work
and there is a lot of wrong words!

**Comment by abdullahaljedaie** [comment]
I did not try this because the file is (xllif)  but I edit en.lproj for For myself  it`s  work with me. ( pic in attachments ).


for wrong words you can tell me and I will edited 



<img width="1916" alt="screen shot 1438-07-27 at 4 11 48 am" src="https://cloud.githubusercontent.com/assets/18357922/25381133/4b07293e-29bb-11e7-9314-938d6ceb71ea.png"> 
<img width="1919" alt="screen shot 1438-07-27 at 4 12 13 am" src="https://cloud.githubusercontent.com/assets/18357922/25381141/52c8d938-29bb-11e7-9b3b-9be564d3802e.png"> 
<img width="1921" alt="screen shot 1438-07-27 at 4 12 56 am" src="https://cloud.githubusercontent.com/assets/18357922/25381163/621fc1c6-29bb-11e7-8e1a-bb2ab52ec825.png">

**Comment by abdullahaljedaie** [comment]
update translation File . ( attachments )

1- Corrected some words.

2- Corrected some codes of translation because arabic language write from right to left .



notice : 
1-  TvOS not Support RTL (  right to left ) . and TvOS support write and read of Arabic language but the system interface does not support Arabic.

  iOS supported all of them.

some code when I translation from EN to AR maybe need to edit code like this:

<img width="531" alt="1" src="https://cloud.githubusercontent.com/assets/18357922/25397776/3347bc50-29f2-11e7-8596-ab4ccf7f214d.png">

2- Terms of service because they contain several lines and because of problems with Arabic language on TvOS i can`t translated. ( \n\n ) RTL

<img width="846" alt="2" src="https://cloud.githubusercontent.com/assets/18357922/25398090/62de9816-29f3-11e7-86b6-49833c4ffcfd.png">


I will try to fixed that .

thank you :)

**Comment by Mixer2030** [comment]
still don't work for me

**Comment by abdullahaljedaie** [comment]
ok I will send ar.lproj to you next time

1- ar.lproj For iOS .
2 ar.lproj For TvOS.

After tested I will upload it.

**Comment by abdullahaljedaie** [comment]
this is File ar.lproj For iOS only (attachments)

I tested it`s work on iOS 
iPad mini 2 - iOS 10.1.1
iPhone 7 - iOS 10.1.1
iPad Air iOS 10.3.1
iPad Pro 9.7 iOS 10.2

[PopCornTime ar.lproj For iOS.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/956709/PopCornTime.ar.lproj.For.iOS.zip)

**Comment by FlaviaBondJamesBondsHusband** [comment]
I have added your arabic translations but I am unable to verify their legitimacy as I am not a native arabic speaker. I would ask that other arabic speakers verify these translations. If there are any errors, please create an issue so we can fix it together.

@abdullahaljedaie Thanks for all your hard work 😄 .

**Comment by abdullahaljedaie** [comment]
thank you for PopCorn Time and support.

take your time to Do what you see right .

:) best greetings

**Comment by abdullahaljedaie** [comment]
new update is ready :)

[Updates.xliff_AR.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/1131642/Updates.xliff_AR.zip)
