### ISSUE TITLE
Arabic Subtitle dose no`t show up

### ISSUE THREAD

**Issue by abdullahalbrahim** [PopcornTimeTV/PopcornTimeTV#455]
App version: 3.1.2
iOS/tvOS version: 10.1.1

subtitles Arabic did not show up on last version of popcorn time on TvOS or iOS.

in version 3.1.1 it`s work.

i try choose another language it`s work but when i selected Arabic subtitle Disappear.

Encoding Subtitles is: Arabic ( Windows 1256 ) .

Hopefully solve the problem in next update.

thank you 👍

**Comment by FlaviaBondJamesBondsHusband** [comment]
We changed nothing in relation to subtitles in 3.1.2
