### ISSUE TITLE
Audio enhancement issue when choosing between Full Dynamic Range and Reduce Loud Sounds

### ISSUE THREAD

**Issue by felipecabralf** [PopcornTimeTV/PopcornTimeTV#456]
App version: tvOS 3.1.1 / 3.1.2
iOS/tvOS version: tvOS 10.2

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Enhance audio by choosing between Full Dynamic Range and Reduce Loud Sounds.

#### Actual Behaviour

No change or enhancement in audio when choosing between Full Dynamic Range and Reduce Loud Sounds. Actually, audio is of lower quality when compared to the one played by version 3.1.0. This seemed to happen only in the tvOS versions of the app. There is also a weird "Speakers" difference between 3.1.0 and 3.1.1/2 apps: while in 3.1.0 "Speakers" is shown a "Dock" (even though there is no kind of dock being used, audio is transmitted through HDMI cable), in 3.1.1/2 the "Speakers" is shown as Apple TV itself, which is a standard option to other video apps, eg. Netflix.

#### Steps to reproduce the behaviour

1. Choose video to play
2. Scroll down in Siri Remote to open video options
3. Under Audio, choose between Full Dynamic Range and Reduce Loud Sounds

**Comment by FlaviaBondJamesBondsHusband** [comment]
I have tweaked the Full Dynamic Range setting to a more flat equaliser profile which should reduce any distortion brought about by the previous profile (full bass, full treble). 

Regarding you not hearing a difference, we are using default equaliser profiles that VLCKit ships with. If you have an issue with them, open an issue with them on their gitlab. Although I doubt they will respond because your issue is very subjective.
