### ISSUE TITLE
Slow UI

### ISSUE THREAD

**Issue by dinolaza** [PopcornTimeTV/PopcornTimeTV#457]
App version: tvOS 3.1.1 
iOS/tvOS version: tvOS 10.2

Hi everyone, 
Ever since i started using popcorn time, thanks the app is great, i notice a big lag in scrolling speed in the UI.
I cleared the cache but not much of a difference... Is there something I'm missing or not doing?

Thanks

**Comment by FlaviaBondJamesBondsHusband** [comment]
This is not an issue. Performance is extremely subjective and an issue is designed for clear, reproducible bugs.
