### ISSUE TITLE
 sound track continues

### ISSUE THREAD

**Issue by dinolaza** [PopcornTimeTV/PopcornTimeTV#458]
App version: tvOS 3.1.1 
iOS/tvOS version: tvOS 10.2

Hi everyone,

When I finish watching a movie the sound track continues in the background when i scroll through the menu. Is there something I'm not doing? Thanks

**Comment by FlaviaBondJamesBondsHusband** [comment]
3.1.2 is the latest version of the app please try again with that. Also you have completely ignored the issue template so this issue will be closed.
