### ISSUE TITLE
Fast forwarding is not working correctly if it needs to buffer

### ISSUE THREAD

**Issue by litengulfisk** [PopcornTimeTV/PopcornTimeTV#46]
When starting a movie and forward to like 60 min into it and play if from there. The movie is not playable from there even if I pause and wait a while for it to buffer.

I only get a freeze frame and it's some times green and some times just a freeze frame.

**Comment by RefusedFlow** [comment]
We're aware of this issue, it's a major problem with the torrent streamer. Something we're looking at fixing within the next few weeks hopefully if we can get a developer to work on the Torrent Streaming area of the app.

**Comment by buzzel** [comment]
Closing this as it's already on the PopcornTorrent repo.
