### ISSUE TITLE
error with TVVLCKit-bitcode

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#46]
When running pod install it gave me this error when installing TVVLCKit-bitcode

[!] Error installing TVVLCKit-bitcode
[!] /usr/bin/curl -f -L -o /var/folders/dw/w6m8dq4d3cnf0_7vw864j_4c0000gn/T/d20160829-75878-1v5t5gf/file.zip https://appd.be/kronos/TVVLCKit.framework.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) Server aborted the SSL handshake

**Comment by Hackormahn** [comment]
@moh0sw could you please try again, and tell me the result? A lot of times the error will disappear after a couple retrys. :)

**Comment by moh0sw** [comment]
@Hackormahn tried at least 20 times and the same error even with 1.0.3.1

**Comment by ynnad696** [comment]
same here , keeps asking username crap

**Comment by Hackormahn** [comment]
@ynnad696 then type in your GitHub username.

**Comment by Hackormahn** [comment]
@ynnad696 attempt to download TVVLCKit.framework directly from the download link here: https://appd.be/kronos/TVVLCKit.framework.zip and please tell me the result.

**Comment by Faisal-nz** [comment]
The link is not working properly, i have cloned the repo and downloaded the framework to my site, feel free to use it as a temporary solution 

https://github.com/Faisal-nz/Spec

**Comment by Hackormahn** [comment]
@Faisal-nz the link is working properly. The problem lies in the SSL Handoff which will fail on your side if the machine is outdated or messed up somehow. Is your issue the same as mos0sw's?

**Comment by moh0sw** [comment]
@Hackormahn for me i downloaded the 1.0.3.1 ipa from appdb and resign it and it works fine for now but the pod install problem (SSL) still the same

**Comment by Faisal-nz** [comment]
Yes i have the same problem if i try to download or pod install from my computer. It worked when i used pho curl through my website

**Comment by Hackormahn** [comment]
Changed to your mirror for now, will continue looking into this issue.

**Comment by Hackormahn** [comment]
Changed to your mirror for now, will continue looking into this issue.

**Comment by JulienMalige** [comment]
same issue in 2018 🤔

**Comment by JulienMalige** [comment]
Updating the dependency fixed my issue but I'm not sure that it is just luck.

**/Podfile**
`pod 'TVVLCKit', '~> 3.1.3'`
