### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by rarias84** [PopcornTimeTV/PopcornTimeTV#460]
TV Version 3.1.2

dyld: Library not loaded: @rpath/AEXML.framework/AEXML
  Referenced from: /private/var/containers/Bundle/Application/BB5FFEB0-5F26-4D2D-A006-55809B28B9A7/PopcornTime.app/Frameworks/PopcornKit.framework/PopcornKit
  Reason: image not found
(lldb)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Use the ipa
