### ISSUE TITLE
Russian subtitles are displayed in incorrect encoding

### ISSUE THREAD

**Issue by kambala-decapitator** [PopcornTimeTV/PopcornTimeTV#462]
App version: 3.1.2
iOS/tvOS version: tvOS 10.2.1

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Russian subtitles are readable.

#### Actual Behaviour

Russian subtitles are unreadable.

#### Steps to reproduce the behaviour

1. Start any movie that contains Russian subtitles, e.g. Guardians of the Galaxy.
2. Select Russian subtitles and encoding Cyrillic (Windows-1251). For Guardians of the Galaxy I've verified that this is the correct encoding by inspecting the downloaded .srt file.
3. Subtitles are displayed, but aren't decoded properly.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Can you try again using UTF-8 encoding?

**Comment by kambala-decapitator** [comment]
Currently subtitles aren't working on my side at all, seems opensubtitles.org is down. I've checked in the simulator - the error is

    domain: "Alamofire.AFError" - code: 3

Will retest later. Yesterday it didn't work with UTF-8 either though.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Yeah that'd be an open subtitles error. There's a special Russian encoding called Russian (KOI8-R), you might try with that also and let me know how you get on.

**Comment by kambala-decapitator** [comment]
> Note, on-demand subtitle encoding changes (i.e. from the drop-down menu in the player) is not supported and is really just there for show so change the encoding in the settings section of the app and then retry.

Oh, I was not aware of this... Changing encoding in Settings did the trick, thanks. (Windows-1251 was the proper one)

Well, then encoding selection should be removed from player's drop-down IMO as it's completely misleading. Or maybe make the list "read-only" (non-interactable).

Is it VLC's limitation?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Yup it's VLC's limitation. They only allow for encoding to be changed before the media has started playing. We thought we'd leave it in hoping they would fix it on their end some day.
