### ISSUE TITLE
Spanish localisation 

### ISSUE THREAD

**Issue by soygalla** [PopcornTimeTV/PopcornTimeTV#467]
Hi, just finished translating the file to Spanish but when translating and testing I found some issues that could have been unnoticed, i've listed them below so they may be fixed in future releases, some of which I think have already been mentioned.

### Misspelling
1. "Cache was already empty, no disk space was **_reclamed_**." -> Reclaimed?
2. "**_Staring_**" -> Starring?
3. "Start from **_Begining_**" -> Beginning?
4. "Subtitles for the deaf and Hard of Hearing (SDH) refer to subtitles in the original **_lanuage_** with the addition of relevant non-dialog information." -> Language?
5. "It looks like your ISP/Network admin is blocking our servers. You can try again with a VPN to hide your internet traffic from them. **_Please do so your own risk_**." -> Please do so at your own risk?

### UI Issues
1. "Rating" label ("Clasificación" in Spanish)
![clasificacion](https://cloud.githubusercontent.com/assets/12305078/25766363/6b7a37d2-31af-11e7-82a1-1c9a0299edca.png)
2. "Sort" label (tvOS only, iOS it's fine)
![sort](https://cloud.githubusercontent.com/assets/12305078/25766390/89d4eace-31af-11e7-97c2-96df863a804b.png)

### Translation issues
1. The terms of service text is not been translated(the long text, not the header text. tvOS & iOS) .
2. "Play" text is not been translated(tvOS)
3. "Watched" text is not been translated(tvOS)
4. "Series" text is not been translated(used to display other seasons of the tv show. tvOS).
5. "On" word, this case is different. In the tvOS version of the app the word is used in different contexts, in English the word works fine for the different contexts in the app but in other languages such as Spanish don't.
![image](https://cloud.githubusercontent.com/assets/12305078/25767683/e7ed5c8c-31b8-11e7-8e8b-77b8f4386108.jpg)
For setting it's fine, but "Mira Prison Break sí FOX (US)" doesn't make sense. I think it would work better if the format it's something like "Watch %1$@ on %2$@" so it can be translated properly.

And after that long ass list, here's the translation file:
[es.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/980534/es.zip)

If there's anything else I can do to help, let me know 😁.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Ok I think everything should be fixed in master. Wanna give it a go?

**Comment by soygalla** [comment]
Thank you! most is fixed, i've updated the translation to fix some misspellings but with the recent changes made to the project i think the previous base localization file doesn't work properly so i exported a .xliff from the project and updated the translations, should work, heres the updated file:
[es v2.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/981282/es.v2.zip)

 With the UI there's still some issues, the rating label on tvOS, it's fixed on iOS.
![clasificacion](https://cloud.githubusercontent.com/assets/12305078/25777332/724ae2c6-3297-11e7-926b-981ec40ac62e.png)

When choosing a subtitle on tvOS "language" and "encoding" it's not been translated.
![subs](https://cloud.githubusercontent.com/assets/12305078/25777343/dead9724-3297-11e7-8471-3acb2ba138f3.png)

"trailer" text on tvOS is not been translated but on iOS is. It's
![captura de pantalla 2017-05-06 a las 8 13 16 p m](https://cloud.githubusercontent.com/assets/12305078/25777385/fc51a760-3298-11e7-8594-7b5d081bacc6.png)
![captura de pantalla 2017-05-06 a las 8 16 43 p m](https://cloud.githubusercontent.com/assets/12305078/25777386/ff04cb18-3298-11e7-84de-3fd7a2c62f42.png)

Thank you in advance! 😃

**Comment by FlaviaBondJamesBondsHusband** [comment]
Can you use the Base localisation with your updated translations? The problem with the ones you export from Xcode is all the mess that comes with - hard coded CFBundleVersion strings, placeholder translations etc.. 

I have added the missing Language and Encoding translations into the new Base.xliff. Sorry for the inconvenience :/.

**Comment by FlaviaBondJamesBondsHusband** [comment]
OK everything should be fixed. Can you try it out just in case I've missed something 😄

**Comment by soygalla** [comment]
It's all fixed! Thank you for your hard work 😄👍

**Comment by FlaviaBondJamesBondsHusband** [comment]
We're getting ready for the next release and were wondering if you wouldn't mind updating your 
[Localisations](https://github.com/PopcornTimeTV/PopcornTimeTV/files/1128084/Updates.zip). The release is scheduled for next week so please have it completed for then. Thanks!

**Comment by soygalla** [comment]
Sorry for responding late, been quite busy. But sure i'll do it.

**Comment by soygalla** [comment]
Here's the translated file 😁
[Updates-es.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/1139683/Updates-es.zip)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks, added updates to master
