### ISSUE TITLE
iCloud Sync

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#469]
Would be nice if there is a way to sync what I have watched and where I stoped between my devices.
Could use iCloud drive to sync it.. Or dropbox (for dropbox must have an app api key)

So, if I watch one episode show at my iPhone, later on my apple TV, it will mark as watched, so, I won't get confused to continue where I've stoped.

Even better, all my watchlist will be synced

**Comment by FlaviaBondJamesBondsHusband** [comment]
This feature has existed since day one. #441
