### ISSUE TITLE
TV Shows Issue: Processing State

### ISSUE THREAD

**Issue by mohorani** [PopcornTimeTV/PopcornTimeTV#47]
Most or all TV Shows say "Processing" and then they don't actually load. I have waited 2-3 and it never changes from "Processing" to "Downloading." Please fix this issue. Thanks.

**Comment by litengulfisk** [comment]
Do they work from a PC or Mac client? This might be because of no uploaders and not actually a problem with the app itself.

**Comment by mohorani** [comment]
Yes it works just fine from a Mac.

**Comment by mohorani** [comment]
Update: It downloads, and then it automatically crashes.(I tested a TV Show on PopcornTime)

**Comment by buzzel** [comment]
Does this happen in the simulator as well?

**Comment by mohorani** [comment]
The app does not even work in the simulator now. Please refer to the new issue that I posted. Thanks.

**Comment by mohorani** [comment]
Alright the simulator finally works, but even in the simulator when I try a specific TV show, it downloads then automatically crashes. Please fix this ASAP. Thanks. Here is a screenshot:
<img width="1280" alt="screen shot 2016-04-15 at 4 30 37 pm" src="https://cloud.githubusercontent.com/assets/17534565/14577308/32b14d08-0327-11e6-86eb-bc64f7b32b7e.png">

**Comment by buzzel** [comment]
@mohorani Make sure you are downloading a 480p version. Anything higher will fail as VLC currently isn't implemented.

**Comment by mohorani** [comment]
I did do the 480p version and it still didn't work.

**Comment by buzzel** [comment]
I'll look into it when I have time this week

**Comment by buzzel** [comment]
This should be fixed. If not, try clearing your DerivedData and recompiling it.
