### ISSUE TITLE
Any movie after loading freezes in beginning.

### ISSUE THREAD

**Issue by dmytrokoren** [PopcornTimeTV/PopcornTimeTV#473]
App version: 3.1.2
iOS/tvOS version: 10.2

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Not freeze at all since the movie has been loaded enough (loading bar has far past where the movies freezes)

#### Actual Behaviour

All movies freezes in the beginning. I don't know about shows

#### Steps to reproduce the behaviour

1. Open any movie
2. Select 720p
3. Movie plays and then freezes in the beginning.
4. After I click pause and then play the movies continues without further freezings.

The issue is only in the beginning of the movie and usually happens when movies play till 1-3 minutes.

**Comment by FlaviaBondJamesBondsHusband** [comment]
You clearly have not done any sort of search because if you had even searched the word "freeze" 4 other issues, exactly the same as this would have shown up, the latest being yesterday. #299
