### ISSUE TITLE
Movie screen typo

### ISSUE THREAD

**Issue by PencilNotPen** [PopcornTimeTV/PopcornTimeTV#475]
PopcornTime 3.1.2 tvOS

The movie screen, after you select a thumbnail and are taken to the page showing the movie's genre, cast, and trailer, has a typo.

The cast section on the left-hand side says "STARING" instead of "STARRING".

A small thing I know, but noticeable.

Thanks!

**Comment by FlaviaBondJamesBondsHusband** [comment]
Already fixed in master
