### ISSUE TITLE
Subtitles in Hebrew displayed as a series of question marks

### ISSUE THREAD

**Issue by clementbarry** [PopcornTimeTV/PopcornTimeTV#476]
App version: latest
tvOS version: latest

#### Expected Behaviour
Subtitles should display Hebrew characters (אבגדהוזחטיכלמנסעפצקרשת)

#### Actual Behaviour
Subtitles only display "???????????? ???? ???" on every line

#### Steps to reproduce the behaviour
1. Watch popular TV show
2. In Subtitles, select Hebrew
3. Selecting another encoding (UTF-8, UTF-16, Hebrew-Windows, Hebrew ISO-8859-8 etc.) won't matter

Comment: I suspect this has to do with the font used for subtitles which could be unavailable in some languages on tvOS

**Comment by FlaviaBondJamesBondsHusband** [comment]
> Selecting another encoding (UTF-8, UTF-16, Hebrew-Windows, Hebrew ISO-8859-8 etc.) won't matter

Changing encoding while playing does nothing. Leave the setting as UTF-8 and it will work for the majority of the subtitles. I suspect this is your issue as every single show/movie i have tried has had no issue.

> Comment: I suspect this has to do with the font used for subtitles which could be unavailable in some languages on tvOS

You are able to change the font yourself in settings
