### ISSUE TITLE
Music character for English SDH captions not rendered properly

### ISSUE THREAD

**Issue by clementbarry** [PopcornTimeTV/PopcornTimeTV#477]
App version: latest
iOS/tvOS version: 10.2.1 (latest)

#### Expected Behaviour
When a song is heard in a show, SDH captions display lyrics between note symbols ( 🎵lyrics🎵 )

#### Actual Behaviour
When a song is heard in a show, SDH captions display lyrics between cryptic symbols ( ⌸ lyrics ⌸ )

#### Steps to reproduce the behaviour
1. Watch a popular US TV show with frequent use of songs (e.g. Grey's Anatomy or Supernatural)
2. Select English subtitles

**Comment by FlaviaBondJamesBondsHusband** [comment]
We don't parse or create the subtitles. Opensubtitles creates, VLCKit parses, we just link the two
