### ISSUE TITLE
Playback stop after 10seconds

### ISSUE THREAD

**Issue by caminagetcha** [PopcornTimeTV/PopcornTimeTV#478]
Everityme I try to play a video it starts to download fine but after a little time like 10s the video freezes and doesn't play Anymore.

If I start it again and move to the middle of movie/tv show it plays good for a bit and stops/freezes again.

Pressing play pause does nothing. All other buttons work fine.
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by eldegos** [comment]
Try pausing the film or show immediately and wait about ten seconds, that should do the trick. Plus this isn't a problem with Popcorntime, but a problem with VLC player

**Comment by FlaviaBondJamesBondsHusband** [comment]
#299
