### ISSUE TITLE
Subtitles in PT_BR

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#479]
All portuguese subtitles are in `PT_PT`, there is no `PT_BR`, there is a **huge** difference between both.
It's missing `brazilian portuguese` at the subtitle menu.

**Comment by FlaviaBondJamesBondsHusband** [comment]
We do not make the subtitles

**Comment by CavalcanteLeo** [comment]
But you link them. There are subtitles in PT_BR too

PopcornTime is only linking PT_PT, excluding all PT_BR,

@FlaviaBondJamesBondsHusband

**Comment by CavalcanteLeo** [comment]
![captura de tela 2017-05-23 as 14 54 14](https://cloud.githubusercontent.com/assets/1735944/26368335/b68a5574-3fc7-11e7-80e7-9bb82396b82a.png)
