### ISSUE TITLE
0.4.2 breaks support?

### ISSUE THREAD

**Issue by Kazom** [PopcornTimeTV/PopcornTimeTV#48]
[!] Unable to satisfy the following requirements:

- `PopcornTorrent` required by `Podfile`
- `PopcornTorrent (= 1.0.8)` required by `Podfile.lock

**Comment by Sonikkua** [comment]
Same issue here.

**Comment by buzzel** [comment]
Try this: `cd ~/Desktop/PopcornTimeTV/ && rm -rf /Pods && rm -rf Podfile.lock && rm -rf ~/.cocoapods/repos/popcorntimetv` then `pod install && open PopcornTime.xcworkspace`
