### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by MrTehes** [PopcornTimeTV/PopcornTimeTV#481]
App version: 3.1.2
tvOS version: 10
 
Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Build succeed

#### Actual Behaviour

Build failed

#### Steps to reproduce the behaviour

2 errors
1. /path/to/xCode/PopcornTimeTV/PopcornKit/Managers/WatchlistManager.swift:74:13: Initializer for conditional binding must have Optional type, not '[N]'
The line concerned is 
` let map = Mapper<N>().mapArray(JSONArray: array),`

2. /path/to/xCode/PopcornTimeTV/PopcornKit/Managers/WatchlistManager.swift:89:112: Initializer for conditional binding must have Optional type, not '[N]'
The line concerned is 
`if let array = UserDefaults.standard.object(forKey: "\(currentType.rawValue)Watchlist") as? jsonArray, let map = Mapper<N>().mapArray(JSONArray: array) {`

Thanks for your time !

**Comment by eldegos** [comment]
Try the .ipa and see if you can install it with that instead of using Xcode

**Comment by FlaviaBondJamesBondsHusband** [comment]
Weird... ObjectMapper broke compatibility with a patch release, breaking semantic versioning guidelines and therefore making our app not compile. Sorry about this, it should be fixed now.

**Comment by MrTehes** [comment]
It works fine now. Thanks !
