### ISSUE TITLE
Main theme music volume is too loud compare to volume of the video. Even if 25% is set up

### ISSUE THREAD

**Issue by sweetw0r** [PopcornTimeTV/PopcornTimeTV#483]
Set up it for 25%
Go to tv show landing page with them playing 
Start an episode and compare the volume 

Expected:
25% has to be slightly heard as a background 

Actual:
25% is much louder then sound of actual video

**Comment by tobsn** [comment]
oh yes, way too loud... should be 60-80% less than now. I always turn down volume when browsing.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue fixed in master. Thanks for reporting
