### ISSUE TITLE
xcode 8.3.3  tvos

### ISSUE THREAD

**Issue by superdoctor1** [PopcornTimeTV/PopcornTimeTV#486]
<img width="1440" alt="captura de pantalla 2017-06-10 a la s 12 28 35" src="https://user-images.githubusercontent.com/26314134/27004913-15636c84-4dd8-11e7-8ee1-a6363724d2e1.png">

**Comment by Faisal-nz** [comment]
+1 same here!!

**Comment by matthijs2704** [comment]
You should read the commit message. It says that tvOS is broken currently and the latest commit was for iOS only.
