### ISSUE TITLE
App crashes on content selection

### ISSUE THREAD

**Issue by akaFTS** [PopcornTimeTV/PopcornTimeTV#487]
App version: 3.1.2
iOS/tvOS version: 9.3.3 (iPad)

When I select a title on the list (movie or TV show), it displays the content detail page, with a spinner icon, and then immediately crashes. Happens with any title. This wasn't happening before, and I did not update the app, so I guess some API-related update broke the served data structure and the app cannot parse it anymore.

**Comment by akaFTS** [comment]
Update: version 3.1.1 also crashes.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Yeah we fixed this a while back in master (b4fac45). It only exists on iOS 9 so you must have recently downgraded?

**Comment by akaFTS** [comment]
Is there any way to compile it without a development team and provisioning profile? XCode is not allowing me to do it. Thanks

**Comment by willwhitney** [comment]
You can create one by adding an Apple account to Xcode. If you then change the team to the one it automatically creates for you the compilation should go ahead.
