### ISSUE TITLE
Search tab crashes on iOS 11

### ISSUE THREAD

**Issue by willwhitney** [PopcornTimeTV/PopcornTimeTV#490]
App version: https://github.com/PopcornTimeTV/PopcornTimeTV/commit/0c2c241915bdf96e7702ac297a233492ab3f9a96
iOS/tvOS version: iOS 11 beta 1

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Open the search tab

#### Actual Behaviour

Crash to springboard

#### Steps to reproduce the behaviour

Occurred on iPad Pro 13” (2nd generation) running iOS 11 developer beta.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Beta versions of iOS/Xcode are not supported
