### ISSUE TITLE
When playing many movies, audio cuts out every half second.

### ISSUE THREAD

**Issue by me4502** [PopcornTimeTV/PopcornTimeTV#492]
App version:
iOS/tvOS version: tvOS 10.2.2

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

The audio would play normally

#### Actual Behaviour

The audio plays for half a second, then doesn’t for the next half second.

#### Steps to reproduce the behaviour

1. Play Pulp Fiction
2. Have sound turned on
3. Audio cuts out every half second

**Comment by FlaviaBondJamesBondsHusband** [comment]
This doesn't happen for any movie we've tried. Are you using external speakers? If not, are you sure it's not the speakers on your TV?

**Comment by me4502** [comment]
It only happens for some, and I’ve tried multiple different audio devices. Normally I use external speakers through my TV, however I’ve tried the TVs speakers and AirPods connected directly to the AppleTV.

**Comment by FlaviaBondJamesBondsHusband** [comment]
If it's not happening for every movie, it sounds like an issue with either [VLCKit](https://code.videolan.org/videolan/VLCKit) or with (YTS.ag)[https://yts.ag/] and we cannot do anything about it. Maybe try using a different quality? Or if you have an iPhone you can download our app on that, manually select a torrent on (YTS.ag)[https://yts.ag/], and use AirPlay to stream to your Apple TV.

**Comment by me4502** [comment]
Hmm, okay - thanks.
