### ISSUE TITLE
Can't build tvOS app. Even 3.1.1 is failing in Xcode 

### ISSUE THREAD

**Issue by sweetw0r** [PopcornTimeTV/PopcornTimeTV#493]
<img width="972" alt="screen shot 2017-06-24 at 4 11 29 pm" src="https://user-images.githubusercontent.com/12688470/27512516-dfc4b63e-58f7-11e7-9725-1b2a1c4f4adc.png">

**Comment by FlaviaBondJamesBondsHusband** [comment]
Look at the master commit message. #486. #481. No idea why you're building 3.1.1, just trying to be difficult maybe? There's an ipa available on the release page where you would've had to go to download the source for the release. The issues page is for bugs and enhancements within the application, not for your incompetency. Have a nice day

**Comment by sweetw0r** [comment]
@FlaviaBondJamesBondsHusband  The reason I am using build from the source is because *ipa method isn't working for me. After attempt to auth I got the error (checked with two different credentials):
<img width="786" alt="screen shot 2017-06-25 at 10 30 01 am" src="https://user-images.githubusercontent.com/12688470/27518334-4191c33a-5992-11e7-8a4c-6a1c5536fcc2.png">

So, complete used to be the only way for me to install it **tvOS** version. Although, It's not clear how to compile with fix #481, replacing row files in 3.1.2 did the trick!

I appreciate you help and work on #481 Sorry if the ticket seems inconvenient.
