### ISSUE TITLE
apple TV 4, stop working every week

### ISSUE THREAD

**Issue by sarkistlt** [PopcornTimeTV/PopcornTimeTV#494]
Basically that's it, already a month have that issue, and I have paid apple dev. account. it works fine on mobile, but on apple TV, every week needs to be reinstalled to make it work.

**Comment by williamoconnorme** [comment]
If it needs to be reinstalled each week to work it sounds like you are not signing it with your developer account. Before anyone can help you though you should use the issue template.

https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/ISSUE_TEMPLATE.md

**Comment by sarkistlt** [comment]
Expected Behaviour

work without reinstalling every 7 days.

Actual Behaviour

needs to be reinstalled every 7 days

Steps to reproduce the behaviour

1. connect apple TV to mac, via usb-c.
2. turn off 2-factor verification temporarily.
3. open 'impactor' it automatically detects apple TV
4. drop app file to impactor (v3.1.2)
5. enter required email and password for my apple ID, for the same apple ID that has paid developer account.

**Comment by eldegos** [comment]
You don’t have to turn off 2-factor authentication, just log into the AppleID web page and generate an app specific password and use that as your password in Cydia Impactor

**Comment by sarkistlt** [comment]
got it, ok will try, thank you!

**Comment by FlaviaBondJamesBondsHusband** [comment]
@williamoconnorme, @eldegos Thanks guys! @sarkistlt As they said, it sounds like you're not signing in with the correct developer ID. Did leaving 2 factor auth enabled fix your issue?

**Comment by sarkistlt** [comment]
I don't know yet, will see in 7 days)

**Comment by FlaviaBondJamesBondsHusband** [comment]
I guess we will 😄 . Feel free to reopen this or create a new issue if the problem hasn't been fixed
