### ISSUE TITLE
Crash on search section on latest update

### ISSUE THREAD

**Issue by kakaswr22** [PopcornTimeTV/PopcornTimeTV#496]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for the super detailed bug report

**Comment by kakaswr22** [comment]
crashes on both ios/tvos

**Comment by FlaviaBondJamesBondsHusband** [comment]
Found and fixed. In future please read the issue template otherwise your issue will be closed and ignored

**Comment by kakaswr22** [comment]
not fixed yet and u should thank me and i dont know u rules ... and if you want to public ur app with bugs ban me ...and i did let u know the issue the same way other ..i cant see any problem with that
