### ISSUE TITLE
new update AR Language for PopcornTime 

### ISSUE THREAD

**Issue by abdullahaljedaie** [PopcornTimeTV/PopcornTimeTV#497]
new update for translation ARABIC Language 

complete for #454

[Updates.xliff_AR.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/1131624/Updates.xliff_AR.zip)

:)

**Comment by FlaviaBondJamesBondsHusband** [comment]
Sorry, completely forgot to reopen your localisation. Anyway, thanks, your translations have been added in the latest push (7ab6135).
