### ISSUE TITLE
Download functionality not working on physical Apple TV

### ISSUE THREAD

**Issue by FerasArabiat** [PopcornTimeTV/PopcornTimeTV#498]
App version: N/A (Built from code)
iOS/tvOS version: Apple TV 4, tvOS 10.2.1

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Clicking the download button under the movie details screen should start the download process

#### Actual Behaviour

Clicking the download button under the movie details screen results in a popup message saying "Could not create download directory", and the download button gets stuck in the pending state.

#### Steps to reproduce the behaviour

1. Fresh Install App
2. Select movie from the main screen
3. In the details page click the download button
4. "Could not create download directory" is displayed, and download button is stuck in pending state

Note: This only happens on the the physical device, it works fine in simulator.

**Comment by FlaviaBondJamesBondsHusband** [comment]
This used to be an issue in a previous version of PopcornTorrent but I thought it had been fixed. Can you make sure:
a) You have the latest version of master
b) Your dependencies are up to date (`pod repo update; pod install; pod update PopcornTorrent`)
c) You have sufficient storage on your Apple TV.

**Comment by newyork1** [comment]
![img_20170706_160933](https://user-images.githubusercontent.com/30024989/27995812-77711b82-649a-11e7-8580-48924a4cde7e.jpg)

**Comment by FerasArabiat** [comment]
a) I'm on the latest commit 6ee5a5bc418a0adba00245b80d03c20e1ae43ef8
b) updated all dependencies
c) my apple tv is empty

Rebuilt with the above and I'm still facing the same issue.

**Comment by FlaviaBondJamesBondsHusband** [comment]
@FerasArabiat Able to reproduce now. Completely forgot that AppleTV doesn't allow permanent storage basically rendering the download feature pointless as storing it in some sort of cache directory doesn't guarantee it won't get purged by the system at some arbitrary time. Will push an update to fix soon

**Comment by FlaviaBondJamesBondsHusband** [comment]
Fixed, thanks for reporting https://github.com/PopcornTimeTV/PopcornTorrent/commit/beb27efc41c3199614e3f22e175d9073939a47c6
