### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by pbo1976** [PopcornTimeTV/PopcornTimeTV#5]
hi, i get this error and not know how to solve:

/Users/Oksfilms/Downloads/PopcornTimeTV-master/PopcornTime/VLC/SYVLCPlayerViewController.m:1541:27: No visible @interface for 'VLCMediaPlayer' declares the selector 'addPlaybackSlave:type:enforce:'

Any help is welcome, 
Thanks.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Go into your podfile and change the line `pod 'TVVLCKit'` to `pod 'TVVLCKit-unstable', :git => 'https://github.com/popcornMaster/VLCKit.git'`

**Comment by Evhelden** [comment]
It seems it is a general error. Why not change the podfile?

**Comment by FlaviaBondJamesBondsHusband** [comment]
I dont own the repo. Its the owners job to change not me :(

**Comment by pbo1976** [comment]
Thank you, I will give it a try.
