### ISSUE TITLE
Issue With Update Build(Build 0.4.2 is only shown in the ReadMe)

### ISSUE THREAD

**Issue by mohorani** [PopcornTimeTV/PopcornTimeTV#50]
When building the PopcornTimeTV app in Xcode, I notice that it is only actually 0.4.1. Also, in the commits, it only shows 0.4.2 in the instructions not in the actual build. Please fix this issue. Thanks.

**Comment by buzzel** [comment]
The bundle version must not of been updated. Will get that taken care of ASAP.
