### ISSUE TITLE
[!] Error installing TVVLCKit-unstable

### ISSUE THREAD

**Issue by rafaelfsramos** [PopcornTimeTV/PopcornTimeTV#50]
[!] Error installing TVVLCKit-unstable
[!] /usr/bin/curl -f -L -o /var/folders/_z/5cp1h55j2w5b0cl2fc369d980000gn/T/d20160829-47129-rg82r2/file.zip http://download.videolan.org/pub/cocoapods/unstable/TVVLCKit-unstable-3.0.0a10.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  7  408M    7 29.7M    0     0  56112      0  2:07:15  0:09:15  1:58:00     0curl: (56) Recv failure: Operation timed out

**Comment by Hackormahn** [comment]
You need to remove the Podfile, Podfile.lock, ad Pods file. Then try a Pod Install and it should work.
