### ISSUE TITLE
Download in background mode

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#500]
It's almost impossible to download anything by now, because the app must be opened.
If the app closes, you lose all progress download, and even worst, it removes from the queue. Every time I have to tap on download button and start again, from scratch. 

It will be much better if we could download in background mode. And if the users closes the app, should NOT remove from the queue.

**Comment by FuzzyNutz** [comment]
Yea agree with it staying in queue so that u can delete if u change your mind, but I think the download does resume mine started back from half way but I didint close the app I just went over to kodi

**Comment by FlaviaBondJamesBondsHusband** [comment]
This is not possible

**Comment by CavalcanteLeo** [comment]
It's possible with `UIBackgroundModes`
 
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html

**Comment by FlaviaBondJamesBondsHusband** [comment]
If you had read the article you linked to, you would realise that only finite tasks can be executed in the background, not downloads. Apps like Spotify use a special `plist` key that only allows music to be played in the background. 

We have done the research. Why would we build an inferior product if downloading in the background were possible?
