### ISSUE TITLE
Installing the ipa through Safari always fail.

### ISSUE THREAD

**Issue by Yaldo425** [PopcornTimeTV/PopcornTimeTV#501]
I'm aware that the ipa file could be installed using Cydia Impactor but I would also like to try installing it via Safari but for some reason it always fails and I don't know why. The ipa file is code signed properly and when trying to download it from my website or services such as Diawi.com it fails each time.

Would anyone know what the issue could be?

**Comment by RefusedFlow** [comment]
We don't support other 3rd party services, either install the ipa we provide or compile the application yourself
