### ISSUE TITLE
Suggestion :  subtitles on popcorn time

### ISSUE THREAD

**Issue by abdullahaljedaie** [PopcornTimeTV/PopcornTimeTV#502]
Can you add option for Download Subtitles a manually

Because when i choose a subtitle for movie there is a lot of delay at the time of subtitle
It does not help me control the subtitle time in an application

we need to add option for download subtitle from opensubtitles.org or subscene.com

thank you :)

**Comment by FlaviaBondJamesBondsHusband** [comment]
#107
