### ISSUE TITLE
Choppy sound 

### ISSUE THREAD

**Issue by FuzzyNutz** [PopcornTimeTV/PopcornTimeTV#503]
App version: 3.1.3
iOS/tvOS version: 10.0

I'm finding that a lot of the older movies the sound is choppy any idea why that is?

Movies I've tried so far are, The fifth element, The  departed and good fellas I'll post more when I come across them

**Comment by jeffhodsdon** [comment]
I'm seeing this too

**Comment by FuzzyNutz** [comment]
The template was kinda  tedious for this situation I felt like describing would be better, but please check this out with movies I listed.
