### ISSUE TITLE
Cant install Popcorn Time on iOS

### ISSUE THREAD

**Issue by adeelsid** [PopcornTimeTV/PopcornTimeTV#504]
Please help. I keep getting this error

./plist.hpp:92
_assert(plist_get_node_type(plist) == PLIST_STRING)

App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by FlaviaBondJamesBondsHusband** [comment]
#453 The app will install regardless.
