### ISSUE TITLE
Popcorn Time showing blank screen

### ISSUE THREAD

**Issue by mohorani** [PopcornTimeTV/PopcornTimeTV#51]
In the simulator when I am running the latest version, I see a blank screen that looks like this:
<img width="1280" alt="screen shot 2016-04-13 at 5 25 05 pm" src="https://cloud.githubusercontent.com/assets/17534565/14513422/853324d4-019c-11e6-84a8-d29ca7c6b8fd.png">

**Comment by buzzel** [comment]
Restart the simulator and try building again.

**Comment by mohorani** [comment]
Ok thanks.

**Comment by tomidelucca** [comment]
Had the same issue. Happens when your device/simulator is not connected to the internet.
