### ISSUE TITLE
No sound when casting to Chromecast

### ISSUE THREAD

**Issue by PerPerJB** [PopcornTimeTV/PopcornTimeTV#511]
App version:
iOS/tvOS version: iOS

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Cast the tv show to my chromecast and have working sound.

#### Actual Behaviour

Everything but having working sound.

#### Steps to reproduce the behaviour

1. Just try to cast a tv show to a chromecast.

**Comment by angryDuck2** [comment]
I will try and see what can be done with a chromecast simulator, as I have no available chromecast enabled devices

**Comment by PerPerJB** [comment]
Thanks!

**Comment by angryDuck2** [comment]
Hey I have done some testing with the airserver application for mac but it did not manage to play the content served by the app at all. Could you let me know which tv show and episode you were trying to watch?

**Comment by PerPerJB** [comment]
Its all of them, really. Like 99% of the time, the sound wont work. But I was going to watch the lates episode of Lucifer. No sound on the chromecast, but sound on my iphone. And yes, the sound on the chromecast does work when I cast, lets say, youtube :)

**Comment by angryDuck2** [comment]
The thing is Chromecast does not support mkv files so it is entirely possible that tv shows do not play when you use mkv files. Could you go to your preferred torrent website click on the magnet link for a tv show that uses an mp4 file and then check if that one plays correctly through Chromecast?

**Comment by PerPerJB** [comment]
I will do so tomorrow! I dont think it has worked in previous versions either.

**Comment by PerPerJB** [comment]
I did try what you told me to, and it worked!

Also, when i cast to apple tv, it just casts the sound, and not the picture.

And one question: is there a way to get the magnet link inside of popcorn time, so that i don't need to go to a torrent site to get them?

**Comment by angryDuck2** [comment]
Well then issue lies with chromecast not being able to play mkv/avi files which are much smaller in size and are the preferred ones for all popcorn api sources. This means that you will mostly have to use external sources! No there is no way to store these links internally. The same thing goes for airplay to apple tv, it neither can play mkv/avi files natively, we are using a third party library to do so both for iOS and tvOS! I am closing this issue as resolved!
