### ISSUE TITLE
Shows/Movies pause then won't play even though it shows buffering (Apple TV 4) 

### ISSUE THREAD

**Issue by ctschalk** [PopcornTimeTV/PopcornTimeTV#512]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... Play movies and shows

#### Actual Behaviour

... They play for 20 seconds then stop playing.. I can see it buffering but pushing play on the remote does nothing.  My internet is 100mb/s and never have any issues with it

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ctschalk** [comment]
Also, sometimes they work fine.  It happens often and random

**Comment by eldegos** [comment]
This is not an issue with the app, it’s an issue with VLC Kit unfortunately, so it’s nothing that the developers of this app can do. But a fix is just pausing the show/film for about 10 seconds before it starts playing, that should let the films/shows play without interruption

**Comment by angryDuck2** [comment]
Exactly, plus if you just let it wait for some time, it will eventually resume! Mind you just pausing at the beginning of the stream will be much faster!

**Comment by haythamelkhoja** [comment]
Hi, I understand that this is a VLC kit issue, but can't we get both developers (PopcorntimeTV and VLC Kit) to address it?

Also, in the mean time, can't popcorntimetv simply workaround the issue by pausing 10 sec in the beginning of every film/show and writing "buffering" or whatever, this way it's transparent to the user.

**Comment by angryDuck2** [comment]
Unfortunately there is no single number that will do just that, since torrents vary widely in speed, availability and size, hence just choosing a single number might fix some torrents, break some others. Apart from that the internet connection that users of this app have vary incredibly. In general there is no good workaround to this!
