### ISSUE TITLE
search for tv shows dont work, they only show movie results 

### ISSUE THREAD

**Issue by Group46** [PopcornTimeTV/PopcornTimeTV#513]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
show tv show results 
...

#### Actual Behaviour
only show movie results 
...

#### Steps to reproduce the behaviour

Go on search tab and search for a tv show name with no results coming up

**Comment by angryDuck2** [comment]
Unfortunately there is a bug with the uisearchcontroller class in tvOS. But there is a workaround built into the application. Just leave the search tab and go back to it and you will see the filtering options
