### ISSUE TITLE
Top Shelf Not Showing Cover Art

### ISSUE THREAD

**Issue by thekennygreene** [PopcornTimeTV/PopcornTimeTV#514]
App version: latest
tvOS version: latest

Make sure these boxes are checked before submitting your issue - thanks!

- [ x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Steps to reproduce the behaviour

On the Apple TV 4 on latest Version. After the install of the newest popcorn time ipa, I lost the top shelf cover art on the Apple TV home screen.

**Comment by angryDuck2** [comment]
Hello there, do you mean that you see the top shelf and there are movies and shows there, just without the covers, or is nothing there?

**Comment by thekennygreene** [comment]
Movies and TV Shows there, just without covers

**Comment by PerPerJB** [comment]
Its the same with many covers on the ios version aswell.

**Comment by thekennygreene** [comment]
![8d9207c3-30b5-49fb-ab21-e8b5d14c1c19](https://user-images.githubusercontent.com/34927819/35879187-328ce5f8-0b40-11e8-9b65-f2de2a0a91c2.jpeg)

**Comment by thekennygreene** [comment]
![b6cfec30-4ae1-462d-8e0c-f55ba33167de](https://user-images.githubusercontent.com/34927819/35879244-54e4486c-0b40-11e8-8b9b-6388c4959d9f.jpeg)

**Comment by angryDuck2** [comment]
Issue has been identified and will be fixed in the next version. Thank you for reporting this!

**Comment by majedsahi** [comment]
As `thekennygreene` mentioned above. I also get the cover placeholders but no artwork. I am currently on 3.1.3, reluctant to update until this has been sorted. Thanks

**Comment by thekennygreene** [comment]
Majedsahi, this problem was fixed in the latest release.
