### ISSUE TITLE
Movies crash, tv episodes play fine iOS

### ISSUE THREAD

**Issue by misswhitetiger** [PopcornTimeTV/PopcornTimeTV#515]
App version: 3.2.0
iOS/tvOS version: iOS 9.3.2 iPad Pro 9.7" jailbroken

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... Play the desired movie

#### Actual Behaviour

... Crashes after torrent is buffered on iOS native video player

#### Steps to reproduce the behaviour

1. ... Play any movie
2. ...
3. ...

All defaults selected in settings. Tried multiple movies same result. PCT version 3.1.0 on the same device plays the movies fine.

**Comment by angryDuck2** [comment]
Thank you for reporting this issue, it is currently under investigation

**Comment by angryDuck2** [comment]
Issue has been identified and solution will be integrated in the next version of the application. Thanks for reporting
