### ISSUE TITLE
External link

### ISSUE THREAD

**Issue by djsuit** [PopcornTimeTV/PopcornTimeTV#516]
App version: 3.2.0
iOS/tvOS version: 11.2.5

When adding a external Magnet link, PopcornTime crashes.

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...Open external link

#### Actual Behaviour

...crashes to Appletv 4k home screen

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by angryDuck2** [comment]
Please post here the magnet link you were trying to open. Make sure to post it from the same device you entered it into the popcorn website. Thank you for reporting this issue

**Comment by djsuit** [comment]
Gomorra S03 E03 - 1080p x265 HEVC - ITA (ENG SUBS) [BRSHNKV].torrent

**Comment by djsuit** [comment]
Sorry. Wrong one

magnet:?xt=urn:btih:27d1fb60b8255d6eb8533fcca707935e1c5998b2&dn=Suburra%20S01%201080p%20WEB%20x264-MIXED&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce

**Comment by angryDuck2** [comment]
Ok I have checked this torrent out and unfortunately it is not currently supported by the application. We do not support torrents with more than one video on them currently. It is in our plans to do so but not with this version! If you would like to see this functionality added please open another issue claiming so. Thank you for reporting this issue! This torrent should play, but you will be able to watch only the video with the largest video file!

**Comment by PerPerJB** [comment]
I thought that popcorn time did not support apple tv 5th gen (4k)? It says it only supports 4th gen, am i wrong? i can't find out myself, i don't have a 4k apple tv.

**Comment by angryDuck2** [comment]
We do support the 5th gen(4k) apple tv but without any 4k video sources! Only up to 1080p

**Comment by PerPerJB** [comment]
Okey, good to know!
