### ISSUE TITLE
Stream freezes when beginning to watch Movies/TV Shows

### ISSUE THREAD

**Issue by ryannixon** [PopcornTimeTV/PopcornTimeTV#517]
App version:
tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

When clicking the torrent and selecting the quality of torrent it would play without disturbance.

#### Actual Behaviour

When clicking the torrent and selecting the quality the torrent would begin to play, after about 7 seconds it would freeze - I would try to pause and play but nothing happens (remains in frozen state) Same happens when trying to scrub the Movie/TV Show. It takes me to go back to the cover screen and reselect the quality. I would then pause the Movie/TV Show when it begins to play for about 4-6 minutes until it loads. My internet speed is around 65-85 mb/s.

#### Steps to reproduce the behaviour

1. Click on Movie/TV Show
2. Select quality
3. Movie/TV Show will play - and it should freeze after about 7-10 seconds.

I hope this not just me. I have had the last 4 builds of Popcorn time and issue still persists. I really appreciate the developers commitment! Thank You!

**Comment by eldegos** [comment]
This is (most likely) the same thing as issue #512, it’s VLC Kit, so nothing the developers can do about, try pausing the film/show for about ten seconds when it’s loaded in and it should work just fine

**Comment by ryannixon** [comment]
Ok! I will do this! Thank you for replying to me!

**Comment by eldegos** [comment]
Let me know if it helps!

**Comment by angryDuck2** [comment]
Duplicate issue, please search for issues before posting new ones!
