### ISSUE TITLE
Popcorn time not working right with Hdmi adapter movies / tv shows super zoomed in

### ISSUE THREAD

**Issue by Fonzee9** [PopcornTimeTV/PopcornTimeTV#519]
App version:
iOS/tvOS version: iOS 11.2.2 iPhone 8 Plus

Make sure these boxes are checked before submitting your issue - thanks!

 If app was installed using Cocoapods, make sure the latest version of master has been cloned (git reset --hard; git pull). If app was installed by downloading an .ipa file, please make sure you have the latest version installed. 
Check 
 You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal. 
Check
 You have read the Issue Contributing Guidelines for this repository. 
Check
Expected Behaviour
I plug in the Hdmi Adapter to my iPhone to watch a movie /  tv show on the Tv, and it shows up on the screen and the movie / tv show looks normal.

Actual Behaviour
When i plug in the Hdmi Adapter to my iPhone the movie / tv show is so zoomed in on the TV so zoomed that i can't even watch it on my TV

Steps to reproduce the behaviour
Plug in the Hdmi Adapter to you're iPhone or iPad and try and watch a movie / tv show and you'll notice it's zoomed in like heck and you can't zoom it out.

**Comment by angryDuck2** [comment]
The issue has been identified and will be fixed in the next release. Thank you very much for reporting this issue!

**Comment by Fonzee9** [comment]
Do you know when the next release will come out i really want to use Popcorn time on my Tv? 👍
