### ISSUE TITLE
Small font size still too big

### ISSUE THREAD

**Issue by Mossito** [PopcornTimeTV/PopcornTimeTV#52]
Hello
Congratulations!! the app is working really good now, love it!!

Please could you add in the fonts size options another even smaller than small? Im using a projector for watching movies and it is still too big for me.

Thank you very much!
Best regards

**Comment by abufreeh** [comment]
actually still problem with subs handle ! , what is the source for subs ..? is it opensubtitles? or subcenter ... is that possible to choose? which source to take , it will be great


BR

**Comment by joaomvfsantos** [comment]
@abufreeh Just my opinion, PopcornTime should just work, the user shouldn't need to worry about trivial stuff like selecting sources for subtitles etc, it should just press a button and start watching, PopcornTime should figure everything by itself. I'm guessing if you need all that level of customization there are better alternatives out there like Kodi for example.
