### ISSUE TITLE
Problem to install the app

### ISSUE THREAD

**Issue by mixeta** [PopcornTimeTV/PopcornTimeTV#52]
Hello, 
I'm trying to install the app on my apple tv 4 and I get this problem after following your tutorial:

An App ID with Identifier 'com.popcorntime.PopcornTime' is not available. Please enter a different string.

Could you let me know what to do?
Thanks!

**Comment by litengulfisk** [comment]
In xcode, you will find "Bundle identifier" saying: "com.popcorntime.PopcornTime" just change that some something else like "com.your-name.popcorntime.PopcornTime" and flick on the "Fix issue" button below.

**Comment by mixeta** [comment]
Thank you!!!! That fixed the issue!!
