### ISSUE TITLE
Apple tv subtitle issue

### ISSUE THREAD

**Issue by clopex** [PopcornTimeTV/PopcornTimeTV#520]
Hello, 

can you fix issue with searching subtitle on Apple TV 4, it's very hard to scroll and to find subtitles

Thanks

**Comment by angryDuck2** [comment]
You can always just set your preferred subtitle language in settings and have it applied every time automatically, when available for a video

**Comment by clopex** [comment]
there is no Croatian, Serbian or Bosnian in settings, that is why I must change within movie

**Comment by angryDuck2** [comment]
Well this is the fix then. We will be adding croatian and bosnian languages in the default subtitle selection menu
