### ISSUE TITLE
Issues with accents in subtitles 

### ISSUE THREAD

**Issue by ceuaugusto** [PopcornTimeTV/PopcornTimeTV#521]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Show regular accents in subtitles. Example: café, pátria, nós...

#### Actual Behaviour

Letters with accents are replaced by '?' character. Ex: caf?, p?tria, n?s...

I've tried to change the encoding, before (in settings menu) and after the movie started (within the player), but none of them solved the problem.

#### Steps to reproduce the behaviour

1. Set the subtitles to Portuguese
2. Play any movie or TV show
3. See the bug when the subtitle appears

**Comment by angryDuck2** [comment]
If none of the available encodings were able to resolve this issue I am afraid there is nothing more that we can do! It is dependent on the VLC player we are using and them adding support for accents in their implementation!
