### ISSUE TITLE
Instructions within

### ISSUE THREAD

**Issue by OKNoah** [PopcornTimeTV/PopcornTimeTV#523]
1. Clone the repo through the UI or `git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git`. Wait, and then go to the newly made directory `cd PopcornTimeTV`.

1. Open the `Podfile` like `open Podfile` and change the version number of this line to `2.2.0` (as shown: `pod 'AlamofireXMLRPC', '~> 2.2.0'` (old value is `2.1.0`).

1. There are two drop-down menus in the top right go the centre column. Make sure the top says PopcornTime. Then, go through each entry in the second menu and and "Signing" select your name in the Team dropdown.

<img width="387" alt="screen shot 2018-02-08 at 6 04 08 pm" src="https://user-images.githubusercontent.com/3739277/36011516-b3da7c7e-0d0c-11e8-955e-c2e944aa1f39.png">

4. Go to `Product > Archive` and wait for the process to complete.

1. The "Archives" view will open. From here, right click the most recently try and click "Show in Finder". Leave Finder open for now. You may close the Archives window.

1. Attach your Apple device. If the main window now says you must register the device under the "Signing" area, click to do so.

1. Press CMD + Shift + 2 to open the "Devices and Simulators" windows which should show your Apple device.

1. Open the Finder window with the archive, right click the archive, and click "Show package contents".

1. Go to Products > Applications and drag the sold "PopcornTime" file into the Devices and Simulators window, into the section called "installed apps". Wait a few short minutes, and you're done.

**Comment by angryDuck2** [comment]
Hello and thank you for this issue. Exactly what is the point of this?

**Comment by OKNoah** [comment]
The purpose is to help folks i stall this app.

I discovered a few bugs along the ways that’s i’ve made PRs for too.

Will perhaps do a PR with similar text.

**Comment by angryDuck2** [comment]
Thanks for the help. But there are instructions available already https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Archiving-Popcorn-Time

They do work quite well I think. Plus we distribute ready .ipa files with every release!

**Comment by OKNoah** [comment]
@angryDuck2 Here is my fix for the bug that breaks those instructions: https://github.com/PopcornTimeTV/PopcornTimeTV/pull/522

However, other parts are incomplete and out-dated. Do you mind if I make some changes?

**Comment by angryDuck2** [comment]
Nope not at all, submit PRs away! Yes I will be merging in the #522 . Thank you for that! Closing this issue then
