### ISSUE TITLE
Build errors / new app icon 

### ISSUE THREAD

**Issue by FuzzyNutz** [PopcornTimeTV/PopcornTimeTV#525]
I know your uploading the .ipa now I just thought u would like to know the errors I'm getting when trying to build, I would like to be able to build tho because I change the app icon to the iOS version. I think it was supposed to be changed in the past but the devs never got around to doing it, I have the .png if u need it.

![img_2843](https://user-images.githubusercontent.com/26355018/36024961-6c45bf4c-0d5f-11e8-8161-de33672a576f.JPG)

![img_2841](https://user-images.githubusercontent.com/26355018/36024758-b4c7fe0c-0d5e-11e8-9912-8751b78cf5e1.JPG)

**Comment by angryDuck2** [comment]
if you pull the master branch now and perform a pod update, all these errors should go away!

**Comment by FuzzyNutz** [comment]
Ok thank you
