### ISSUE TITLE
Popcorn Time not loading Movie screen in landscape mode on iPad

### ISSUE THREAD

**Issue by Fonzee9** [PopcornTimeTV/PopcornTimeTV#526]
App version:
iOS/tvOS version: iOS 11.1.2 iPad Pro 12.9 2nd gen

Make sure these boxes are checked before submitting your issue - thanks!

- [check ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [check ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ check] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

When i'm in landscape mode and i press a movie it loads.

#### Actual Behaviour

It loads infinitely with the circle loading screen in landscape mode.

#### Steps to reproduce the behaviour

Click on a movie to watch and be in landscape mode you'll notice it doesn't load the screen.

**Comment by Fonzee9** [comment]
It's working now.

**Comment by angryDuck2** [comment]
This is a known bug, it will be fixed in the next release, coming soon. Along with a lot of other things! Thank you for reporting this
