### ISSUE TITLE
4K Torrent Streaming for Apple TV4K and DD 5.1 

### ISSUE THREAD

**Issue by fdm96** [PopcornTimeTV/PopcornTimeTV#528]
Hell0 PopcornTime Team,

Welcome back 💯  I am very pleased, 

Is there a chance to get **4K Torrent Streaming for Apple TV 4K and Dolby Digital 5.1** support in PopcornTime? Or is it a problem of torrent sources?

Thx for your work... 👍 

Greez fdm96

mytvOS version:
AppleTV4K 11.3 Beta 2 🔢

**Comment by popcornMaster** [comment]
Hello and thank you for your suggestion. I am afraid this is going to have to be put back for a while. Unfortunately our torrent sources do not currently provide 4K content. You are always welcome to choose your own torrent in 4K and open them. I believe that VLC should be compatible with 4K quality and able to process it correctly. As far as Dolby digital is comcerned I am afraid that this is a copyrighted technology that we will never be able to get our hands on without a proper license from their creators, hence this will never come to be!
