### ISSUE TITLE
Swift 

### ISSUE THREAD

**Issue by The1PRimeYT** [PopcornTimeTV/PopcornTimeTV#53]
![screen shot 2016-08-30 at 4 57 44 pm](https://cloud.githubusercontent.com/assets/21149526/18106702/eb9aad52-6ed2-11e6-9851-4a16eb2e8172.png)

Hello what do i do here i know am using the beta but this is the first time that this popup so what o i do it because Xcode 7.3 docent want to download

**Comment by Hackormahn** [comment]
Do not do it, we have not made this for Swift 3 yet.

**Comment by The1PRimeYT** [comment]
can u guys pls do i really need it

**Comment by rafaelfsramos** [comment]
Man, you should need restore your apple tv for 9.2. Don't use tvOS 10. Wait for release new version.
