### ISSUE TITLE
Search function in TVOS

### ISSUE THREAD

**Issue by PrimeX7** [PopcornTimeTV/PopcornTimeTV#530]
App version: 3.2.5
iOS/tvOS version: 11.2.5

Make sure these boxes are checked before submitting your issue - thanks!

- [Y ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ Y] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ Y] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... search for the tv show i wanted

#### Actual Behaviour

... doesn't do anything. looks like it might only be searching for movies

#### Steps to reproduce the behaviour

1. ...In tvos go to search and search for any tv show. It will not work. Issue was fixed in app version 3.2.0 when you first came back on. For some reason this stopped working. 

I am using the IPA file that is provided with the releases.

**Comment by angryDuck2** [comment]
Please see #513
