### ISSUE TITLE
PLEASE ADD PORTUGUESE BRAZIL SUBTITLES

### ISSUE THREAD

**Issue by diegosm3** [PopcornTimeTV/PopcornTimeTV#533]
Portuguese is different from Portuguese Brazil, please add this option.

**Comment by ceuaugusto** [comment]
There are these instructions on a thread of another project here on GitHub (Popcorn Time as well) that can be useful:

> On class SubtitlesManager.swift, on line 23, change the "search" method by this:
> 
> ```
> open func search(_ episode: Episode? = nil, imdbId: String? = nil, limit: String = "500", completion:@escaping ([Subtitle], NSError?) -> Void) {
>         guard let token = token else {
>             login() { error in
>                 guard error == nil else { completion([], error); return }
>                 self.search(episode, imdbId: imdbId, limit: limit, completion: completion)
>             }
>             return
>         }
>         var params = ["sublanguageid": "pb,pob,por,eng"]
>         if let imdbId = imdbId {
>             params["imdbid"] = imdbId.replacingOccurrences(of: "tt", with: "")
>         } else if let episode = episode {
>             params["query"] = episode.title
>             params["season"] = String(episode.season)
>             params["episode"] = String(episode.episode)
>         }
>         let limit = ["limit": limit]
>         let queue = DispatchQueue(label: "com.popcorn-time.response.queue", attributes: DispatchQueue.Attributes.concurrent)
>         self.manager.requestXMLRPC(OpenSubtitles.base, methodName: OpenSubtitles.search, parameters: [token, [params], limit], headers: OpenSubtitles.defaultHeaders).validate().responseXMLRPC(queue: queue) { response in
>             guard
>                 let value = response.result.value,
>                 let status = value[0]["status"].string?.components(separatedBy: " ").first,
>                 let data = value[0]["data"].array,
>                 response.result.isSuccess && status == "200"
>                 else {
>                     return DispatchQueue.main.async {
>                         completion([], response.result.error as NSError?)
>                     }
>             }
>             var subtitles = [Subtitle]()
>             for info in data {
>                 guard
>                     let subDownloadLink = info["SubDownloadLink"].string?.replacingOccurrences(of: ".gz", with: ""),
>                     let ISO639 = info["ISO639"].string,
>                     let localizedLanguageName = Locale.current.localizedString(forLanguageCode: ISO639)?.localizedCapitalized,
>                     let rating = Double(info["SubRating"].string ?? "")
>                     else {
>                         continue
>                 }
> ```
>                 
>                 let subtitle = Subtitle(language: localizedLanguageName, link: subDownloadLink, ISO639: ISO639, rating: rating)
>      
>                 subtitles.append(subtitle)
>             }
>             
>             DispatchQueue.main.async(execute: { completion(subtitles, nil) })
>         }
>     }

I hope it was helpful! Thanks in advance!

**Comment by diegosm3** [comment]
Hey buddy,

So I know how to install the ipa file on my AppleTV (TvOs) but i dont know how to program and build the ipa file for my apple tv. May I ask you something? Can you build this for me with portuguese subtitles, for my Apple TV? Please I will very glad. Hugs.

Sent from my iPhone

On 14 Feb 2018, at 13:07, ceuaugusto <notifications@github.com<mailto:notifications@github.com>> wrote:


There are these instructions on a thread of another project here on GitHub (Popcorn Time as well) that can be useful:

On class SubtitlesManager.swift, on line 23, change the "search" method by this:

open func search(_ episode: Episode? = nil, imdbId: String? = nil, limit: String = "500", completion:@escaping ([Subtitle], NSError?) -> Void) {
        guard let token = token else {
            login() { error in
                guard error == nil else { completion([], error); return }
                self.search(episode, imdbId: imdbId, limit: limit, completion: completion)
            }
            return
        }
        var params = ["sublanguageid": "pb,pob,por,eng"]
        if let imdbId = imdbId {
            params["imdbid"] = imdbId.replacingOccurrences(of: "tt", with: "")
        } else if let episode = episode {
            params["query"] = episode.title
            params["season"] = String(episode.season)
            params["episode"] = String(episode.episode)
        }
        let limit = ["limit": limit]
        let queue = DispatchQueue(label: "com.popcorn-time.response.queue", attributes: DispatchQueue.Attributes.concurrent)
        self.manager.requestXMLRPC(OpenSubtitles.base, methodName: OpenSubtitles.search, parameters: [token, [params], limit], headers: OpenSubtitles.defaultHeaders).validate().responseXMLRPC(queue: queue) { response in
            guard
                let value = response.result.value,
                let status = value[0]["status"].string?.components(separatedBy: " ").first,
                let data = value[0]["data"].array,
                response.result.isSuccess && status == "200"
                else {
                    return DispatchQueue.main.async {
                        completion([], response.result.error as NSError?)
                    }
            }
            var subtitles = [Subtitle]()
            for info in data {
                guard
                    let subDownloadLink = info["SubDownloadLink"].string?.replacingOccurrences(of: ".gz", with: ""),
                    let ISO639 = info["ISO639"].string,
                    let localizedLanguageName = Locale.current.localizedString(forLanguageCode: ISO639)?.localizedCapitalized,
                    let rating = Double(info["SubRating"].string ?? "")
                    else {
                        continue
                }


            let subtitle = Subtitle(language: localizedLanguageName, link: subDownloadLink, ISO639: ISO639, rating: rating)

            subtitles.append(subtitle)
        }

        DispatchQueue.main.async(execute: { completion(subtitles, nil) })
    }
}


I hope it was helpful! Thanks in advance!

**Comment by ceuaugusto** [comment]
@diegosm3 fala, cara! Tô na mesma situação que você! Rs! Colei essas instruções acima pro pessoal que gerencia esse app pra que eles possam fazer essa implementação. Vamos ficar no aguardo de acatarem nossa sugestão e implementarem. Abs!

**Comment by diegosm3** [comment]
@ceuaugusto Vamos torcer para que consigam fazer isso sim, sabe me informar se o app para o iphone funciona? Valeu abraços!

**Comment by ceuaugusto** [comment]
@diegosm3 pelo que vejo aqui, deve funcionar sim, mas nunca testei.

**Comment by popcornMaster** [comment]
Unfortunately the code that you provided does not work at all. The issue here is that you language is recognized by apple with the language sort code pt_BR and the Opensubtitles report it as pb and so we are unable to map it to a language name when we receive it from OpenSubtitles. This is because your language is not included in the ISO693 officially and so its implementation is dependent on the code writer!

**Comment by diegosm3** [comment]
Ok I got it, but I realized that may have another option, because WINDOWS 1252 work it with PT_BR, but somehow have a way to implement this. Thanks for the answer. Hugs.


Diego Santos Moura

Tel (81) 3228 9688

Cel (81) 99755 5187

Diegosm3@outlook.com


________________________________
De: popcornMaster <notifications@github.com>
Enviado: quarta-feira, 21 de fevereiro de 2018 12:01
Para: PopcornTimeTV/PopcornTimeTV
Cc: Diego Moura; Mention
Assunto: Re: [PopcornTimeTV/PopcornTimeTV] PLEASE ADD PORTUGUESE BRAZIL SUBTITLES (#533)


Unfortunately the code that you provided does not work at all. The issue here is that you language is recognized by apple with the language sort code pt_BR and the Opensubtitles report it as pb and so we are unable to map it to a language name when we receive it from OpenSubtitles. This is because your language is not included in the ISO693 officially and so its implementation is dependent on the code writer!

**Comment by popcornMaster** [comment]
The upcoming release will include this feature, but mind you the language in the selector will still show up as "Portuguese", you will just have 2 Portuguese subtitle selections, one of them will be for Brazilian Portuguese

**Comment by ceuaugusto** [comment]
That's awesome! Many thanks!

**Comment by popcornMaster** [comment]
Closing this as implemented

**Comment by CavalcanteLeo** [comment]
Pessoa, apesar de eles ter implementado, eu adicionei uns códigos para mostrar TODAS as legendas em português, e não somente uma, como o Popcorn faz

no arquivo SubtitlesManager.swift  (https://github.com/PopcornTimeTV/PopcornTimeTV/blob/2551e80128390b4b5842c8405fadfae4e89f7c30/PopcornKit/Managers/SubtitlesManager.swift#L68)

<img width="1058" alt="captura de tela 2018-04-14 as 16 44 34" src="https://user-images.githubusercontent.com/1735944/38771989-2eabbb1a-4003-11e8-88c6-282e78dd1e2d.png">
mudar disso:
```swift
                let subtitle = Subtitle(language: localizedLanguageName, link: subDownloadLink, ISO639: ISO639, rating: rating)
                
                if let same = subtitles.first(where: {$0.ISO639 == ISO639}),
                    let index = subtitles.index(of: same) {
                    if rating > same.rating {
                        subtitles[index] = subtitle
                    }
                } else {
                   subtitles.append(subtitle)
                }
```



<img width="1059" alt="captura de tela 2018-04-14 as 16 44 51" src="https://user-images.githubusercontent.com/1735944/38771991-3188e56a-4003-11e8-8d4c-762f4bb23bd3.png">

para isso:
```swift
let subtitle = Subtitle(language: localizedLanguageName.localized, link: subDownloadLink, ISO639: ISO639, rating: rating)

if (subtitle.ISO639.lowercased().range(of:"pt") != nil){
    subtitles.append(subtitle)
}else if let same = subtitles.first(where: {$0.ISO639 == ISO639}),
    let index = subtitles.index(of: same) {
    if rating > same.rating {
        subtitles[index] = subtitle
    }
} else {
    subtitles.append(subtitle)
}
```

**Comment by CavalcanteLeo** [comment]
@popcornMaster 

just add an if to check if the if it has pb or pob, then append BR at the end of the string

```swift
    var tmpLanguage = localizedLanguageName

    //append BR at the end
    if ISO639 == "pb" || ISO639 == "pob" {
        tmpLanguage = NSString(format: "%@ BR", localizedLanguageName) as String
    }
    
    // also use capitalized for sorting correctly 
    let subtitle = Subtitle(language: tmpLanguage.capitalized, link: subDownloadLink, ISO639: ISO639, rating: rating)
                
```

**Comment by ceuaugusto** [comment]
@CavalcanteLeo você fez isso em uma versão que você baixou e modificou? Ou fez essa alteração no código disponibilizado nesta página? Valeu!

**Comment by CavalcanteLeo** [comment]
@ceuaugusto , dessa página
