### ISSUE TITLE
Home indicator bar not hidden during playback on iPhone X

### ISSUE THREAD

**Issue by GenuineButter** [PopcornTimeTV/PopcornTimeTV#538]
App version: 3.2.5
iOS/tvOS version: iOS

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Hide the iPhone X home indicator bar after a few seconds during playback, only revealing it when swiping up from the bottom.

#### Actual Behaviour

The iPhone X home indicator bar remains on-screen during playback.

#### Steps to reproduce the behaviour

1. Play a video on an iPhone X

**Comment by popcornMaster** [comment]
Thank you for reporting this issue. It has been identified and will be fixed in the next update
