### ISSUE TITLE
Cydia Impactor encounters error

### ISSUE THREAD

**Issue by louuuleung** [PopcornTimeTV/PopcornTimeTV#539]
App version: 3.2.5
iOS iPad version: 11.2.5 (15D60)

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... Using Cydia Impactor to install Popcorn.ipa encounter error "provision.cpp.138 maxQuantity"

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by popcornMaster** [comment]
http://lmgtfy.com/?q=provision.cpp.138+maxQuantity
