### ISSUE TITLE
program crash when i activated trait.tv account

### ISSUE THREAD

**Issue by dincer54** [PopcornTimeTV/PopcornTimeTV#54]

**Comment by dincer54** [comment]
trakt.tv account

**Comment by maitremiju** [comment]
Hello,

Same issue here. When I activate trakt the app stops working.
Reboot of AppleTV doesn't help, the app just shows white screen.

I have to uninstall and start over.

JuMi

**Comment by FlaviaBondJamesBondsHusband** [comment]
Could you connect your apple TV to your computer, open Xcode and run the application while it is connected and then screenshot the stack trace [http://i.stack.imgur.com/zfirG.pnghttp://i.stack.imgur.com/zfirG.png](url) and post a reply with the picture

**Comment by FlaviaBondJamesBondsHusband** [comment]
As stated in release notes, you must delete the app and reinstall in order for trakt to work
