### ISSUE TITLE
Movies stop after 5 sec

### ISSUE THREAD

**Issue by Gsuz** [PopcornTimeTV/PopcornTimeTV#54]
at the 0.4.2 version. The movie starts but then stops after 5 sec. No amount of waiting will fix it.

**Comment by tengis** [comment]
@buzzel same issue we discussed on slack

**Comment by Gsuz** [comment]
tried star wars and "sisters" they both stop after 5 sec. Then again some 3rd movie i tried actually played for like 3-4 min before stopping.

**Comment by buzzel** [comment]
Can any of you guys confirm this is happening on TV shows as well?

**Comment by Sonikkua** [comment]
@buzzel Tried your fix of reverting to the older version of PopcornTorrent 1.0.7, and I'm 10 minutes into a film and no issues, so that fix seems to have done the trick. 👍

**Comment by sasagr** [comment]
this fix worked for me too

**Comment by buzzel** [comment]
Okay cool. Going to move this issue over to the PopcornTorrent repo.
