### ISSUE TITLE
Can't load details page of certain TV shows

### ISSUE THREAD

**Issue by ascarrambad** [PopcornTimeTV/PopcornTimeTV#540]
App version: Currently on 3.2.5, issue present at least since 3.1.2
iOS/tvOS version: iOS 11.2.5

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
After selecting a TV show it should load info, season and episodes.

#### Actual Behaviour
For certain types of TV shows, such as "Real Time with Bill Maher", apps presents unknown error.

#### Steps to reproduce the behaviour
Just search for the late night of your choice and try to watch it

**Comment by popcornMaster** [comment]
Thank you for reporting this issue. It has been identified and will be fixed in the next update
