### ISSUE TITLE
The Video/Streaming allways stops at the begining

### ISSUE THREAD

**Issue by jlillop** [PopcornTimeTV/PopcornTimeTV#543]
App version: 3.2.5
iOS/tvOS version: tvOS

Make sure these boxes are checked before submitting your issue - thanks!

- [ X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Dont stop the video once is started

#### Actual Behaviour

The video and audio is stopped after a few seconds of having started. NOTE: the seconds in the menu bar continues.

#### Steps to reproduce the behaviour

1. Select a movie/show
2. Play in streaming

**Comment by pascualin** [comment]
I get the same problem. As a workaround I need to press Pause as soon as the movie/show starts playing, wait about 30 seconds and then press Play again. This prevents it from freezing, but it would be nice to fix the issue.

**Comment by popcornMaster** [comment]
Since so many people have been requesting this(#517 ) we will be incorporating a fix in the next release, expect much longer pre-load times though, 3-8 minutes longer
