### ISSUE TITLE
Settings : Theme Song Volume

### ISSUE THREAD

**Issue by jlillop** [PopcornTimeTV/PopcornTimeTV#544]
App version: 3.2.5
iOS/tvOS version: tvOS

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Allow to change the theme song volume

#### Actual Behaviour

Nothing.

#### Steps to reproduce the behaviour

1. Go to setting
2. Select "Theme song volume"
3. select "50%"

**Comment by popcornMaster** [comment]
I am sorry but we were unable to replicate your issue! There may not be a huge difference with a low TV volume setting but there is one! Just try 25% to 100% levels. You will see quite a difference!
