### ISSUE TITLE
Movies - MDP gets unscrollable to up on Download button

### ISSUE THREAD

**Issue by sweetw0r** [PopcornTimeTV/PopcornTimeTV#548]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

User should be able to scroll up to the very top of a MDP

#### Actual Behaviour

User gets stuck on Download button. Can't scroll up

#### Steps to reproduce the behaviour

1. Open the app > Movies > Movie description page (MDP)
2. Scroll down to Cast & Crew section 
3. Scroll up to Play button

tvOS version 10.3
![screen shot 2018-02-18 at 11 07 22 pm](https://user-images.githubusercontent.com/12688470/36365944-b3cd1614-1500-11e8-9f1f-885ff4d33551.png)

**Comment by popcornMaster** [comment]
First of all the screenshot that you are showing here is not from our application, since this is not how we present the download button within a movie but within the tv shows page. So I took the liberty to try with both views. [Here are my results](https://imgur.com/a/m6L6E)

**Comment by sweetw0r** [comment]
Were you on tvOS 10.3? I am. I see somehow you don't have "Label" section while it is populating for me. I was building the latest version of master. [Here is my result of movie view](http://recordit.co/Hk6uDOWwXh). Notice x2 Download buttons?

**Comment by popcornMaster** [comment]
Wow! That is some disturbing thing! You are basically seeing both a movie view and a tv show view into one window! Ok we will check this out and come back to you!

**Comment by popcornMaster** [comment]
I am afraid that I have been unable to replicate your issue! Please try to download the .ipa available [here](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/tag/3.2.6) and check if the issue resolves for you

**Comment by sweetw0r** [comment]
.ipa appears to be fine. It happens only when I build it myself. But why?
