### ISSUE TITLE
TVOS - Pressing Menu takes you to Home Screen

### ISSUE THREAD

**Issue by majedsahi** [PopcornTimeTV/PopcornTimeTV#549]
App version: 3.2.5
iOS/tvOS version: 11.2.5

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
Pressing Menu on Apple TV 4 remote should go back to the previous menu. Pressing it multiple times will evantually go back to Home Screen.  
...

#### Actual Behaviour
If you select a Trending movie from the Apple TV Home Screen Top draw, this will take you to the movie page. Here pressing Menu takes you back to Home Screen, rather than previous page. However if you press up or down then press Menu, it will take you to the previous screen. 
This seems like an intended feature however it is a bit annoying if you press on a movie but decide not to watch it and want to go back to the previous page, while staying within the app.   
...

#### Steps to reproduce the behaviour

1. ... From the Home Screen press a movie title
2. ... Decide you don’t want to watch the movie/trailer 
3. ... Press Menu to show all movies, it will take you back to Home Screen instead.

**Comment by sweetw0r** [comment]
Happens all the time. Workaround is to scroll until the main menu disappears then press MENU button on RC.

**Comment by grandxadmiral** [comment]
This seems to be fixed in 3.2.6 – Hooray, and thank you to devs.

**Comment by sweetw0r** [comment]
Confirm. Fixed in 3.2.6. Can be closed

**Comment by angryDuck2** [comment]
Closing
