### ISSUE TITLE
4.3 not installing.

### ISSUE THREAD

**Issue by d1cee** [PopcornTimeTV/PopcornTimeTV#55]
Have pulled the latest update but i get this when compiling to apple tv 

"App installation failed"
"An unknown error has occurred".

**Comment by buzzel** [comment]
Have you tried running a Build & Clean and Restarting both Xcode and the device? A lot of time doing that fixes the issue

**Comment by d1cee** [comment]
tried a few times now works

**Comment by buzzel** [comment]
Sweet, glad its all working now.
