### ISSUE TITLE
Some video audio not playing correctly

### ISSUE THREAD

**Issue by CokePokes** [PopcornTimeTV/PopcornTimeTV#550]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Video audio should not glitch

#### Actual Behaviour

Audio is very jacked up, not sure if it has to do with a unsupported codec, even when playing the lower quality video.

#### Steps to reproduce the behaviour

1. An example movie would be "Harry Potter & The Deathly Hollows Part 2." The audio is not working. Perhaps you could add a "report video button" so there isn't any movies being unplayable on the PopcornTime app?

**Comment by popcornMaster** [comment]
We have been unable to replicate this issue! Tried with multiple movies and tv shows and none of them had an issue. We should be updating the VLC media player with the next version that will bring some much needed stability to the video playback. I will close this issue for now, if you have any more issues please go ahead and comment on this one and we will reopen it!
