### ISSUE TITLE
iPad Pro 12.9" (landscape mode) - Stuck at loading screen after selecting random movie

### ISSUE THREAD

**Issue by aaron01437** [PopcornTimeTV/PopcornTimeTV#552]
App version: 3.2.6
iOS/tvOS version: 11.2.5

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

After at most 10-20 seconds the movie or TV Show details should load up properly.

#### Actual Behaviour

Stuck at loading screen, and app not responsive any more. The app would crash if you wait long enough after attempting to tap on any menu icons.

#### Steps to reproduce the behaviour

1. Make sure the iPad Pro 12.9" screen is in landscape mode (the app would work fine in portrait mode).
2. Tap on any of the movie. Wait for 20 seconds or so and try to tap on any icons on the screen.

**Comment by popcornMaster** [comment]
Really sorry the previous fix did not work for you. We think that we have a solution that will definitely fix it this time! It will be available on the next release! Again thanks for reporting this!
![simulator screen shot - ipad pro 12 9-inch 2nd generation - 2018-02-21 at 16 45 19](https://user-images.githubusercontent.com/20759040/36486259-c9cedd4e-1726-11e8-950f-736aeff57be7.png)

**Comment by aaron01437** [comment]
I'm sorry, just tested that it's actually working in Shows, but not for Movies. Thanks a million by working on the fix!
