### ISSUE TITLE
Trakt not working

### ISSUE THREAD

**Issue by tomto147** [PopcornTimeTV/PopcornTimeTV#553]
App version: 3.2.6
tvOS version: 11.2.5

Trakt is not syncing my watchlist any more between devices like iPhone and AppleTV version. It used to work properly o 3.2.5. I’ve downgraded and it works.

**Comment by popcornMaster** [comment]
Please fill in the issue template correctly. I do not understand what the exact issue is! Did you try to mark something as watched in iOS and it did not show in tvOS? Please fill in the issue template correctly!

**Comment by tomto147** [comment]
I’ve added some films to watchlist on iOS and they don’t sync with tvOS. Watchlist on tvOS does not show any content at all. Even the old inputs. Downgraded to 3.2.5 on both iOS and tvOS and everything is syncing properly
