### ISSUE TITLE
Media player scrubbing timeline and mute button not working

### ISSUE THREAD

**Issue by aaron01437** [PopcornTimeTV/PopcornTimeTV#555]
App version: 3.2.6
iOS/tvOS version: iOS 11.3 Public beta 2 (iPhone X)

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Tapping on the mute button to unmute button should work when attempting to unmute. Scrubbing forward on the media player timeline bar would work to move the movie progress to the right timeline. 

#### Actual Behaviour

Scrubbing forward on the media player timeline bar is causing the video to freeze and hang. After tap once on volume button to mute, the volume was muted fine - However, when I try to tap the same button to unmute, the button is not responding to unmute (even after a few try).

#### Steps to reproduce the behaviour

1. Play any movie, then tap once on the volume button on the right upper corner to mute. Try to tap again to unmute and it doesn't work. Tap a few times and it will remain the same. If you force touch, it will show a volume bar for you to scrub adjusting volume (this is working).
2. After the movie started for 1 minute or so, scrub forward on the media player timeline bar and wait. The movie would freeze and not continue loading.

**Comment by popcornMaster** [comment]
The scrubbing is an issue with VLCKit that will be fixed in the next Popcorn update since they finally made a stable version of their library compatible with the newest swift library that we will implement. The unmute button functionality has not been implemented. It should be for the next update! Thank you for reporting this!
