### ISSUE TITLE
Unable to search for tv shows? only movies can be searched

### ISSUE THREAD

**Issue by enerette** [PopcornTimeTV/PopcornTimeTV#556]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...Just try and search a tv show such as game of thrones, it will just act as if the show doesn't exist
2. ...
3. ...

**Comment by popcornMaster** [comment]
Please search for your issues before posting them! #513
