### ISSUE TITLE
Ability to load external subtitles

### ISSUE THREAD

**Issue by matiasloda** [PopcornTimeTV/PopcornTimeTV#557]
App version: 3.2.6
iOS/tvOS version: 11.2.5

Theres any chance to add the possibility to load subtitles from opensubtitles.org ?? like infuse app 
thanks

**Comment by fdm96** [comment]
App version: 3.2.8
iOS/tvOS version: 11.3 beta 3

Hello the idea would be **great** from @matiasloda 👍 or it would be possible that one could insert the subtitles themselves for example like webpage open external for subtitles ??

Thank you for the great work.... 
now is Popcorn Time :))

**Comment by fredimesper** [comment]
Yes, I would love this feature, the current subtitles are really unreliable.

**Comment by DJMpc99** [comment]
They are always not synced correctly
