### ISSUE TITLE
Add ability to connect via Proxy

### ISSUE THREAD

**Issue by sweetw0r** [PopcornTimeTV/PopcornTimeTV#558]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

The app should be able to connect with Proxy enabled profile.

#### Actual Behavior
Error shown: Unknown Error The operation couldn't be completed. (KCFERRORDOMAINCFNETWORK error 301.)
The app can't connect while Amazon Prime Video has no problem to connect

#### Steps to reproduce the behaviour

1.  Set up a proxy by Apple Profile Configurator: https://youtu.be/qVUde3kie1Q
2. Open the app

<img width="1190" alt="screen shot 2018-02-23 at 10 25 41 pm" src="https://user-images.githubusercontent.com/12688470/36626572-111e1358-18ea-11e8-9044-bce8cb8b1fdd.png">

![screen shot 2018-02-23 at 10 26 12 pm](https://user-images.githubusercontent.com/12688470/36626576-1b7bd66e-18ea-11e8-8baa-2e6b9c07f8e6.png)

To give you more insight:
I just received the following email. Which tells us that Apple TV is now being tracked as well. While we were able to get away on ATV for a while it doesn't seem to the case any more.

> Notice of Action under the Digital Millennium Copyright Act
>  
>  
> Incident Number:        IH⑄⑄⑄⑄⑄⑄⑄⑄⑄
> Report Date/Time:      ⑄⑄⑄⑄-⑄⑄-⑄⑄ ⑄⑄:⑄⑄:⑄⑄.⑄ UTC
> 
> 
> ⑄⑄⑄⑄⑄ ⑄⑄⑄⑄⑄
> ⑄⑄⑄⑄ ⑄ ⑄⑄⑄⑄ ST APT ⑄⑄⑄
> ⑄⑄⑄ ⑄⑄⑄⑄ ⑄⑄ ⑄⑄⑄⑄
> 
> 
> Dear Internet Customer:
> 
> Comcast has received a notification by a copyright owner, or its authorized agent, reporting an alleged infringement of one or more copyrighted works made on or over Comcast’s Xfinity Internet or Business-Class Internet service (the “Service”).  The copyright owner has identified the Internet Protocol (“IP”) address associated with your Service account at the time as the source of the infringing works.  The works identified by the copyright owner in its notification are listed below.  Comcast reminds you that use of the Service (or any part of the Service) in any manner that constitutes an infringement of any copyrighted work is a violation of Comcast’s Acceptable Use Policy and may result in the suspension or termination of your Service account.
> 
> If you have any questions regarding this notice, you may direct them to Comcast in one of the following formats:
> 
>                          Comcast Customer Security Assurance
>                          Comcast Cable Communications, LLC
>                          141 Woodcrest Road
>                          Cherry Hill, NJ 08003 U.S.A.
>                          Phone: (877) 842-2112
>                          Fax: (856) 324-2940
>  
> For more information regarding Comcast’s copyright infringement policy, procedures, and contact information, please read our Acceptable Use Policy for XFINITY Internet for residential customers, or our Acceptable Use Policy for High-Speed Internet Services for business customers.
>  
> Sincerely,
> Comcast Customer Security Assurance
>  
> Copyright work(s) identified in the notification of claimed infringement:
>  
> Infringing Work: Atomic Blonde
> Filename: Atomic Blonde (2017) [1080p] [YTS.AG]
> Infringement Date: ⑄⑄⑄⑄-⑄⑄-⑄⑄ ⑄⑄:⑄⑄:⑄⑄.⑄ UTC
> Infringement Type: BitTorrent
> Infringement Method: BITTORRENT
> IP Address: ⑄⑄⑄.⑄⑄⑄.⑄⑄⑄.⑄⑄⑄
> Reporting Party: IP-Echelon Compliance <p2p@copyright.ip-echelon.com>
> Reporting Party Case: ⑄⑄⑄⑄⑄⑄⑄⑄⑄⑄⑄⑄⑄⑄⑄

**Comment by popcornMaster** [comment]
Unfortunately the framework required to enable VPN on the Apple TV is not implemented by Apple(see here: [](https://developer.apple.com/documentation/networkextension)) on tvOS and nothing else equivalent is available.

**Comment by angryDuck2** [comment]
This issue you are having is due to an Authorization policy on your proxy. This needs code specifically written for your proxy setup, including dns/ip addresses of your proxy. There is not much we can do with that! Unfortunately you will have to code something up to match your specific setup. I would suggest looking this up: https://www.queryoverflow.gdn/query/handle-challenge-with-alamofire-27_44137022.html
