### ISSUE TITLE
Bug: Director/Actor names line break in wrong place

### ISSUE THREAD

**Issue by grandxadmiral** [PopcornTimeTV/PopcornTimeTV#559]
App version: 3.2.6
iOS/tvOS version: 11.2.6
✓✓✓

#### Expected Behaviour:

Names of Directors and Actors in left info panel would be listed correctly.

#### Actual Behaviour:

Names of Directors and Actors ("Starring") are breaking on the wrong lines. Example of how its displaying with Thor Ragnarok:

**DIRECTORS**
Ben CookeTaika
WaititiTaika
WaititiTom Hooper

**STARRING**
Chris
HemsworthTessa
ThompsonIdris

#### Steps to reproduce the behaviour
1. Open at any movie details screen, look at info panel on left.

**Comment by popcornMaster** [comment]
This should be fixed on v3.2.8

**Comment by popcornMaster** [comment]
@grandxadmiral Please confirm if this is fixed in the latest version!

**Comment by angryDuck2** [comment]
Closing this as resolved after not receiving an answer
