### ISSUE TITLE
Issue with TV Show Steaming(Again)

### ISSUE THREAD

**Issue by mohorani** [PopcornTimeTV/PopcornTimeTV#56]
When I try to stream a TV show, it still crashes after downloading. Here is a screenshot.
<img width="1280" alt="screen shot 2016-04-19 at 7 09 56 pm" src="https://cloud.githubusercontent.com/assets/17534565/14661409/436657a4-0662-11e6-9c96-bbabbbd94b3e.png">

**Comment by buzzel** [comment]
Only thing I can think of is this.

1. Delete your DerivedData
2. Delete the entire cloned repo
3. Reclone it and reinstalled.

**Comment by tengis** [comment]
All working fine my end

**Comment by mohorani** [comment]
I cleared the DerivedData but it still does not work in the simulator. Here is another screenshot
<img width="1280" alt="screen shot 2016-04-20 at 4 42 37 pm" src="https://cloud.githubusercontent.com/assets/17534565/14693764/c6bf92dc-0716-11e6-9137-12356f109728.png">

**Comment by buzzel** [comment]
This issue was only present in an older build. I suggest you delete everything regarding popcorntime and redownloading it

**Comment by buzzel** [comment]
Closed for being inactive.

**Comment by tengis** [comment]
Some TV Shows working some of them not. I also see exactly same error like @mohorani 

For example: Walking Dead's last episodes working but Vikings not.

**Comment by metieske** [comment]
I'm having the same issues. Almost no TVShows play. Sometimes the crash at the end of downloading and sometimes they crash at the end of processing. I can reproduce this by trying to watch Breaking Bad S01E01 480p. 
![image](https://cloud.githubusercontent.com/assets/11176517/15050119/1bf60876-12f2-11e6-9f02-c31e0169fe48.png)

Also sometimes processing doesn't even start, or stops halfway there. The app doesn't crash, nor does it hang. Also there's no useful logging at these times. App just looks like its stuck. There's no CPU usage, Disk usage or network usage.
