### ISSUE TITLE
pod update issue 

### ISSUE THREAD

**Issue by FuzzyNutz** [PopcornTimeTV/PopcornTimeTV#560]
getting this error when trying to update/install pod 
![screen shot 2018-02-25 at 8 54 31 pm](https://user-images.githubusercontent.com/26355018/36649942-8c6903e4-1a6e-11e8-8995-10ec00984ca6.png)

**Comment by CokePokes** [comment]
Can you not read? It tells you to run "pod repo update"

**Comment by FuzzyNutz** [comment]
That's an ironic question because if you read at the top that's exactly what I did 😉
"Pod repo update; pod install"

**Comment by angryDuck2** [comment]
Try performing a "pod update" command

**Comment by FuzzyNutz** [comment]
I get an error "failed to connect to Github to update the cocoapods/specs repo - please check if you are offline or that github is down" my internet is fine tho.

**Comment by angryDuck2** [comment]
This is an issue with your internet connection, therefore not an application or deployment issue. Closing this report as resolved. Pro tip: Make sure you are not behind a proxy or vpn since they may be blocking your access to the github repo through command line

**Comment by FuzzyNutz** [comment]
Never mind a simple reboot fixed the issue

**Comment by FuzzyNutz** [comment]
Actually it didn't :( I thought it was working and responded to early, I've tried using my iphones hotspot with a VPN and same issue it might be a problem with my Mac OS, will try in Linux next
