### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by helmehraz** [PopcornTimeTV/PopcornTimeTV#561]
version: 3.2.6
iOS/tvOS version: tvOs-11.2.6

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

The application shall support the French localization.
Please find attached to this issue the needed file [fr.xliff] to make the application supporting French language.

Link : https://we.tl/2dQrxM7Vap

#### Actual Behaviour

The application does not support the French localization

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by helmehraz** [comment]
fr.xliff

**Comment by helmehraz** [comment]
[fr.xliff.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/1767922/fr.xliff.zip)

**Comment by helmehraz** [comment]
closed by mistake

**Comment by popcornMaster** [comment]
Added to v3.2.8
