### ISSUE TITLE
Sync with trakt account

### ISSUE THREAD

**Issue by WindowsScorpion** [PopcornTimeTV/PopcornTimeTV#562]
After finish watching an episode or a movie it’s syncing with trakt account auto, but sending it 3 times.
In trakt website I have the movie watched 3 times
Don’t know when is the trigger of the sync

App version:
iOS/tvOS version: 3.2.5

Make sure these boxes are checked before submitting your issue - thanks!

- [x ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Should sync once 

#### Actual Behaviour

Syncing 3 times

#### Steps to reproduce the behaviour

1. Sign in trakt account 
2. Watch a movie or episode to end
3. Check trakt.tv website how many times is play for tha movie

**Comment by popcornMaster** [comment]
We have not being able to reproduce this issue! Could you elaborate on the steps to reproduce it? Maybe specify a specific tv show or movie that this happens to?

**Comment by popcornMaster** [comment]
Thank you for reporting this bug, we have identified the issue and it should be resolved on the next release
