### ISSUE TITLE
popcorntime 3.2.8 closes 

### ISSUE THREAD

**Issue by pc2019** [PopcornTimeTV/PopcornTimeTV#563]
App version:3.2.8
iOS/tvOS version: IOS VERSION:11.2 (Ipad pro 12.9) TVOS VERSION: 11.2 (Apple TV 4K)

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...play movies

#### Actual Behaviour

...app closes

#### Steps to reproduce the behaviour

1. ...open movies menu and select any movie
2. ...the movie doesn't play and app closes
3. ...sometimes the app closes downloading movies

**Comment by popcornMaster** [comment]
Version 3.2.8 is under closed beta testing. Thank you for your comment but please hold off on opening issues on non-released versions

**Comment by popcornMaster** [comment]
Hey since you like testing beta releases, would you be interested in the new 3.2.8 build? I would love to know if it works on all your devices!

**Comment by pc2019** [comment]
Yes
