### ISSUE TITLE
IMDb star rating not visible in 3.2.6

### ISSUE THREAD

**Issue by Hoeckmanden** [PopcornTimeTV/PopcornTimeTV#564]
App version: 3.2.6
iOS/tvOS version: tvOS 11.1

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Show star rating for movie above the text plot, did work again for app version 3.2.5

#### Actual Behaviour

Star rating for movie doesn’t appear above text plot, no stars visible 

#### Steps to reproduce the behaviour

1. Select any movie
2. Missing on all movie info pages

**Comment by popcornMaster** [comment]
The issue has been identified and will be fixed in the next release. Thank you for reporting this
