### ISSUE TITLE
3..2.8 crash issues

### ISSUE THREAD

**Issue by FuzzyNutz** [PopcornTimeTV/PopcornTimeTV#565]
App version: 3.2.8
iOS/tvOS version: 11.1 

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
 play a movie / tv show
...

#### Actual Behaviour
 plays the movie and crashes app, somethings during the movie sometimes during loading 
...

#### Steps to reproduce the behaviour

1. ... play any movie and wait 
2. ...ive gotten 5 crashes within 10 mins of installing the app 
3. ...movies I've tried Thor ragnorok and justice league

**Comment by popcornMaster** [comment]
Thank you for reporting this. Revoking the release pending review
