### ISSUE TITLE
Crash when watching movies [crashlog attached]

### ISSUE THREAD

**Issue by CokePokes** [PopcornTimeTV/PopcornTimeTV#566]
App version: 3.2.8
iOS/tvOS version: 11.0

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Play video with no hiccups

#### Actual Behaviour

Crashes when the movie is playing or even when the video is paused.

#### Steps to reproduce the behaviour

1. Play "The Shape of Water", last night this was not happening while watching a show, so I'm not sure if this is related to the specific movie.
2. Here is the crashlog (yay) https://pastebin.com/heF9ubzn

**Comment by angryDuck2** [comment]
3.2.8 has been revoked due to this issue with vlckit. You will be notified when we re-release it with a solution for this. Meanwhile, try to watch any movie on 3.2.8 on 720p and not 1080p
