### ISSUE TITLE
"popcorn master does not exist"

### ISSUE THREAD

**Issue by hessius** [PopcornTimeTV/PopcornTimeTV#57]
Was getting an error when running install.swift, redownloading and running it again gives the following error;

````
["-c", "pod repo remove popcornmaster;pod setup;pod repo update"]
[!] repo popcornmaster does not exist
````

I dunno if this is just something that happens on the first run because the pods weren't previously set up but hadn't seen anything about this before so thought I'd mention it!

**Comment by popcornMaster** [comment]
This is no issue, it is just a precaution measure just to stop the script requesting username/password when performing an update to the project!
