### ISSUE TITLE
Subtitle question/suggestion

### ISSUE THREAD

**Issue by k4nai** [PopcornTimeTV/PopcornTimeTV#570]
Hi,

This is actually not an issue, more a suggestion / question.

Would it be possible to add a little note in the movie screen if a specific subtitle for the movie is availaible or not before starting the movie?
As an example I chose Turkish in the settings page and each time I want to know if a movie has my chosen subtitle available I must first start it and when it starts playing I will notice right away (since the subtitle will load) or I need to go to the list with available subtitles and check.

To save some clicks and time it would be great if you could see right away in the movie page if my chosen language is available or not.

Or maybe another option if possible would be to add a new setting in the settings page to hide movies which doesn't have your chosen language available and that way I don’t need to start the movie first. I will also know right away in the main screen which movies are available in my language.

Keep up the good work!

**Comment by bao3** [comment]
suggestion:use opensubtitle

**Comment by popcornMaster** [comment]
We are already using opensubtitles api! There is the ability to preselect your desired subtitle and encoding from the settings of the application

**Comment by k4nai** [comment]
@popcornMaster I am aware of the preselecting the subtitles and encoding but this doesn't reflect the main page which I described earlier.
For example I am unable to see if the latest movie added to the Main page has my subtitle available or not.
I must first start the movie and then check which can be time consuming sometimes (some movies takes a couple of minutes to load).

One useful feature would be to hide movies/series which doesn't have my preselected subtitle available right from start when looking at the main page because then I would know what I can watch or not.

**Comment by popcornMaster** [comment]
Unfortunately we need to download the first few megabytes of the file in order to download the subtitles that are most fitting to the particular video, since not all videos have the same subtitle timing! Hence this feature is not really achievable

**Comment by k4nai** [comment]
@popcornMaster  oh sad :( ..thanks for the info!
