### ISSUE TITLE
Arabic subtitle problem

### ISSUE THREAD

**Issue by Tarek-Depp** [PopcornTimeTV/PopcornTimeTV#571]
App version: 3.2.8
iOS/tvOS version: 10.2.2

Arabic subtitle problem , most of the times the subtitles timing are wrong .

It's possiple to load subtitles from opensubtitles.org or Subscene ?? like kodi app.
or ability to chose between several subtitles like popcorntime desktop version .
thanks

**Comment by bao3** [comment]
I have the same question or suggestion . I'm using Chinese but almost all the movies have no subtitles .  If you could use opensubtitles.org , this would very appreciate. Please ,consider this.

**Comment by popcornMaster** [comment]
This is a duplicate issue, continue on #531
