### ISSUE TITLE
App Crash when adding TV Series to watch list

### ISSUE THREAD

**Issue by PlasmaSoftUK** [PopcornTimeTV/PopcornTimeTV#573]
App version:
iOS/tvOS version:

#### Expected Behaviour

Expected app to add TV Show to watch list

#### Actual Behaviour

Hard crash Xcode shows the following:

Simultaneous accesses to 0x10a386dd8, but modification requires exclusive access.
Previous access (a modification) started at PopcornTime`ItemViewController.toggleWatchlist(_:) + 72 (0x1008d664c).
Current access (a read) started at:
0    libswiftCore.dylib                 0x000000010562b810 swift_beginAccess + 512
1    PopcornTime                        0x0000000100815fd0 ItemViewController.media.getter + 72
2    PopcornTime                        0x00000001008d6604 ItemViewController.toggleWatchlist(_:) + 284
3    PopcornTime                        0x00000001008d696c @objc ItemViewController.toggleWatchlist(_:) + 72
4    UIKit                              0x0000000198ae4a40 <redacted> + 96
5    UIKit                              0x0000000198ae49d0 <redacted> + 80
6    UIKit                              0x0000000198acfee8 <redacted> + 440
7    PopcornTime                        0x00000001008b5794 TVButton.pressesEnded(_:with:) + 552
8    PopcornTime                        0x00000001008b5a20 @objc TVButton.pressesEnded(_:with:) + 120
9    UIKit                              0x0000000198d59e7c <redacted> + 708
10   UIKit                              0x0000000198ade8d0 <redacted> + 2352
11   UIKit                              0x0000000198ab1378 <redacted> + 364
12   UIKit                              0x00000001a76271ac <redacted> + 100
13   UIKit                              0x00000001993244f0 <redacted> + 2252
14   UIKit                              0x00000001993260e0 <redacted> + 4744
15   UIKit                              0x00000001993206c8 <redacted> + 152
16   CoreFoundation                     0x000000018f177aac <redacted> + 24
17   CoreFoundation                     0x000000018f1771d8 <redacted> + 276
18   CoreFoundation                     0x000000018f1749a8 <redacted> + 1204
19   CoreFoundation                     0x000000018f095450 CFRunLoopRunSpecific + 552
20   GraphicsServices                   0x0000000191049fbc GSEventRunModal + 100
21   UIKit                              0x0000000198b130f8 UIApplicationMain + 236
22   PopcornTime                        0x00000001007aafbc main + 76
23   libdyld.dylib                      0x000000018eb3d448 <redacted> + 4

#### Steps to reproduce the behaviour

1. ...Browse TV Shows
2. ...Select "Good Doctor"
3. ...Select "Add to Watch List"

Application Crashes back to Home Screen

**Comment by popcornMaster** [comment]
Could you specify the version of the app this issue occurs to as well as the device

**Comment by PlasmaSoftUK** [comment]
Standard ATV 4 (non 4K) and its still happening with the latest Commit for 3.2.9 Release which I just installed. Same crash doing the same thing.

**Comment by popcornMaster** [comment]
We have not being able to reproduce this issue! Could you elaborate on the steps to reproduce it? Maybe specify a specific tv show or movie that this happens to?

**Comment by chlebta** [comment]
Have the same issue latest release

**Comment by popcornMaster** [comment]
We are unable to replicate this issue. Please update to the latest version after signing out of the application from your trakt account

**Comment by angryDuck2** [comment]
You were using an unrelease version of iOS/tvOS and so this was out of scope for the team. This issue has been resolved for version 3.2.16. Please refrain from submitting bugs for beta firmware versions! Thank you for reporting this
