### ISSUE TITLE
Subtitles not working in 3.2.8

### ISSUE THREAD

**Issue by calcarod** [PopcornTimeTV/PopcornTimeTV#574]
App version: 3.2.8
iOS/tvOS version: 11.2.6

#### Expected Behaviour

Show subtitles on the video

#### Actual Behaviour

Dont show subtitles

#### Steps to reproduce the behaviour

1. Play a movie or tv show
2. The video starts but no subtitles anywhere.

I have to downgrade to another previous version and the subtitles worked.

Please fix it.

Thank you!

**Comment by helmehraz** [comment]
have the same issue here

**Comment by CTZH** [comment]
Hello, my subtitles work fine but it can only be adjusted by second (1,2,3... but not 0.1,0.2,0.3...)
so it's impossible to sync subtitles precisely
sorry for my poor english and thank you!

**Comment by labcerouno** [comment]
That's the cause: https://github.com/PopcornTimeTV/PopcornTimeTV/commit/4d7778dfc4cb9bc9b475b0898ea5b55aaef60247#diff-2f309cff07622a6581b22c1ecb7e203c

**Comment by popcornMaster** [comment]
We have not been able to recreate this issue! Would you mind deleting your installed app and installing from start. If this does not work try the pre-built releases. If not even then, please provide further details on how to recreate it

**Comment by labcerouno** [comment]
sure, i'll try it

**Comment by calcarod** [comment]
Im from Colombia, so I select subtitles in Spanish;  but with this version, doesnt show anything. 

I reinstalled the previous version and subtitles worked again.

**Comment by calcarod** [comment]
I can confirm the subtitles work in the new version 3.2.9

Thank you so much.
