### ISSUE TITLE
Airplay zooming on tv extend feature

### ISSUE THREAD

**Issue by Fonzee9** [PopcornTimeTV/PopcornTimeTV#576]
App version:
iOS/tvOS version: iOS 11.2.2 iPhone 8 Plus 

Make sure these boxes are checked before submitting your issue - thanks!

[check ] If app was installed using Cocoapods, make sure the latest version of master has been cloned (git reset --hard; git pull). If app was installed by downloading an .ipa file, please make sure you have the latest version installed.
[check ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
[ check] You have read the Issue Contributing Guidelines for this repository.
Expected Behaviour
When i airplay to my tv i am able to expand the screen size of the movie / show to fit the screen but not so zoomed in. (Movie box does this well when watching movies the extending part to the tv)

Actual Behaviour
When i press the zoom in button on the top of Popcorntime the tv it zooms it in to much instead of extending so some parts are cut off.

Steps to reproduce the behaviour
Airplay to a tv and you'll notice some movies aren't fullscreen and when pressing the fullscreen button on the top of Popcorntime it zooms it in to much.

**Comment by popcornMaster** [comment]
This issue should be fixed in version 3.2.12, please test and report back! Thank you for reporting this issue

**Comment by Fonzee9** [comment]
I can't find 3.2.12 to test it like it says the latest is 3.2.9 from 8 days ago?

**Comment by Fonzee9** [comment]
Okay I see it now I’m out at a restaurant will test soon

**Comment by Fonzee9** [comment]
It didn't fix it just extended the screen but very little

**Comment by popcornMaster** [comment]
Could you suggest a video that this happens to, so we can test on it?

**Comment by Fonzee9** [comment]
A video with the black bars? Play any video in your photos app that you recorded and you'll see it's proper fullscreen with black bars on the side as it should be in Popcorn time when you press the extend button.

**Comment by Fonzee9** [comment]
I just tested the latest update 3.2.16 and it works amazing! 👍 thank you so much the issue has been solved! 🥇
