### ISSUE TITLE
Playback controls in landscape mode are weird

### ISSUE THREAD

**Issue by M1staAwesome** [PopcornTimeTV/PopcornTimeTV#580]
iPhone 8+, iOS 11.3b3. In landscape mode while watching a video, the landscape mode is squished to the right a bit. In portrait mode, it looks completely ok.

Picture of issue: https://imgur.com/a/MRbRi

**Comment by popcornMaster** [comment]
We do not support beta versions on iOS. This is an issue we cannot reproduce up to iOS 11.2.x
