### ISSUE TITLE
Subtitles has the wrong encoding.

### ISSUE THREAD

**Issue by Leof800** [PopcornTimeTV/PopcornTimeTV#581]
App version: 3.2.8
iOS/tvOS version: tvOS 11.2

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

**Expected Behaviour**
(Subtitle File) from (subDownloadLink) (SubtitlesManager.swift)

> Example (episode or movie: Justice League) (localizedLanguageName: português) (ISO639: pb)
> > 00:01:02,800 --> 00:01:04,600
> > Quantas pessoas você já...
> > Você já salvou?

**Actual Behaviour**
(Subtitle File) from (subDownloadLink) (SubtitlesManager.swift)

> Example (episode or movie: Justice League) (localizedLanguageName: português) (ISO639: pb)
> > 00:01:02,800 --> 00:01:04,600
> > Quantas pessoas voc� j�...
> > Voc� j� salvou?

**Steps to reproduce the behaviour**
1. Get file from subDownloadLink (SubtitlesManager.swift).

> _Example_ (episode or movie: Justice League) (localizedLanguageName: português) (ISO639: pb)
> 
> `print(subDownloadLink)`
> 
> (Console Output)
> https://dl.opensubtitles.org/en/download/src-api/vrf-19cd0c55/sid-IlsRWyeurHt0re8YU,Rp0Sdlem6/file/1955752550

I think the problem is subtitle file, it haven't been uploaded as UTF-8.
Obs: Any chance to implement another subtitle API?

**Comment by labcerouno** [comment]
I'm having the same problem with spanish language. What if you try to fill the issue according to the template? ;)

**Comment by Midifreakz** [comment]
I’ve seen this problem come up here many times.. Also Dutch is affected. seems to be an issue with VLCkit rather than popcorn time...

**Comment by Leof800** [comment]
@Midifreakz There is no issue with PopcornTime/VLCKit.

**Comment by Midifreakz** [comment]
I've seen a moderator type that here 2 weeks ago or so and then he closed the issue. The subtitle problem has been going on for a while now. 

I have also tried all the encoding options built in for a while and with different subtitles but no luck fixing the accent issue. These subtitle files usualy work fine in programs like KODI, Plex etc.

**Comment by labcerouno** [comment]
Does anybody know if the encoding is detected automatically or if it is informed by the same .SRT or .SUB file? In the latter, we should think the possibility that the file is bad encoded, i.e., it has an encoding different from what the same file informs (in its header or wherever it is).

I have had different results, always trying the spanish language: the characters with accents (ñ á é...) are often shown as '?'. Few times they're shown correctly. Trying to find the right encoding inside PopCorn App is kinda trick, due to the amount of options available.

Also, I took a look at the code and it seems to choose the sub file with better score in OpenSubtitles. Unfortunately, this is not always the best or more suitable sub. Maybe we could think a different approach to allow the user to choose the best file. I know that some movie files have a hash which can be matched with the sub in order to be sure it's a perfect fit...

Some random thoughts. What do you think, guys?

**Comment by Leof800** [comment]
@labcerouno By default encoding is defined as UTF-8.

    var size: Size = .medium
    var color: UIColor = .white
    var encoding: String = "UTF-8"
    var language: String? = nil
    var font: UIFont = UIFont.systemFont(ofSize: CGFloat(Size.medium.rawValue))
    var style: UIFont.Style = .normal
    
    static let shared = SubtitleSettings()
    override init() {
        guard let codedData = UserDefaults.standard.data(forKey: "subtitleSettings"), let settings = NSKeyedUnarchiver.unarchiveObject(with: codedData) as? SubtitleSettings else { return }
        self.size = settings.size
        self.color = settings.color
        self.encoding = settings.encoding
        self.language = settings.language
        self.font = settings.font
        self.style = settings.style
    }

**Comment by labcerouno** [comment]
Thank you, @Leof800 ! The curious is that most of the times I've tried (with spanish subtitles), even though I choose another encoding within the app, it will show accents as '?'. Maybe the same file downloaded from OpenSubtitles is already bad encoded. I'll try to debug when I have some time and tell you my results. Thank's.

**Comment by angryDuck2** [comment]
For Spanish try using the Windows Latin 1 encoding. This should get you correct subtitle encoding

**Comment by labcerouno** [comment]
Ok. I'll try. Thank's

**Comment by angryDuck2** [comment]
Did using windows-1252 encoding solve the subtitle characters issue?

**Comment by Leof800** [comment]
Yes, the issue is solved.
