### ISSUE TITLE
Arabic subtitle

### ISSUE THREAD

**Issue by momi393** [PopcornTimeTV/PopcornTimeTV#582]
App version:3.2.8
iOS/tvOS version: tvOS 11.2.6 Apple tv 4k

Please add option to chose from multiple arabic subtitle beacause there is diffrent time probleme. 
Add option to chose from external subtitle (from web eg. subscence ,opensubtitle). 
(My device is Apple TV 4K)

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by popcornMaster** [comment]
Continue on #531
