### ISSUE TITLE
Build fail 3.2.8 Apple TV 4K

### ISSUE THREAD

**Issue by luukvanmaanen** [PopcornTimeTV/PopcornTimeTV#583]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Install the app op Apple TV

#### Actual Behaviour

I get a 'Build failed' on xcode

#### Steps to reproduce the behaviour

1. Use the steps from https://www.popcorntimevpn.org/how-to-install-popcorn-time-on-apple-tv/. The xcode way.

**Comment by popcornMaster** [comment]
Please continue on #567

**Comment by luukvanmaanen** [comment]
This is not the same issue?
The pod issue is allready fixed. But I get al kinds of other fails in Xcode.

Why is my case closed now?

Verstuurd vanaf mijn iPhone
