### ISSUE TITLE
application cannot stream 1080p 

### ISSUE THREAD

**Issue by pc2019** [PopcornTimeTV/PopcornTimeTV#585]
App version:
iOS/tvOS version: IOS 11.2 TVOS 11.2.6

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...play videos in 1080p

#### Actual Behaviour

...suddenly stop playing and video closed

#### Steps to reproduce the behaviour

1. ...play any movie at 1080p
2. ...s]
3. ...

**Comment by popcornMaster** [comment]
Please continue on #568
