### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by Hamood54** [PopcornTimeTV/PopcornTimeTV#59]
hey guys, I'm new into hacking/modifying, i tried to add popcorn time but i couldn't in anyway, i tried the terminal and it kept one saying i don't have the permission, other apps like koi were easy to install with the .ipa file, does anyone have the .ipa file for popcorn time and thank you

**Comment by pself89** [comment]
Hey hamood54. The app is still in development and has a bit of a way yet to go until it's ready to be rolled out. It's not even clear yet if the app will be release as a compiled .ipa file. 
The instructions on how to build it and install to your device are on the main screen and inside the readme file. 
But my best advice would not to fiddle around with it too much if you are unsure how install it. You need to do more than just download something and install it. If you are receiving permission errors, try using Sudo on gem install cocoapods. 
The bundle identifier will need to be changed and resolved against your Dev account once you have downloaded and built the project however. Just incase you are able to get as far as installing it on your ATV. 

Good luck!

**Comment by IrishBGS** [comment]
I had the same issue, you literally have to go into finder and edit the properties for the folders to give you "Read & Write Permissions" for every folder & subfolders necessary that needs access. It was a pain at first, took about 10 minutes but that will fix the permissions error.

**Comment by pself89** [comment]
I never had to do that :/ literally just installed the new update 0.4.3 tonight. Terminal errors are normally relating to not using Sudo to install/change root files

**Comment by IrishBGS** [comment]
Oh I meant when I FIRST tried to do all of this in the beginning, very first time I got the permissions error & change the level on the folders fixed it ha but I'm running on a VM so maybe that played into it.

But ever since I changed the permissions, haven't had a problem installing since then.

**Comment by Hamood54** [comment]
Ive managed to do the cocoa and then i also commanded the cd and etc, now I’m kind of stuck for the next step


-- 
Mohammed Haji
Sent with Airmail

On April 22, 2016 at 1:57:18 AM, IrishBGS (notifications@github.com) wrote:

Oh I meant when I FIRST tried to do all of this in the beginning, very first time I got the permissions error & change the level on the folders fixed it ha but I'm running on a VM so maybe that played into it.

But ever since I changed the permissions, haven't had a problem installing since then.

**Comment by pself89** [comment]
pod install will also need sudo

**Comment by Hamood54** [comment]
it says i can’t run cocoa pods as root

-- 
Mohammed Haji
Sent with Airmail

On April 22, 2016 at 2:05:11 AM, pself89 (notifications@github.com) wrote:

pod install will also need sudo

**Comment by pself89** [comment]
Yeah that's my bad. I realise I have you the wrong info. pod install will fail if run as root. 
To be honest, without knowing more, it's very difficult to resolve generic errors. 

Like I said, this is still in development so my best advice is to use whatever knowledge you have. Maybe read up on cocoapod commands more

**Comment by Hamood54** [comment]
I just lost hope lol been all day trying lol, ill just wait till a proper one comes out

-- 
Mohammed Haji
Sent with Airmail

On April 22, 2016 at 2:37:45 AM, pself89 (notifications@github.com) wrote:

Yeah that's my bad. I realise I have you the wrong info. pod install will fail if run as root.
To be honest, without knowing more, it's very difficult to resolve generic errors.

Like I said, this is still in development so my best advice is to use whatever knowledge you have. Maybe read up on cocoapod commands more

**Comment by buzzel** [comment]
PopcornTIme will never be released as a compiled .ipa or on any App Store or Jailbreak installer. The only way to install PopcornTime is to use Xcode. 

Regarding your issues, give the cocoapods app (https://cocoapods.org/app) a go. It comes bundled with its own version of cocoapods if memory serves me right so it might fix any of your issues. If it still fails I suggest deleting your DerivedData, the cloned repository and then recloning the repo again. You can also try user the master branch as seeing if that works.

**Comment by buzzel** [comment]
@Hamood54 Was this able to fix your issue? Im going to close this but if you are still having issues, go ahead and reopen this.
