### ISSUE TITLE
Freeze then crash

### ISSUE THREAD

**Issue by enerette** [PopcornTimeTV/PopcornTimeTV#591]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
 Play movie with sound and not freeze and crash upon first 3 mins of movie
...

#### Actual Behaviour

... Has no sound and freezes and crashes after about 2 mins into movie 

#### Steps to reproduce the behaviour

1. ... opening app
2. ...
3. ...

**Comment by popcornMaster** [comment]
There is an issue already up for this #568 . There is a temporary workaround of simply closing all open applications before initiating a streaming or downloading of a movie
