### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by WindowsScorpion** [PopcornTimeTV/PopcornTimeTV#593]
App version:3.2.9
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... give option in search

#### Actual Behaviour

...disappear 

#### Steps to reproduce the behaviour

1. ...open app
2. ...go to search
3. ...type any show name where is the option of movies/shows/actor

**Comment by popcornMaster** [comment]
I do not understand exactly what the issue is? Could you elaborate a bit more? Is it that you cannot search for shows or actors in tvos app? If so there is an issue with tvOS and we have a workaround already in place. Read this issue #513

**Comment by WindowsScorpion** [comment]
The select box below the letters box in search tab is disapeared

**Comment by WindowsScorpion** [comment]
Workaround for tvOS to leave search and come back is not working
This bug need to be fixed

**Comment by angryDuck2** [comment]
Read issue #513 it contains the answer to your issue
