### ISSUE TITLE
App crashing when watching TV shows on tvOS

### ISSUE THREAD

**Issue by sarandafl** [PopcornTimeTV/PopcornTimeTV#594]
App version:
tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
Play the tv series

#### Actual Behaviour
App crashes a few minutes in. If the show is already cached, the app will crash as soon as the seeds have finished loading.

#### Steps to reproduce the behaviour
1. Open a TV show (e.g Lucifer S03E16)
2. Wait for video to load
3. A few min. in the app crashes

**Comment by popcornMaster** [comment]
There is an issue already up for this, #568. Please continue there!
