### ISSUE TITLE
Would like to contribute to the team.

### ISSUE THREAD

**Issue by sergixmatos** [PopcornTimeTV/PopcornTimeTV#595]
Hello, 

Love the app, I would like to contribute to the team if you guys don’t have a graphic artist.
I have 15 years of experience doing Graphic Design. Photoshop, illustrator, are my major skills, logos, icons, images are my thing. Hit me up if you guys want the help.

Thanks,
Serg

**Comment by popcornMaster** [comment]
We would love the assistance

**Comment by popcornMaster** [comment]
Hit us up on popcornmaster2@gmail.com

**Comment by popcornMaster** [comment]
Pardon the mistake, it is popcorntimetv2@gmail.com

**Comment by popcornMaster** [comment]
Join us here https://join.slack.com/t/popcorntimetv/shared_invite/enQtMzI4OTgwNjA4NTE2LWIxN2UxNjRiNzYxYjI2YjRlYTczNDA0YjhlNjc5ZjQwMWYxMTIzM2M0MTA1N2ZlNzI0ZTViOGY2MjViNjQ2OTM
