### ISSUE TITLE
App crashes while loading a movie

### ISSUE THREAD

**Issue by biagios** [PopcornTimeTV/PopcornTimeTV#596]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Load the movie I intended to watch.

#### Actual Behaviour

The app crashes while loading the movie.

#### Steps to reproduce the behaviour

1. Open the app.
2. Click on a movie and follow the steps to start watching it.
3. App crashes while loading the movie.

**Comment by angryDuck2** [comment]
Please see #568
