### ISSUE TITLE
Resume can crash the app on TVOS

### ISSUE THREAD

**Issue by damianxd** [PopcornTimeTV/PopcornTimeTV#597]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Play the video again

#### Actual Behaviour

Crashed

#### Steps to reproduce the behaviour

1. Open up a movie, in this test I used "Star wars: The last Jedi"
2. Play the movie just some seconds until the title stars to scroll
3. Stop it and then play it again with the same resolution
4. The app will crash

Crash log
`{
  "crashReporterKey" : "ac04f558dd8014809888626463b0dfcda0a8cf8b",
  "kernel" : "Darwin Kernel Version 17.4.0: Wed Dec 13 08:39:13 PST 2017; root:xnu-4570.40.9~5\/RELEASE_ARM64_T7000",
  "product" : "AppleTV5,3",
  "incident" : "253F129A-2EBB-4F30-9058-E10642D6E2F6",
  "date" : "2018-03-12 08:31:41.29 -0300",
  "build" : "Apple TVOS 11.2.6 (15K600)",
  "timeDelta" : 92,
  "memoryStatus" : {
  "compressorSize" : 72764,
  "compressions" : 113014,
  "decompressions" : 2541,
  "zoneMapCap" : 402653184,
  "largestZone" : "APFS_4K_OBJS",
  "largestZoneSize" : 13107200,
  "pageSize" : 16384,
  "uncompressed" : 95907,
  "zoneMapSize" : 62029824,
  "memoryPages" : {
    "active" : 23021,
    "throttled" : 0,
`

**Comment by tibtiby** [comment]
also crashes if you go to settings > clear cache > play movie again - tvOS.

**Comment by damianxd** [comment]
No, if I clear the cache it works, but if I stop it and resume again it crashes

**Comment by angryDuck2** [comment]
@damianxd has 3.2.12 solved this issue?

**Comment by damianxd** [comment]
Yeah :) thanks @angryDuck2
