### ISSUE TITLE
App unstable

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#60]
Hi, Since version 1.0.3.1 and higher the app is unstable at my Apple TV. After compiling, without errors, the app runs once on the Apple TV. Selecting ' favorite ' on a show or movie or when running one show, the app suddenly goes to the background. Restoring the app is not possible. After restarting the Apple TV the app still does not work. After putting back factory settings and install the app on a ' blank ' Apple TV also the app quickly crashes and does not open again. Downgrading to 1.0.2.1 is now what I am going to do and see if that runs again.

- Result: 1.0.2.1 is the last version which runs stable. Higher versions do not run stable. The higher versions run 2 -3 minutes than they go automatically to the background. When stopping the app and starting again, the app does not start anymore.

**Comment by Evhelden** [comment]
Update 1.0.2.1 works well. Higher versions not.

**Comment by tvOSPopcorn** [comment]
@Evhelden Give the NewUI branch a go? A lot has been fixed but don't expect it to be 100% perfect just yet the Player got a new UI and other things https://github.com/PopcornTimeTV/PopcornTimeTV/tree/newUI

**Comment by Evhelden** [comment]
I feel honored. Let me check in the next week, as I am swamped till and including the weekend. I have not had any issues with 1.0.3.2 since I did not log into Trakt.Tv. It might be that there is some issue to look into? I am still trying (but it has ' The Voice ' ;0) to see if it keeps running in this mode. As said: After the weekend.

**Comment by popcornMaster** [comment]
Any bugs with Trakt are now vanished, please update to the latest version!

**Comment by Evhelden** [comment]
Great.. Let me check in the course of the week. I have a user-id with Trakt, but what does it exactly do?
