### ISSUE TITLE
Loading Video Takes Longer and Progress Bar Does Not Move 

### ISSUE THREAD

**Issue by foxhead24** [PopcornTimeTV/PopcornTimeTV#603]
App version:
tvOS version: 11.2.6
Popcorn Time version: 3.2.12

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...Should load faster and show a real representation of what's downloading before the video plays

#### Actual Behaviour

...Loading bar does not move after showing download speed and number of seeds. Takes about 3 minutes total. As a side note, I have a good internet connection with 100 Mbps tested before the issue began and now

#### Steps to reproduce the behaviour

1. ...Select any movie or tv show
2. ...Click on play
3. ...Wait for the video to load and it should take significantly longer to load with no real indication of the status by looking at the progress bar

**Comment by angryDuck2** [comment]
This is all normal behavior! Nothing out of the ordinary!

**Comment by foxhead24** [comment]
The thing is I have used every version of Popcorn released for tvOS since it first came out. There is a black splash screen with the name of the movie or tv show and then the download speed and number of seeds available. It usually would take 1 min to load and then it would display the video playing. 

However what happens now is that progress does not move at all and the video does not load and my screen saver which is set to activate after 2 min kicks in. Then when I press a button on my Siri remote and come back to the black splash screen the progress bar still has not loaded. Then the video suddenly plays. It takes a total of 3-4 min to load.

I don't think that is normal from what I've been used to for all previous versions.

I love the application but maybe I wasn't clear enough in my original post.

I've already troubleshooted the issue by reinstalling popcorn time on my Apple TV 4K through Xcode and restarting my Apple TV. Still the same issue persists. I've tried loading the same film before version 3.2.12 and now and it would take 1 min total for the film to initially load with the progress bar actually moving and then the video playing on the screen to now where there's no progress bar loading and the video suddenly plays after 3-4 min. 

Please review this issue before closing the ticket again.

Thank you.
