### ISSUE TITLE
Movie Does Not Load

### ISSUE THREAD

**Issue by foxhead24** [PopcornTimeTV/PopcornTimeTV#605]
App version: 3.2.12
tvOS version: 11.2.6

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... Play the movie or tv show selected.

#### Actual Behaviour

... After selecting play the movie or tv show does not play - it stays on the black splash screen for several minutes - it shows the download speed and number of seeds but never plays the movie or tv show

#### Steps to reproduce the behaviour

1. ... Select a movie or tv show
2. ... Select play and then the quality of choice (I've tried 720 and 1080)
3. ... Then the black splash screen is displayed and the movie or tv show never plays

I've waited 15 minutes for a couple movies I tried. Netflix and other apps work fine on my Apple TV.

**Comment by popcornMaster** [comment]
This could be an issue with older movies, or even movies that are not that popular, since their existence relies solely on people downloading them and keeping them alive by letting others download them. Unfortunately there is nothing we can do about that!

**Comment by popcornMaster** [comment]
Please provide a movie that has such an issue

**Comment by foxhead24** [comment]
Ferdinand, Molly’s Game and Blade Runner 2049. I see the download speed with the kb per second and how many seeds but the progress bar never loads and the movie never loads…




Adam Volpentesta
avolpentesta@gmail.com | 416.998.6991

**Comment by angryDuck2** [comment]
Is this resolved with 3.2.16?

**Comment by angryDuck2** [comment]
Could someone try to delete their installed app and install the latest? If you do so, does it solve the issue? If it doesn’t can anyone with this issue build the project from source?

**Comment by angryDuck2** [comment]
Due to no responses to this issue, it is now closed
