### ISSUE TITLE
Subtitles is not working at all 

### ISSUE THREAD

**Issue by ghass64** [PopcornTimeTV/PopcornTimeTV#610]
tvOS version: 3.2.12

Make sure these boxes are checked before submitting your issue - thanks!

- [✔︎] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [✔︎ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ✔︎] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

i should see a list of subtitles in the subtitle section in the movie/show

#### Actual Behaviour

The subtitles in the movie/show in TVOS is always showing "no subtitles available"
even i tried to change it from setting and select a different subtitle default language but no working

#### Steps to reproduce the behaviour

1. go to any movie/show
2. swipe up to show the menu and then go to subtitle and it always showing "no subtitles available"

**Comment by cpvbruno** [comment]
The subtitles came back today at my TV without any update. Just with some encontrinho mistakes for Latino languages
