### ISSUE TITLE
Popcorn Time crashes randomly (tvos)

### ISSUE THREAD

**Issue by tibtiby** [PopcornTimeTV/PopcornTimeTV#611]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

not crash/exit.

#### Actual Behaviour

Ever since v.3.2.8 the app started crashing randomly. Whether I am simply looking at the list of movies/tv shows, or actually selecting something to play, the app just goes to gray and exits. Already tried restarting my Apple Tv, reinstalling tvos, reinstalling PopcornTime, deleting cache, force quitting app - nothing works.

#### Steps to reproduce the behaviour

1. Open App.
2. Scroll down movie/tv shows list or select any movie (1080p or 720p)
3. Screen goes gray and the app force quits.

**Comment by angryDuck2** [comment]
This is resolved with version 3.2.16
