### ISSUE TITLE
Subtitles don't show

### ISSUE THREAD

**Issue by betta9** [PopcornTimeTV/PopcornTimeTV#612]
App version:
iOS (iPad)

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
Displays the subtitle selection button on the screen.

#### Actual Behaviour
It doesn't show any button to select a subtitle at all. I tried with previous versions and I have the same issue, but the first time I installed the app I was able to select de subtitle from a list. I installed it from the .ipa

**Comment by cpvbruno** [comment]
The subtitles came back today at my TV without any update. Just with some encontrinho mistakes for Latino languages

**Comment by r1qu3br** [comment]
same here, and now 1080p running ok, I tested on "The greatest sho..."
