### ISSUE TITLE
Subtitles integration

### ISSUE THREAD

**Issue by giwrgos88** [PopcornTimeTV/PopcornTimeTV#617]
Hello I want to suggest the option of adding multiple subtitle pages integrations.

**Comment by angryDuck2** [comment]
We do not current have a plan to do something like that. Instead we will be implementing a hash based search method for subtitles to help with selecting more appropriate subtitles to the videos being watched

**Comment by giwrgos88** [comment]
@angryDuck2 sounds good!!
