### ISSUE TITLE
Wrong subtitles enconding for PT-BR even when UTF-8

### ISSUE THREAD

**Issue by cpvbruno** [PopcornTimeTV/PopcornTimeTV#619]
Apple TV - Latest Version

**Comment by r1qu3br** [comment]
Use Windows-1252 :)

**Comment by cpvbruno** [comment]
Can’t test right now, for some reason the subtitles are vanishing and showing up again many times during the day

**Comment by cpvbruno** [comment]
Just tested, worked fine, thanks man!

Also found a bug that subtitles doesn’t show when my Apple TV has a different language than my default language from Popcorntime app
