### ISSUE TITLE
Update from the app on jailbroken devices?

### ISSUE THREAD

**Issue by wahlmanj** [PopcornTimeTV/PopcornTimeTV#62]
Could there be a update mechanism built into the app for jailbroken devices so it could be updated from within the app itself? Otherwise could there be a dropbox or separate github or similar place to grab the exported ipa from Xcode since the usb-c is disabled for a lot of jailbroken aTV4 users and it cannot be exported until if/when the issue usb-c is fixed so we can do it ourselves?

For example if it had a update mechanism it could find a new update from wherever then use wget then appinst:

cd ~
/usr/bin/wget http://locationoflatestPCT.ipa
/usr/bin/appinst ~/PopcornTimev1.0.3.2.ipa

*Assuming the user has appsync and cydia substrate installed from nitoTV which I assume most do ;)

Also if anyone could upload the latest PCT.ipa for the meantime for testing purposes it would be appreciated :)

**Comment by wahlmanj** [comment]
For example if it had a update mechanism it could find a new update from wherever then use wget then appinst:

cd ~
/usr/bin/wget http://locationoflatestPCT.ipa
appinst  PopcornTimev1.0.2.1.ipa

*Assuming the user has appsync and cydia substrate installed from nitoTV...

**Comment by wahlmanj** [comment]
For example if it had a update mechanism it could find a new update from wherever then use wget then appinst:

cd ~
/usr/bin/wget http://locationoflatestPCT.ipa
appinst  PopcornTimev1.0.2.1.ipa

*Assuming the user has appsync and cydia substrate installed from nitoTV...

**Comment by wahlmanj** [comment]
For example if it had a update mechanism it could find a new update from wherever then use wget then appinst:

cd ~
/usr/bin/wget http://locationoflatestPCT.ipa
appinst  PopcornTimev1.0.2.1.ipa

*Assuming the user has appsync and cydia substrate installed from nitoTV...

**Comment by wahlmanj** [comment]
For example if it had a update mechanism it could find a new update from wherever then use wget then appinst:

cd ~
/usr/bin/wget http://locationoflatestPCT.ipa
/usr/bin/appinst PopcornTimev1.0.2.1.ipa

*Assuming the user has appsync and cydia substrate installed from nitoTV...

**Comment by tomsbrinkis** [comment]
@wahlmanj here you go: http://jmp.sh/hF6PZPP

**Comment by wahlmanj** [comment]
The minimumOSversion is set to 9.1. It needs to be set to 9.0 otherwise I cannot use it.

**Comment by tomsbrinkis** [comment]
@wahlmanj i coud not get newer version. BTW. you have a jailbroken aTV?

**Comment by wahlmanj** [comment]
Yes two of them 64gb both jb. Maybe you need to switch the PCT branch from master to newUI to get latest version then export that ipa making sure  minimumOSversion is set to 9.0 in build settings of Xcode? If you could so I could test that also either way it would be a big help since my usb-c is not working after jb until if/when they fix the usb-c bug.

https://github.com/PopcornTimeTV/PopcornTimeTV/tree/newUI?files=1

Back to my original question, seems there is a detection if a user is running the latest version. What file(s) do the detection in the master branch?

**Comment by popcornMaster** [comment]
Please do not use newUI branch, it is highly experimental and completely unstable! Once the newUI changes have been ironed out they will be integrated into master and made into a new release which will show up on your applications when you open them!

**Comment by ynnad696** [comment]
@wahlmanj hi do you think you can now upload a updated PopcornTime .IPA ?
thanks

**Comment by wahlmanj** [comment]
Here is the one from @tomsbrinkis with minimumOSversion set to 9.0 resigned:

http://www.mediafire.com/download/4tbe37dusau5tl1/PopcornTimev1.0.3.1.ipa

**Comment by ynnad696** [comment]
PopcornTime 1.0.5 ipa please....

**Comment by ynnad696** [comment]
are you running OS X sierra ? ii thing that may be the issue...
