### ISSUE TITLE
Adding TopShelf Support

### ISSUE THREAD

**Issue by RefusedFlow** [PopcornTimeTV/PopcornTimeTV#62]
TopShelf support on the home screen of Apple TV to include showing;
- Watchlist
- Latest Movies
- Latest TV Shows

[Documentation](https://developer.apple.com/library/tvos/documentation/TVServices/Reference/TVTopShelfProvider_Ref/index.html#//apple_ref/doc/uid/TP40016416-CH1-DontLinkElementID_6) _Tried to implement myself before however didn't succeed_

**Comment by tengis** [comment]
![simulator screen shot 27 apr 2016 11 16 54 pm](https://cloud.githubusercontent.com/assets/358442/14853456/ef2b1634-0cce-11e6-86b4-63bfbfe73e2d.png)
![simulator screen shot 27 apr 2016 11 16 41 pm](https://cloud.githubusercontent.com/assets/358442/14853457/ef2fe61e-0cce-11e6-8c6d-fc0f3be7c08d.png)
