### ISSUE TITLE
Option to stream in 4k resolution

### ISSUE THREAD

**Issue by smurfsenator** [PopcornTimeTV/PopcornTimeTV#620]
Hello, I want to suggest the option of streaming in 4k I am currently using the apple 4k but dont have the option to stream in 4k I understand that most people wouldnt be able to because long wait time since not many people would seed Id just like to have the option so I could, and not to be limited just with 720p and 1080p.

**Comment by popcornMaster** [comment]
Unfortunately our api provider does not have 4k for movies or 1080p for tv shows, so there is nothing we can do for that. What you can do with version 3.2.9 and onwards is upload your own torrent of a 4k movie and enjoy it using the 'Open Magnet' button on top of the movies and shows lists. Mind you, you will not have the ability to have subtitles for movies loaded in this way.
