### ISSUE TITLE
Chromecasting dont work

### ISSUE THREAD

**Issue by SirRichardLXIX** [PopcornTimeTV/PopcornTimeTV#621]
App version:
3.2.17
iOS 11.3

Make sure these boxes are checked before submitting your issue - thanks!

- [ X ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ X ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ X ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
Play video on TV via chromecast

#### Actual Behaviour
Looks like its attempting to play but quickly gives up, the app does not crash.
Video of what happends (github does not support this file type): https://imgur.com/sZEVH56

#### Steps to reproduce the behaviour

1. Connect to chromecast
2. Select anything to play
3. Watch it do nothing

**Comment by SirRichardLXIX** [comment]
Same thing happends on iPhone 5s, with iOS 11.2.6.
3.2.17 also have same issue as before on iPhone X.

**Comment by dony71** [comment]
I'm using iphone 7 with iOS 11.2.5
3.2.17 can start casting video however after a while it stops
I guess this is because iphone going to sleep mode
Is it possible to add background refresh mode to prevent apps not to sleep?

**Comment by SirRichardLXIX** [comment]
Same thing happening on 3.2.19

**Comment by SirRichardLXIX** [comment]
Chromecasting works in 3.2.19 on iOS 11.4, closing.
