### ISSUE TITLE
Norwegian subtitles missing 3 letters

### ISSUE THREAD

**Issue by teknim** [PopcornTimeTV/PopcornTimeTV#625]
App version: 3.2.26
iOS/tvOS version: tvOS

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Show letters Æ (æ), Ø (ø) and Å (å)

#### Actual Behaviour

Shows a "?" instead of said letters.

#### Steps to reproduce the behaviour

1. Start movie
2. Select norwegian subtitles
3. See a "?" instead of the letters Æ, Ø and Å.

**Comment by chipivk** [comment]
It will be resolved adding Latin-1 to enconding. I did a pull request with that #640
