### ISSUE TITLE
No subtitles

### ISSUE THREAD

**Issue by WindowsScorpion** [PopcornTimeTV/PopcornTimeTV#629]
App version: 3.2.12
iOS/tvOS version: 11.3

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Show subtitles to select
...

#### Actual Behaviour

No subtitles 
...

#### Steps to reproduce the behaviour

1. Open any movie or show
2. Sweep down on the remote
3. Select subtitle
4. Nothing is there

**Comment by angryDuck2** [comment]
Refer to #624
