### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#63]
Can u open slack again?
it was a really good thing

**Comment by Faisal-nz** [comment]
Totally agree

Sent from my iPhone

On 7 Sep 2016, at 5:37 am, moh0sw <notifications@github.com<mailto:notifications@github.com>> wrote:


Can u open slack again?
it was a really good thing

-

**Comment by tvOSPopcorn** [comment]
Unfortunately we won't be opening the Slack group again, for security reasons in the meantime you're more than welcome to create an issue if you'd like to speak to anyone on the team
