### ISSUE TITLE
Trakt Watchlist not syncing on TvOS (as described in #553)

### ISSUE THREAD

**Issue by Midifreakz** [PopcornTimeTV/PopcornTimeTV#631]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Sync my Trakt watchlist with "my list" in PopcornTime (as it used to do)

#### Actual Behaviour

No items are synced from the trakt watchlist.

#### Steps to reproduce the behaviour

1. put movies in your trakt watchlist
2. fire up popcorn time ATV
3. Check "my list"

______
Same issue as  #553 but with correct use.

**Comment by angryDuck2** [comment]
We are syncing the watchlist with the list named "Watchlist" under your trakt profile's lists, as we have done since day one

**Comment by Midifreakz** [comment]
Hi AngryDuck2,

I have double checked this. Logged out of Trakt, reinstalled PopcornTime to the ATV, Then logged back in to Trakt on PT. The issue stil persists. 

As a second note: If I add a movie to my watchlist trough the PopcornTime interface it appears briefly before disappearing again. However, the movie is actually added to my watchlist if i take a look on the Trakt website.

I made a small video on what's happening:
https://youtu.be/2V5eSvXam7c

**Comment by angryDuck2** [comment]
This issue should be resolved with version 3.2.17

**Comment by angryDuck2** [comment]
Closing as resolved
