### ISSUE TITLE
Seen movies still don’t sync with the app

### ISSUE THREAD

**Issue by QiuIcs** [PopcornTimeTV/PopcornTimeTV#633]
App version: 3.2.16
iOS/tvOS version: 11.4

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
Seen movies should have the blue badge on them as they had in past versions (prior to 3.2.12)

#### Actual Behaviour
Seen movies don’t have the badge

#### Steps to reproduce the behaviour

1. Sync with trakt succesfully
2. Refresh movies tab
3. No “seen” badge shows

**Comment by Midifreakz** [comment]
Same problem over here, seems like trakt syncing is a bit off in general, as I described in 631

**Comment by angryDuck2** [comment]
Closing as duplicate
