### ISSUE TITLE
Subtitles do not display automatically when language is set in settings.

### ISSUE THREAD

**Issue by Midifreakz** [PopcornTimeTV/PopcornTimeTV#636]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

When subtitle language is set in the settings menu, display the correct subtitles when playing a movie or TV show. (automatically, without having to select them)

#### Actual Behaviour

No subtitle auto-load (I need to select them myself)

#### Steps to reproduce the behaviour

1. Set subtitle language in settings
2. Start movie or show
3. No subtitles showing.

EDIT:
This only seems to be happening with some episodes of some shows so it's rather a minor issue.

**Comment by angryDuck2** [comment]
Due to the new way of downloading subtitles(it is now based on the actual video downloaded and not the movie/show title) this is something that can occur. The upside is subtitles that do not require manual adjustment to get synced up as often as they used to
