### ISSUE TITLE
No subtitles available

### ISSUE THREAD

**Issue by WindowsScorpion** [PopcornTimeTV/PopcornTimeTV#638]
App version: 11.3
tvOS:3.2.17

No subtitles available

**Comment by teknim** [comment]
Used to happen to me a lot. It seems to have something to do with the VPN or DNS you're using. What fixed it for me, since I was using Google's DNS (8.8.8.8), I just changed it to another working DNS, and the problem disappeared.

**Comment by angryDuck2** [comment]
It was just an issue with the opensubtitles api. Subtitles should be back now. Closing as resolved
