### ISSUE TITLE
import TVMLKitchen error

### ISSUE THREAD

**Issue by alshizawi** [PopcornTimeTV/PopcornTimeTV#64]
Hi every one .. 

I faced a problem while compiling the app ..

I tried to clean .. 
Tried to re-install pod
update pod

and couldn't solve the issue yet

hope you can help :)

**Comment by tengis** [comment]
What is the Xcode version?

**Comment by alshizawi** [comment]
The latest version ..

**Comment by tengis** [comment]
7.3?

**Comment by tengis** [comment]
i had same problem 7.2 then i upgraded to 7.3. Now no problem at all

**Comment by alshizawi** [comment]
I'm not sure about the virsion right now since i'm not in front of my mac .. But I'm updating all my apps when ever there is a new update ..

**Comment by tengis** [comment]
Did you upgrade to OSX EL Captain?

**Comment by iAYMANi** [comment]
not Open the project PopcornTime.xcworkspace the same file
Go directly to xCode Then open -PopcornTime.xcworkspace- through the menu will work not error

**Comment by alshizawi** [comment]
Hi ,

@tengis 
Yes , i have OS X El Capitan ' the latest version '
And the Xcode version is 7.3

@iAYMANi 
Yes Bro , Finally it works without any issues or errors 👍 

Thank you both of @tengis & @iAYMANi
