### ISSUE TITLE
Support for 4k

### ISSUE THREAD

**Issue by pc2019** [PopcornTimeTV/PopcornTimeTV#643]
App version: 3.2.17
iOS/tvOS version: tvOS 11.3

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... Support for 4k movies in apple TV 4K

#### Actual Behaviour

...dont have 4k movies

#### Steps to reproduce the behaviour

1. ...its not a bug, its only a request for future versions.
2. ...
3. ...

**Comment by angryDuck2** [comment]
As requested in multiple other (now closed) issues, this is not possible and not up to us :(

**Comment by Fonzee9** [comment]
I know Popcorn time gets there movies from YRS.am but is it possible to add a second torrent website to Popcorn time that offers 4k movies?

**Comment by angryDuck2** [comment]
Unfortunately there is currently no such feed/api. This issue will remain open in order not to have any more duplicates, but no progress is expected to be made

**Comment by angryDuck2** [comment]
You can now load any movie you like on whichever quality you want through the "Open External" feature
