### ISSUE TITLE
Build issue 

### ISSUE THREAD

**Issue by FuzzyNutz** [PopcornTimeTV/PopcornTimeTV#644]
getting this error when trying to build 3.2.17

![screen shot 2018-04-20 at 6 23 52 am](https://user-images.githubusercontent.com/26355018/39046243-81b6c962-4463-11e8-9e85-f452a3747c83.png)

**Comment by angryDuck2** [comment]
(This is the relevant issue)[https://github.com/tadija/AEXML/issues/147] of the associated pod, the solution is on the second message 😃

**Comment by FuzzyNutz** [comment]
Crap so I have to update to high Sierra  to update Xcode 😞 I didn’t want to update I feel like apple is systematically slowing down my Mac with these updates
