### ISSUE TITLE
Change the button to the entire element in downloaded list

### ISSUE THREAD

**Issue by RaulOlmedoCheca** [PopcornTimeTV/PopcornTimeTV#647]
App version: 3.2.17
iOS/tvOS version: 11.3

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Play the downloaded element when tapping in any place of the element in the list.

#### Actual Behaviour

Only works if the mobile icon on the right side of the element is clicked.

#### Steps to reproduce the behaviour

1. Download an episode from a tv show
2. Go to downloaded section
3. Tap on the show and try to play an episode without tapping the right icon

**Comment by angryDuck2** [comment]
This is the intended way of this feature's functionality.
