### ISSUE TITLE
App crashes when starting chromecast reproduction

### ISSUE THREAD

**Issue by RaulOlmedoCheca** [PopcornTimeTV/PopcornTimeTV#648]
App version: 3.2.17
iOS/tvOS version: 11.3

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Play the content in Chromecast.

#### Actual Behaviour

Exits the view with the play/pause controls to return to the episode view.

#### Steps to reproduce the behaviour

1. Select a show
2. Click on the top-right sharing icon 
3. Select the device
4. Tap the play button
5. The first time will simply exit the reproducing view, but the second time the button play is touched, the app crashes with _"Unexpectedly found nil while unwrapping an Optional value"_ in _PopcornTime/UI/iOS/View Controllers/CastPlayerViewController.swift_  in `streamer.cancelStreamingAndDeleteData(UserDefaults.standard.bool(forKey: "removeCacheOnPlayerExit"))` line.

**Comment by angryDuck2** [comment]
Is this resolved on 3.2.19?

**Comment by RaulOlmedoCheca** [comment]
It is!, sorry for keeping this open
