### ISSUE TITLE
An issue with the menu bar on landcaps mode for Arabic language both phone and app

### ISSUE THREAD

**Issue by mohdalyahri** [PopcornTimeTV/PopcornTimeTV#649]
App version:3.5.17
iOS/tvOS version:11.4

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... 
nothing more fixing the problem:D

#### Actual Behaviour

...
Fixing!
#### Steps to reproduce the behaviour

1. Going Portrait mode to jump where ever I want.

**Comment by mohdalyahri** [comment]
Here is a photo: https://imgur.com/a/BYzKgtm

**Comment by angryDuck2** [comment]
This is probably an issue with iOS 11.4. We do not support beta firmware versions. If you have this issue with the iOS 11.3 or lower please reopen this issue
