### ISSUE TITLE
Feature request: search and stream on kat.ph or other torrent websites

### ISSUE THREAD

**Issue by simonepsp** [PopcornTimeTV/PopcornTimeTV#65]
Hi,
would it possible to add this feature to Popcorn time tv?
Would be greatly appreciated :)

Just a suggestion, tough.
Thanks and have a nice day

**Comment by RefusedFlow** [comment]
I don't believe there are any public API's available to pull data from Kickass? At the moment we're just using YTS & EZTV

**Comment by simonepsp** [comment]
popcorntime.sh desktop client supports searching on KAT :) Probably there are APIs

**Comment by RefusedFlow** [comment]
Appreciate you're suggestion! I'll get it added to the Progress list but as this isn't something that's a priority it may take some time for something like this to be looked into and implemented.

You're more than welcome to look at the progress list of features awaiting to be implemented.
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress

But as it stands this issue will be closed, reopened when/if this feature is implemented.
Thanks & Enjoy your day 😄
