### ISSUE TITLE
HomePod support

### ISSUE THREAD

**Issue by nuvzzy** [PopcornTimeTV/PopcornTimeTV#650]
please before stereo HomePod is released add support for HomePod in speakers natively in app, with delay currently found. YouTube etc don’t experience lag , although can b fixed with delay options auto would be great.

**Comment by angryDuck2** [comment]
Incoming 👍

**Comment by angryDuck2** [comment]
Please check version 3.2.19. You should be able to select the output route you wish from the audio panel

**Comment by nuvzzy** [comment]
3.2.19 installed, went to test and drop down crashes app, doh, prob coz I’m running beta tvOS 11.4? So I can’t test for you :(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahmetwbu** [comment]
@nuvzzy same here! I'm on beta too and it crashes when I pull down

**Comment by angryDuck2** [comment]
There is nothing we can do for beta versions unfortunately. That is the reason they are called beta

**Comment by nuvzzy** [comment]
Updated to 11.4 today & went to test HomePod support in audio pull down however this crashes the app?

**Comment by nuvzzy** [comment]
Also if u select the audio preference as HomePod in Apple TV setting the audio delay is still there

**Comment by angryDuck2** [comment]
The latest master branch has the fix for this issue from #669
