### ISSUE TITLE
Can not search shows, tab bar is missing.

### ISSUE THREAD

**Issue by CokePokes** [PopcornTimeTV/PopcornTimeTV#651]
App version:
iOS/tvOS version: Using AppleTV 4k on tvOS 11

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

-- The Shows/Movies tab bar is missing when searching. 

#### Actual Behaviour

Does not give the option to search shows. Search results only give movies.

#### Steps to reproduce the behaviour

1. Just search, there is no tab bar to choose which to search.  
2. I'm using the ipa provided here on github.
3.

**Comment by angryDuck2** [comment]
Could you please specify which version of tvOS 11 you are using(11.3,11.2,11.0)?

**Comment by CokePokes** [comment]
11.0 (15J381) And App Version: 3.2.17

**Comment by angryDuck2** [comment]
This issue should be resolved on 3.2.19. Although since there is no outright solution, you should be able to get to the scope bar from the second time you enter the search view and onwards
