### ISSUE TITLE
aTV: Playback freezes around 1-to-2 min of most videos

### ISSUE THREAD

**Issue by grandxadmiral** [PopcornTimeTV/PopcornTimeTV#657]
App version: 3.2.19 for tvOS
iOS/tvOS version: 11.3
✓✓✓

#### Expected Behaviour
When video finishes buffering, and begins playing, it should continue playing uninterrupted if the download speed is faster than the playback speed. (i.e. the download progress bar zooms to end of media.)

#### Actual Behaviour
On almost every media file, the episode buffers and then begins playing, and then will freeze or pause somewhere between 1:00 and 2:00 minutes in. Sometimes, pressing play/pause a few times will get the video playing again, but sometimes, nothing will get it playing again. I can seek forward and backward, but will not play. To get video playing, I must leave the app, return, reselect the video, buffer it again, choose "continue from last spot" and then the media will play properly.

#### Steps to reproduce the behaviour
1. Play an episode, with a good internet connection (wifi)
2. Wait for episode to buffer, then begin playing.
3. Wait for episode to pause itself, somewhere around 1-2 minute mark.
4. Verify that a healthy chunk has downloaded, if not the whole thing.
5. Try to get it playing again. Pressing play will not always work.

**Comment by grandxadmiral** [comment]
I'm also experiencing app crashes, about 1-minute in. I just upgraded to 3.2.19 and thought it might have been addressed in the update, but crashes still happening.
You can test with 'The Crossing'

**Comment by grandxadmiral** [comment]
Another detail to reproduce crashing: first episode of a show might play successfully, but then the next episode auto-plays (after selecting 480p quality) but after buffering, app immediately crashes. This has happened twice in row.

**Comment by teknim** [comment]
Same problems.

**Comment by Tom2527** [comment]
Exact same issue. I think a workaround might be to press pause immediately after the video first starts playing so it can buffer some more. Then after a minute (or two depending on your speed), press play. I haven't had the issue when doing that, but it's all very random.

**Comment by rkundrata** [comment]
Also noticed this, I fixed it by archiving the app first and then installing it to Apple TV instead of building and running it.
