### ISSUE TITLE
Italian subtitles

### ISSUE THREAD

**Issue by bubez81** [PopcornTimeTV/PopcornTimeTV#66]
Hi! Great app!! Unfortunately there are never Italian subtitles and it's strange because on opensubtitles I can always find the right Italian subtitle

**Comment by Beorn1988** [comment]
I commented on this a while ago. When it comes to swedish subs I can find them there aswell. For the djungle book for example. But my guess is that they aren't hashed for that particular torrent which is used as a movie. But I'm hoping for a download option to be implemented later on. Then even if a sub dont fit exactly you can just adjust sub with delays.

**Comment by popcornMaster** [comment]
As it is already said, duplicate of #35 . Closing!
