### ISSUE TITLE
error installing via terminal

### ISSUE THREAD

**Issue by falcon21** [PopcornTimeTV/PopcornTimeTV#66]
Hi there,

I managed to install earlier version of PopcornTime TV (0.4.0) - tried to update it to the newest version, followed the terminal guide, but no luck.

Error: 
```
[!] Unable to satisfy the following requirements:

- `PopcornTorrent` required by `Podfile`
- `PopcornTorrent (= 1.0.9)` required by `Podfile.lock`
```

and sometime i got this error as well

`[!] You cannot run CocoaPods as root.`

Help?

**Comment by iAYMANi** [comment]
try:
sudo gem install -n /usr/local/bin cocoapods

cd ~/Desktop
git clone https://github.com/PopcornTimeTV/PopcornTimeTV.git
cd ~/Desktop/PopcornTimeTV
git checkout 0.4.3
pod install

**Comment by falcon21** [comment]
Hi iAYMANi,

thanks for the reply, I still got the following error
please refer to the screenshot here: http://d.pr/i/1lU1X

Any thoughts? @

**Comment by buzzel** [comment]
Couple of options here. 

1. run `sudo gem install cocoapods --pre`
2. Download the Cocoapods Mac App and try installing the pods that way. 

The current stable cocoapods release has created a ton of issues for people including myself and this usually fixes those issues for some reason. 

Let us know if it does indeed fix it.

**Comment by buzzel** [comment]
@falcon21 Any updates on this issue? If not I'll go ahead and close this

**Comment by buzzel** [comment]
Reopen this issue if its still persisting.

**Comment by falcon21** [comment]
hi buzzel, i have downloaded Cocoapods Mac App, how do i install the pods using this?

thanks!
