### ISSUE TITLE
correct encoding for subtitles in Portuguese Brazil

### ISSUE THREAD

**Issue by renandbl** [PopcornTimeTV/PopcornTimeTV#666]
tvOS version:

Hello, could you help me set up the correct encoding for subtitles in Portuguese Brazil?

because whenever I configure UTF-8 in the TV application .. even then they do not correctly display the accents that are not few ... I tried to find the ANSI option, but unfortunately I did not find ... so if anyone can help me. I will be VERY grateful .. because I have already taken a look at the internet and I have not got any guide to help me or something of the genre.

**Comment by CavalcanteLeo** [comment]
usa o `windows-1252`

**Comment by renandbl** [comment]
vou testar.. obrigado
