### ISSUE TITLE
Missing movies

### ISSUE THREAD

**Issue by iclems** [PopcornTimeTV/PopcornTimeTV#67]
For instance, cannot find "Cafe Society" on TV while it can be found in the regular app. 

Is there any API difference?

**Comment by iclems** [comment]
Sorry if this is a duplicate of #58 feel free to close! May I help with updating the APIs?

**Comment by angryDuck2** [comment]
I will be closing this! Sure we already have a branch on popcornKit that will implement the new APIs. Feel free to drop PRs!

**Comment by popcornMaster** [comment]
I will be closing this. Yes sure feel free to post PRs on the PopcornKit project and the new-apis branch
