### ISSUE TITLE
Not loading movies or series.

### ISSUE THREAD

**Issue by aaron3030** [PopcornTimeTV/PopcornTimeTV#671]
App version: 3.2.19
iOS/tvOS version: 11.4

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... The app will start to load the seed finding the movie and then starts playing the movie.

#### Actual Behaviour

... You choose the quality of the movie and it stays loading, without loading the bar of the seeds and without playing the movie. It freeze in loading.

#### Steps to reproduce the behaviour

1. ... Open any movie
2. ... Click Play button
3. ... Choose the quality
4. ... You will see a black screen with the name of the movie and the loading sign and it will stays like that.

**Comment by Tom2527** [comment]
I don't have that issue with version 3..2.19 on tvOS 11.4. I occasionally do (also on older versions) but that is linked to a specific title not properly seeding and downloading.
