### ISSUE TITLE
Crash on iOS 12

### ISSUE THREAD

**Issue by QiuIcs** [PopcornTimeTV/PopcornTimeTV#672]
App version: 3.2.19
iOS/tvOS version: iOS 12

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Launch ok

#### Actual Behaviour

Crashes on every launch

#### Steps to reproduce the behaviour

1. Open app

**Comment by malonehedges** [comment]
Doesn't work with iOS 12 using the most recent IPA provided

**Comment by Manu83** [comment]
As seen on various reddit threads, it seems cydia impactor is not fully operational on iOS 12. If you used this tool to install the .ipa, even the latest, it might be the issue.
As it's the onlyone I use, I can't tell if any side-loaded app is working on iOS 12, regardless of the tool used to install it.

**Comment by darkobg79** [comment]
Scrolling down on Apple TV 4K crashes the application on tvOS 12, solution for tvos 11.4 dont work. Have some idea what is problem?

I can't go back to tvOS 11.4, because downgrade doesn't work on Apple TV 4K. :(((

**Comment by tomto147** [comment]
Install a modified version that solves this problem from here (ipa). https://mega.nz/#!fPA31CRL!sEk8465A48sqFIVB8XLLYNpJwYAxe-1FA0Ir-GnDV64) resign yourself or register for a paid appsign service from here https://appdb.to?ref_code=a1c6f2f507f2f162365b1625c9fafd91

**Comment by darkobg79** [comment]
Compiled app for TVOS 12, problem with scrolling down top menu is resolved. Thank you @MatthieuLab

Download and install a modified version that solves this problem from here: https://uptobox.com/2qp5jt6fn076

It need to resign app.
