### ISSUE TITLE
Update popcorntimetv to tvos

### ISSUE THREAD

**Issue by Jezze83** [PopcornTimeTV/PopcornTimeTV#679]
I have ipastore installed to my atv but in ipastore app, there is old version of popcorntimetv and its not working with 11.4. I contacted to support but seems they are too lazy to update popcorntimetv. Can i install that .ipa file manually with ifunbox and do i need developer account? I dont want reinstall that every 7 days.

**Comment by MML9** [comment]
You can finde the latest ipa’s from the Releases page here: https://github.com/PopcornTimeTV/PopcornTimeTV/releases
And use impactor to sign and install the app
