### ISSUE TITLE
TRAKT issues when building in xcode

### ISSUE THREAD

**Issue by mitcheble** [PopcornTimeTV/PopcornTimeTV#68]
I keep getting these erorrs when building in xcode
![screen shot 2016-09-10 at 6 13 11 pm](https://cloud.githubusercontent.com/assets/21270835/18413806/5957db14-7782-11e6-9762-3d4bde9aba35.png)

**Comment by FlaviaBondJamesBondsHusband** [comment]
please run pod install to make sure you have the latest version downloaded

**Comment by popcornMaster** [comment]
Please use the install script every time you want to update to the latest version since, it performs many necessary commands for the project to build successfully!

**Comment by bubez81** [comment]
same error here but i can't understand the solution, run the install scripts till the error stop?

**Comment by wahlmanj** [comment]
You must build from scratch everytime. Follow this exactly again to compile:

https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/README.md
