### ISSUE TITLE
Not enough space to download error while streaming

### ISSUE THREAD

**Issue by FuzzyNutz** [PopcornTimeTV/PopcornTimeTV#680]
So I went to play a movie and I got an error saying not enough space to download must clear 1.9 gb to play. So what I ended up doing was clearing the cache which had 9gb! Question is.. my Apple TV is 30gb so I’m wondering if popcorn time is saving the movies/shows I watch, since I never download anything why would I be at my Max with just 9gb in cache ?

**Comment by DJMpc99** [comment]
Having the same issue on my 32gb 4k Apple TV. I have to clear my cache, and when I do it says 13 Gbs cleared. Never happened on prior version. I think it is saving the movies and shows.

**Comment by DJMpc99** [comment]
Having the same issue on my 32gb 4k Apple TV. I have to clear my cache, and when I do it says 13 Gbs cleared. Never happened on prior version. I think it is saving the movies and shows.

**Comment by DJMpc99** [comment]
Having the same issue on my 32gb 4k Apple TV. I have to clear my cache, and when I do it says 13 Gbs cleared. Never happened on prior version. I think it is saving the movies and shows.
