### ISSUE TITLE
Missing spanish localizations

### ISSUE THREAD

**Issue by soygalla** [PopcornTimeTV/PopcornTimeTV#682]
Hey i've updated the spanish localizations for the missing ones. Here's the file:
[es.xliff.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/2104658/es.xliff.zip)

But there's two issues:
1. One button text is clipped.
2. There's a missing translation in the .xliff file (the "Please navigate to the webpage %@ and insert the magnet link of the torrent you would like to play" line) and i got it working by adding it to the Localizable.strings file. And i think it's easier just to write the translation here and you copy/paste it in the spanish .strings instead of uploading the Localizable.strings file.

Both issues are from the open external view, as you can see in the below image:
![41448506-1d4dd5de-7018-11e8-8fa9-1b20fd98f28b](https://user-images.githubusercontent.com/12305078/41619846-ed53d792-73c4-11e8-8f46-2b04fc18795d.png)

Here's the translation:
"Please navigate to the webpage %@ and insert the magnet link of the torrent you would like to play" = "Por favor, navegue a la página web %@ e inserte el enlace magnet del torrent que le gustaría reproducir";

**Comment by angryDuck2** [comment]
Thank you for your time. The localization will be updated in the next version
