### ISSUE TITLE
Scrolling down on Apple TV 4K crashes the application

### ISSUE THREAD

**Issue by DJMpc99** [PopcornTimeTV/PopcornTimeTV#684]
Scrolling down on Apple TV 4K crashes the application 

tvOS 11.4

**Comment by DJMpc99** [comment]
This happens when you're watching movies. When you scroll down to get more info or subs, the app completely crashes.

**Comment by calcarod** [comment]
I have the same error, please fix it!!

Thank you.

**Comment by kutbuz** [comment]
Scrolling down on Apple TV 4K crashes the application. Please fix it.

**Comment by Endilus** [comment]
Same error on Apple TV (non 4K) running latest tvOS version.
I tried to install earlier version (3.2.17) but it crashes also.

**Comment by Jezze83** [comment]
@tomto147 do we need install that every 7 days because of that developer account?

**Comment by tomto147** [comment]
Yes every 7 days or use a paid service like appdb.to to do it evry 365 days ;-) Register as pro for ca €20 and you will be able to install apps even romotely. I use it for my appleTV4k and iphone. Works great

**Comment by Jezze83** [comment]
I have ipastore but seems they dont have working version available for atv.

**Comment by tomto147** [comment]
I used to use ipastore but they are far behind appdb both on amount of apps but also on usability level. And you can sign any app from the net there.

**Comment by Endilus** [comment]
Thanks @tomto147 that solved the problem for now.

**Comment by Ch0w77** [comment]
Thank you @tomto147 it solved for me too, but now there's no subtitle at all.

**Comment by darkobg79** [comment]
Scrolling down on Apple TV 4K crashes the application on **tvOS 12,** this solution dont work. Have some idea what is problem?

In PopcornTime/Resources/AVSpeakerManager.swift i make change in line:

  if #available(iOS 11.4, tvOS 11.4, *) {

to:

  if #available(iOS 12.0, tvOS 12.0, *) {

Make new IPA and install on Apple TV 4K, but when scrolling down crashes the application again.
