### ISSUE TITLE
Subtitles are most of the time delayed

### ISSUE THREAD

**Issue by AnasEltiar** [PopcornTimeTV/PopcornTimeTV#686]
[App]() version: 3.2.19
iOS/tvOS version:11.4

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Have well timed and not delayed subtitles while watching a movie

#### Actual Behaviour

horribly timed subtitles and the delay option in the drag down menu is not any help.

#### Steps to reproduce the behaviour

1. choose a movie or tv show
2. Enable subtitles
3. watch as the subtitles are completely mistimed with the movie by minutes.

**Comment by andyverdenelli** [comment]
Same problem. On apple tv you can delay or add 60 second. But its not enought. Some subtitles are delay about 2 minutes.
