### ISSUE TITLE
Chromecast crashing when streaming from iPad to chromecast

### ISSUE THREAD

**Issue by Dumeli** [PopcornTimeTV/PopcornTimeTV#688]
App version:
iOS/tvOS version: 3.2.19

Make sure these boxes are checked before submitting your issue - thanks!

- [x ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Cast the whole movie/show with no interruption 

#### Actual Behaviour

Streams for a short period of time, usually less then 2 minutes. Afterwards it stop streaming

#### Steps to reproduce the behaviour

1. ...install ipa
2. ...select movie or show
3. ...cast it to chromecast
4 ....movie / show will play for a short while before stopping from casting. App doesn’t crash but the cast simply stops.

**Comment by SirRichardLXIX** [comment]
I have exact same problem.
3.2.20, ios 11.4, iphone x.

**Comment by Dumeli** [comment]
Resolved issue by turning off the screen ‘auto-lock’. I believe when the iPad or iPhone screen would go off, the app stops downloading in the background.
