### ISSUE TITLE
New .IPA's for IOS/TvOS 11.4 & 12 for 

### ISSUE THREAD

**Issue by nuvzzy** [PopcornTimeTV/PopcornTimeTV#689]
Is there gonna be new .IPA's to download? As the latest release is from 4th may and crashes in 11.4 , I see there's a fix for it however the latest downloadable .IPA doesn't include this fix :(

**Comment by angryDuck2** [comment]
We are currently busy with fixing the airplay streaming functionality available to the app up to 11.4. Once we are able to find a fix for that we will issue a new update
