### ISSUE TITLE
Watching interrupted by black screens

### ISSUE THREAD

**Issue by iclems** [PopcornTimeTV/PopcornTimeTV#69]
While watching, every minute or so of an episode I'm getting a temporary black screen for 1s. Not download related this full file already buffered / downloaded

**Comment by popcornMaster** [comment]
I have also had some torrents with such issues both on the desktop version, where this issue would manifest as a temporary pause in the video, without a black screen, it seems it is an issuw with inconsistencies on the video file! Nothing we can do for that, closing this issue!
