### ISSUE TITLE
Cannot assign value of type 'Double' to type 'Float' 

### ISSUE THREAD

**Issue by Ao7378** [PopcornTimeTV/PopcornTimeTV#690]
When i try to compile the PopcornTime.xcworkspace i got 2 errors saying

Double(movie.rating)/20.0           Cannot assign value of type 'Double' to type 'Float'

Double(show.rating)/20.0            Cannot assign value of type 'Double' to type 'Float'

**Comment by angryDuck2** [comment]
Thank you for reporting this, we will push a new update to the repository very soon
