### ISSUE TITLE
3.2.20 version is shown as 3.2.19 on the apple TV and the top menu bug is still there.

### ISSUE THREAD

**Issue by saveyourskin** [PopcornTimeTV/PopcornTimeTV#691]
App version:3.2.20
iOS/tvOS version: 11.4

Make sure these boxes are checked before submitting your issue - thanks!

- [*] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [*] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [*] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

Hi, i´ve downloaded the Latest version  3.2.20 .ipa file , then i signed it using koditvbox.ca service as I always do for every release.

but after installing the app on the Apple TV4 (1080p)  the app version shows 3.2.19 and the top menu bug it´s still there.

i´ve downloaded the .ipa file several times, and deleted the app for a fresh install and i can´t get it to install.

**Comment by angryDuck2** [comment]
Could you check if maybe the app is installed twice on your AppleTV?

**Comment by tomto147** [comment]
Install a modified version that solves this problem from here (ipa). https://mega.nz/#!fPA31CRL!sEk8465A48sqFIVB8XLLYNpJwYAxe-1FA0Ir-GnDV64) resign yourself or register for a paid appsign service from here https://appdb.to?ref_code=a1c6f2f507f2f162365b1625c9fafd91

**Comment by darkobg79** [comment]
Compiled app for TVOS 12, problem with scrolling down top menu is resolved. Thank you @MatthieuLab

Download and install a modified version that solves this problem from here: https://uptobox.com/2qp5jt6fn076

It need to resign app.
