### ISSUE TITLE
installing on Apple TV 4k

### ISSUE THREAD

**Issue by matiasloda** [PopcornTimeTV/PopcornTimeTV#692]
App version: any
iOS/tvOS version: 11.4
the only way to install popcornTV on Apple TV 4k is by Xcode?
because it doesn't have USB-C port
Thanks

**Comment by darkobg79** [comment]
Yes, only way is XCODE for model Apple TV 4K..

**Comment by AnasEltiar** [comment]
I recently switched to the Apple TV 4K model and ran into your same issue. Simply access Xcode, then on the top menu bar click window then devices and simulators. access bluetooth remotes/devices on the Apple TV 4k and connect with your Mac.

**Comment by tomto147** [comment]
You can also install ready to use ipa from here https://mega.nz/#!fPA31CRL!sEk8465A48sqFIVB8XLLYNpJwYAxe-1FA0Ir-GnDV64) resign yourself or register for a paid appsign service from here https://appdb.to?ref_code=a1c6f2f507f2f162365b1625c9fafd91
