### ISSUE TITLE
Swift error: State' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by crookedbard** [PopcornTimeTV/PopcornTimeTV#695]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [X ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Build and run

#### Actual Behaviour

Doesn't build. Throws: error: 'State' is ambiguous for type lookup in this context

#### Steps to reproduce the behaviour

/Users/dkr/Documents/GitHub/PopcornTimeTV/PopcornTime/UI/Shared/Views/DownloadButton.swift:37:24: error: 'State' is ambiguous for type lookup in this context
    var downloadState: State = .normal {
                       ^~~~~
/Users/dkr/Documents/GitHub/PopcornTimeTV/PopcornTime/UI/Shared/Views/DownloadButton.swift:14:10: note: found this candidate
    enum State {
         ^
UIKit.UIControl:115:19: note: found this candidate
    public struct State : OptionSet {

**Comment by qinyuhang** [comment]
Same issue when run in Xcode 10 beta 3

**Comment by PlasmaSoftUK** [comment]
I have same issue in Xcode 10 Beta 4.

**Comment by PlasmaSoftUK** [comment]
Still the same in Xcode 10 Beta 6, I've done a complete delete and re-check out followed by a pod update. :(

**Comment by PlasmaSoftUK** [comment]
I fixed this by renaming "Enum State" to "Enum Status" seems UIKit also has a "State" and they conflict. Re-naming the Enum and updating the references to it has solved the problem and I can now build on Xcode 10 beta 6. :D

**Comment by PlasmaSoftUK** [comment]
IOS builds fine, for tvOS I also had to comment out line 153 - 165 in ItemViewController.swift as I couldn't figure out how to fix the errors. But this is only in the 'playTrailer()' section so watching movies still works fine.

**Comment by hiburn8** [comment]
Thanks @PlasmaSoftUK !!! the iOS build wouldnt work until i renamed the State enum.
