### ISSUE TITLE
Running app from /Applications on tvOS or iOS doesn't work.

### ISSUE THREAD

**Issue by Diatrus** [PopcornTimeTV/PopcornTimeTV#696]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
Launch the app.

#### Actual Behaviour
Crashes pretty much before it opens.

#### Steps to reproduce the behaviour

1. Install PopcornTime on a jailbroken device, iOS or tvOS, into /Applications by simply copying the .app folder over and running uicache.
2. Attempt to run the app.
3. App will either crash without opening or open for half a second, then crash. I haven't gotten any crash logs as of yet.

**Comment by Diatrus** [comment]
Issue was COMPLETELY FIXED by adding entitlements to the binary and every framework. Place this script+plist in the .app folder of the Apple TV version and run it, that should fix the issue. 

[Place In Popcorntime.app.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/2193375/Place.In.Popcorntime.app.zip)

I have also set up a nitoTV repo with a working version of PopcornTime: http://diatrus.github.io/tv

**Comment by angryDuck2** [comment]
The code to do this already existed in a script on our [https://github.com/PopcornTimeTV/popcorntimetv.github.io](repo)

**Comment by Diatrus** [comment]
@angryDuck2 no offense, but the script obviously didn’t do the job right in adding entitlements, as the iOS application crashed when adding from the Cydia repo without adding entitlements to the binary and all framworks.

**Comment by Jeffryyyy** [comment]
> Issue was COMPLETELY FIXED by adding entitlements to the binary and every framework. ~Place this script+plist in the .app folder of the Apple TV version and run it, that should fix the issue.~
> 
> ~Place In Popcorntime.app.zip~
> 
> ~EDIT: You will need to put ldid2 in /usr/bin/ on a Mac for the above to work. ldid2.zip~
> 
> [I made a script](https://github.com/Diatrus/App2deb) to add entitlements and automatically create a deb. ~I will update so it will work with both iOS and tvOS.~ Just drop the tvOS/iOS ipa(s) into the folder with the App2deb files and run ./App2deb [IPA].
> 
> EDIT: Updated to now repack both iOS and tvOS ipas automatically.
> 
> This could help @popcornMaster if they decided to setup a working repo again.
> 
> I have also set up a nitoTV repo with a working version of PopcornTime: http://diatrus.github.io/tv

Link say 404 File not Found, is it dead?
