### ISSUE TITLE
TVVLCKit/TVVLCKit.h file not found

### ISSUE THREAD

**Issue by JohnRPoole** [PopcornTimeTV/PopcornTimeTV#7]
When compiling the code for v 1.0, I get the following errors:

"TVVLCKit/TVVLCKit.h file not found"

"Failed to import bridging header '/
Users/Home/Desktop/PopcornTimeTV-1.0/PopcornTime/PopcornTime-..."

Cocoapods are installed in project file and updated

**Comment by Faisal-nz** [comment]
Having the same error, i have tried to delete the repo folder. Reinstall it again. Same error keep appearing

**Comment by maitremiju** [comment]
Exact same error on my side. Issue with TVVLCKit.

**Comment by sasagr** [comment]
same error here

**Comment by popcornMaster** [comment]
People please redownload the project and try again running the swift install script. Thank you!

**Comment by Faisal-nz** [comment]
Thank you for the great effort and the quick response

Many Thanks



On 10 Aug 2016, at 5:10 pm, popcornMaster <notifications@github.com<mailto:notifications@github.com>> wrote:


People please redownload the project and try again running the swift install script. Thank you!

-
