### ISSUE TITLE
Crashes on tvOS version 12.0

### ISSUE THREAD

**Issue by anonymouse1989** [PopcornTimeTV/PopcornTimeTV#700]
App version:
iOS/tvOS version: tvOS 12.0

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

When you pull down from the top menu it crashes i am using tvOS version 12.0 beta, and latest popcorn time 3.2.20, installed and reinstalled 3 times, but never solved the problem.

**Comment by tomto147** [comment]
Install a modified version that solves this problem from here (ipa). https://mega.nz/#!fPA31CRL!sEk8465A48sqFIVB8XLLYNpJwYAxe-1FA0Ir-GnDV64) resign yourself or register for a paid appsign service from here https://appdb.to?ref_code=a1c6f2f507f2f162365b1625c9fafd91

**Comment by Endilus** [comment]
@tomto147 I tried the modified version on tvOS 12.0 but it still crashes when pulling down the top menu.

**Comment by tomto147** [comment]
So something must have changed in ios12. I’m still on 11.4.1. You have to downgrade or wait till someone fix it

**Comment by arturaskerelis** [comment]
Hey @tomto147, do we have an iOS 12 "PopcornTimeiOS.ipa fix? iPhone not Apple TV, thanks!

**Comment by tomto147** [comment]
Don't know... I'm using only ATV version...

**Comment by zapton** [comment]
I used the newest .ipa filed on AppleTV but when I scroll down for using the subtitle menu the popcorn time app freeze (crash). So I have to start the app again. Everytime the app crashed when I try it again. The bug was also on version 3.2.19.
Is there a solution?

**Comment by vikram909060** [comment]
You can get PopcornTime TV App signed for 1 Year Premium Service [HERE](https://appipa.online/shop) and You can just drag and drop app using a PC and it will last for full 1 year without any revoke and charge is $15 for 1 Year App Signing you will need to pay.

**Comment by darkobg79** [comment]
Compiled app for TVOS 12, problem with scrolling down top menu is resolved. Thank you @MatthieuLab

Download and install a modified version that solves this problem from here: https://uptobox.com/2qp5jt6fn076

It need to resign app.

**Comment by Wilabs** [comment]
Hello
I am trying to install Popcorntime tv 12 on my device through Xcode but tell me(The argument is invalid.)I have Apple tv 4k.version on tvOS 12.0
Is there a solution?
Thank you.

**Comment by vikram909060** [comment]
Do you have the app signed already with developer program or just directly trying to install app after download from here ?

**Comment by Wilabs** [comment]
No i haven't, I just directly trying to install app after download from here.

**Comment by vikram909060** [comment]
Sign it with Free Developer Program ( 7 Days or buy 1 Year App signing service here appipa.online/shop and just download and install signed app.
