### ISSUE TITLE
Infinite processing on some shows

### ISSUE THREAD

**Issue by louaizema** [PopcornTimeTV/PopcornTimeTV#701]
App version:
iOS/tvOS version:
11.4
Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

two or three days ago some shows like GOT, Lost... that I used to watch normally on the app started to act strangely. I can’t watch them anymore. When I play the show it’s just stuck at processing forever

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by angryDuck2** [comment]
Unfortunately this is usually due to people stopping to seed back the torrents that our app downloads. This is out of our hands and it happens all the time

**Comment by louaizema** [comment]
Is there any way to change the API, add trackers or change the torrent provider?

**Comment by louaizema** [comment]
Thank you! Can u please add a way to add subtitles to torrents imported opened on Popcorn time?
