### ISSUE TITLE
Issues installing Apple TV 4

### ISSUE THREAD

**Issue by zzoltonn** [PopcornTimeTV/PopcornTimeTV#702]
App version:
iOS/tvOS version: Apple TV 4

I am having trouble installing popcorn time  on my Apple TV 4. I used to have no problems, now I can not install it giving me an API error. 

The past I usually get it signed through Kodi. then upload the sign .ipa file. I get an error on every app I use. 

I can't even install the current version, I was using. I get the same error, any help would be great.

**Comment by BryanN0919** [comment]
I get the same type issue.

**Comment by vikram909060** [comment]
Get PopcornTime Signed with Developer account and delete old apps from system. I am using this signing service to get it signed https://appipa.online/product/tvos-ipa-membership-atv-4/

**Comment by zzoltonn** [comment]
That is what we are doing, I am getting it signed at kodi. It used to work. I think most of us are getting “it is not compatiable with iOS 11”. I can’t even install version I had on before.

**Comment by mighty2nyce** [comment]
Does anyone know how to get Kodi on Apple TV 4 and get it to stay without having to put it back on every 7 days?! I been searching all day. Please help

**Comment by vikram909060** [comment]
You can purchase KODI Signing Service with Premium Apple Developer Account from Appipa.online/shop for Apple TV 4 and Apple 4K.

**Comment by chgeorgakidis** [comment]
Please stay relevant to the issue. I too have the problem of the API error when installing both signed and unsigned ipa files. Should we try to find some common ground? What tvOS version has everyone having the same problem installed?

**Comment by vikram909060** [comment]
App itself is working fine with latest version 3.2.23 installed on latest TvOS 12.1.
