### ISSUE TITLE
Type Lookup Error in iOS12

### ISSUE THREAD

**Issue by arturaskerelis** [PopcornTimeTV/PopcornTimeTV#705]
Within DownloadButton.swift, line 37: ` var downloadState: State = .normal {
        didSet {
            guard downloadState != oldValue else { return }
            
            invalidateAppearance()
        }
    }`

Error shows 

> 'State' is ambiguous for type lookup in this context

**Comment by PlasmaSoftUK** [comment]
To fix this you need to rename the "Enum State" at the top of your screen shot to something like "Enum Status" as it conflicts with something in UIKit. After that compile and amend all the references to the new name and it will go away. After fixing this if you are building for tvOS you will get another compile error, and will also need to comment out lines 153 - 167 in UI/Shared/ViewControllers/ItemViewController.swift.  I couldn't figure out how to fix that error but its only in the Trailers section so compiling and watching movies works fine.
