### ISSUE TITLE
Error build PopcornTime

### ISSUE THREAD

**Issue by ADMNTK** [PopcornTimeTV/PopcornTimeTV#709]
App version:
iOS/tvOS version: AppleTV 4 , v 3.2.22

Error : Extension.swift:63:40: Extra argument 'selectFileToStream' in call 

[ https://e.top4top.net/p_959m7sil1.png ](url)

help me

Thanks.

**Comment by ADMNTK** [comment]
Thank You 👍 
Done!

**Comment by pc2019** [comment]
i delete the old project, erase all files in derived data, and clone the project again, i use pod repo update; pod install, but still i have this error, maybe im doing something wrong?

**Comment by darkermatter** [comment]
Hello!

I am getting this error after a fresh git pull and pod install.

**Comment by angryDuck2** [comment]
Try a pod update and not a pod install as the cache that cocoapods has downloaded is probably outdated and only pod update refreshes the cache

**Comment by darkermatter** [comment]
Hi @angryDuck2 ,

I ran the update and it compiled fine. Perhaps an update to the README is needed?
