### ISSUE TITLE
How To Un-Favorite Content

### ISSUE THREAD

**Issue by JonnyBoy333** [PopcornTimeTV/PopcornTimeTV#71]
This seams like there must be something very simple I am missing but I've gone and favorited a few movies/tv shows and now would like to un-favorite some of those items and can't figure out how to do so. I've tried clicking the favorite button again and holding down various buttons on the apple remote on the favorited item but still no luck.

**Comment by popcornMaster** [comment]
There was a bug in previous versions, resolved with the latest version 1.0.5, please download latest version!
