### ISSUE TITLE
0.5.0 - Many TV shows still have broken playback

### ISSUE THREAD

**Issue by Sonikkua** [PopcornTimeTV/PopcornTimeTV#71]
Many shows (i.e. Game of Thrones, etc) play back only a few seconds before freezing or becoming very garbled when playing back in HD resolution. Waiting does not help. Related to new VLC?

**Comment by buzzel** [comment]
This is looking more like an issue with Game of Thrones in 1080p. I managed to play 720p fine. I don't have any issues with any other shows in 720 or 1080, just that show so it could be bad torrents. We'll have a look at this though and see if it is an issue with VLC.

**Comment by mtwww** [comment]
same issue here with Sonikkua. I tried with 720 and 1080 both. (game of thrones)
other shows like Breaking Bad even not playing.. a black screen appearing and freezing.

**Comment by buzzel** [comment]
I have tested both shows in the simulator and they seem to be working for me. I've tested them both in 480, 720 and 1080p and they seem to be working fine. run a `pod update` as PopcornTorrent was updated to hopefully download shows faster and buffer more of them before it begins playing

**Comment by buzzel** [comment]
@Sonikkua Does this issue still exist?

**Comment by Sonikkua** [comment]
@buzzel seems to be working fine now here.
