### ISSUE TITLE
PopcornTimeTV ready for aTV OS 10?

### ISSUE THREAD

**Issue by tomsbrinkis** [PopcornTimeTV/PopcornTimeTV#72]
When it will be ready?

**Comment by iAYMANi** [comment]
yes ready

**Comment by JohnRPoole** [comment]
Is there a timeframe on the release for the tvOS 10 compatible source code?

**Comment by tomsbrinkis** [comment]
@iAYMANi @popcornMaster @tvOSPopcorn 

What are the steps for best update?

1) update to 1.0.5 and install it to tvOS 10 with Xcode 7 ? 
OR
1) update to Xcode 8
2) then download 1.0.5 and install to  tvOS 10? 

Or maybe popcorntime 1.0.5 still isnt ready for tvOS 10?

**Comment by moh0sw** [comment]
@tomsbrinkis PopcornTime isn't ready for tvOS 10 yet

**Comment by Hackormahn** [comment]
PopcoenTimeTV is compatible with TVOS 10, however we have not ported it to Swift 3. You will need to manually resign the 1.0.5 iPA available on our releases page or resign it with Appdb.cc Pro.
