### ISSUE TITLE
swift 4.2 problems

### ISSUE THREAD

**Issue by pc2019** [PopcornTimeTV/PopcornTimeTV#725]
App version: 3.2 BUILD 22
iOS/tvOS version: TVOS 12.0.1

Make sure these boxes are checked before submitting your issue - thanks!

- [X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...compiling without problems

#### Actual Behaviour

...xcode cant compile the project

#### Steps to reproduce the behaviour

1. ...download the project
<img width="1395" alt="captura de pantalla 2018-10-02 a la s 09 27 15" src="https://user-images.githubusercontent.com/36860727/46355170-eb62a400-c625-11e8-98ab-ef2956f4e543.png">
<img width="1398" alt="captura de pantalla 2018-10-02 a la s 09 27 28" src="https://user-images.githubusercontent.com/36860727/46355230-09300900-c626-11e8-9626-749145354814.png">

2. ...start compiling
3. ...appears many swift 4.2 problems

**Comment by leonidster** [comment]
Yep, you should change pod compiler setting for: TvOSMoreButton, SwiftyTimer-iOS', SwiftyTimer-tvOS, FloatRatingView-iOS', FloatRatingView-tvOS' pods to Swift 4 instead of Swift 4.2.

or you update the podfile, uploaded updated file here:
https://uploadfiles.io/9r3i5

replace current podfile and run 'pod install'

**Comment by pc2019** [comment]
thank you for your response, i try both options, but any lucky, i use the pod file and probe change compiler setting to swift4 and still have errors. Please your help.
<img width="1142" alt="captura de pantalla 2018-10-04 a la s 09 48 33" src="https://user-images.githubusercontent.com/36860727/46482339-061a5180-c7bb-11e8-8c97-78f3b0c2d99c.png">

**Comment by Farslasher** [comment]
![image](https://user-images.githubusercontent.com/43863374/46500452-dd14b380-c7f0-11e8-9e73-bb943126acfd.jpg)
All,
I went and changed the deployment target on everything to 12.0 and that seemed to fix one of the issues but I’m still left with the AlarmofireImage and ObjectMapper issue after doing the pull reset. Any more suggestions?

**Comment by leonidster** [comment]
> thank you for your response, i try both options, but any lucky, i use the pod file and probe change compiler setting to swift4 and still have errors. Please your help.
> <img alt="captura de pantalla 2018-10-04 a la s 09 48 33" width="1142" src="https://user-images.githubusercontent.com/36860727/46482339-061a5180-c7bb-11e8-8c97-78f3b0c2d99c.png">

Please close Xcode and open again, clean and build project. Updating the podfile and running pod install solved the problem completely for me.

**Comment by pc2019** [comment]
please, i do all recomendations but still no lucky
<img width="1440" alt="captura de pantalla 2018-10-07 a la s 14 37 24" src="https://user-images.githubusercontent.com/36860727/46586066-b21f9f00-ca3e-11e8-9eee-adfce5442270.png">
