### ISSUE TITLE
Subtitle not downloaded or presented - after killing app it works

### ISSUE THREAD

**Issue by GerTeunis** [PopcornTimeTV/PopcornTimeTV#73]
I'll attach some console logging here as soon as I can see it again.

What happens: we start watching a movie in want to open the Dutch subtitles.
We select Dutch, it doesn't show the Dutch subtitles. We select English and it DOES work.

Then we kill the app (home button double tap, kill Popcorn Time) and start the same movie again, select Dutch. This time it works as expected. This is my default-work-around for the last couple of weeks. Can't have my mac attached all the time.

**Comment by popcornMaster** [comment]
Please check the latest version, this issue was reported and fixed! #59

**Comment by GerTeunis** [comment]
You're awesome! Keep up the great work, I should get you a beer someday.
