### ISSUE TITLE
Subtitles not showing

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#730]
App version: 3.2.23
iOS/tvOS version: 12.0.1

Hi, Subtitles do not show. Selecting several languages from the pull down menu. None of them show with several movies. 

Am I the only one, or is this a common issue?

Thanks

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by angryDuck2** [comment]
They might take a while to download for whatever reason, opensubs seems to be a bit slow in serving them. Just hold off from pushing the top menu away until you see the subtitle you chose

**Comment by Evhelden** [comment]
Thanks. Will check. Does this potentially create an automated delay and per definition not synchronous?
