### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by juanfrancisco227** [PopcornTimeTV/PopcornTimeTV#738]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

I expect the compile to through 

#### Actual Behaviour

when it gets to the last bit of compiling it freezes the whole computer. Never done that before not sure if it is Xcode 10 or the new version of the app

#### Steps to reproduce the behaviour

1. try to compile it 
2. ...
3. ...

**Comment by Red-Mak** [comment]
i have the exacte same problem, iOS version compile fine (i install it into my iPhone X), but if i want to install it directly to my Apple TV 4K (or archive it) xcode (and the whole mac) froze and i have to force shutdown it.

config:
last code available (git clone)
macOS 10.14
xcode 10.0
Apple TV 12.0

**Comment by DarkoBG79** [comment]
Same problem :( cant compile for Apple TV or archive it. 
Identical description.

**Comment by williamoconnorme** [comment]
Also having this issue

**Comment by angryDuck2** [comment]
Here is a rdar filed to Apple describing the issue with XCode 10. Nothing this team can do about

http://www.openradar.me/45324895
