### ISSUE TITLE
Open External error "Sorry something went wrong, try again"

### ISSUE THREAD

**Issue by TinyOutsider** [PopcornTimeTV/PopcornTimeTV#739]
App version: 3.2.23
iOS/tvOS version: tvOS 12.0.1

#### Expected Behaviour
1. Go to the Open External page.
2. Visit the displayed IP address on your PC.
3. Paste the magnet link.
4. The video starts playing.

#### Actual Behaviour
1. Go to the Open External page.
2. Visit the displayed IP address on your PC e.g. http://10.0.0.5:54320 
3. Paste the magnet link.
4. The website shows an error message: "sorry something went wrong, try again"

#### Additional Notes
This feature has never worked for me, i have previously tried different versions fo Popcorn. I am on the same Wifi network on both my Mac and AppleTV. I have also tried this on both Safari/Chrome.

**Comment by angryDuck2** [comment]
We have identified that there is an issue when the magnet link contains the hash for the torrent in capitals, this can occur. It will be fixed in the next release
