### ISSUE TITLE
Theme audio (intro music) for movies?

### ISSUE THREAD

**Issue by wahlmanj** [PopcornTimeTV/PopcornTimeTV#74]
Could theme audio be added to movies as well like iTunes extras provides then in the settings tab set it to off as default like it is for tv show theme song volume and let us turn it on if desired?

For example:

https://www.youtube.com/watch?v=5uJfWqBZ5pk

This would be a more cinematic experience like popping in a dvd ;)

Maybe this would help?

https://itunesconnect.apple.com/docs/iTunesExtrasPackageSpecification.pdf

```
<!-- 2b. This is the vendor ID of menu background gallery referenced by the <background_gallery_link> tag above (2a) that stores the image asset(s) and audio
file. -->
      <vendor_id>CLOUDY_MEATBALLS2_MAIN_BG_GALLERY</vendor_id>
      <!-- Items used for the background are stored in a menubg-type gallery -->
      <gallery_type>menubg</gallery_type>
      <!-- The display name for the gallery is for internal use only; users do not
  see this name -->
      <display_name>MAIN_BG_GALLERY</display_name>
      <gallery_items>
        <gallery_item type="image">
          <vendor_id>CLOUDY_MEATBALLS2_MAIN_BG_IMG1</vendor_id>
          <assets>
   ...
<!-- Image assets goes here; one for each display target.  -->
  </assets>
</gallery_item>
<gallery_item type="audio">
  <vendor_id>CLOUDY_MEATBALLS2_BG_GALLERY_LOOP</vendor_id>
  <assets>
    <!-- Audio asset goes here.  -->
    <asset>
      <data_file>
        <file_name>cm2_bg.wav</file_name>
        <size>10004316</size>
        <checksum type="md5">d335dad616ab73fdfcec
38592d0f5d82</checksum>
              </data_file>
            </asset>
          </assets>
      </gallery_items>
</gallery>
        <!-- You can have multiple galleries of type menubg for localized menu
  backgrounds as well as a menubg gallery for each navigation node, for example,
  SCENES, RELATED, and so on. -->
```

So you can find movies like the dark knight on imdb.com for example tt0468569, but how could PCT scrape the internet for a intro theme...

Only way I can think is to search youtube by title of movie and year then add theme for example:

'the dark knight' & '2008' & 'theme' (Guess you could do without the year and just do the movie title and add the text 'theme')

grab the first result from youtube and play the audio only. Now coding that into PCT is another story 👍

**Comment by FlaviaBondJamesBondsHusband** [comment]
Thanks for the suggestion. Enjoy!
