### ISSUE TITLE
Home button not working?

### ISSUE THREAD

**Issue by Sonikkua** [PopcornTimeTV/PopcornTimeTV#74]
Is it just me, or is the home button not working in 0.5.0? I'm able to get out of the app by using the 'back' button repeatedly, or by double tapping home to invoke the task switcher, but home by itself doesn't seem to do anything. I'll add it could be a tvOS beta issue, but this is the only app that appears to be exhibiting this issue.

**Comment by buzzel** [comment]
That wouldn't pertain to the app at all. tvOS doesnt allow any hooks on the button.
