### ISSUE TITLE
Watchlist item disappears 

### ISSUE THREAD

**Issue by TinyOutsider** [PopcornTimeTV/PopcornTimeTV#745]
App version: 3.2.23
iOS/tvOS version: tvOS 12.1

Actual Behaviour

1. Choose/search a TV Show to watch
2. Add it to your Watchlist 
3. Next time go straight to Watchlist 
4. That show is not in your Watchlist anymore. This only happens to those shows which I watch. All previously added shows are still there.

**Comment by TinyOutsider** [comment]
Sorry I’m not talking about One Episode, but the whole show disappears from Watchlist. So next time I find the show again (watch another episode), add it to Watchlist and it disappears again.
This only started with the latest tvOS 12.1 update I believe.

**Comment by angryDuck2** [comment]
No this is the behaviour the app has had since day one of the integration with trakt. This is how trakt functions

**Comment by TinyOutsider** [comment]
Don’t take me wrong but I don’t think that’s true.  
I know Movies disappear after you watch them, but tv shows stay there until you finish watching all episodes. I know that for a fact. Because I have added a number of tv shows and watch them regularly. I never had to add them to Watchlist the second time (otherwise there is no point adding to Watchlist if you have to add them every time you watch an episode).

**Comment by angryDuck2** [comment]
Will make sure to double check with devs. Almost certain though that it is the way trakt works

**Comment by angryDuck2** [comment]
The devs came back with a "as expected" answer. I found [this](https://support.trakt.tv/knowledgebase/articles/154739-why-do-things-get-removed-from-my-watchlist-after) on trakt's website. As I told you this is how the function is supposed to work
