### ISSUE TITLE
Thumbnails not showing on ATV homescreen

### ISSUE THREAD

**Issue by Midifreakz** [PopcornTimeTV/PopcornTimeTV#748]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
Show thumbnails on ATV homescreen (Trending)

#### Actual Behaviour
It appears that movie covers, nor TV-show covers load in the trending pane, at the ATV homescreen. It also seems to affect the thumbnails showing 'continue watching' for netflix. 

When I remove Popcorn time, Netflix thumbnails reappear. In the PT app itself, only a few movie covers load. Tv shows seems to be fine, with exeption of a few not loading covers. -->
...

#### Steps to reproduce the behaviour
What steps do we need to take to find the same bug that you found?

1. Install PopcornTime tvos 23
2. No thumbnails in trending pane, also netflix trending pane does not load any thumbnails.
3. Remove PT from ATV
4. Netflix Thumbnails reappear after restart.

I get that sometimes movie covers wil not load because of the external hosting, but it's weird however that also the netflix thumbnails get affected.

**Comment by TinyOutsider** [comment]
I’ve got the same issue with both Popcorn Time and Netflix thumbnails. Im using the latest version 3.2.23.
However TV Show thumbnails are working fine.

**Comment by ricardopereira** [comment]
I was facing this issue but it started working again. @Midifreakz do you confirm?

**Comment by Midifreakz** [comment]
@ricardopereira Yes I can confirm that the issue is gone by now. Maybe one of the developers can explain to us what was happening?

**Comment by angryDuck2** [comment]
The api of trakt was being a lot sluggish and the http request was timing out when requesting the covers
