### ISSUE TITLE
App crashing after scroll down for subtitles

### ISSUE THREAD

**Issue by itshenriqueyall** [PopcornTimeTV/PopcornTimeTV#755]
App version: 3.2.30
iOS/tvOS version: tvOS 12.1

Everytime i scroll down to select a subtitle the app crashes. Any way to fix it? 

Make sure these boxes are checked before submitting your issue - thanks!

- [ X ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ x ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
 load the subtitle bar
...

#### Actual Behaviour

... the app crash

#### Steps to reproduce the behaviour
 

1 - load a movie or tv show 
2 - use the remote to scroll down (to select a subtitle) and the app will crash.

**Comment by angryDuck2** [comment]
Delete app and reinstall

**Comment by jberglinds** [comment]
@angryDuck2 That did not fix it for me. 
This line is the problem: https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/PopcornTime/UI/tvOS/Option%20View%20Controllers/SubtitlesViewController.swift#L77
For me, `subtitles` has no key "English" so that force-unwraps an optional.
My device language is Swedish so the key "Engelska" (English in Swedish) existed instead. 

Quick-fix:
```diff
- subtitlesInView = [currentSubtitle ?? subtitles["English"]!.first!,Subtitle(name: "", language: "Select Other", link: "", ISO639: "", rating: 0.0)]
+ subtitlesInView = [currentSubtitle ?? subtitles["English"]?.first,Subtitle(name: "", language: "Select Other", link: "", ISO639: "", rating: 0.0)].compactMap({ $0 })
```

**Comment by whatthehomepod** [comment]
Do you mind to share the ipa? My MBP is at repair and only having a Windows laptop here. I can sign it myself through appdb. Would be very appreciated, the app crashes are really annoying
