### ISSUE TITLE
Build errors on the master branch (iOS)

### ISSUE THREAD

**Issue by tychop** [PopcornTimeTV/PopcornTimeTV#756]
App version: 3.2 build 25
iOS version: 12.1.1 (16C50)
XCode Version 10.1 (10B61)
Cocoapods 1.5.3 (pod repo update && pod install && open *.xcw*)

Project compiled and runs successfully on tvOS.
But on iOS, I get some build errors on the master branch:
Tried deployment target 9.0 as it was in the master branch, and also tried 12.1.

What could I be doing wrong?

```
Swift Compiler Error Group
PopcornTimeTV/PopcornTime/UI/iOS/Extensions/ShowsViewController+iOS.swift:32:152: Use [:] to get an empty dictionary literal
PopcornTimeTV/PopcornTime/UI/iOS/View Controllers/CastPlayerViewController.swift:39:45: Cannot invoke 'index' with an argument list of type '(of: Subtitle)'
PopcornTimeTV/PopcornTime/UI/iOS/View Controllers/CastPlayerViewController.swift:209:60: Value of tuple type '(key: String, value: [Subtitle])' has no member 'language'
PopcornTimeTV/PopcornTime/UI/iOS/View Controllers/CastPlayerViewController.swift:228:53: Cannot invoke 'first' with an argument list of type '(where: (_) -> _)'
PopcornTimeTV/PopcornTime/UI/iOS/View Controllers/CastPlayerViewController.swift:276:41: Cannot invoke 'index' with an argument list of type '(of: (key: String, value: [Subtitle]))'
PopcornTimeTV/PopcornTime/UI/iOS/View Controllers/CastPlayerViewController.swift:285:62: Ambiguous reference to member '=='
PopcornTimeTV/PopcornTime/UI/iOS/Extensions/MoviesViewController+iOS.swift:35:156: Use [:] to get an empty dictionary literal
```

**Comment by angryDuck2** [comment]
Peform a pod update and not a pod repo update. Always a pod update. Never a pod repo update. Pod repo update does not download package updates

**Comment by tychop** [comment]
"Always a pod update. Never a pod repo update. " Well, that depends. In my company new repositories are added regularly.. 
Back on topic: I get the same errors after pod update...

**Comment by tychop** [comment]
I deleted the derived data dirs (rm -rf ~/Library/Caches/com.apple.dt.Xcode ~/Library/Developer/Xcode/DerivedData/ModuleCache/* ~/Library/Developer/Xcode/DerivedData/*)
I cleaned the build folder (Command+Shift+K  & Command+Option+Shift+K
But the problem stays. Even after consequent rebuilding....
PopcornKit compiles fine:
<img width="520" alt="screenshot 2018-12-24 at 18 37 56" src="https://user-images.githubusercontent.com/80199/50404704-34507180-07ab-11e9-8b86-a348fcf32037.png">

What exactly do you mean with "It is not compiling PopcornKit from start and does not see the changes" ??

**Comment by tychop** [comment]
If I zoom in on a single error I see incompatibilities....

line 24 of Media.swift in PopcornKit reads: `var subtitles: Dictionary<String, [Subtitle]> { get set }`
line 208 in CastPlayerViewController.swift reads: 
```
        for subtitle in media.subtitles {
            alertController.addAction(UIAlertAction(title: subtitle.language, style: .default) { [unowned self] _ in
                self.currentSubtitle = subtitle
            })
        }
```
This means the error  `Value of tuple type '(key: String, value: [Subtitle])' has no member 'language'` is correct.

But which is wrong? Is it Media.swift or CastPlayerViewController.swift ?
What do these files read on your side?

**Comment by jfernandogt** [comment]
I got the same issues.

**Comment by angryDuck2** [comment]
Really sorry you are all right, we did not upload the latest local commits before, they are now up. This issue is now fixed
