### ISSUE TITLE
3.2.30 Stream to Chromecast Not Working

### ISSUE THREAD

**Issue by jo2kGH** [PopcornTimeTV/PopcornTimeTV#757]
App version: 3.2.30
iOS/tvOS version: iOS 11.3.1/12.1

Make sure these boxes are checked before submitting your issue - thanks!

[X] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
[X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
[X] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

Expected Behaviour
Content Streaming to Chromecast when selected

Actual Behaviour
Once the video processing/buffering completes, the buffering page disappears and reverts back to the info page 

Steps to reproduce the behaviour
1. Start App, choose a video and select "Stream to Devide --> *(your) Chromecast Device"
2. Click "Play" & wait for video processing/buffering to complete
3. Watch the buffering page disappear and app reverts to previous page

**Comment by angryDuck2** [comment]
If you can compile from source check out the latest commit. It should solve your issues.

**Comment by jo2kGH** [comment]
Indeed it is fixed in 3.2.33. Thanks!
