### ISSUE TITLE
appletv 4k still crash to homescreen when pulldown menu

### ISSUE THREAD

**Issue by PoepieFloepie** [PopcornTimeTV/PopcornTimeTV#758]
App version: 3.2.30
tvOS version: 12.1.1

Expected Behaviour
menu comes down to select something subtitles or audio
...

Actual Behaviour
crashed back to homescreen
...

Steps to reproduce the behaviour
What steps do we need to take to find the same bug that you found

1. ...install app on apple tv 4k
2. ...select movie
3. ...movie begins playing ,pulldown menu crash to homescreen

i installed several times
also restart de appletv then install

please fix .....i installed it 15 time now and still the same thing

i tryed 3.2.30 crash to homescreen with pulldownmenu when playing movie
i tryed 3.2.23 all is good with pulldown menu ..no crash to homescreen when playing movie ...is also fixed in this version
i tryed 3.2.22 crash to homescreen with pulldownmenu when playing movie

i think they forgot to add the fix from build 3.2.23 for the crash with pulldownmenu

**Comment by Midifreakz** [comment]
Also hapens on regular AT4. At first test everything worked fine... started happening just now and persists after reinstall

**Comment by Evhelden** [comment]
Same here on regulaire AT4. Via prepareerde .ipa and self compiled versions.

**Comment by albcc** [comment]
Change line 77 adding Capitalized in SubtitlesViewController fixed the problem for me.

            subtitlesInView = [currentSubtitle ?? subtitles[Locale.current.localizedString(forLanguageCode: "en")!.capitalized]!.first!,Subtitle(name: "", language: "Select Other".localized, link: "", ISO639: "", rating: 0.0)]

**Comment by r1qu3br** [comment]
@albcc thanks man, fixed the problem for me too.

**Comment by PoepieFloepie** [comment]
Can someone post a link for de fixed version here please...👍

**Comment by angryDuck2** [comment]
The issues have been fixed with the latest commit. A new version will be out soon

**Comment by Midifreakz** [comment]
For me this issue stil persists with version 33. Instant crash

**Comment by PoepieFloepie** [comment]
i updated also to this version .33 
apple tv 4k ios 12.1.1
so far so good,updated it not clean install

**Comment by angryDuck2** [comment]
@PoepieFloepie if this issue is resolved then please close this issue. Thank you

**Comment by Evhelden** [comment]
Give me a day to install as well. Will let you know.
