### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ArsalanS1** [PopcornTimeTV/PopcornTimeTV#76]
Hi,

sorry this is not an issue but a query. If i download this now, will i need to redownload it each time it gets updated or movies get added to it. Also currently the images for the cast are blank.

Thanks,

**Comment by RefusedFlow** [comment]
Hi, each time updates are released you will need to clone the repo again and install. If you use the same BundleID as the previous installation all watchlist items will stay and won't be deleted. As for cast images, i believe it's not been implemented yet maybe in the future.

**You can track the progress off the application over on the wiki**
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress
