### ISSUE TITLE
Chromecast devices not detected in v3.2.33

### ISSUE THREAD

**Issue by vpatilvasu** [PopcornTimeTV/PopcornTimeTV#760]
App version: 3.2.33
iOS/tvOS version: iOS 12.1.2

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Cast video to Chromecast connected to same network

#### Actual Behaviour

Doesn't detect Chromecast devices on same network.
(Apps like Youtube, Netflix, etc. are able to detect and cast)

#### Steps to reproduce the behaviour

1. Open Popcorn Time app
2. Click on any movie
3. Click the casting symbol in top right corner
4. Only "Nearby Device" is shown

**Comment by angryDuck2** [comment]
Could you clarify to which device you are trying to cast to?

**Comment by jo2kGH** [comment]
I encountered the same issue with 3.2.33 App for iOS 12.1 - same version App in iOS 11.3.1 has no issue finding the Chromecast. In my case I tested it on 1 TV with Chromecast built-in & Gen3 Chromecast.

**Comment by vpatilvasu** [comment]
> Could you clarify to which device you are trying to cast to?

I'm trying to cast movie (from within PopcornTime) to Chromecast Ultra attached to my TV. I was able to do so in the previous version. In the latest version (3.2.33), Popcorntime doesn't detect any chromecast device.

**Comment by angryDuck2** [comment]
Is the Chromecast on the latest version, v1.36140138?

**Comment by pativash-lab126** [comment]
> Is the Chromecast on the latest version, v1.36140138? @vpatilvasu

@angryDuck2 Yes, cast firmware version is 1.36.140318

**Comment by Daaneman** [comment]
Same here, latest chromecast firmware, PCT v.3.2.33. iOS. Chromecast not showing in devices to cast to. Or not detected.

**Comment by angryDuck2** [comment]
The issue has been identified and will are fixed soon. In the meantime anyone that know how to build from source and run the app from Xcode directly to device will find that casting will work that way

**Comment by Daaneman** [comment]
Any progress with the fix? Tia! :)

**Comment by vpatilvasu** [comment]
> The issue has been identified and will be fixed soon. In the meantime anyone that knows how to build from source and run the app from Xcode directly to device will find that casting will work that way

Btw, I couldn't get casting working even after building and running the app from Xcode 10.

**Comment by G2Jose** [comment]
Have the same issue building and running from xcode

**Comment by Daaneman** [comment]
> The issue has been identified and will be fixed soon. In the meantime anyone that knows how to build from source and run the app from Xcode directly to device will find that casting will work that way

Is it 'soon' already? ;)

**Comment by SirRichardLXIX** [comment]
Got the same problem, it just says 'nearby devices' instead of my chromecast.

**Comment by huiskesmartijn** [comment]
Same problem here, the chromecast sign does not show up at all in this version

**Comment by sweetw0r** [comment]
Same

**Comment by thecyclops13** [comment]
Same here, latest chromecast firmware, PCT v.3.2.33. iOS. Chromecast not showing in devices to cast to. Or not detected

**Comment by sweetw0r** [comment]
https://github.com/PopcornTimeTV/PopcornTimeTV/issues/800#issuecomment-504776226

**Comment by vpatilvasu** [comment]
@angryDuck2 Thanks for [#800 (comment)](https://github.com/PopcornTimeTV/PopcornTimeTV/issues/800#issuecomment-492489820). I was able to compile Xcode with entitlement "Access Wifi Information" set to YES.
