### ISSUE TITLE
Wrong subtitles regardless of choice

### ISSUE THREAD

**Issue by JohnJacksonSmyth** [PopcornTimeTV/PopcornTimeTV#763]
App version: 3.2.33
iOS/tvOS version: tvOS 12.1.1

Make sure these boxes are checked before submitting your issue - thanks!

- [√] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [√] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [√] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...  The app should give me subtitles that somewhat matches what I'm watching.

#### Actual Behaviour

... Gives the subtitles from a totally different show or movie.  E.g. when putting on Big Bang Theory, S12E01, I'm getting NCIS: New Orleans S4E16 (Empathy) subtitles, even when the subtitles chosen from the list clearly has the title that it matches The Big Bang Theory (The.Big.Bang.Theory.S12.E01.HDTV.x264-Killers). 
This happens with every movie or series.

#### Steps to reproduce the behaviour

1. ... Choose a movie or series
2. ... Put on subtitles
3. ... Observe.

**Comment by Midifreakz** [comment]
Having the exact same issue... happens on al movies & shows.

**Comment by JohnJacksonSmyth** [comment]
I did some additional testing and debugging last night - I've cleaned the cache (even though I haven't watched the shows that wrongs subs are from), removed my own custom code (which has nothing to do with subs), and did several complete clean reinstall. 
The only consistent thing I'm seeing is that whenever I'm on VPN on my Apple TV (4K and regular) devices, I'm getting the wrong subs. The weird thing is that when I'm putting in breakpoints in the subtitle manager, check the urls, and then manually fetch the .srt with wget, it's the correct subs. Even though the wrong ones are displayed on top of the media.  
When I turn off the VPN, everything works fine. Running in simulator, everything works as expected, with or without VPN.
I ran the same builds when testing device vs. simulator. 

@Midifreakz, are you using VPN? If so, it would be interesting to see if you're getting the same results with on device with or without VPN, and the same thing on simulator.

Anyways, I'll see if I can dig a little deeper when I have the time on my hands, but since I'm not that familiar with the code, it might take a while.

**Comment by JohnJacksonSmyth** [comment]
I just tried to look inside the app package I fetched when initially testing. 

And sure enough, title of the .srt is called exactly what would be expected, but the contents of the file is completely wrong. It's weird though, because when I manually fetch the subtitles, the title and content is correct. I'm beginning to suspect that this might be a OpenSubtitle thing. 

![Uploading Screenshot 2019-01-23 at 16.25.46.png…]()

**Comment by JohnJacksonSmyth** [comment]
So it looks like OpenSubtitles.org blacklists some IP addresses, but instead of blocking requests from those IPs, they purposely send bullshit subs in return.

https://github.com/Diaoul/subliminal/issues/784#issuecomment-313583719

I'll go ahead and close this issue.

**Comment by Midifreakz** [comment]
Damn, that's a dick move... so far for the pirate community :')

**Comment by JohnJacksonSmyth** [comment]
I'm not quite sure. They might put IPs in groups regardless of VIP or not. 
https://github.com/pannal/Sub-Zero.bundle/issues/303#issuecomment-313638842

But it's worth a shot.

I think test VPN providers endpoints, to see which is allowed. If all are blacklisted, I'll setup a RPi on my LAN that fetches the subs, that PopcornTime can call instead.
