### ISSUE TITLE
Response code was unacceptable 403

### ISSUE THREAD

**Issue by sqig** [PopcornTimeTV/PopcornTimeTV#764]
App version:
iOS/tvOS version: tvOS 12.1.1 PopcornTimeTv 3.2.33

Make sure these boxes are checked before submitting your issue - thanks!

- [x ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...See movies and shows after opening app as usual.

#### Actual Behaviour

...I get an error "Unknown Error. Response code was unacceptable 403

#### Steps to reproduce the behaviour

1. ...Open PopcornTime Tv on an apple tv4 or 4K
2. ...This is on multiple Apple tvs in my house and others in other European countries.
3. ...

**Comment by stonko2** [comment]
Same issue as previously listed, Location Doha Qatar

**Comment by ncapela1** [comment]
Same issue here... Location Portugal :(

**Comment by ness1785** [comment]
Same issue here... Location USA

**Comment by ness1785** [comment]
Working now in USA
