### ISSUE TITLE
Unknown Error: 403

### ISSUE THREAD

**Issue by Fraysa** [PopcornTimeTV/PopcornTimeTV#765]
App version: Latest (3.2.33)
iOS/tvOS version: tvOS 12.1.2

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Work as expected.

#### Actual Behaviour

Did not work and display the error "Response status code was unaccept able: 403.".

#### Steps to reproduce the behaviour

1. Install the app using iOS App Signer and XCode.
2. Launch the app on the Apple TV 4K.

#### Extra information
After searching around the web, it seems some ISP block the API. Mine DOES NOT. It works perfectly on any other device.

**Comment by Red-Mak** [comment]
Same here, was working perfectly today.

**Comment by gringoireDM** [comment]
same here. Last time I used it was yesterday. :(

Tried both iPad Pro and Apple TV (the previous model to the 4k)

**Comment by stonko2** [comment]
attempted to install older versions of the software for both IOS and apple tv 4k and no version has been able to successfully operate.  All have had error 403 on both iPhone 7-8 and apple tv 4k

**Comment by r30** [comment]
check my merge request. popcorn api now forces a user agent.

**Comment by stonko2** [comment]
can you push so I cant download and compile?  If not I'll just wait until someone compiles and uploads the IPA ;)

**Comment by jjickrsa** [comment]
Same issue here, Location United Kingdom

**Comment by r1qu3br** [comment]
Same issue here, location Brazil.

**Comment by tushariscoolster** [comment]
same issues

**Comment by tushariscoolster** [comment]
Worked for me too, donno what was problem

**Comment by Fraysa** [comment]
Issue fixed on its own.
