### ISSUE TITLE
Problem Side-loading

### ISSUE THREAD

**Issue by rhett1989** [PopcornTimeTV/PopcornTimeTV#77]
I'm having issues side-loading PopcornTimeTv. Can somebody please make a detailed tutorial?
edit: I think its a cocoapods issue. I'm missing the pods in my project and I don't know where to get them.

side note: I installed PopcornTimeTV form the nitoTV package where he hosts third party apps. Ive been having an issue where I can only get about a minute into a movie and the application gets stuck on an infinite buffer. I believe this was an issue on a previous version, but when nitoTV had the updated version available the issue persists. I think some of the old corrupted files were left behind on the device and I do not know how to access them via SSH so I want to try Sideloading.

**Comment by drew5494** [comment]
Wouls be nice heehee

**Comment by drew5494** [comment]
Could someone put it on Jenkins maybe?

**Comment by buzzel** [comment]
The only way to install this on the Apple TV 4 is through Xcode at this time. There isn't a jailbreak out for the latest version of tvOS so if it was hacked to run on an older version, that could be the cause of your issues

**Comment by pnewell** [comment]
So is the only way to install to pay for a developer account then?

**Comment by tomto147** [comment]
I have a problem with 0.5.0 side load (no problems with previous versions). What I am getting is this message when trying to put the app on my AppleTv4
"No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.popcorntime.PopcornTime.TopShelf” were found." Any suggestions?

**Comment by Sonikkua** [comment]
Well, all accounts are (limited) "developer" accounts now.

Anyone with a Mac and Xcode can deploy to their own personal devices.

See: 

https://i.imgur.com/WpU02XF.png

https://developer.apple.com/xcode/

**Comment by tomto147** [comment]
Sorry but I don't get you... I am registered on developer.apple.com, have Xcode 7.3 and was able to sign and sideload any previous version of Popcorn before 0.5.0. What has changed on apple side since then?

**Comment by drew5494** [comment]
Would it be possible for someone to post a dev build in .deb ?

**Comment by buzzel** [comment]
Its quite easy to load this onto your Apple TV. You might have to change the Bundle ID and if so you have two of them to change. The actual app and the TopShelf. Once you adjust those, you should be good to go. 

If you are using a paid developer account it should be an issue as Xcode an generate bundle ID's, but if you are using the free account, then your Bundle ID usually has to be your name, at least this is what I have heard.

**Comment by Sonikkua** [comment]
@buzzel You don't need to use your own name for free accounts, just something other than what it was.

I've been using com.popcorntime.PopcornTime99 and com.popcorntime.PopcornTime99.TopShelf.

**Comment by stenar70** [comment]
It says the build is successful, but I get an error message "App installation failed. An unknown error has occurred."

Any ideas as to what could be wrong?

**Comment by tomto147** [comment]
I have changed bundle ID to my unique one and still get the error of TopShelf not found. The directory of TopShelf was not there in any previous version before 0.5.0. Even when I try to use com.popcorntime.PopcornTime100 and com.popcorntime.PopcornTime100.TopShelf it still says it can not find TopShelf provision...

**Comment by tengis** [comment]
@tomto147 

1. Delete your DerivedData
2. Delete the entire cloned repo
3. Clone again
4. pod update
5. pod install
6. Build again

**Comment by tomto147** [comment]
@tengis 
I'm not a developer just a normal user ;-))
1. what is DerivedData?
2. do you mean the folder on my desktop? Or the repo from Xcode? or both? - I was always deleting both
3. pod update - I have the latest version of pods (even the lest beta version I think)
4. OK
5. OK - will give it a try today in the evening.
6. attached pictures - they look exactluy the same at my place, before I change the budle ID. Do I have to change it both on Popcorntim Target and TopShelf?

Sorry for stupid questions, but any previous version before 0.5.0 was laoding with no problems and I was using it... So now I am confused...

**Comment by hunkarkadam** [comment]
Add .xxx should fix it

**Comment by tomto147** [comment]
1. I have deleted all DerivedData - I have even uninstalled the whole Xcode
2. I have updated my pods
3. I have cloned the entire repo again
4. I have installed it again
5. I have changed bundle ID (screen attached) - fix issue has worked as always
6. Same problem when building the app... still trying to find TopShelf
Screen attached. Any ideas?
![1](https://cloud.githubusercontent.com/assets/19311926/15216759/c3d150f8-1858-11e6-8967-40262c15fa66.png)

**Comment by falcon21** [comment]
finally a very clear guide on how to install, this should be stickied!

**Comment by tomto147** [comment]
very clear? but it my case still unsuccessful...

**Comment by rhett1989** [comment]
@tomto147 what firmware is your Apple TV on? I'm on 9.0 and I guess that's why I'm getting the problems. I would be nice to have a .deb file. I bet that would be easier to sideload.

**Comment by hunkarkadam** [comment]
Open .xcodeproj
Error or warnings will show up
Go to project settings and click on "Fix it" or something like that.
Also change device to iPad from Universal (depends on what u wanna to deploy, I just wanna iPad) and choose iOS 9!
Build & deploy from Xcode
On success you can close Xcode and go to Qt Creator and run it from there!

**Comment by hunkarkadam** [comment]
Try Xcode 7.2
If no success pay 12$ year and get all signed api

**Comment by tomto147** [comment]
I can do all of that, but first would like to understand. I had no problems whatsoever with any previous versions of the app (before 0.5.0). And I've also installed KODI and Web browser on my ATV4 without any problems....

**Comment by Sonikkua** [comment]
@tomto147 Did you rename the bundle ID of the top shelf app to match the name scheme of PopcornTime?

i.e. if you named your bundle com.popcorntime.PopcornTime.BLAHBLAH

Your Top Shelf needs to be name com.popcorntime.PopcornTime.BLAHBLAH.TopShelf

Also make sure you're opening the project from the workspace file, and that you've set the main app and the top shelf file to be signed by the same Apple ID.

**Comment by hunkarkadam** [comment]
@tomto147 I believe u have updated to Xcode 7.3 where apple wants to add extra .xxx where xxx can be any name or laters

**Comment by hunkarkadam** [comment]
@tomto147 I believe u have updated to Xcode 7.3 where apple wants to add extra .xxx where xxx can be any name or laters

**Comment by tomto147** [comment]
@hunkarkadam but where should I add this extra .xxx in bundle ID as last part of the name? I am quite sure, that I was using Xcode 7.31 from the beginning and was able to install and build and sign everything before version 0.5.5. I will git it a try later today.

**Comment by anaqi** [comment]
Anyone else running into this problem. Tried everything mentioned above, deleted DerivedData, cloned repo again, updated cocoapods, updated and installed pods, changed bundle ids. But stuck with this error. Anyone know a way to fix this?

![screen shot 2016-05-13 at 6 30 52 pm](https://cloud.githubusercontent.com/assets/3098037/15253042/292c6f42-1939-11e6-86b7-d6a89bbfc257.png)

**Comment by tomto147** [comment]
I am still stuck... But a step further.. Now I am able to build the app with no problems but when it starts to transfer on my APTV4 I am getting this error: "This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique." And again google knows not much about this... Any help?

**Comment by Dexwell** [comment]
I'm personally getting these errors, even after deleting, recloning and updating everything. Any ideas?

<img width="1140" alt="screen shot 2016-05-13 at 18 44 11" src="https://cloud.githubusercontent.com/assets/521176/15255197/d5f3f398-193a-11e6-92c4-c98a6ca1314b.png">

**Comment by tomto147** [comment]
Soon.... Finally I have deleted TopShelf from targets and then I was able to load 0.6.1 on my APTV4 with no errors. Why is that? Still don't understand. Have tried everything...

**Comment by RefusedFlow** [comment]
I wrote a super simple installation guide for all you guys having issues.
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

@tomto147 @Dexwell @hunkarkadam @rhett1989 @stenar70 @drew5494

**Comment by tomto147** [comment]
@RefusedFlow 
Finally!!!! ;-)))))
I was not getting the final 2 steps... that TopShelf is sub module of all the rest... So no need to change the last part of the name. Now I got it to work. Thanks!

**Comment by Sonikkua** [comment]
Lol I said exactly to do that yesterday

**Comment by RefusedFlow** [comment]
@Sonikkua Since it wasn't obvious enough and clearly other people will find it helpful in the future i decided to document it on the wiki which details each step from start to finish.

**Comment by Sonikkua** [comment]
@RefusedFlow meant to @tomto147, glad he fixed his issue though and an install wiki is definitely a great idea.

**Comment by RefusedFlow** [comment]
@tomto147 Anytime, glad i could simply it for you!

**Comment by Evhelden** [comment]
Cool. Will try after the weekend! Want to learn.

**Comment by rhett1989** [comment]
Thank you @refusedflow! Turns out I skipped a terminal command. You're tutorial will help many people. I was able to run the new version on tvOS 9.0

**Comment by sqig** [comment]
Delete your DerivedData
This worked for me. 0.6.1 installed.
Thank you.
