### ISSUE TITLE
update ipa

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeTV#77]
when you get a 1.0.5 version ipa with appdb.cc page popcorntimetv

**Comment by Hackormahn** [comment]
I will update PopcornTimeTV to 1.0.5 on AppDB asap. :)

**Comment by iAYMANi** [comment]
@Hackormahn 
Thank you kindly be fast😇

**Comment by moh0sw** [comment]
@Hackormahn that will be awesome bro
Thanks a lot

**Comment by Hackormahn** [comment]
@moh0sw @iAYMANi @chocolatesuper Done, the iPA is on AppDB and our releases page. Report an issue if anything fails. :)
