### ISSUE TITLE
Hi all

### ISSUE THREAD

**Issue by wieli040** [PopcornTimeTV/PopcornTimeTV#771]
App version:
iOS/tvOS version: 3.2.33

Make sure these boxes are checked before submitting your issue - thanks!

- [ X ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [X ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ X ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

... I could use it without renewing the app every week

#### Actual Behaviour

... After 6/7 days of use the app says it is not available

#### Steps to reproduce the behaviour

1. ... Re-installed the app
2. ...
3. ...

**Comment by JohnJacksonSmyth** [comment]
That's expected behaviour when signing without an Apple Developer certificate and provisioning. The signing expire after week. https://forums.developer.apple.com/thread/62594

Your fix is to pay Apple $99 and the app will last a year. Or you could build a bash/automator script that builds/signs/deploy the app at your chosen time.

**Comment by helmehraz** [comment]
@rrroyal using signing services such as ignition.fun is a good idea for ios devices but it doesnt work on tvOS 😔 do you have an equivalent solution for tvOS ?

**Comment by wieli040** [comment]
Good question. I also tried it yesterday and couldn't get it working.

**Comment by tomto147** [comment]
https://appdb.to

**Comment by Celoinsurance** [comment]
Why is this still listed as an issue. Kindly close.
