### ISSUE TITLE
Latest tv season under player options similar to auto select quality but auto select latest season

### ISSUE THREAD

**Issue by misswhitetiger** [PopcornTimeTV/PopcornTimeTV#772]
Hello team!

“Settings tab” can you add option for app to open latest television season available. Set to default as off and allowed to be enabled by user only if desired so it opens season 1 still by default. I’m using version PCT 3.2.33 on tvOS 10.2.2 jailbroken of course ;)

Thanks in advance!

**Comment by angryDuck2** [comment]
It is a two click step. FFS
