### ISSUE TITLE
Problem with 1.0.5 IPA (Cannot install)

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#78]
@Hackormahn Hi
I just downloaded the ipa file from appdb.cc and when resign it with my own developer certificate and and (iOS App Signer) and I've tried to install it from Xcode ( Window - Devices ) and I got this error
( App installation failed - This application does not support this device's CPU type.)
tried to install it again with ifunbox and still getting errors

I'm using Xcode 8.0 , macOS 10.12 GM Version (16A320)
Apple TV 4 (tvOS 10)

Thanks!

**Comment by Mossito** [comment]
Same here :/

**Comment by Hackormahn** [comment]
I will fix ASAP!

**Comment by moh0sw** [comment]
@Hackormahn Thanks u bro I really appreciate what u are doing and the hard work

Waiting for u

Thanks!

**Comment by wahlmanj** [comment]
Same on jb aTV4 via appinst.

Thx for all the fixes :)

**Comment by chocolatesuper** [comment]
brother many thanks for fix ipa

**Comment by chocolatesuper** [comment]
thank you very much for tryng to fix it

**Comment by Hackormahn** [comment]
Ok @moh0sw @wahlmanj @Mossito, it is late here. I will fix iPA tomorrow. I just wish all our dependancies would update to Swift 3. :/

**Comment by chocolatesuper** [comment]
thank you very much

**Comment by chocolatesuper** [comment]
thank you very much friend

**Comment by moh0sw** [comment]
@Hackormahn Thanks for ur hard work
Good Night

**Comment by Mossito** [comment]
thanks @Hackormahn thank you very much! good night!

**Comment by iAYMANi** [comment]
Thanks @Hackormahn

**Comment by moh0sw** [comment]
@Hackormahn Hi
Any updates on the ipa issue ?

**Comment by chocolatesuper** [comment]
<img width="1440" alt="captura de pantalla 2016-09-17 a las 12 00 17 p m" src="https://cloud.githubusercontent.com/assets/22038180/18609707/702b78d6-7cce-11e6-94b0-0571ed8916c1.png">

**Comment by Hackormahn** [comment]
Update: I have just gotten home and will work on the issue now.

**Comment by chocolatesuper** [comment]
@Hackormahn thank you very much friend

**Comment by Hackormahn** [comment]
Ok, my compile is not working due to a problem with AEXML. However, almost all our dependancies are ported to Swift 3. For now, use version 1.3.0.1 on AppDB. :)

**Comment by chocolatesuper** [comment]
@Hackormahn When there is a stable version but the version 1.0.3.1 When errors are giving version 1.0.5 will be available ipa
