### ISSUE TITLE
Airplay no video, only sound

### ISSUE THREAD

**Issue by Farslasher** [PopcornTimeTV/PopcornTimeTV#780]
Whenever i hit airplay I can only ever airplay the audio I can not airplay video what so ever. What do I change to get this adjustment made?

**Comment by rbeemsterboer** [comment]
This is not possible at the moment in the latest release 3.2.33. The devs created a work around around 3.2.19 , but Apple closed the loop hole i guess.

i tried searching the apple dev portal, but couldnt find/understand why they needed to create a work around and not implement the normal way. maybe someone can explain?

for now it’s to buy a chromecast for €40,-
works great!

**Comment by Farslasher** [comment]
A workaround to this on an apple device is to scroll down from the top right on the new devices and hit screen mirroring and select the Apple TV device. Then hit play on popcorn time on iOS and it will stream at full screen. I was just hoping to be able to enable it through the built in airplay button on the app.

**Comment by angryDuck2** [comment]
Since the app is not using the traditional video player for iOS we cannot provide airplay with a video stream from a video player it recognises hence there needed to be a workaround for the streaming of the video file to work. Unfortunately, the loophole we were using is no longer valid.
