### ISSUE TITLE
0.6.0 - Trying to load certain shows cause crash to homescreen

### ISSUE THREAD

**Issue by Sonikkua** [PopcornTimeTV/PopcornTimeTV#79]
Clicking on certain shows (not even getting to the point where one could play) causes crash to home screen.

See: Game of Thrones, Hannibal.

**Comment by buzzel** [comment]
A simple `pod update` should fix this issue. I forgot to commit a fix for this in v1.0.2 of PopcornKit, but it should be good now. Give a test and if its still happening, reopen this issue.
