### ISSUE TITLE
Video player won't show end time on Apple TV

### ISSUE THREAD

**Issue by NSExceptional** [PopcornTimeTV/PopcornTimeTV#796]
The standard Apple TV video player has a feature where the progress bar shows the time the video will end—instead of time remaining—if you tap the touch pad again. Popcorn time doesn't do that.

Are you guys using the standard video player or a custom one?

**Comment by rbeemsterboer** [comment]
VLC libraries are being used, because of that airplay integration doesn’t work

**Comment by NSExceptional** [comment]
Ah. That's unfortunate but I see why it's necessary. Thanks!
