### ISSUE TITLE
Feature: Apple TV App integration?

### ISSUE THREAD

**Issue by maslyankov** [PopcornTimeTV/PopcornTimeTV#798]
Is it possible to integrate PopcornTime as a Provider in the (new) Apple TV app?

App version:
iOS/tvOS version:

**Comment by whatthehomepod** [comment]
What do you mean? I can use the Apple Remote app (from Control Centre)

**Comment by maslyankov** [comment]
https://support.apple.com/en-ng/HT208083
With the upcoming version of tvOS, there is support for third-party apps as movie/tv show source I believe.

**Comment by teknim** [comment]
Yes please!

**Comment by angryDuck2** [comment]
There has always been support for third-party apps to join the Apple TV app but is was and still is governed by Apple. It is not an open API part of the public tvOS SDK that allows the integration of the Apple TV functionality
