### ISSUE TITLE
Add MobileVLCKit

### ISSUE THREAD

**Issue by pepibumur** [PopcornTimeTV/PopcornTimeTV#8]
#### What?
Add the VLC framework to the app. VLC supports subtitles and more formats than the native AVFoundation player.

#### References
- Opened issue in the repository: https://code.videolan.org/videolan/VLCKit/issues/15

**Comment by falk** [comment]
Have a look at https://gist.github.com/lg/5c8c8e24355e07d68042 for instructions. There is also a premade project in there: http://cl.ly/2D3e29113B2O

**Comment by pepibumur** [comment]
Great! I'll follow the steps there @falk

**Comment by steve228uk** [comment]
Not sure this is necessary. The `AVPlayerViewController` also supports subtitles, feels nicer, and afaik YTS distributes everything in MP4.
