### ISSUE TITLE
Feature Request(s): AutoPlay next episode in a series, resume watching function

### ISSUE THREAD

**Issue by Sonikkua** [PopcornTimeTV/PopcornTimeTV#80]

**Comment by buzzel** [comment]
Currently PopcornTorrent doesnt support advancing to a part of a movie or episode that hasn't been downloaded. It's on the list of things to implement but I am not the best when it comes to C++, so feel free to submit a PR on PopcornTorrent. For the time being I'm marking this as closed as we already have it on our list.
