### ISSUE TITLE
Watchlist not working properly

### ISSUE THREAD

**Issue by whatthehomepod** [PopcornTimeTV/PopcornTimeTV#803]
App version: Latest build of couple days ago
iOS/tvOS version: tvOS

Watchlist not saving, keeps removing movies and tv shows I’ve added, Trakt support is not working properly, very annoying to manually find my show each time

**Comment by angryDuck2** [comment]
Once you watch a tv show episode or movie the entire tv show/movie is deleted from the watchlist. This is a functionality of the Trakt database. We cannot change that

**Comment by whatthehomepod** [comment]
That’s the biggest bullshit I have ever read. I use several other movie and tv shows applications and I don’t have this issue with those. This is just a bug.

Verstuurd vanaf mijn iPhone

**Comment by angryDuck2** [comment]
https://support.trakt.tv/knowledgebase/articles/154739-why-do-things-get-removed-from-my-watchlist-after

**Comment by whatthehomepod** [comment]
Maybe those other apps are using the custom watchlist where they reffering to? Try to use MediaBox HD for example or the standalone PT doesn’t have this as well, only the iOS/tvOS version. It’s very annoying please check into this.

Verstuurd vanaf mijn iPhone
