### ISSUE TITLE
Unable to find a specification for `PopcornTorrent (~> 1.3.0)

### ISSUE THREAD

**Issue by richlira** [PopcornTimeTV/PopcornTimeTV#809]
App version: Current ver.
iOS/tvOS version: TV4k

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
... "pod install" installing like normal

#### Actual Behaviour
... "pod install" it's getting an error, can't install

#### Steps to reproduce the behaviour
1. It's a new Mac. Fresh install.
2. Install Cocoapods.
3. Following build instructions. Running pod install.
4. Getting this: "Pre-downloading: `Reachability` from `https://github.com/tonymillion/Reachability`, commit `788111ebf98e86368cd03da17f884015d2fc1543`
[!] Unable to find a specification for `PopcornTorrent (~> 1.3.0)`
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default."

### What I tried
- Reinstalling Cocoa Pods
- Cloning again and again
- pod repo remove master
- sudo rm -fr ~/.cocoapods/repos/master
- pod install --repo-update

**Comment by ammichael** [comment]
I also have this issue, and also tried those steps

**Comment by angryDuck2** [comment]
There is a fix now integrated into the repo. Please clone once again. Also a few more steps are required to build. Check the readme page

**Comment by reden87** [comment]
This ticket is the duplication of issue #805 . The fix was merged a few minites ago to ‘master’.

**Comment by richlira** [comment]
Closing :)
