### ISSUE TITLE
VLC

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeTV#81]
VLC media player supports the project popcorntimetv version

**Comment by Hackormahn** [comment]
What is your issue?

**Comment by chocolatesuper** [comment]
@Hackormahn  Whether the project supports vlc media player

**Comment by Hackormahn** [comment]
@chocolatesuper we use VLCKit for our videoplayer, but you cannot play our movies on VLC Media player if that's what you're asking.
