### ISSUE TITLE
0.6.1 TV Show Music

### ISSUE THREAD

**Issue by Sonikkua** [PopcornTimeTV/PopcornTimeTV#81]
First off -  this is an awesome idea, just two suggestions:

1) If the user hits back to leave a show, the music should be made to stop rather than continuing to play while browsing other stuff, particularly for shows with long intros.

2) Volume for the show tunes should be slightly lower, Plex does this well at about 70% of normal volume.

Great work!

**Comment by buzzel** [comment]
Some additions have to be made to TVMLKitchen for point *1* to work and as for point *2* the ability to enable, disable and just volume will be coming in the next update with settings

**Comment by buzzel** [comment]
Closing this as there is an issue already created for PopcornTorrent
