### ISSUE TITLE
put the version 1.0.3.1 until it is resolved

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeTV#82]
I was told to put the version 1.0.3.1 until the ipa 1.0.5 solves appdb.cc. I already did it

**Comment by wahlmanj** [comment]
Here is 1.0.3.1 resigned. I don't know what else you need until they get everything updated like you were told prior https://github.com/PopcornTimeTV/PopcornTimeTV/issues/78. Why do you keep opening issues? Give them time to update everything. Opening issues is doing nothing to get to swift 3.0 and 1.0.5 released any faster.

http://www.mediafire.com/download/4tbe37dusau5tl1/PopcornTimev1.0.3.1.ipa

**Comment by chocolatesuper** [comment]
@wahlmanj ok friend thank you very much understand

**Comment by chocolatesuper** [comment]
@wahlmanj ok friend I get it
