### ISSUE TITLE
Unable forward and rewind

### ISSUE THREAD

**Issue by iAYMANi** [PopcornTimeTV/PopcornTimeTV#82]
Unable forward and rewind when movie playback

**Comment by Sonikkua** [comment]
This is a known issue.

**Comment by iAYMANi** [comment]
the issue Only version 0.6.1 & 0.5.0

Before the version 0.4.3 the is ok

**Comment by RefusedFlow** [comment]
This is a known issue and requires work on the PopcornTime Streamer, in the meantime it's already been added to the Progress page over on the wiki.

You can track the progress of the application over on the wiki
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress
