### ISSUE TITLE
An empty identity is not valid when signing a binary for the product type 'TV App Extension'.

### ISSUE THREAD

**Issue by CavalcanteLeo** [PopcornTimeTV/PopcornTimeTV#835]
<img width="1552" alt="Captura de Tela 2019-09-23 às 23 22 00" src="https://user-images.githubusercontent.com/1735944/65476355-fe830b00-de58-11e9-81b7-24a64bb306a2.png">

my apple tv is on tvOS 13

<img width="549" alt="Captura de Tela 2019-09-23 às 23 24 24" src="https://user-images.githubusercontent.com/1735944/65476426-4d30a500-de59-11e9-894b-7eeec9fabf8c.png">

**Comment by hiburn8** [comment]
Have you looked at your signing profile? Looks like you just didn't select one, so the app cant get signed.

**Comment by CavalcanteLeo** [comment]
yes... for both tvos and TopShelf 

<img width="767" alt="Captura de Tela 2019-09-25 às 12 59 32" src="https://user-images.githubusercontent.com/1735944/65618256-5d996a80-df94-11e9-99fd-591aaf8f6def.png">

**Comment by JulienMalige** [comment]
it is link to the signing profiles. Check to re-generate new ones and do not forget to use a custom bundle id (mine is `com.popcorntimetv.popcorntime9`).
Also, I prefer to use the general tab to check if everything is ok.

**Comment by sqig** [comment]
Hello, I get the same error. I have made a custom bundle id. My profiles seem ok. I have a paid account.
Thank you.

**Comment by CavalcanteLeo** [comment]
@JulienMalige i worked after i re-generated
