### ISSUE TITLE
Archiving Problem

### ISSUE THREAD

**Issue by malhaar** [PopcornTimeTV/PopcornTimeTV#84]
TVVLCKit Needs Rebuilding with bitcode enabled.
"
ld: bitcode bundle could not be generated because '/Users/********/Downloads/PopcornTimeTV-0.6.1/Pods/TVVLCKit/TVVLCKit.framework/TVVLCKit(VLCEventManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
"

**Comment by buzzel** [comment]
Just disable bitcode support and you'll be fine.

**Comment by malhaar** [comment]
Bitcode is mandatory for TVOS cant be disabled only option is to compile VLCKit with bitcode support.

**Comment by buzzel** [comment]
As far as I know, VLCKit doesnt support bitcode. I'll have a look though. How come you need to Archive the app? A simple Build & Run is all that is needed to install it

**Comment by malhaar** [comment]
I have managed it, and complied VLC Kit with bitcode support, I needed to archive coz some of my friends don't have macs for sideloading, they wanted the ipafile to resign and install on Apple TV 4.
