### ISSUE TITLE
A Network Trojan Was Detected

### ISSUE THREAD

**Issue by Ioan-Popovici** [PopcornTimeTV/PopcornTimeTV#842]
App version:
iOS/tvOS version: 13

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Not contact Ransomeware CnC servers

#### Actual Behaviour

Contacts Ransomeware CnC servers

#### Steps to reproduce the behaviour

1. Use a packet inspector
![C069E78C-62C2-4C9C-B316-A0DCE9BDCC85](https://user-images.githubusercontent.com/17069425/67245687-3f287100-f465-11e9-81e6-08143e4073e6.jpeg)

**Comment by mattiaborsoi** [comment]
🤔

**Comment by Ioan-Popovici** [comment]
Same goes for desktop version (https://popcorntime.sh).
It may be a false positive but why is it connecting to known CnC malware servers?

**Comment by 2600box** [comment]
Seems suspicious but apparently malware has not been active on this ip since 2016. https://ransomwaretracker.abuse.ch/ip/195.22.28.198/

Could just be recycled ip address...

**Comment by Ioan-Popovici** [comment]
Seems to be ok, I'm blocking those automatically anyway...
