### ISSUE TITLE
Installation via iFunbox not working anymore

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#85]
Since version 0.5 the installation on the Apple TV via iFunBox shows:

Error# e8008001. Sorry for the inconvenience. Please send us feedback. 

Received the package via a signing party ' ipa store ' . Other apps in same stores no issue. apparently an issue with the PopcornTV app in development?

**Comment by Sonikkua** [comment]
Solution: compile and install the correct way as described in the ReadMe, not through some shady, developer-license-breaking IPA store.

**Comment by buzzel** [comment]
We dont support installing by 3rd party installers. The simplest and easiest way is to open the Xcode project and install it manually.
