### ISSUE TITLE
install pod error

### ISSUE THREAD

**Issue by observe1147** [PopcornTimeTV/PopcornTimeTV#87]
Hi,

I'm getting this error below when running install pod.  Does any one know the solution?  

[!] Unable to find a specification for `YoutubeSourceParserKit`.

**Comment by tengis** [comment]
try
`pod update`
`pod install`

**Comment by pbo1976** [comment]
Hi, I get this error in Terminal after the command "gem install cocoapods":

Fetching: i18n-0.7.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

What should I do?

Thanks!

**Comment by RefusedFlow** [comment]
@pbo1976 Have you tried running the following commands? 

     sudo gem install cocapods
     sudo gem update

**Comment by Sonikkua** [comment]
sudo!

**Comment by pbo1976** [comment]
Yes! sudo did the trick! thanks!

13 gems installed
