### ISSUE TITLE
Subtitle not displayed at all

### ISSUE THREAD

**Issue by abusiam84** [PopcornTimeTV/PopcornTimeTV#87]
I installed PopcornTimeTV Version 1.0.3.1 on my apple tv4 through ipwnstore ( https://tv.ipwnstore.me), It works perfect but I can't get subtitles to work on the apple tv.

The subtitle menu is there and I can choose languages ( Arabic, English, etc... ) but no subtitle displayed on the screen, Any help?

**Comment by samfranz** [comment]
I also am unsure how to use the subtitles. Nothing is ever displayed for me too.

**Comment by galdo320** [comment]
close the app from the background & open it again.

**Comment by abusiam84** [comment]
I tried this so many times but it did not fix the problem.

**Comment by tomto147** [comment]
Same here... When I initially launch the app the Polish subtitles are working OK. But when changing the film or even next episode of TV show they stop showing. I am able to choose them from top menu but no response after selecting it. In the same time when I switch to any other subtitle like Spanish or German they work properly. But no luck with Polish ones...I have to relaunch the whole app to get it to work again.

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue should be fixed in latest version. Please run `pod update PopcornKit` and try again.
