### ISSUE TITLE
API error, server down?

### ISSUE THREAD

**Issue by shaahin** [PopcornTimeTV/PopcornTimeTV#879]
App version: 3.2
iOS/tvOS version: 13.4

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
Load movies and TV shows

#### Actual Behaviour

Server not found. Seems the server is down:
https://tv-v2.api-fetch.website

#### Steps to reproduce the behaviour

1. open the app
2. try to navigate anywhere

**Comment by QiuIcs** [comment]
See [here](https://github.com/PopcornTimeTV/PopcornTimeTV/issues/877)
