### ISSUE TITLE
1.0.5 does not compile without errors

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#88]
Noticed in 1.0.5 that there is still the actual developer account still shows of the final programmer. On top of that the building is not error free, hence I can not sign it error free. Could you put the 1.0.5 version in the following option:

PSA: We have our full focus on porting all of our repos to Swift 3. Please be patient with us. For now download and resign the iPA available HERE, or use AppDB Pro!

There is still version 1.0.3.1 on that. It would be great to have 1.0.5 available there. That would help loads. Thanks!

**Comment by moh0sw** [comment]
@Evhelden the 1.0.5 ipa have been uploaded before and has problems on installing so yeah for now u can't install it :)
