### ISSUE TITLE
Resume feature

### ISSUE THREAD

**Issue by Evhelden** [PopcornTimeTV/PopcornTimeTV#88]
Suggestion for an additional feature:
- Resume at last moment watched. After stopping a TV Show half way, next time starting the same TV Show (or movie) give the option to ' start from the beginning ' or ' Resume at xx:xx ' (xx:xx meaning the time when the show/movie was left last time watching. Surely helpful when the fast forward and rewind functions do not work (yet)

**Comment by michalzelinka** [comment]
+1, would combine well with possible Local Library with all the content already downloaded. I know all the stuff is kept in `Caches` folder so the TV can delete pop's caches at any time, but in that case there's no need to care about that more than refreshing such Local Library index.

**Comment by RefusedFlow** [comment]
@Evhelden Resuming content, fast forward and rewind feature's are already planned to be added into the application, it's on the [progress list](https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Progress) you can take a look! 

@michalzelinka PopcornTime isn't based around the idea of locally stored content, more like the fact of streaming torrents on the go. So you won't being such feature anytime soon, like you've said the cache on Apple TV can wipe it's contents at any time so your idea wouldn't be feasible on the current Apple TV as we don't have direct access to the storage on the device. Hope help it helps!

**Comment by Evhelden** [comment]
@RefusedFlow : Thanks. Found the update. Questions: (1) No subtitles in progress list (noticed the open issue / feature). Would be appreciated. (2) What will be behind the ' settings ' section? (3) some tv series won't open (e.g. flash, voice) and some make the app close / go to back ground (e.g. Vinyl). Great work.

**Comment by RefusedFlow** [comment]
@Evhelden We're looking into subtitle support,

The settings section is currently disabled, but will allow you to set a default quality settings etc, it'll be there in future builds.

Question number three i believe has been fixed in the latest commit to the master branch so try that out.

**Comment by iAYMANi** [comment]
+1, No plan to add subtitles in progress list?

Thank you the great work

**Comment by RefusedFlow** [comment]
@iAYMANi Added to Progress List

**Comment by michalzelinka** [comment]
@RefusedFlow I get the view about the content, but sometimes it would be a bit comfortable to f.e. let to fetch some movie I wish to see tonight – let's say cache it in 2–3 hours in advance and be sure I'll be able to watch it. You can call it “cached” content if it's more appropriate, but there's a use case for it. Moreover, latest 0.6.1 build often fails to seek-and-play or resume playback in different states so I need to cancel playback and perform whole download and play from the beginning again.

**Comment by RefusedFlow** [comment]
@michalzelinka As i said earlier the Apple TV doesn't allow cacheing to the system, well it does but it's way too small to store a movie in the application for later viewing so it wouldn't be possible on the current apple tv alone.

Again, fast forward and rewind & resume haven't been implemented yet this will require some work on the PopcornTorrent streamer of which will be implemented in the future.

**Comment by michalzelinka** [comment]
@RefusedFlow Not completely true, `NSCachesDirectory` is fully accessible filesystem path; the device can delete the contents at any time when not having enough space, but that's the only drawback, you can store any content up to device's storage capacity in `Caches` folder.

Ad FF/Rewind, thanks for the info, but it's a stepback from the version I've used previously (0.4.x I guess). Would it be possible to (at least temporarily) include the switching between `VLC` and `AVFoundation` playback in newly introduced _Settings_? Only until the previous capabilities will be brought back.

**Comment by RefusedFlow** [comment]
@michalzelinka You're more than welcome to submit pull request, there's already a back log of features we want to add and they're being done one by one but we're happy for you to contribute to the master branch.

**Comment by michalzelinka** [comment]
@RefusedFlow Would love to, if I find something useful enough. :) Anyway, thanks for your feedback.
