### ISSUE TITLE
The latest ipa forked and compiled by @tychop

### ISSUE THREAD

**Issue by Yashsinh** [PopcornTimeTV/PopcornTimeTV#882]
When I click on a show like Agents of s.h.i.e.l.d and play or download nothing happens please help for iPadOS

**Comment by michrome** [comment]
I get the same when compiling `master`. On Apple TV (simulator and hardware), clicking play flashes the resolution options then returns to the menu without playing.

**Comment by michrome** [comment]
@Yashsinh I got it working by running `pod install` and not `pod update`. One thing you could try if you're not compiling your own code: in the app's settings menu, enable "Auto Select Quality" to either "Highest" or "Lowest" (not "Off").

**Comment by Yashsinh** [comment]
Okay man. Thanks!

**Comment by Yashsinh** [comment]
@michrome amything else that I can try for the ios app?

**Comment by JoelPeterPage** [comment]
Hello,

Thanks for your hard work!

I’m looking for the link to your updated PopcornTime.app for iOS, could you please point me in the right direction? I’m not really used to github!

**Comment by QiuIcs** [comment]
[Here](https://github.com/PopcornTimeTV/PopcornTimeTV/issues/877#issuecomment-617595581)

**Comment by JoelPeterPage** [comment]
TYVM .. 
![62F2F584-E2F8-47BE-971E-25616EDD54EE](https://user-images.githubusercontent.com/9304573/80194428-83d1d680-8659-11ea-9599-efe1204aa589.png)

**Comment by JoelPeterPage** [comment]
> @JoelPeterPage [Here](https://github.com/PopcornTimeTV/PopcornTimeTV/issues/877#issuecomment-617595581)

Trakt logs in fine. I can stream everything, I can download, but...

I can’t watch the movie I’ve downloaded! (I’ve tried to download twice, same issue, try to view from downloaded tab, nothing happens!

Anyone know?

**Comment by Yashsinh** [comment]
> > @JoelPeterPage [Here](https://github.com/PopcornTimeTV/PopcornTimeTV/issues/877#issuecomment-617595581)
> 
> 
> 
> Trakt logs in fine. I can stream everything, I can download, but...
> 
> 
> 
> I can’t watch the movie I’ve downloaded! (I’ve tried to download twice, same issue, try to view from downloaded tab, nothing happens!
> 
> 
> 
> Anyone know?

Yes search up the movie in the search tab and then click on it. It works.

**Comment by JoelPeterPage** [comment]
I can download, but I cannot view the download..

It used to open the saved movie to view if I clicked the rightmost “iPhone ✔️“ on the downloaded movie... now NOTHING happens..

![B9AD5833-271D-4D23-8CDE-E5D5B52B029C](https://user-images.githubusercontent.com/9304573/80385496-44b7b580-88e5-11ea-87c6-46fbbf1955d6.png)

**Comment by JoelPeterPage** [comment]
My new issue with this fork... no subtitles on iOS app!  Someone else raised this issue yesterday https://github.com/PopcornTimeTV/PopcornTimeTV/issues/884#issue-605620511

I’m trying to watch a French film, I only speak enough French to say the basics!

**Comment by Yashsinh** [comment]
> I can download, but I cannot view the download..
> 
> 
> 
> It used to open the saved movie to view if I clicked the rightmost “iPhone ✔️“ on the downloaded movie... now NOTHING happens..
> 
> 
> 
> ![B9AD5833-271D-4D23-8CDE-E5D5B52B029C](https://user-images.githubusercontent.com/9304573/80385496-44b7b580-88e5-11ea-87c6-46fbbf1955d6.png)
> 
> 
> 
> 

- Man search for the movie as if you wanted to download it again and then play the movie it will surely work

**Comment by Yashsinh** [comment]
Yes but you can’t play it if you are really offline. Let me try to fix the issue.

**Comment by Yashsinh** [comment]
> My new issue with this fork... no subtitles on iOS app!  Someone else raised this issue yesterday https://github.com/PopcornTimeTV/PopcornTimeTV/issues/884#issue-605620511
> 
> 
> 
> I’m trying to watch a French film, I only speak enough French to say the basics!

Some movies don’t have subs

**Comment by mohandshamada** [comment]
no 

> > My new issue with this fork... no subtitles on iOS app!  Someone else raised this issue yesterday [#884 (comment)](https://github.com/PopcornTimeTV/PopcornTimeTV/issues/884#issue-605620511)
> > I’m trying to watch a French film, I only speak enough French to say the basics!
> 
> Some movies don’t have subs

no the problem is that the open subtitle has closed loading subtitles without account. so the developer of popcorn should allow us to load our open subtitle's accounts.
