### ISSUE TITLE
VPN for iPhone & MacBook Pro 

### ISSUE THREAD

**Issue by JoelPeterPage** [PopcornTimeTV/PopcornTimeTV#886]
App version: 3.2.35 forked by tychop
iOS/tvOS version: iOS 13.4.1

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.
What is the recommendation for VPN to use with iPhone?

I know this isn’t directly related to PopcornTime, but you guys know best!

I’m in South Australia by the way...

**Comment by QiuIcs** [comment]
You can use whatever service you like. 
I’m using [CyberGhost](https://apps.apple.com/ro/app/cyberghost-vpn-vpn-proxy/id583009522) and everything works fine. Lots of servers in many countries. You get a 7 day free trial.

**Comment by JoelPeterPage** [comment]
> You can use whatever service you like.
> I’m using [CyberGhost](https://apps.apple.com/ro/app/cyberghost-vpn-vpn-proxy/id583009522) and everything works fine. Lots of servers in many countries. You get a 7 day free trial.

I’ll give it a go! Thanks mate!

**Comment by JoelPeterPage** [comment]
CyberGhost is fantastic!
