### ISSUE TITLE
ITransmission downloaded Movies open in PopcornTime?

### ISSUE THREAD

**Issue by JoelPeterPage** [PopcornTimeTV/PopcornTimeTV#887]
Is there a way to make .mkv files downloaded via iTransmission to open in PopcornTime?

I was messing around and downloaded a movie with Safari via a torrent website, downloaded the file, I can view it with the VLC Player (in a round about way).

I would love it if there was a way to import directly to PopcornTime (and maybe even seed the file)?

I am on iOS (sometimes MacBook Pro), got my VPN (CyberGhost 👻 ), I’ll get  most movies straight from PopcornTime, but if there’s a film without subtitles, or not on PT, I’ll get a torrent, download via iTransmission, and watch with VLC Player, but wish I could import to PT and use Trakt too!

I’m using @tychop fork.. (thank you sooooooo much tychop!)

I hope someone knows a way to do this (if it’s already possible)..

Thanks,
Joel

**Comment by Yashsinh** [comment]
> Is there a way to make .mkv files downloaded via iTransmission to open in PopcornTime?
> 
> 
> 
> I was messing around and downloaded a movie with Safari via a torrent website, downloaded the file, I can view it with the VLC Player (in a round about way).
> 
> 
> 
> I would love it if there was a way to import directly to PopcornTime (and maybe even seed the file)?
> 
> 
> 
> I am on iOS (sometimes MacBook Pro), got my VPN (CyberGhost 👻 ), I’ll get  most movies straight from PopcornTime, but if there’s a film without subtitles, or not on PT, I’ll get a torrent, download via iTransmission, and watch with VLC Player, but wish I could import to PT and use Trakt too!
> 
> 
> 
> I’m using @tychop fork.. (thank you sooooooo much tychop!)
> 
> 
> 
> I hope someone knows a way to do this (if it’s already possible)..
> 
> 
> 
> Thanks,
> 
> Joel 

Okay if you press and hold on the torrent file, then click on share and then popcorn Time. You can press and hold on the .mkv file and open with PT. 
Hey, did you subscribe to my friends YT channel? He’s jobless!

**Comment by JoelPeterPage** [comment]
Doesn’t work from iTransmission, Filza or Apple Files...
![52840175-1BE8-45E9-9230-CADEBCF15D10](https://user-images.githubusercontent.com/9304573/80790897-38767580-8bcf-11ea-9cb4-da5fb4d311b9.png)
![35D676CA-F744-4878-BDF5-CA00CEBE0582](https://user-images.githubusercontent.com/9304573/80790903-3d3b2980-8bcf-11ea-9941-114bd88d768d.png)


Your mate‘s YouTube is?

**Comment by Yashsinh** [comment]
> Doesn’t work from iTransmission, Filza or Apple Files...
> 
> ![52840175-1BE8-45E9-9230-CADEBCF15D10](https://user-images.githubusercontent.com/9304573/80790897-38767580-8bcf-11ea-9cb4-da5fb4d311b9.png)
> 
> ![35D676CA-F744-4878-BDF5-CA00CEBE0582](https://user-images.githubusercontent.com/9304573/80790903-3d3b2980-8bcf-11ea-9941-114bd88d768d.png)
> 
> 
> 
> 
> 
> Your mate‘s YouTube is?

Okay meaning you want to play with PTonly for subtitles? Why don’t u just add it to the video?
My friends YT https://www.youtube.com/channel/UCvBl5cnz9OjSxMksGngBjfw

**Comment by Yashsinh** [comment]
Hey man I fixed the open subtitles issue with the little coding that I know! Here it is you should get subtitles now! https://drive.google.com/file/d/1lWz2_cFKKnc_jvwham07F1atbLQPabNI/view?usp=drivesdk

**Comment by Yashsinh** [comment]
> Doesn’t work from iTransmission, Filza or Apple Files...
> 
> ![52840175-1BE8-45E9-9230-CADEBCF15D10](https://user-images.githubusercontent.com/9304573/80790897-38767580-8bcf-11ea-9cb4-da5fb4d311b9.png)
> 
> ![35D676CA-F744-4878-BDF5-CA00CEBE0582](https://user-images.githubusercontent.com/9304573/80790903-3d3b2980-8bcf-11ea-9941-114bd88d768d.png)
> 
> 
> 
> 
> 
> Your mate‘s YouTube is?

Am i talking to myself ?

**Comment by Yashsinh** [comment]
> > Doesn’t work from iTransmission, Filza or Apple Files...
> > 
> > ![52840175-1BE8-45E9-9230-CADEBCF15D10](https://user-images.githubusercontent.com/9304573/80790897-38767580-8bcf-11ea-9cb4-da5fb4d311b9.png)
> > 
> > ![35D676CA-F744-4878-BDF5-CA00CEBE0582](https://user-images.githubusercontent.com/9304573/80790903-3d3b2980-8bcf-11ea-9941-114bd88d768d.png)
> > 
> > 
> > 
> > 
> > 
> > Your mate‘s YouTube is?
> 
> Am i talking to myself ?

This is my friend’s YouTube channel will be helpful to him if you subscribe 😀😀😀😀😀☺️☺️ https://www.youtube.com/channel/UCvBl5cnz9OjSxMksGngBjfw

**Comment by tychop** [comment]
@JoelPeterPage Can you please close this issue?
Im getting hammered with email notifications and the unsubscribe button doesn't seem to have any effect.

**Comment by Yashsinh** [comment]
Thanks @JoelPeterPage it will help him a lot!!
Please share the channel with others too!!
He is very thankful to you!

**Comment by JoelPeterPage** [comment]
> Hey man I fixed the open subtitles issue with the little coding that I know! Here it is you should get subtitles now! https://drive.google.com/file/d/1lWz2_cFKKnc_jvwham07F1atbLQPabNI/view?usp=drivesdk

Thanks mate! Your coding skills must be a lot better than you say!

![BC816DF2-56C5-4751-B6C6-78EEB703FB1F](https://user-images.githubusercontent.com/9304573/80855838-aaa89200-8c83-11ea-954f-94f823f77142.png)

I’d still love other torrents to open in PT, and share(seed) the movie for others to DL, (right now it appears EVERYTHING & anything I plan to watch is on PT, even with subtitles now! Thanks so much for your help!

**Comment by JoelPeterPage** [comment]
>....Here it is you should get subtitles now! https://drive.google.com/file/d/1lWz2_cFKKnc_jvwham07F1atbLQPabNI/view?usp=drivesdk

I think you should submit this for release as the current version of PopcornTime for iOS!

The only thing that does not work is the “play button“ in the downloaded tab..

Also, if (like me) you need to download on wifi to watch later, you must keep PT in the foreground (otherwise crash! I have the crash logs if anyone want to check or fix!)

**Comment by Yashsinh** [comment]
Try clearing the cache to fix the crash.
