### ISSUE TITLE
unknown Error  A server with the specified hostname could not be found

### ISSUE THREAD

**Issue by m0hd2005005** [PopcornTimeTV/PopcornTimeTV#889]
App version: 3.2.35
iOS/tvOS version: tvOS 13.4 (17L256)

Make sure these boxes are checked before submitting your issue - thanks!

- [ yes] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [yes] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ yes] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

unknown Error 
A server with the specified hostname could not be found

#### Actual Behaviour

just open and not loading any movies or tvshows only showing the above message when trying to show any content 

#### Steps to reproduce the behaviour

1. just open and sowing the error massage 
2. ...
3. ...

**Comment by Freyja-Folkvangr** [comment]
Do you have the issue with specific shows?
I've compiled the app yesterday and today, I haven't seen the issue

**Comment by QiuIcs** [comment]
[are you serious](https://github.com/PopcornTimeTV/PopcornTimeTV/issues/877) 🤦🏻‍♂️

**Comment by m0hd2005005** [comment]
it does not 

> Do you have this issue with specific shows?
> I've compiled the app yesterday and today, I haven't seen the issue

it is not showing anything the massage appears for all content, I downloaded the api for here and install it using cydiaimpactor

**Comment by marcelojulianoramos** [comment]
Hi there, I got same error.
I deleted from Apple TV and installed it back, also installed in the iPhone and the error sill there.

Any ideia to fix it?

**Comment by Freyja-Folkvangr** [comment]
I'm sorry for my last message.

I was able to reproduce the issue. It seems the issue got fixed but there are problems with the server again.

In the meantime, if your app already loaded the catalog, try adding the movie or show to the download queue.

I was able to download the stuff instead of streaming and then watch.

**Comment by m0hd2005005** [comment]
> I'm sorry for my last message.
> 
> I was able to reproduce the issue. It seems the issue got fixed but there are problems with the server again.
> 
> In the meantime, if your app already loaded the catalog, try adding the movie or show to the download queue.
> 
> I was able to download the stuff instead of streaming and then watch.

unfortunately the app is not loading the catalog it only shows the massage " unknown Error A server with the specified hostname could not be found" so cant put any movie in the download queue

**Comment by m0hd2005005** [comment]
just to let every one know the app works after I complied the app my self, it wasnt working with the ready api downloaded directly from here
