### ISSUE TITLE
Pod install problem (TVVLCKit and CocoaPods)

### ISSUE THREAD

**Issue by krantzet** [PopcornTimeTV/PopcornTimeTV#89]
I cant get 0.6.1 (and also 0.5.0) to work. I had no problems to compile 0.4.3 when it was released.
I have been following https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime just to make sure I dont do anything creative.
Cocoapods is installed and updated, but when I try pod install I get the following error

Installing TVVLCKit (3.0.0)
[!] Error installing TVVLCKit
[!] /usr/bin/curl -f -L -o /var/folders/yc/r7558tc17dn3gy0v0vck23680000gn/T/d20160514-829-zjjpwy/file.zip https://github.com/PopcornTimeTV/VLCKit/releases/download/3.0.0/TVVLCKit.framework.zip --create-dirs

It halts on Installing TVVLCKit (3.0.0) for atleast 30m mins before the error message shows up.
I have removed the popcorntimetv repo using rm -rf ~/.cocoapods/repos/popcorntimetv and verified that folder is deleted
I have tried both pod install and pod update.

Then I tried on a second computer, but that was even worse.
On the second computer I get the following error when trying install pod

"Setting up CocoaPods master repo
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`."

Help please!

**Comment by RefusedFlow** [comment]
Did you follow the wiki installation guide?
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime

**Comment by krantzet** [comment]
I did. help please! :)

**Comment by sqig** [comment]
I also am having problems with 0.6.1  
I am get 4 errors about Network Manager,
eg. Desktop/PopcornTimeTV/PopcornTime/Latest.swift:31:21: Value of type 'NetworkManager' has no member 'fetchShows'
My build fails, can anyone please teach me how to fix this?
Thank you

![screen shot 2016-05-14 at 15 18 27](https://cloud.githubusercontent.com/assets/19361341/15268680/371813f0-19e7-11e6-9cf3-568f2d9cb96c.png)

**Comment by drew5494** [comment]
Yup.. same here

**Comment by buzzel** [comment]
What version of cocoapods are you guys running? You can check by running `pod --version `

**Comment by sqig** [comment]
Cocoa pods latest release candidate. 1.0.0.rc.2
I have finally made it work.
Delete your DerivedData . this made all the difference for me.
Follow these instructions
https://github.com/PopcornTimeTV/PopcornTimeTV/wiki/Building-PopcornTime
Thank you.

**Comment by krantzet** [comment]
I am running 1.0.0 of Cocoapods
Just uninstalled and reinstalled both Xcode and Cocoapods, but the same result (on second computer now, so that means this error:

"Setting up CocoaPods master repo
[!] Unable to add a source with url https://github.com/CocoaPods/Specs.git named master.
You can try adding it manually in ~/.cocoapods/repos or via pod repo add."

I have also tried to change the thirde line in podfile from source 'https://github.com/CocoaPods/Specs' to source 'https://github.com/CocoaPods/Specs.git' but that did not change anything. I have also tried to download the master repo from Cocoapods and placed it in ~/.cocoapods/repos/master

**Comment by buzzel** [comment]
Uninstall cocoapods and reinstall it via `sudo gem install cocoapods` Sometimes using the system ruby version requires sudo when installing gems.

**Comment by krantzet** [comment]
Already tried that buzzel. No success.
Trying now after deleteing the DerivedData-folder. Hopefully it solves it, but I am far from sure.

**Comment by krantzet** [comment]
That did not help either. Back to square one.
I did however have both 0.3.9 and 1.0.0 of cocoapods installed, but uninstalled them both and installed it again via sudo gem install cocoapod. Deleted DerivedData-folder. Deleted ~/.cocoapods/repos/popcorntimetv

Ran pod install. Result:

[!] Error installing TVVLCKit
[!] /usr/bin/curl -f -L -o /var/folders/yc/r7558tc17dn3gy0v0vck23680000gn/T/d20160514-22637-1lq7v7r/file.zip https://github.com/PopcornTimeTV/VLCKit/releases/download/3.0.0/TVVLCKit.framework.zip --create-dirs --netrc

**Comment by drew5494** [comment]
Still don't see why someone can't just put some test builds up

**Comment by krantzet** [comment]
@drew5494 

Yeah, if someone that managed to build it could upload a compiled file we should be able to sign it with ios app signer. That should work,  it works great with Kodi.

**Comment by krantzet** [comment]
Tried pod update too. Getting a new error:

"Update all pods
Updating local specs repositories
Performing a deep fetch of the `master` specs repo to improve future performance
[!] /usr/bin/git fetch --unshallow

error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed"

**Comment by buzzel** [comment]
@drew5494 Distributing a compiled version puts all of us at more risk. That is something none of us want so don't expect a compiled version any time soon. None of us want any of our sensitive information such as code signing keys in an app like this.

**Comment by buzzel** [comment]
As for the issues at hand, this is looking more like a system error. The last thing I can think of trying without getting to nitty and gritty in the command line is using the Cocoapods mac app beta. https://cocoapods.org/app This is distributed with its own copy of ruby and cocoapods so see if this helps with your installation.

**Comment by krantzet** [comment]
Okay, I solved the errors I wrote about. Turned out network setting on the virtual OSX-machine was set to NAT and not Bridged in VMWare. That turned the network connection slow so I guess I simply received timeouts. So, I was able to do a successfull "pod update/install". So if anyone with a virtual Mac received the same errors I did, check the network settings in Vmware/Virtualbox.

Still not succeded though. My new error is when I try to compile the project. I have changed the budle name to  com.whatvevermynameis.PopcornTime and com.whatvevermynameis.PopcornTime.TopShelf according to the guide, but received the following error: "No such module: "PopcornKit"

So more help needed, please!

![popcornkit](https://cloud.githubusercontent.com/assets/13383380/15272645/f56fb11c-1a7f-11e6-80a4-de1b197eb04f.png)

**Comment by Sonikkua** [comment]
Make sure your opening the workspace file (pods should be listed as well as PopcornTime in Xcode).

**Comment by krantzet** [comment]
That fixed it! :) 
It works! Thanks everyone!

**Comment by drew5494** [comment]
Im still stuck here :(
Analyzing dependencies
Pre-downloading: `PopcornKit` from `https://github.com/PopcornTimeTV/PopcornKit.git`
Pre-downloading: `TVMLKitchen` from `https://github.com/toshi0383/TVMLKitchen.git`, branch `swift2.2`
[!] Unable to find a specification for `TVVLCKit`

**Comment by drew5494** [comment]
@buzzel 
![screen shot 2016-05-15 at 2 16 18 pm](https://cloud.githubusercontent.com/assets/9094103/15275960/cd7703ea-1aa7-11e6-9a52-8bc6de8fb001.png)

**Comment by buzzel** [comment]
@drew5494 What does the podfile look like? Its looking like something is missing. Try running Update install of an install as well. If you hit Command + U that will run the pod update command

**Comment by drew5494** [comment]
@buzzel 
Tried that too 

Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `PopcornKit` from `https://github.com/PopcornTimeTV/PopcornKit.git`
Pre-downloading: `TVMLKitchen` from `https://github.com/toshi0383/TVMLKitchen.git`, branch `swift2.2`

[!] CocoaPods was not able to update the `popcorntimetv` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
[!] Unable to find a specification for `TVVLCKit`

**If I try update verbose** 

[!] Unable to find a specification for `TVVLCKit`

/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:57:in `resolve'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:227:in `analyze'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:114:in `install!'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/command/update.rb:60:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `load'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `<main>'

[!] CocoaPods was not able to update the `popcorntimetv` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

**Comment by buzzel** [comment]
Okay try this Delete the `Pods` directory and then run `rm -rf ~/.cocoapods/repos/popcorntimetv ` then run `pod install && pod update`

**Comment by buzzel** [comment]
@drew5494 Any luck?

**Comment by drew5494** [comment]
@buzzel haven't tried it yet.  I'm out right now. 
Thanks for the help though ;)

**Comment by buzzel** [comment]
@drew5494 Oh okay, no worries. Let me know when you do.

**Comment by drew5494** [comment]
@buzzel pods installed!!!!! Thanks so much!
