### ISSUE TITLE
App does not open in iOS 13.4.1

### ISSUE THREAD

**Issue by swingchampion** [PopcornTimeTV/PopcornTimeTV#899]
App version: 3.26
iOS/tvOS version: 13.4.1

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

The app should open normally.

#### Actual Behaviour

The app opens for 1 second with a black screen and then closes immediately.

#### Steps to reproduce the behaviour

Uninstalled reinstalled. 
New IPA file created in Xcode.

**Comment by duquesnay** [comment]
Closed? Fixed elsewhere?
