### ISSUE TITLE
Create installation script

### ISSUE THREAD

**Issue by pepibumur** [PopcornTimeTV/PopcornTimeTV#9]
### What?
The app cannot be distributed via AppStore because it'll be banned as illega. However, we can provide an script that can easily executed by any user, even if it's not developer, from its computer. The script will automatically fetch the project, compile it and run it into the user's device.

### Ideas
- Use a ruby script that is fetched using `curl` and executed using the system `ruby` version like [Brew](http://brew.sh/) does.
- Create a mini app with the installation steps and requirements and a button that fires the installation action.

More ideas?

**Comment by pepibumur** [comment]
Idea: http://www.libimobiledevice.org/

**Comment by pepibumur** [comment]
@EskiMag I'm currently working on this,

**Comment by josefdlange** [comment]
Perhaps a bit heavy-handed, but Fastlane and its suite of automated actions may provide a number of the automation features to make this a less intensive task.

https://fastlane.tools
