### ISSUE TITLE
issue with TVVLCKit-unstable (3.0.0a10)

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#9]
when installing TVVLCKit-unstable (3.0.0a10) it shows this error:

[!] Error installing TVVLCKit-unstable
[!] /usr/bin/curl -f -L -o /var/folders/dw/w6m8dq4d3cnf0_7vw864j_4c0000gn/T/d20160811-31783-1jo251m/file.zip http://download.videolan.org/pub/cocoapods/unstable/TVVLCKit-unstable-3.0.0a10.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  7  408M    7 32.5M    0     0   132k      0  0:52:41  0:04:11  0:48:30 18689
curl: (18) transfer closed with 394296424 bytes remaining to read

**Comment by angryDuck2** [comment]
Make sure that you are not using a vpn or any other in-betweens on your network!
