### ISSUE TITLE
Error when Installing

### ISSUE THREAD

**Issue by mohorani** [PopcornTimeTV/PopcornTimeTV#90]
When I try to test out Popcorn Time in the simulator, I getting the following errors included in the screenshot attached.
<img width="1280" alt="screen shot 2016-05-14 at 12 59 24 pm" src="https://cloud.githubusercontent.com/assets/17534565/15270389/6168eefe-19d3-11e6-8706-8b0a77804e13.png">

**Comment by buzzel** [comment]
Are you pulling the master branch or from the tag?

**Comment by mohorani** [comment]
No it is from the master branch.

**Comment by buzzel** [comment]
If issues like this arise on the master branch, be sure to use one of the actual release tags. The master branch usually has a working copy of the app, but from time to time, things like can happen. 

Be sure to check out the latest tag v0.6.2
