### ISSUE TITLE
Subtitle Position

### ISSUE THREAD

**Issue by imurreflection** [PopcornTimeTV/PopcornTimeTV#902]
Thanks for this awesome application. However, for only one reason, i m.not able to use it and its because of awkward subtitle positioning. It comes right in middle of the movie and it kills viewing experience. Can you please add subtitle positioning like vertical 0,10,20 etc or like "Bottom of the video" and it will be a one stop shop for viewing. Here the operating system i m referring to is android and android TV. Thanks

**Comment by imurreflection** [comment]
Can I please get some response on this?

**Comment by Midifreakz** [comment]
Hi, I'm not a developer so I can not help but you should note that this Github is dedicated to the iOS and tvOS compatible versions of Popcorn Time. You should try to look for the developers of the app you are trying to use.
