### ISSUE TITLE
Anybody tested on iOS 14 BETA ?

### ISSUE THREAD

**Issue by senadaruc** [PopcornTimeTV/PopcornTimeTV#919]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dev-myatminsoe** [comment]
Tested, crashing on iOS 14. Working on iOS 13.

**Comment by rsemedo2002** [comment]
:-(

**Comment by dev-myatminsoe** [comment]
It's working. Just need to add "NSBluetoothAlwaysUsageDescription" in info.plist.

**Comment by rsemedo2002** [comment]
Anyone will create a new working vers to install on tvOS 14...?

**Comment by iAYMANi** [comment]
> Anyone will create a new working vers to install on tvOS 14...?

no one ):
