### ISSUE TITLE
Swift 3  solve 

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeTV#92]
@FlaviaBondJamesBondsHusband   update swift 3.0

**Comment by GIthHub2die4** [comment]
update coming soon? since i've upgraded to Xcode 8, unable to compile app.

**Comment by tomsbrinkis** [comment]
After last update, it seems, that @FlaviaBondJamesBondsHusband has updated app to Swift 3.0?! 
![screen shot 2016-09-26 at 15 45 14](https://cloud.githubusercontent.com/assets/20775280/18834744/4fdb0acc-8400-11e6-83f5-a5aed13d0b9b.png)

**Comment by GIthHub2die4** [comment]
Ok Will give a try when I get home

**Comment by tomsbrinkis** [comment]
@GIthHub2die4 same here! 
Leave some response when you tried it :)

**Comment by GIthHub2die4** [comment]
tried, after cleaning file, still unable to build, here's what i get 
![screen shot 2016-09-26 at 4 58 08 pm](https://cloud.githubusercontent.com/assets/20074247/18851545/8b053e74-840a-11e6-84c0-fcbff2d51390.png)

**Comment by chocolatesuper** [comment]
Analyzing dependencies
Pre-downloading: `GCDWebServer` from `https://github.com/swisspol/GCDWebServer.git`
Pre-downloading: `ObjectMapper` from `https://github.com/Hearst-DD/ObjectMapper.git`
Pre-downloading: `PopcornKit` from `https://github.com/PopcornTimeTV/PopcornKit.git`, branch `new-apis`
Pre-downloading: `PopcornTorrent` from `https://github.com/PopcornTimeTV/PopcornTorrent.git`
Pre-downloading: `TVMLKitchen` from `https://github.com/toshi0383/TVMLKitchen.git`, branch `swift3.0`
Pre-downloading: `YoutubeSourceParserKit` from `https://github.com/lennet/YoutubeSourceParserKit.git`
Unable to find a specification for `SRT2VTT` depended upon by `PopcornKit`
