### ISSUE TITLE
Re-signing app?

### ISSUE THREAD

**Issue by rahalb** [PopcornTimeTV/PopcornTimeTV#93]
Hi I've been trying to install the ipa for more than 2 hours now and I cannot figure it out. Is there a tutorial out there that I can follow? I've tried using impactor and installing directly through Xcode, but each time i get an error saying I do not have the proper provisioning codes. Thank you.

**Comment by rahalb** [comment]
Think I sorted it out using appdb.cc, thanks!

**Comment by chocolatesuper** [comment]
They arranged the  ipa 1.0.5 version appdb.cc ipa
