### ISSUE TITLE
Subtitles black box

### ISSUE THREAD

**Issue by Mossito** [PopcornTimeTV/PopcornTimeTV#94]
Hi
Congratulations for the last merge, it's amazing!! I'm loving the app :)

Could be possible to disable the black box on subtitles? at least have an option?

Thank you very much!
Best regards

**Comment by buzzel** [comment]
Im sure that would be possible, what would you want in place of it? If its not there it might make subtitles tough to read in some cases.

**Comment by ozkrtech** [comment]
A black outline on each letter would work too. Right?

Oscar Rodriguez
IT Technician

On May 15, 2016, at 2:38 PM, buzzel <notifications@github.com<mailto:notifications@github.com>> wrote:


Im sure that would be possible, what would you want in place of it? If its not there it might make subtitles tough to read in some cases.

-

**Comment by Mossito** [comment]
Yes tiny black outline would be good. This is the way its displayed in VLC player in windows by default. 
Also Netflix uses some type of shadows i think: https://www.quora.com/Can-anyone-help-me-identify-the-subtitle-closed-captioning-typeface-used-by-Netflix

But white text without box would also be ok for me anycase

**Comment by buzzel** [comment]
I added some options for font sizes and background types. Feel free to pull the master branch and play around with it. I'll look into adding a stroke around the letters for a future update.

**Comment by Mossito** [comment]
Works great! thank you very much! :)

**Comment by buzzel** [comment]
No problem!

**Comment by pbo1976** [comment]
custom subtitles in the Settings please!

**Comment by pbo1976** [comment]
Good job with subtitles settings. One thing happens: after a couple of minutes the "swipe down for subtitles/options" menu disappears. Sometime the already working subtitles as well.

**Comment by ozkrtech** [comment]
Same here, sometimes the touch function on the remote just stops working obly after swiping down for the first time to set audio and subtitles.

Oscar Rodriguez
IT Technician

On May 18, 2016, at 8:36 AM, pbo1976 <notifications@github.com<mailto:notifications@github.com>> wrote:


Good job with subtitles settings. One thing happens: after a couple of minutes the "swipe down for subtitles/options" menu disappears. Sometime the already working subtitles as well.

-
