### ISSUE TITLE
The platform of the target `PopcornTime` (tvOS 9.0) is not compatible with `AlamofireXMLRPC (2.0.0)`, which does not support `tvos`.

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#96]
@FlaviaBondJamesBondsHusband @Hackormahn @popcornMaster @tvOSPopcorn 

After a the fix of #94 now a new issue have came

[!] The platform of the target `PopcornTime` (tvOS 9.0) is not compatible with `AlamofireXMLRPC (2.0.0)`, which does not support `tvos`.

**Comment by Hackormahn** [comment]
Wait for the kodlian guy to make a new release of the dependancy.
