### ISSUE TITLE
Stream stops midway

### ISSUE THREAD

**Issue by pnewell** [PopcornTimeTV/PopcornTimeTV#97]
Have an issue where streams stop randomly midway. Not sure why it is happening. Also, if I start a stream, and fast forward it never resumes.

**Comment by buzzel** [comment]
@pnewell Run a `pod update` and see if it updates anything. This should of been fixed with the 0.6.0 release but Im wondering if some people haven't properly updated their pods.

**Comment by pnewell** [comment]
@buzzel I just got my apple tv/installed 0.6.2 today for the first time

**Comment by pnewell** [comment]
What is a pod update?

**Comment by pbo1976** [comment]
Movies also stop streaming within the first 5 minutes or so. Tv shows stream mostly fine for me.

**Comment by pnewell** [comment]
This is happening to tv shows for me

**Comment by RefusedFlow** [comment]
Closing this issue as a duplicate of #96
