### ISSUE TITLE
Python update script

### ISSUE THREAD

**Issue by pbo1976** [PopcornTimeTV/PopcornTimeTV#98]
What is the proper way of updating to the latest version? Doing all the process again? Replacing files?

Thanks,
p.

**Comment by buzzel** [comment]
The best way to update is to simply just run a `git fetch && git rebase` then `git checkout newVersionNumber` then run a `pod update`. I've been trying to come up with the best dynamic solution to update and im thinking about putting in a Python script to do all of the heavy lifting for users.

**Comment by buzzel** [comment]
@pbo1976 I pushed a new python script to the master branch. If you want, feel free to clone that branch and give it a whirl.

**Comment by sqig** [comment]
@buzzel great work with the python script. I will try it next update.
Thank you.

**Comment by tomto147** [comment]
when trying to use the script I am getting an error: 
File "install.py", line 38
    break
SyntaxError: 'break' outside loop

**Comment by pbo1976** [comment]
Thanks! I have no idea what a Python is, but I'll do my best in order to understand what is going on.

**Comment by buzzel** [comment]
@tomto147 Give the new one a try. I haven't written python in a while so I used break in the wrong context.

**Comment by buzzel** [comment]
@tomto147 the requests module should come with python. Try running `sudo easy_install -U requests` and see if it installs.

**Comment by tomto147** [comment]
@buzzel 
This has worked for me!
Wow what a piece of work you have done.
Great ;-))

**Comment by pbo1976** [comment]
It worked for me !

**Comment by buzzel** [comment]
@tomto147 @pbo1976 Would you guys be willing to test out the new swift version of the install script? Run it the same way you would the python script. `cd /path/to/popcorntimerv/` then `swift install.swift`

**Comment by pbo1976** [comment]
I'll give it a try tonight.

**Comment by tomto147** [comment]
@buzzel 
Swift install worked for me with no problems and errors. I even got the feeling that it was faster than python for some reason. So all good here!

**Comment by pbo1976** [comment]
i don't know if i am doing right, i get the following error message in Terminal:

<unknown>:0: error: no such file or directory: 'install.swift'

**Comment by tomto147** [comment]
@pbo1976
Have you pulled the last release? Install.swift has been added few hours ago.

**Comment by buzzel** [comment]
@tomto147 Okay sweet. Going to ditch the python script and replace it with the swift version. 

@pbo1976 Make sure you fetch the latest changes on the master branch. Once you do that, open terminal and cd into the PopcornTImeTV folder, then run `swift install.swift`

**Comment by pbo1976** [comment]
@buzzel right, I forgot that part. Every day learning something new

**Comment by buzzel** [comment]
@pbo1976 No worries :)
